-- Lote gerado automaticamente a partir de tooling/bragantino_passport/
-- source/bragantino_passport_2026.json (node generate_seed_sql.mjs 2026) —
-- nunca edite este arquivo à mão, regenere a partir do JSON fonte.
--
-- Rode no projeto Supabase do BRAGANTINO — NÃO no do Goiás — nesta ordem:
--   1. bragantino_passport_infra.sql       (colunas de enriquecimento)
--   2. bragantino_passport_venues_seed.sql (catálogo de estádios)
--   3. este arquivo
-- Idempotente (ON CONFLICT DO UPDATE): reexecutar atualiza, nunca duplica, e
-- não encosta em presença de usuário.

insert into public.passport_matches (
  id, season, match_date, match_time, status, competition, competition_code, competition_edition, round, phase_status, opponent, club_is_home, neutral_site, home_team, away_team, home_score, away_score, club_score, opponent_score, score_display, outcome, stadium, stadium_status, venue_id, weekday, day_type, day_period, kickoff_at, display_timezone, date_precision, source_provider, source_match_id, source_url, source_confidence, data_notes
) values
  ('pb_onef_2648171', 2026, '2026-01-11', '18:15:00', 'FINISHED', 'Paulista', 'PAULISTA', 'Paulista 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'EC Noroeste SP', false, false, 'EC Noroeste SP', 'RB Bragantino', 0, 1, 1, 0, '0–1', 'WIN', 'Estádio Dr. Alfredo de Castilho', 'MATCH_SPECIFIC', 'venue_estadio_dr_alfredo_de_castilho', 'domingo', 'WEEKEND', 'NIGHT', (timestamp '2026-01-11 18:15:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2648171', 'https://onefootball.com/pt-br/match/2648171', 'HIGH', null),
  ('pb_onef_2648184', 2026, '2026-01-15', '19:30:00', 'FINISHED', 'Paulista', 'PAULISTA', 'Paulista 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Corinthians', true, false, 'RB Bragantino', 'Corinthians', 3, 0, 3, 0, '3–0', 'WIN', 'Estádio Municipal Cícero de Souza Marques', 'MATCH_SPECIFIC', 'venue_estadio_municipal_cicero_de_souza_marques', 'quinta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-01-15 19:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2648184', 'https://onefootball.com/pt-br/match/2648184', 'HIGH', null),
  ('pb_onef_2648192', 2026, '2026-01-18', '18:15:00', 'FINISHED', 'Paulista', 'PAULISTA', 'Paulista 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Botafogo-SP', true, false, 'RB Bragantino', 'Botafogo-SP', 5, 0, 5, 0, '5–0', 'WIN', 'Estádio Municipal Cícero de Souza Marques', 'MATCH_SPECIFIC', 'venue_estadio_municipal_cicero_de_souza_marques', 'domingo', 'WEEKEND', 'NIGHT', (timestamp '2026-01-18 18:15:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2648192', 'https://onefootball.com/pt-br/match/2648192', 'HIGH', null),
  ('pb_onef_2648197', 2026, '2026-01-21', '20:00:00', 'FINISHED', 'Paulista', 'PAULISTA', 'Paulista 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Mirassol', false, false, 'Mirassol', 'RB Bragantino', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio José Maria de Campos Maia', 'MATCH_SPECIFIC', 'venue_estadio_jose_maria_de_campos_maia', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-01-21 20:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2648197', 'https://onefootball.com/pt-br/match/2648197', 'HIGH', null),
  ('pb_onef_2648208', 2026, '2026-01-25', '16:00:00', 'FINISHED', 'Paulista', 'PAULISTA', 'Paulista 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Santos', false, false, 'Santos', 'RB Bragantino', 0, 0, 0, 0, '0–0', 'DRAW', 'Neo Química Arena', 'MATCH_SPECIFIC', 'venue_neo_quimica_arena', 'domingo', 'WEEKEND', 'AFTERNOON', (timestamp '2026-01-25 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2648208', 'https://onefootball.com/pt-br/match/2648208', 'HIGH', null),
  ('pb_onef_2652208', 2026, '2026-01-28', '19:00:00', 'FINISHED', 'Brasileirão Betano', 'BRASILEIRAO_A', 'Brasileirão Betano 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Coritiba', false, false, 'Coritiba', 'RB Bragantino', 0, 1, 1, 0, '0–1', 'WIN', 'Estádio Major Antônio Couto Pereira', 'MATCH_SPECIFIC', 'venue_estadio_major_antonio_couto_pereira', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-01-28 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2652208', 'https://onefootball.com/pt-br/match/2652208', 'HIGH', null),
  ('pb_onef_2648216', 2026, '2026-02-01', '18:15:00', 'FINISHED', 'Paulista', 'PAULISTA', 'Paulista 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'São Bernardo FC', true, false, 'RB Bragantino', 'São Bernardo FC', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Municipal Cícero de Souza Marques', 'MATCH_SPECIFIC', 'venue_estadio_municipal_cicero_de_souza_marques', 'domingo', 'WEEKEND', 'NIGHT', (timestamp '2026-02-01 18:15:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2648216', 'https://onefootball.com/pt-br/match/2648216', 'HIGH', null),
  ('pb_onef_2652215', 2026, '2026-02-04', '19:00:00', 'FINISHED', 'Brasileirão Betano', 'BRASILEIRAO_A', 'Brasileirão Betano 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Atlético-MG', true, false, 'RB Bragantino', 'Atlético-MG', 1, 0, 1, 0, '1–0', 'WIN', 'Estádio Municipal Cícero de Souza Marques', 'MATCH_SPECIFIC', 'venue_estadio_municipal_cicero_de_souza_marques', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-02-04 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2652215', 'https://onefootball.com/pt-br/match/2652215', 'HIGH', null),
  ('pb_onef_2648220', 2026, '2026-02-08', '18:30:00', 'FINISHED', 'Paulista', 'PAULISTA', 'Paulista 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Velo Clube', false, false, 'Velo Clube', 'RB Bragantino', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Benito Agnelo Castellano', 'MATCH_SPECIFIC', 'venue_estadio_benito_agnelo_castellano', 'domingo', 'WEEKEND', 'NIGHT', (timestamp '2026-02-08 18:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2648220', 'https://onefootball.com/pt-br/match/2648220', 'HIGH', null),
  ('pb_onef_2652224', 2026, '2026-02-12', '20:00:00', 'FINISHED', 'Brasileirão Betano', 'BRASILEIRAO_A', 'Brasileirão Betano 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Corinthians', false, false, 'Corinthians', 'RB Bragantino', 2, 0, 0, 2, '2–0', 'LOSS', 'Neo Química Arena', 'MATCH_SPECIFIC', 'venue_neo_quimica_arena', 'quinta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-02-12 20:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2652224', 'https://onefootball.com/pt-br/match/2652224', 'HIGH', null),
  ('pb_onef_2648231', 2026, '2026-02-15', '20:30:00', 'FINISHED', 'Paulista', 'PAULISTA', 'Paulista 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Grêmio Novorizontino', true, false, 'RB Bragantino', 'Grêmio Novorizontino', 3, 0, 3, 0, '3–0', 'WIN', 'Estádio Municipal Cícero de Souza Marques', 'MATCH_SPECIFIC', 'venue_estadio_municipal_cicero_de_souza_marques', 'domingo', 'WEEKEND', 'NIGHT', (timestamp '2026-02-15 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2648231', 'https://onefootball.com/pt-br/match/2648231', 'HIGH', null),
  ('pb_onef_2665365', 2026, '2026-02-21', '18:30:00', 'FINISHED', 'Paulista', 'PAULISTA', 'Paulista 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'São Paulo', true, false, 'RB Bragantino', 'São Paulo', 1, 2, 1, 2, '1–2', 'LOSS', 'Estádio Municipal Cícero de Souza Marques', 'MATCH_SPECIFIC', 'venue_estadio_municipal_cicero_de_souza_marques', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2026-02-21 18:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2665365', 'https://onefootball.com/pt-br/match/2665365', 'HIGH', null),
  ('pb_onef_2652235', 2026, '2026-02-25', '19:00:00', 'FINISHED', 'Brasileirão Betano', 'BRASILEIRAO_A', 'Brasileirão Betano 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Athletico Paranaense', true, false, 'RB Bragantino', 'Athletico Paranaense', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Municipal Cícero de Souza Marques', 'MATCH_SPECIFIC', 'venue_estadio_municipal_cicero_de_souza_marques', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-02-25 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2652235', 'https://onefootball.com/pt-br/match/2652235', 'HIGH', null),
  ('pb_onef_2652247', 2026, '2026-03-12', '21:30:00', 'FINISHED', 'Brasileirão Betano', 'BRASILEIRAO_A', 'Brasileirão Betano 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Grêmio', false, false, 'Grêmio', 'RB Bragantino', 1, 1, 1, 1, '1–1', 'DRAW', 'Arena do Grêmio', 'MATCH_SPECIFIC', 'venue_arena_do_gremio', 'quinta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-03-12 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2652247', 'https://onefootball.com/pt-br/match/2652247', 'HIGH', null),
  ('pb_onef_2652255', 2026, '2026-03-15', '20:30:00', 'FINISHED', 'Brasileirão Betano', 'BRASILEIRAO_A', 'Brasileirão Betano 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'São Paulo', true, false, 'RB Bragantino', 'São Paulo', 1, 2, 1, 2, '1–2', 'LOSS', 'Estádio Municipal Cícero de Souza Marques', 'MATCH_SPECIFIC', 'venue_estadio_municipal_cicero_de_souza_marques', 'domingo', 'WEEKEND', 'NIGHT', (timestamp '2026-03-15 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2652255', 'https://onefootball.com/pt-br/match/2652255', 'HIGH', null),
  ('pb_onef_2652269', 2026, '2026-03-18', '19:00:00', 'FINISHED', 'Brasileirão Betano', 'BRASILEIRAO_A', 'Brasileirão Betano 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Bahia', false, false, 'Bahia', 'RB Bragantino', 2, 0, 0, 2, '2–0', 'LOSS', 'Casa de Apostas Arena Fonte Nova', 'MATCH_SPECIFIC', 'venue_complexo_esportivo_cultural_octavio_mangabeira', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-03-18 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2652269', 'https://onefootball.com/pt-br/match/2652269', 'HIGH', null),
  ('pb_onef_2652275', 2026, '2026-03-21', '16:00:00', 'FINISHED', 'Brasileirão Betano', 'BRASILEIRAO_A', 'Brasileirão Betano 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Botafogo', true, false, 'RB Bragantino', 'Botafogo', 1, 2, 1, 2, '1–2', 'LOSS', 'Estádio Municipal Cícero de Souza Marques', 'MATCH_SPECIFIC', 'venue_estadio_municipal_cicero_de_souza_marques', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2026-03-21 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2652275', 'https://onefootball.com/pt-br/match/2652275', 'HIGH', null),
  ('pb_onef_2652285', 2026, '2026-04-02', '21:30:00', 'FINISHED', 'Brasileirão Betano', 'BRASILEIRAO_A', 'Brasileirão Betano 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Flamengo', true, false, 'RB Bragantino', 'Flamengo', 3, 0, 3, 0, '3–0', 'WIN', 'Estádio Municipal Cícero de Souza Marques', 'MATCH_SPECIFIC', 'venue_estadio_municipal_cicero_de_souza_marques', 'quinta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-04-02 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2652285', 'https://onefootball.com/pt-br/match/2652285', 'HIGH', null),
  ('pb_onef_2652295', 2026, '2026-04-05', '20:00:00', 'FINISHED', 'Brasileirão Betano', 'BRASILEIRAO_A', 'Brasileirão Betano 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Mirassol', false, false, 'Mirassol', 'RB Bragantino', 0, 1, 1, 0, '0–1', 'WIN', 'Estádio José Maria de Campos Maia', 'MATCH_SPECIFIC', 'venue_estadio_jose_maria_de_campos_maia', 'domingo', 'WEEKEND', 'NIGHT', (timestamp '2026-04-05 20:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2652295', 'https://onefootball.com/pt-br/match/2652295', 'HIGH', null),
  ('pb_onef_2677386', 2026, '2026-04-09', '21:30:00', 'FINISHED', 'CONMEBOL Sudamericana', 'SULAMERICANA', 'CONMEBOL Sudamericana 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Carabobo FC', false, false, 'Carabobo FC', 'RB Bragantino', 1, 0, 0, 1, '1–0', 'LOSS', 'Estadio Polideportivo Misael Delgado', 'MATCH_SPECIFIC', 'venue_estadio_polideportivo_misael_delgado', 'quinta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-04-09 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2677386', 'https://onefootball.com/pt-br/match/2677386', 'HIGH', null),
  ('pb_onef_2652306', 2026, '2026-04-12', '18:30:00', 'FINISHED', 'Brasileirão Betano', 'BRASILEIRAO_A', 'Brasileirão Betano 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Cruzeiro', false, false, 'Cruzeiro', 'RB Bragantino', 2, 1, 1, 2, '2–1', 'LOSS', 'Estádio Governador Magalhães Pinto', 'MATCH_SPECIFIC', 'venue_estadio_governador_magalhaes_pinto', 'domingo', 'WEEKEND', 'NIGHT', (timestamp '2026-04-12 18:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2652306', 'https://onefootball.com/pt-br/match/2652306', 'HIGH', null),
  ('pb_onef_2677402', 2026, '2026-04-16', '21:30:00', 'FINISHED', 'CONMEBOL Sudamericana', 'SULAMERICANA', 'CONMEBOL Sudamericana 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Blooming', true, false, 'RB Bragantino', 'Blooming', 3, 2, 3, 2, '3–2', 'WIN', 'Estádio Municipal Cícero de Souza Marques', 'MATCH_SPECIFIC', 'venue_estadio_municipal_cicero_de_souza_marques', 'quinta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-04-16 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2677402', 'https://onefootball.com/pt-br/match/2677402', 'HIGH', null),
  ('pb_onef_2652315', 2026, '2026-04-19', '18:30:00', 'FINISHED', 'Brasileirão Betano', 'BRASILEIRAO_A', 'Brasileirão Betano 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Remo', true, false, 'RB Bragantino', 'Remo', 4, 2, 4, 2, '4–2', 'WIN', 'Estádio Municipal Cícero de Souza Marques', 'MATCH_SPECIFIC', 'venue_estadio_municipal_cicero_de_souza_marques', 'domingo', 'WEEKEND', 'NIGHT', (timestamp '2026-04-19 18:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2652315', 'https://onefootball.com/pt-br/match/2652315', 'HIGH', null),
  ('pb_onef_2677819', 2026, '2026-04-22', '21:30:00', 'FINISHED', 'Copa Betano do Brasil', 'COPA_DO_BRASIL', 'Copa Betano do Brasil 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Mirassol', true, false, 'RB Bragantino', 'Mirassol', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Municipal Cícero de Souza Marques', 'MATCH_SPECIFIC', 'venue_estadio_municipal_cicero_de_souza_marques', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-04-22 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2677819', 'https://onefootball.com/pt-br/match/2677819', 'HIGH', null),
  ('pb_onef_2652325', 2026, '2026-04-26', '18:30:00', 'FINISHED', 'Brasileirão Betano', 'BRASILEIRAO_A', 'Brasileirão Betano 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Palmeiras', true, false, 'RB Bragantino', 'Palmeiras', 0, 1, 0, 1, '0–1', 'LOSS', 'Estádio Municipal Cícero de Souza Marques', 'MATCH_SPECIFIC', 'venue_estadio_municipal_cicero_de_souza_marques', 'domingo', 'WEEKEND', 'NIGHT', (timestamp '2026-04-26 18:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2652325', 'https://onefootball.com/pt-br/match/2652325', 'HIGH', null),
  ('pb_onef_2677411', 2026, '2026-04-30', '21:30:00', 'FINISHED', 'CONMEBOL Sudamericana', 'SULAMERICANA', 'CONMEBOL Sudamericana 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Club Atlético River Plate', true, false, 'RB Bragantino', 'Club Atlético River Plate', 0, 1, 0, 1, '0–1', 'LOSS', 'Estádio Municipal Cícero de Souza Marques', 'MATCH_SPECIFIC', 'venue_estadio_municipal_cicero_de_souza_marques', 'quinta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-04-30 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2677411', 'https://onefootball.com/pt-br/match/2677411', 'HIGH', null),
  ('pb_onef_2652340', 2026, '2026-05-03', '18:30:00', 'FINISHED', 'Brasileirão Betano', 'BRASILEIRAO_A', 'Brasileirão Betano 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Chapecoense', false, false, 'Chapecoense', 'RB Bragantino', 1, 2, 2, 1, '1–2', 'WIN', 'Arena Condá', 'MATCH_SPECIFIC', 'venue_arena_conda', 'domingo', 'WEEKEND', 'NIGHT', (timestamp '2026-05-03 18:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2652340', 'https://onefootball.com/pt-br/match/2652340', 'HIGH', null),
  ('pb_onef_2677419', 2026, '2026-05-07', '21:30:00', 'FINISHED', 'CONMEBOL Sudamericana', 'SULAMERICANA', 'CONMEBOL Sudamericana 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Blooming', false, false, 'Blooming', 'RB Bragantino', 0, 6, 6, 0, '0–6', 'WIN', 'Estadio Ramón Aguilera Costas', 'MATCH_SPECIFIC', 'venue_estadio_ramon_aguilera_costas', 'quinta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-05-07 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2677419', 'https://onefootball.com/pt-br/match/2677419', 'HIGH', null),
  ('pb_onef_2652343', 2026, '2026-05-10', '18:30:00', 'FINISHED', 'Brasileirão Betano', 'BRASILEIRAO_A', 'Brasileirão Betano 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Santos', false, false, 'Santos', 'RB Bragantino', 2, 0, 0, 2, '2–0', 'LOSS', 'Estádio Urbano Caldeira', 'MATCH_SPECIFIC', 'venue_estadio_urbano_caldeira', 'domingo', 'WEEKEND', 'NIGHT', (timestamp '2026-05-10 18:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2652343', 'https://onefootball.com/pt-br/match/2652343', 'HIGH', null),
  ('pb_onef_2677835', 2026, '2026-05-13', '20:30:00', 'FINISHED', 'Copa Betano do Brasil', 'COPA_DO_BRASIL', 'Copa Betano do Brasil 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Mirassol', false, false, 'Mirassol', 'RB Bragantino', 2, 1, 1, 2, '2–1', 'LOSS', 'Estádio José Maria de Campos Maia', 'MATCH_SPECIFIC', 'venue_estadio_jose_maria_de_campos_maia', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-05-13 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2677835', 'https://onefootball.com/pt-br/match/2677835', 'HIGH', null),
  ('pb_onef_2652355', 2026, '2026-05-17', '18:30:00', 'FINISHED', 'Brasileirão Betano', 'BRASILEIRAO_A', 'Brasileirão Betano 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Vitória', true, false, 'RB Bragantino', 'Vitória', 2, 0, 2, 0, '2–0', 'WIN', 'Estádio Municipal Cícero de Souza Marques', 'MATCH_SPECIFIC', 'venue_estadio_municipal_cicero_de_souza_marques', 'domingo', 'WEEKEND', 'NIGHT', (timestamp '2026-05-17 18:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2652355', 'https://onefootball.com/pt-br/match/2652355', 'HIGH', null),
  ('pb_onef_2677436', 2026, '2026-05-20', '21:30:00', 'FINISHED', 'CONMEBOL Sudamericana', 'SULAMERICANA', 'CONMEBOL Sudamericana 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Club Atlético River Plate', false, false, 'Club Atlético River Plate', 'RB Bragantino', 1, 1, 1, 1, '1–1', 'DRAW', 'Estadio Monumental', 'MATCH_SPECIFIC', 'venue_estadio_monumental', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-05-20 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2677436', 'https://onefootball.com/pt-br/match/2677436', 'HIGH', null),
  ('pb_onef_2652362', 2026, '2026-05-24', '20:30:00', 'FINISHED', 'Brasileirão Betano', 'BRASILEIRAO_A', 'Brasileirão Betano 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Vasco da Gama', false, false, 'Vasco da Gama', 'RB Bragantino', 0, 3, 3, 0, '0–3', 'WIN', 'Estádio São Januário', 'MATCH_SPECIFIC', 'venue_estadio_vasco_da_gama', 'domingo', 'WEEKEND', 'NIGHT', (timestamp '2026-05-24 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2652362', 'https://onefootball.com/pt-br/match/2652362', 'HIGH', null),
  ('pb_onef_2677459', 2026, '2026-05-27', '21:30:00', 'FINISHED', 'CONMEBOL Sudamericana', 'SULAMERICANA', 'CONMEBOL Sudamericana 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Carabobo FC', true, false, 'RB Bragantino', 'Carabobo FC', 2, 0, 2, 0, '2–0', 'WIN', 'Estádio Municipal Cícero de Souza Marques', 'MATCH_SPECIFIC', 'venue_estadio_municipal_cicero_de_souza_marques', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-05-27 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2677459', 'https://onefootball.com/pt-br/match/2677459', 'HIGH', null),
  ('pb_onef_2652376', 2026, '2026-05-31', '11:00:00', 'FINISHED', 'Brasileirão Betano', 'BRASILEIRAO_A', 'Brasileirão Betano 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Internacional', true, false, 'RB Bragantino', 'Internacional', 3, 1, 3, 1, '3–1', 'WIN', 'Estádio Municipal Cícero de Souza Marques', 'MATCH_SPECIFIC', 'venue_estadio_municipal_cicero_de_souza_marques', 'domingo', 'WEEKEND', 'MORNING', (timestamp '2026-05-31 11:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2652376', 'https://onefootball.com/pt-br/match/2652376', 'HIGH', null),
  ('pb_onef_2652387', 2026, '2026-07-17', '20:00:00', 'FINISHED', 'Brasileirão Betano', 'BRASILEIRAO_A', 'Brasileirão Betano 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Fluminense', false, false, 'Fluminense', 'RB Bragantino', 1, 1, 1, 1, '1–1', 'DRAW', 'Estadio Jornalista Mário Filho (Maracanã)', 'MATCH_SPECIFIC', 'venue_estadio_jornalista_mario_filho', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-07-17 20:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2652387', 'https://onefootball.com/pt-br/match/2652387', 'HIGH', null),
  ('pb_onef_2684244', 2026, '2026-07-22', '21:30:00', 'FINISHED', 'CONMEBOL Sudamericana', 'SULAMERICANA', 'CONMEBOL Sudamericana 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Sporting Cristal', false, false, 'Sporting Cristal', 'RB Bragantino', 0, 0, 0, 0, '0–0', 'DRAW', 'Estadio Nacional de Lima', 'MATCH_SPECIFIC', 'venue_estadio_nacional_de_lima', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-07-22 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2684244', 'https://onefootball.com/pt-br/match/2684244', 'HIGH', null),
  ('pb_onef_2652394', 2026, '2026-07-26', '18:30:00', 'FINISHED', 'Brasileirão Betano', 'BRASILEIRAO_A', 'Brasileirão Betano 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Coritiba', true, false, 'RB Bragantino', 'Coritiba', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Municipal Cícero de Souza Marques', 'MATCH_SPECIFIC', 'venue_estadio_municipal_cicero_de_souza_marques', 'domingo', 'WEEKEND', 'NIGHT', (timestamp '2026-07-26 18:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2652394', 'https://onefootball.com/pt-br/match/2652394', 'HIGH', null),
  ('pb_onef_2652401', 2026, '2026-07-29', '09:00:00', 'POSTPONED', 'Brasileirão Betano', 'BRASILEIRAO_A', 'Brasileirão Betano 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Atlético-MG', false, false, 'Atlético-MG', 'RB Bragantino', null, null, null, null, null, null, 'Arena MRV', 'MATCH_SPECIFIC', 'venue_arena_mrv', 'quarta-feira', 'WEEKDAY', 'MORNING', (timestamp '2026-07-29 09:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2652401', 'https://onefootball.com/pt-br/match/2652401', 'HIGH', null),
  ('pb_onef_2684257', 2026, '2026-07-29', '21:30:00', 'FINISHED', 'CONMEBOL Sudamericana', 'SULAMERICANA', 'CONMEBOL Sudamericana 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Sporting Cristal', true, false, 'RB Bragantino', 'Sporting Cristal', 1, 0, 1, 0, '1–0', 'WIN', 'Estádio Municipal Cícero de Souza Marques', 'MATCH_SPECIFIC', 'venue_estadio_municipal_cicero_de_souza_marques', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-07-29 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2684257', 'https://onefootball.com/pt-br/match/2684257', 'HIGH', null),
  ('pb_onef_2652415', 2026, '2026-08-09', '18:30:00', 'FINISHED', 'Brasileirão Betano', 'BRASILEIRAO_A', 'Brasileirão Betano 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Corinthians', true, false, 'RB Bragantino', 'Corinthians', 0, 2, 0, 2, '0–2', 'LOSS', 'Estádio Municipal Cícero de Souza Marques', 'MATCH_SPECIFIC', 'venue_estadio_municipal_cicero_de_souza_marques', 'domingo', 'WEEKEND', 'NIGHT', (timestamp '2026-08-09 18:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2652415', 'https://onefootball.com/pt-br/match/2652415', 'HIGH', null),
  ('pb_onef_2684376', 2026, '2026-08-12', '19:00:00', 'FINISHED', 'CONMEBOL Sudamericana', 'SULAMERICANA', 'CONMEBOL Sudamericana 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Atlético-MG', true, false, 'RB Bragantino', 'Atlético-MG', 0, 1, 0, 1, '0–1', 'LOSS', 'Estádio Municipal Cícero de Souza Marques', 'MATCH_SPECIFIC', 'venue_estadio_municipal_cicero_de_souza_marques', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-08-12 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2684376', 'https://onefootball.com/pt-br/match/2684376', 'HIGH', null),
  ('pb_onef_2652428', 2026, '2026-08-15', '18:30:00', 'FINISHED', 'Brasileirão Betano', 'BRASILEIRAO_A', 'Brasileirão Betano 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Athletico Paranaense', false, false, 'Athletico Paranaense', 'RB Bragantino', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Mário Celso Petraglia', 'MATCH_SPECIFIC', 'venue_estadio_joaquim_americo_guimaraes', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2026-08-15 18:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2652428', 'https://onefootball.com/pt-br/match/2652428', 'HIGH', null),
  ('pb_onef_2684383', 2026, '2026-08-19', '19:00:00', 'FINISHED', 'CONMEBOL Sudamericana', 'SULAMERICANA', 'CONMEBOL Sudamericana 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Atlético-MG', false, false, 'Atlético-MG', 'RB Bragantino', 2, 2, 2, 2, '2–2', 'DRAW', 'Arena MRV', 'MATCH_SPECIFIC', 'venue_arena_mrv', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-08-19 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2684383', 'https://onefootball.com/pt-br/match/2684383', 'HIGH', null),
  ('pb_onef_2652435', 2026, '2026-08-23', '16:00:00', 'FINISHED', 'Brasileirão Betano', 'BRASILEIRAO_A', 'Brasileirão Betano 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Grêmio', true, false, 'RB Bragantino', 'Grêmio', 1, 0, 1, 0, '1–0', 'WIN', 'Estádio Municipal Cícero de Souza Marques', 'MATCH_SPECIFIC', 'venue_estadio_municipal_cicero_de_souza_marques', 'domingo', 'WEEKEND', 'AFTERNOON', (timestamp '2026-08-23 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2652435', 'https://onefootball.com/pt-br/match/2652435', 'HIGH', null),
  ('pb_onef_2652446', 2026, '2026-08-29', '20:00:00', 'FINISHED', 'Brasileirão Betano', 'BRASILEIRAO_A', 'Brasileirão Betano 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'São Paulo', false, false, 'São Paulo', 'RB Bragantino', 2, 1, 1, 2, '2–1', 'LOSS', 'MorumBIS', 'MATCH_SPECIFIC', 'venue_estadio_cicero_pompeu_de_toledo', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2026-08-29 20:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2652446', 'https://onefootball.com/pt-br/match/2652446', 'HIGH', null),
  ('pb_onef_2652455', 2026, '2026-09-05', '16:00:00', 'FINISHED', 'Brasileirão Betano', 'BRASILEIRAO_A', 'Brasileirão Betano 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Bahia', true, false, 'RB Bragantino', 'Bahia', 2, 3, 2, 3, '2–3', 'LOSS', 'Estádio Municipal Cícero de Souza Marques', 'MATCH_SPECIFIC', 'venue_estadio_municipal_cicero_de_souza_marques', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2026-09-05 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2652455', 'https://onefootball.com/pt-br/match/2652455', 'HIGH', null),
  ('pb_onef_2652463', 2026, '2026-09-12', '20:30:00', 'SCHEDULED', 'Brasileirão Betano', 'BRASILEIRAO_A', 'Brasileirão Betano 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Botafogo', false, false, 'Botafogo', 'RB Bragantino', null, null, null, null, null, null, 'Estádio Olímpico Nilton Santos', 'MATCH_SPECIFIC', 'venue_estadio_olimpico_nilton_santos', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2026-09-12 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2652463', 'https://onefootball.com/pt-br/match/2652463', 'HIGH', null),
  ('pb_onef_2652472', 2026, '2026-09-20', '18:30:00', 'SCHEDULED', 'Brasileirão Betano', 'BRASILEIRAO_A', 'Brasileirão Betano 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Flamengo', false, false, 'Flamengo', 'RB Bragantino', null, null, null, null, null, null, 'Estadio Jornalista Mário Filho (Maracanã)', 'MATCH_SPECIFIC', 'venue_estadio_jornalista_mario_filho', 'domingo', 'WEEKEND', 'NIGHT', (timestamp '2026-09-20 18:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2652472', 'https://onefootball.com/pt-br/match/2652472', 'HIGH', null),
  ('pb_onef_2652486', 2026, '2026-10-07', '19:30:00', 'SCHEDULED', 'Brasileirão Betano', 'BRASILEIRAO_A', 'Brasileirão Betano 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Mirassol', true, false, 'RB Bragantino', 'Mirassol', null, null, null, null, null, null, 'Estádio Municipal Cícero de Souza Marques', 'MATCH_SPECIFIC', 'venue_estadio_municipal_cicero_de_souza_marques', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-10-07 19:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2652486', 'https://onefootball.com/pt-br/match/2652486', 'HIGH', null),
  ('pb_onef_2652491', 2026, '2026-10-12', '21:00:00', 'SCHEDULED', 'Brasileirão Betano', 'BRASILEIRAO_A', 'Brasileirão Betano 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Cruzeiro', true, false, 'RB Bragantino', 'Cruzeiro', null, null, null, null, null, null, 'Estádio Municipal Cícero de Souza Marques', 'MATCH_SPECIFIC', 'venue_estadio_municipal_cicero_de_souza_marques', 'segunda-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-10-12 21:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2652491', 'https://onefootball.com/pt-br/match/2652491', 'HIGH', null),
  ('pb_onef_2652502', 2026, '2026-10-17', '09:00:00', 'SCHEDULED', 'Brasileirão Betano', 'BRASILEIRAO_A', 'Brasileirão Betano 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Remo', false, false, 'Remo', 'RB Bragantino', null, null, null, null, null, null, 'Estádio Evandro Almeida', 'MATCH_SPECIFIC', 'venue_estadio_evandro_almeida', 'sábado', 'WEEKEND', 'MORNING', (timestamp '2026-10-17 09:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2652502', 'https://onefootball.com/pt-br/match/2652502', 'HIGH', null),
  ('pb_onef_2652515', 2026, '2026-10-24', '09:00:00', 'SCHEDULED', 'Brasileirão Betano', 'BRASILEIRAO_A', 'Brasileirão Betano 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Palmeiras', false, false, 'Palmeiras', 'RB Bragantino', null, null, null, null, null, null, 'Nubank Parque', 'MATCH_SPECIFIC', 'venue_nubank_parque', 'sábado', 'WEEKEND', 'MORNING', (timestamp '2026-10-24 09:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2652515', 'https://onefootball.com/pt-br/match/2652515', 'HIGH', null),
  ('pb_onef_2652521', 2026, '2026-10-28', '09:00:00', 'SCHEDULED', 'Brasileirão Betano', 'BRASILEIRAO_A', 'Brasileirão Betano 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Chapecoense', true, false, 'RB Bragantino', 'Chapecoense', null, null, null, null, null, null, 'Estádio Municipal Cícero de Souza Marques', 'MATCH_SPECIFIC', 'venue_estadio_municipal_cicero_de_souza_marques', 'quarta-feira', 'WEEKDAY', 'MORNING', (timestamp '2026-10-28 09:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2652521', 'https://onefootball.com/pt-br/match/2652521', 'HIGH', null),
  ('pb_onef_2652536', 2026, '2026-11-04', '09:00:00', 'SCHEDULED', 'Brasileirão Betano', 'BRASILEIRAO_A', 'Brasileirão Betano 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Santos', true, false, 'RB Bragantino', 'Santos', null, null, null, null, null, null, 'Estádio Municipal Cícero de Souza Marques', 'MATCH_SPECIFIC', 'venue_estadio_municipal_cicero_de_souza_marques', 'quarta-feira', 'WEEKDAY', 'MORNING', (timestamp '2026-11-04 09:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2652536', 'https://onefootball.com/pt-br/match/2652536', 'HIGH', null),
  ('pb_onef_2652541', 2026, '2026-11-18', '09:00:00', 'SCHEDULED', 'Brasileirão Betano', 'BRASILEIRAO_A', 'Brasileirão Betano 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Vitória', false, false, 'Vitória', 'RB Bragantino', null, null, null, null, null, null, 'Estádio Manoel Barradas', 'MATCH_SPECIFIC', 'venue_estadio_manoel_barradas', 'quarta-feira', 'WEEKDAY', 'MORNING', (timestamp '2026-11-18 09:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2652541', 'https://onefootball.com/pt-br/match/2652541', 'HIGH', null),
  ('pb_onef_2652556', 2026, '2026-11-21', '09:00:00', 'SCHEDULED', 'Brasileirão Betano', 'BRASILEIRAO_A', 'Brasileirão Betano 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Vasco da Gama', true, false, 'RB Bragantino', 'Vasco da Gama', null, null, null, null, null, null, 'Estádio Municipal Cícero de Souza Marques', 'MATCH_SPECIFIC', 'venue_estadio_municipal_cicero_de_souza_marques', 'sábado', 'WEEKEND', 'MORNING', (timestamp '2026-11-21 09:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2652556', 'https://onefootball.com/pt-br/match/2652556', 'HIGH', null),
  ('pb_onef_2652568', 2026, '2026-11-28', '09:00:00', 'SCHEDULED', 'Brasileirão Betano', 'BRASILEIRAO_A', 'Brasileirão Betano 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Internacional', false, false, 'Internacional', 'RB Bragantino', null, null, null, null, null, null, 'Estádio José Pinheiro Borda', 'MATCH_SPECIFIC', 'venue_estadio_jose_pinheiro_borda', 'sábado', 'WEEKEND', 'MORNING', (timestamp '2026-11-28 09:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2652568', 'https://onefootball.com/pt-br/match/2652568', 'HIGH', null),
  ('pb_onef_2652576', 2026, '2026-12-02', '09:00:00', 'SCHEDULED', 'Brasileirão Betano', 'BRASILEIRAO_A', 'Brasileirão Betano 2026', null, 'ROUND_NOT_EXPOSED_BY_SOURCE', 'Fluminense', true, false, 'RB Bragantino', 'Fluminense', null, null, null, null, null, null, 'Estádio Municipal Cícero de Souza Marques', 'MATCH_SPECIFIC', 'venue_estadio_municipal_cicero_de_souza_marques', 'quarta-feira', 'WEEKDAY', 'MORNING', (timestamp '2026-12-02 09:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'OneFootball (api.onefootball.com/web-experience)', '2652576', 'https://onefootball.com/pt-br/match/2652576', 'HIGH', null)
on conflict (id) do update set
    season = excluded.season,
    match_date = excluded.match_date,
    match_time = excluded.match_time,
    status = excluded.status,
    competition = excluded.competition,
    competition_code = excluded.competition_code,
    competition_edition = excluded.competition_edition,
    round = excluded.round,
    phase_status = excluded.phase_status,
    opponent = excluded.opponent,
    club_is_home = excluded.club_is_home,
    neutral_site = excluded.neutral_site,
    home_team = excluded.home_team,
    away_team = excluded.away_team,
    home_score = excluded.home_score,
    away_score = excluded.away_score,
    club_score = excluded.club_score,
    opponent_score = excluded.opponent_score,
    score_display = excluded.score_display,
    outcome = excluded.outcome,
    stadium = excluded.stadium,
    stadium_status = excluded.stadium_status,
    venue_id = excluded.venue_id,
    weekday = excluded.weekday,
    day_type = excluded.day_type,
    day_period = excluded.day_period,
    kickoff_at = excluded.kickoff_at,
    display_timezone = excluded.display_timezone,
    date_precision = excluded.date_precision,
    source_provider = excluded.source_provider,
    source_match_id = excluded.source_match_id,
    source_url = excluded.source_url,
    source_confidence = excluded.source_confidence,
    data_notes = excluded.data_notes,
    updated_at = now();

do $$
declare v_orphans int;
begin
  select count(*) into v_orphans from public.passport_matches
   where season = 2026 and stadium is not null and venue_id is null;
  if v_orphans > 0 then
    raise exception 'ha % partidas de 2026 com estadio sem venue_id -- rode bragantino_passport_venues_seed.sql', v_orphans;
  end if;
end $$;
