-- Adivinhe o Jogador — carreiras do Bragantino, reconstruídas a partir do
-- pacote docs/bragantino_data/new_data/adivinhe_jogador_30_carreiras_v1.json
-- (que só tinha nome de clube, sem período nenhum) + pesquisa própria
-- (Wikipedia PT/EN, ogol, imprensa), 2026-09-08.
--
-- 20 READY (período+clube confirmado por fonte) + 7 PARTIAL
-- (pelo menos a passagem pelo Bragantino confirmada; o resto da carreira
-- some quando não achei fonte com período — nunca inventado). 3 ficaram de
-- fora (Carlos Augusto, Souza, Robert): fonte insuficiente ou risco real de
-- homônimo (nomes comuns, vários jogadores com o mesmo nome na época).
--
-- `is_goias` no jsonb é só o flag de destaque visual da linha (nome
-- herdado da tabela compartilhada com o Goiás, ver
-- `lib/features/arena/games/career_path/career_models.dart`) — aqui
-- marca a(s) passagem(ns) pelo BRAGANTINO, nunca pelo Goiás.
--
-- Rodar no SQL editor do projeto Supabase do BRAGANTINO
-- (yrgyzkaaudyzmsqwzecj).

insert into public.career_players (id, club_id, answer, accepted_answers, position, club_career, sort_order) values
('marcelo_martelotte', '51683d2a-ea1d-57c6-8014-996146f242e7', 'Marcelo Martelotte', '["Marcelo Martelotte","Martelotte"]'::jsonb, 'Goleiro', '[{"period":"1987–1988","team":"Taubaté","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"1989–1996","team":"Bragantino","appearances":null,"goals":null,"loan":false,"is_goias":true},{"period":"1993","team":"Santa Cruz","appearances":null,"goals":null,"loan":true,"is_goias":false},{"period":"1997–1998","team":"Santos","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"2000","team":"Sport","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"2002","team":"Taubaté","appearances":null,"goals":null,"loan":false,"is_goias":false}]'::jsonb, 1),
('nivaldo_penafiel', '51683d2a-ea1d-57c6-8014-996146f242e7', 'Nivaldo', '["Nivaldo","Nivaldo Penafiel"]'::jsonb, 'Goleiro', '[{"period":"1988","team":"Noroeste","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"1990","team":"Bragantino","appearances":null,"goals":null,"loan":false,"is_goias":true},{"period":"1991","team":"Palmeiras","appearances":null,"goals":null,"loan":false,"is_goias":false}]'::jsonb, 2),
('gil_baiano', '51683d2a-ea1d-57c6-8014-996146f242e7', 'Gil Baiano', '["Gil Baiano","José Gildásio Pereira de Matos"]'::jsonb, 'Lateral-direito', '[{"period":"1987–1988","team":"Guarani","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"1988–1993","team":"Bragantino","appearances":62,"goals":null,"loan":false,"is_goias":true},{"period":"1993–1994","team":"Palmeiras","appearances":7,"goals":null,"loan":false,"is_goias":false},{"period":"1994","team":"Vitória","appearances":19,"goals":null,"loan":false,"is_goias":false},{"period":"1995–1996","team":"Paraná","appearances":20,"goals":null,"loan":false,"is_goias":false},{"period":"1996–1997","team":"Sporting CP","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"1998","team":"Ituano","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"1998","team":"Paraná","appearances":9,"goals":null,"loan":false,"is_goias":false},{"period":"1999","team":"Bragantino","appearances":null,"goals":null,"loan":false,"is_goias":true},{"period":"2000","team":"Comercial-SP","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"2000","team":"Paraná","appearances":4,"goals":null,"loan":false,"is_goias":false},{"period":"2001","team":"XV de Piracicaba","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"2002","team":"Bragantino","appearances":null,"goals":null,"loan":false,"is_goias":true}]'::jsonb, 3),
('biro_biro_ribeiro', '51683d2a-ea1d-57c6-8014-996146f242e7', 'Biro-Biro', '["Biro-Biro","Gilberto Ribeiro de Carvalho"]'::jsonb, 'Lateral-esquerdo', '[{"period":"1982–1984","team":"Santos","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"1985–1992","team":"Bragantino","appearances":null,"goals":null,"loan":false,"is_goias":true},{"period":"1992","team":"Sport","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"1993","team":"Corinthians","appearances":8,"goals":0,"loan":false,"is_goias":false},{"period":"1993","team":"Sport","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"1996","team":"Bragantino","appearances":null,"goals":null,"loan":false,"is_goias":true},{"period":"1996–1997","team":"XV de Piracicaba","appearances":null,"goals":null,"loan":false,"is_goias":false}]'::jsonb, 4),
('junior_paulista', '51683d2a-ea1d-57c6-8014-996146f242e7', 'Júnior Paulista', '["Júnior Paulista","Antônio Carlos Ribeiro Júnior"]'::jsonb, 'Zagueiro', '[{"period":"1988","team":"Bragantino","appearances":null,"goals":null,"loan":false,"is_goias":true}]'::jsonb, 5),
('nei_bragantino', '51683d2a-ea1d-57c6-8014-996146f242e7', 'Nei', '["Nei"]'::jsonb, 'Zagueiro', '[{"period":"1990–1991","team":"Bragantino","appearances":null,"goals":null,"loan":false,"is_goias":true}]'::jsonb, 6),
('pintado', '51683d2a-ea1d-57c6-8014-996146f242e7', 'Pintado', '["Pintado","Luís Carlos de Oliveira Preto"]'::jsonb, 'Zagueiro', '[{"period":"1984","team":"São Paulo","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"1986","team":"Taubaté","appearances":null,"goals":null,"loan":true,"is_goias":false},{"period":"1987","team":"São Paulo","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"1988–1990","team":"Bragantino","appearances":null,"goals":null,"loan":true,"is_goias":true}]'::jsonb, 7),
('mauro_silva', '51683d2a-ea1d-57c6-8014-996146f242e7', 'Mauro Silva', '["Mauro Silva","Mauro da Silva Gomes"]'::jsonb, 'Volante', '[{"period":"1986–1989","team":"Guarani","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"1989–1992","team":"Bragantino","appearances":null,"goals":null,"loan":false,"is_goias":true},{"period":"1992–2005","team":"Deportivo La Coruña","appearances":458,"goals":null,"loan":false,"is_goias":false}]'::jsonb, 8),
('ivair', '51683d2a-ea1d-57c6-8014-996146f242e7', 'Ivair', '["Ivair"]'::jsonb, 'Volante', '[{"period":"1988–1991","team":"Bragantino","appearances":null,"goals":null,"loan":false,"is_goias":true}]'::jsonb, 9),
('luis_muller', '51683d2a-ea1d-57c6-8014-996146f242e7', 'Luís Müller', '["Luís Müller","Müller","Miguel Luís Müller"]'::jsonb, 'Meia', '[{"period":"1990","team":"Bragantino","appearances":null,"goals":null,"loan":false,"is_goias":true},{"period":"1992–1993","team":"Gamba Osaka","appearances":null,"goals":null,"loan":false,"is_goias":false}]'::jsonb, 10),
('valmir_francisco', '51683d2a-ea1d-57c6-8014-996146f242e7', 'Valmir', '["Valmir","Valmir Francisco da Silva"]'::jsonb, 'Meia', '[{"period":"1982–1987","team":"Ponte Preta","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"1985–1986; 1992","team":"Paysandu","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"1988–1991","team":"Bragantino","appearances":null,"goals":null,"loan":false,"is_goias":true}]'::jsonb, 11),
('joao_santos', '51683d2a-ea1d-57c6-8014-996146f242e7', 'João Santos', '["João Santos","João dos Santos Ferreira"]'::jsonb, 'Meia', '[{"period":"1989–1991","team":"Bragantino","appearances":null,"goals":null,"loan":false,"is_goias":true}]'::jsonb, 12),
('mazinho_oliveira', '51683d2a-ea1d-57c6-8014-996146f242e7', 'Mazinho', '["Mazinho","Waldemar Aureliano de Oliveira Filho"]'::jsonb, 'Atacante', '[{"period":"1983–1988","team":"Santos","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"1988–1990","team":"Athletico-PR","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"1990–1991","team":"Bragantino","appearances":null,"goals":10,"loan":false,"is_goias":true},{"period":"1991–1995","team":"Bayern de Munique","appearances":56,"goals":null,"loan":false,"is_goias":false},{"period":"1995–1999","team":"Kashima Antlers","appearances":100,"goals":52,"loan":false,"is_goias":false},{"period":"2001","team":"Bragantino","appearances":null,"goals":null,"loan":false,"is_goias":true}]'::jsonb, 13),
('mario_maguila', '51683d2a-ea1d-57c6-8014-996146f242e7', 'Mário', '["Mário","Mário Maguila","Mário Carlos Moraes Soares"]'::jsonb, 'Atacante', '[{"period":"1987–1989","team":"Guarani","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"1989–1990","team":"Bragantino","appearances":null,"goals":null,"loan":false,"is_goias":true},{"period":"1991","team":"Celta de Vigo","appearances":10,"goals":2,"loan":false,"is_goias":false},{"period":"1991","team":"Bragantino","appearances":null,"goals":null,"loan":false,"is_goias":true},{"period":"1991–1992","team":"Dunakanyar-Vác","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"1993","team":"Náutico","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"1994–1995","team":"Juventude","appearances":39,"goals":28,"loan":false,"is_goias":false}]'::jsonb, 14),
('silvio_mariola', '51683d2a-ea1d-57c6-8014-996146f242e7', 'Sílvio', '["Sílvio","Sílvio Mariola","Sílvio César Ferreira da Costa"]'::jsonb, 'Atacante', '[{"period":"1990–1994","team":"Bragantino","appearances":null,"goals":null,"loan":false,"is_goias":true},{"period":"1994–1995","team":"Logroñés","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"1995","team":"Paraná","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"1996","team":"Grêmio","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"1996","team":"Guarani","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"1996","team":"Goiás","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"1997","team":"Internacional","appearances":null,"goals":null,"loan":false,"is_goias":false}]'::jsonb, 15),
('tiba_guedes', '51683d2a-ea1d-57c6-8014-996146f242e7', 'Tiba', '["Tiba","Arione Ferreira Guedes"]'::jsonb, 'Atacante', '[{"period":"1988–1991","team":"Vasco","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"1989–1990","team":"Bragantino","appearances":null,"goals":null,"loan":true,"is_goias":true},{"period":"1993","team":"Paraná","appearances":null,"goals":null,"loan":true,"is_goias":false},{"period":"1994–1996","team":"Portuguesa","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"1996–1997","team":"Corinthians","appearances":13,"goals":6,"loan":false,"is_goias":false},{"period":"1998","team":"Ituano","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"1998","team":"Portuguesa","appearances":null,"goals":null,"loan":false,"is_goias":false}]'::jsonb, 16),
('franklin_bittencourt', '51683d2a-ea1d-57c6-8014-996146f242e7', 'Franklin', '["Franklin","Franklin Bittencourt","Franklin Spencer Miguel Bittencourt"]'::jsonb, 'Atacante', '[{"period":"1989–1990","team":"Fluminense","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"1991","team":"Bragantino","appearances":2,"goals":1,"loan":false,"is_goias":true},{"period":"1992–1998","team":"VfB Leipzig","appearances":105,"goals":20,"loan":false,"is_goias":false},{"period":"1998–2003","team":"Energie Cottbus","appearances":84,"goals":22,"loan":false,"is_goias":false}]'::jsonb, 17),
('leo_ortiz', '51683d2a-ea1d-57c6-8014-996146f242e7', 'Léo Ortiz', '["Léo Ortiz"]'::jsonb, 'Zagueiro', '[{"period":"2012–2017","team":"Internacional","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"2018","team":"Sport","appearances":null,"goals":null,"loan":true,"is_goias":false},{"period":"2019–2023","team":"Red Bull Bragantino","appearances":198,"goals":14,"loan":false,"is_goias":true},{"period":"2024–atual","team":"Flamengo","appearances":null,"goals":null,"loan":false,"is_goias":false}]'::jsonb, 18),
('artur_victor', '51683d2a-ea1d-57c6-8014-996146f242e7', 'Artur', '["Artur","Artur Victor Guimarães"]'::jsonb, 'Ponta-direita', '[{"period":"2016–2019","team":"Palmeiras","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"2019","team":"Bahia","appearances":null,"goals":null,"loan":true,"is_goias":false},{"period":"2020–2023","team":"Red Bull Bragantino","appearances":170,"goals":38,"loan":false,"is_goias":true},{"period":"2024–atual","team":"Zenit","appearances":null,"goals":null,"loan":false,"is_goias":false}]'::jsonb, 19),
('aderlan_silva', '51683d2a-ea1d-57c6-8014-996146f242e7', 'Aderlan', '["Aderlan","Aderlan de Lima Silva"]'::jsonb, 'Lateral-direito', '[{"period":"2009","team":"Campinense","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"2019–2023","team":"Red Bull Bragantino","appearances":218,"goals":6,"loan":false,"is_goias":true},{"period":"2024","team":"Santos","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"2025","team":"Sport","appearances":null,"goals":null,"loan":false,"is_goias":false}]'::jsonb, 20),
('fabricio_bruno', '51683d2a-ea1d-57c6-8014-996146f242e7', 'Fabrício Bruno', '["Fabrício Bruno","Fabrício Bruno Soares de Faria"]'::jsonb, 'Zagueiro', '[{"period":"2016–2019","team":"Cruzeiro","appearances":30,"goals":null,"loan":false,"is_goias":false},{"period":"2017–2018","team":"Chapecoense","appearances":46,"goals":2,"loan":true,"is_goias":false},{"period":"2020–2022","team":"Red Bull Bragantino","appearances":65,"goals":1,"loan":false,"is_goias":true},{"period":"2022–2024","team":"Flamengo","appearances":103,"goals":6,"loan":false,"is_goias":false},{"period":"2025–atual","team":"Cruzeiro","appearances":null,"goals":null,"loan":false,"is_goias":false}]'::jsonb, 21),
('helinho', '51683d2a-ea1d-57c6-8014-996146f242e7', 'Helinho', '["Helinho","Hélio Júnior Nunes de Castro"]'::jsonb, 'Ponta', '[{"period":"2018–2021","team":"São Paulo","appearances":31,"goals":2,"loan":false,"is_goias":false},{"period":"2020–2021","team":"Red Bull Bragantino","appearances":50,"goals":10,"loan":true,"is_goias":true},{"period":"2022–2024","team":"Red Bull Bragantino","appearances":65,"goals":13,"loan":false,"is_goias":true},{"period":"2024–atual","team":"Toluca","appearances":53,"goals":14,"loan":false,"is_goias":false}]'::jsonb, 22),
('luan_candido', '51683d2a-ea1d-57c6-8014-996146f242e7', 'Luan Cândido', '["Luan Cândido","Luan Cândido de Almeida"]'::jsonb, 'Lateral-esquerdo', '[{"period":"2019–2020","team":"RB Leipzig","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"2020–2025","team":"Red Bull Bragantino","appearances":200,"goals":21,"loan":false,"is_goias":true},{"period":"2025","team":"Grêmio","appearances":null,"goals":null,"loan":true,"is_goias":false},{"period":"2025","team":"Sport","appearances":null,"goals":null,"loan":true,"is_goias":false},{"period":"2025–2026","team":"Vitória","appearances":null,"goals":null,"loan":true,"is_goias":false}]'::jsonb, 23),
('lucas_evangelista', '51683d2a-ea1d-57c6-8014-996146f242e7', 'Lucas Evangelista', '["Lucas Evangelista","Lucas Evangelista Santana de Oliveira"]'::jsonb, 'Meio-campo', '[{"period":"2013–2014","team":"São Paulo","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"2014–2016","team":"Udinese","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"2016","team":"Panathinaikos","appearances":null,"goals":null,"loan":true,"is_goias":false},{"period":"2018","team":"Nantes","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"2020","team":"Red Bull Bragantino","appearances":null,"goals":null,"loan":true,"is_goias":true},{"period":"2021–2025","team":"Red Bull Bragantino","appearances":null,"goals":null,"loan":false,"is_goias":true},{"period":"2025–atual","team":"Palmeiras","appearances":null,"goals":null,"loan":false,"is_goias":false}]'::jsonb, 24),
('juninho_capixaba', '51683d2a-ea1d-57c6-8014-996146f242e7', 'Juninho Capixaba', '["Juninho Capixaba","Luis Antônio da Rocha Júnior"]'::jsonb, 'Lateral-esquerdo', '[{"period":"2015–2017","team":"Bahia","appearances":26,"goals":null,"loan":false,"is_goias":false},{"period":"2018–2019","team":"Corinthians","appearances":9,"goals":null,"loan":false,"is_goias":false},{"period":"2018–2019","team":"Grêmio","appearances":16,"goals":5,"loan":true,"is_goias":false},{"period":"2019–2022","team":"Grêmio","appearances":15,"goals":null,"loan":false,"is_goias":false},{"period":"2020–2021","team":"Bahia","appearances":56,"goals":null,"loan":true,"is_goias":false},{"period":"2022","team":"Fortaleza","appearances":34,"goals":3,"loan":true,"is_goias":false},{"period":"2023–atual","team":"Red Bull Bragantino","appearances":132,"goals":9,"loan":false,"is_goias":true}]'::jsonb, 25),
('eduardo_sasha', '51683d2a-ea1d-57c6-8014-996146f242e7', 'Eduardo Sasha', '["Eduardo Sasha","Sasha","Eduardo Colcenti Antunes"]'::jsonb, 'Atacante', '[{"period":"2010–2012","team":"Internacional","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"2012–2013","team":"Goiás","appearances":null,"goals":null,"loan":true,"is_goias":false},{"period":"2014–2017","team":"Internacional","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"2018–2019","team":"Santos","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"2020–2023","team":"Atlético-MG","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"2023–atual","team":"Red Bull Bragantino","appearances":null,"goals":null,"loan":false,"is_goias":true}]'::jsonb, 26),
('claudinho', '51683d2a-ea1d-57c6-8014-996146f242e7', 'Claudinho', '["Claudinho","Cláudio Luiz Rodrigues Parise Leonel"]'::jsonb, 'Meia', '[{"period":"2015–2017","team":"Corinthians","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"2016","team":"Bragantino","appearances":null,"goals":null,"loan":true,"is_goias":true},{"period":"2017","team":"Santo André","appearances":null,"goals":null,"loan":true,"is_goias":false},{"period":"2018","team":"Red Bull Brasil","appearances":null,"goals":null,"loan":true,"is_goias":false},{"period":"2018","team":"Oeste","appearances":null,"goals":null,"loan":true,"is_goias":false},{"period":"2017–2019","team":"Ponte Preta","appearances":null,"goals":null,"loan":false,"is_goias":false},{"period":"2019–2021","team":"Red Bull Bragantino","appearances":99,"goals":32,"loan":false,"is_goias":true},{"period":"2021–2025","team":"Zenit","appearances":93,"goals":17,"loan":false,"is_goias":false},{"period":"2025–atual","team":"Al-Sadd","appearances":18,"goals":3,"loan":false,"is_goias":false}]'::jsonb, 27)
on conflict (id) do update set
  club_id = excluded.club_id, answer = excluded.answer, accepted_answers = excluded.accepted_answers,
  position = excluded.position, club_career = excluded.club_career, sort_order = excluded.sort_order;
