-- ============================================================================
-- SUPERSEDED — NÃO RODE ESTE ARQUIVO.
--
-- Este DDL foi escrito para CRIAR `public.passport_matches` no projeto do
-- Bragantino. Testando o banco ao vivo em 2026-09-07, a tabela JÁ EXISTIA, com
-- o schema herdado do Goiás — e com um formato diferente do que este arquivo
-- declarava:
--
--   já existiam e este arquivo não declarava:  venue_id, kickoff_at,
--                                              display_timezone, date_precision
--   este arquivo declarava e não existiam:     stadium, stadium_status,
--                                              competition_edition, phase_status,
--                                              weekday, day_type, day_period,
--                                              venue_city/state/country
--
-- Como o DDL era `create table if not exists`, rodá-lo não teria dado erro
-- nenhum: ele simplesmente não faria nada, e o schema real continuaria sem as
-- colunas de enriquecimento — falha silenciosa, o pior tipo.
--
-- O que vale hoje:
--   supabase/bragantino_passport_infra.sql        -> adiciona só o que falta
--   supabase/bragantino_passport_venues_seed.sql  -> catálogo de estádios
--   supabase/bragantino_passport_matches_*_seed.sql -> as 186 partidas
--
-- Também caiu por terra, no mesmo teste ao vivo, o "bug" que este arquivo
-- documentava: a RPC do Goiás devolveria `goias_is_home`/`goias_score` em vez
-- de `club_is_home`/`club_score`. Em produção ela devolve os nomes genéricos
-- corretos; quem está defasado é o `supabase/passport_esmeraldino_functions.sql`
-- versionado aqui. Não havia bug e nada foi alterado.
--
-- Mantido no repositório só como registro: `venue_city`/`venue_state`/
-- `venue_country` deliberadamente NÃO foram para `passport_matches`, porque a
-- localização do estádio mora em `venues` e é de lá que a RPC lê.
-- ============================================================================
