-- ============================================================================
-- Quem Vestiu o Manto — catálogo de jogadores. Rode no SQL Editor do
-- Supabase. A tabela vira a fonte da verdade; o app cai no banco local
-- (const guessPlayerCatalog) se a tabela estiver vazia ou sem rede. Leitura
-- é pública; escrita só pelo dashboard/admin. `photo_key` guarda só a
-- chave de `squadPhotoAssets` (só o elenco atual tem foto) — a URL real
-- continua resolvida no Flutter, nunca duplicada aqui. Nunca reaproveitar
-- um `id` pra outro jogador (progresso do usuário é rastreado por id).
-- ============================================================================

create table if not exists public.guess_players (
  id text primary key,
  name text not null,
  display_name text not null,
  aliases jsonb not null default '[]'::jsonb,
  position text,
  shirt_number int,
  academy_club text,
  nationality_code text,
  nationality_name text,
  goias_debut_year int,
  photo_key text,
  data_status text not null default 'incomplete' check (data_status in ('verified','review','incomplete')),
  is_active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);

alter table public.guess_players enable row level security;

drop policy if exists "read guess players" on public.guess_players;
create policy "read guess players" on public.guess_players
  for select using (true);

insert into public.guess_players (id, name, display_name, aliases, position, shirt_number, academy_club, nationality_code, nationality_name, goias_debut_year, photo_key, data_status, sort_order) values
('adilson_dos_anjos_oliveira', 'Juninho', 'Juninho', '["Adilson dos Anjos Oliveira"]'::jsonb, 'vol', 8, 'Aparecida-GO', 'BR', 'Brasil', 2025, 'juninho', 'verified', 1),
('aldo', 'Aldo', 'Aldo', '[]'::jsonb, 'zag', null, 'Atlético-MG', 'BR', 'Brasil', 2005, null, 'incomplete', 2),
('alef_manga', 'Alef Manga', 'Alef Manga', '[]'::jsonb, 'ata', 11, 'Santos', 'BR', 'Brasil', 2021, null, 'review', 3),
('alex_dias', 'Alex Dias', 'Alex Dias', '[]'::jsonb, 'ata', 7, 'Remo', 'BR', 'Brasil', 1996, null, 'verified', 4),
('alexandre', 'Alexandre', 'Alexandre', '[]'::jsonb, 'zag', null, 'Valeriodoce', 'BR', 'Brasil', 2003, null, 'incomplete', 5),
('alvaro', 'Álvaro', 'Álvaro', '[]'::jsonb, 'zag', null, 'São Paulo', 'BR', 'Brasil', 1999, null, 'incomplete', 6),
('amaral', 'Amaral', 'Amaral', '[]'::jsonb, 'vol', 8, 'Goiás', 'BR', 'Brasil', 2005, null, 'review', 7),
('andre_dias', 'André Dias', 'André Dias', '[]'::jsonb, 'zag', null, 'Palestra de São Bernardo', 'BR', 'Brasil', 2004, null, 'incomplete', 8),
('andre_leone', 'André Leone', 'André Leone', '[]'::jsonb, 'zag', null, 'Primavera-SP', 'BR', 'Brasil', 2005, null, 'incomplete', 9),
('anselmo_ramon_alves_herculano', 'Anselmo Ramon', 'Anselmo Ramon', '["Anselmo Ramon Alves Herculano"]'::jsonb, 'ata', 9, 'Cruzeiro', 'BR', 'Brasil', 2025, 'anselmo_ramon', 'verified', 10),
('apodi', 'Apodi', 'Apodi', '[]'::jsonb, 'ld', 22, 'Vitória', 'BR', 'Brasil', 2021, null, 'review', 11),
('araujo', 'Araújo', 'Araújo', '[]'::jsonb, 'ata', null, 'Porto-PE', 'BR', 'Brasil', 1997, null, 'incomplete', 12),
('arthur_caike', 'Arthur Caíke', 'Arthur Caíke', '[]'::jsonb, 'ata', null, 'Iraty', 'BR', 'Brasil', 2025, null, 'incomplete', 13),
('artur', 'Artur', 'Artur', '[]'::jsonb, 'le', 6, 'Internacional', 'BR', 'Brasil', 2021, null, 'review', 14),
('augusto', 'Augusto', 'Augusto', '[]'::jsonb, 'le', null, 'Gama', 'BR', 'Brasil', 1992, null, 'incomplete', 15),
('brayann_brito_batista', 'Brayann', 'Brayann', '["Brayann Brito Batista"]'::jsonb, 'mei', 88, null, 'BR', 'Brasil', 2025, 'brayann', 'incomplete', 16),
('breno', 'Breno', 'Breno', '[]'::jsonb, 'le', null, 'Red Bull Brasil', 'BR', 'Brasil', 2018, null, 'incomplete', 17),
('bruno_henrique', 'Bruno Henrique', 'Bruno Henrique', '[]'::jsonb, 'ata', null, null, 'BR', 'Brasil', 2015, null, 'incomplete', 18),
('bruno_melo', 'Bruno Melo', 'Bruno Melo', '[]'::jsonb, 'zag', 19, 'Fortaleza', 'BR', 'Brasil', 2023, null, 'verified', 19),
('caca', 'Cacá', 'Cacá', '[]'::jsonb, 'mei', null, null, 'BR', 'Brasil', 1999, null, 'incomplete', 20),
('caico', 'Caíco', 'Caíco', '[]'::jsonb, 'mei', null, 'Grêmio', 'BR', 'Brasil', 2003, null, 'incomplete', 21),
('caio_vinicius', 'Caio Vinícius', 'Caio Vinícius', '[]'::jsonb, 'vol', 5, 'Fluminense', 'BR', 'Brasil', 2021, null, 'verified', 22),
('caique_sa', 'Caíque Sá', 'Caíque Sá', '[]'::jsonb, 'ld', null, 'Vitória', 'BR', 'Brasil', 2018, null, 'incomplete', 23),
('carlos_alberto', 'Carlos Alberto', 'Carlos Alberto', '[]'::jsonb, 'mei', 2, 'Joinville', 'BR', 'Brasil', 2010, null, 'review', 24),
('carlos_eduardo', 'Carlos Eduardo', 'Carlos Eduardo', '[]'::jsonb, 'ata', null, 'Goiás', 'BR', 'Brasil', 2015, null, 'incomplete', 25),
('carlos_eduardo_amaral_pereira_de_castro', 'Cadu', 'Cadu', '["Carlos Eduardo Amaral Pereira de Castro"]'::jsonb, 'ata', 18, 'Atlético-MG', 'BR', 'Brasil', 2026, 'cadu', 'verified', 26),
('carlos_eduardo_de_sousa_leopoldino', 'Kadu Sousa', 'Kadu Sousa', '["Carlos Eduardo de Sousa Leopoldino"]'::jsonb, 'pe', 40, 'São Joseense-PR', 'BR', 'Brasil', 2026, 'kadu_sousa', 'review', 27),
('cleber_gaucho', 'Cléber Gaúcho', 'Cléber Gaúcho', '[]'::jsonb, 'mc', null, 'Brasil de Pelotas', 'BR', 'Brasil', 2005, null, 'incomplete', 28),
('cleber_goiano', 'Cléber Goiano', 'Cléber Goiano', '[]'::jsonb, 'vol', null, 'Vila Nova', 'BR', 'Brasil', 2003, null, 'incomplete', 29),
('dada_belmonte', 'Dadá Belmonte', 'Dadá Belmonte', '[]'::jsonb, 'ata', 7, 'Salgueiro', 'BR', 'Brasil', 2021, null, 'review', 30),
('dalton', 'Dalton', 'Dalton', '[]'::jsonb, 'le', null, 'Goiânia', 'BR', 'Brasil', null, null, 'incomplete', 31),
('danilo_cunha_da_silva', 'Danilo', 'Danilo', '["Danilo Cunha da Silva"]'::jsonb, 'le', 66, 'Goiás', 'BR', 'Brasil', 2025, 'danilo', 'verified', 32),
('danilo_portugal', 'Danilo Portugal', 'Danilo Portugal', '[]'::jsonb, 'vol', null, 'Goiás', 'BR', 'Brasil', 2003, null, 'incomplete', 33),
('david', 'David', 'David', '[]'::jsonb, 'vol', 45, 'Atlético-MG', 'BR', 'Brasil', 2012, null, 'verified', 34),
('david_duarte', 'David Duarte', 'David Duarte', '[]'::jsonb, 'zag', 3, 'Goiás', 'BR', 'Brasil', 2015, null, 'verified', 35),
('diego_caito', 'Diego Caito', 'Diego Caito', '[]'::jsonb, 'ld', 20, 'Goiás', 'BR', 'Brasil', 2024, null, 'verified', 36),
('diego_goncalves', 'Diego Gonçalves', 'Diego Gonçalves', '[]'::jsonb, 'ata', 11, 'Fluminense', 'BR', 'Brasil', 2023, null, 'review', 37),
('dieguinho', 'Dieguinho', 'Dieguinho', '[]'::jsonb, 'ld', 20, null, 'BR', 'Brasil', 2021, null, 'incomplete', 38),
('dimba', 'Dimba', 'Dimba', '[]'::jsonb, 'ata', 9, 'Sobradinho-DF', 'BR', 'Brasil', 2003, null, 'review', 39),
('djalma_antonio_da_silva_filho', 'Djalma', 'Djalma', '["Djalma Antônio da Silva Filho"]'::jsonb, 'le', 54, null, 'BR', 'Brasil', 2026, 'djalma', 'incomplete', 40),
('douglas', 'Douglas', 'Douglas', '[]'::jsonb, 'ld', 20, 'Goiás', 'BR', 'Brasil', 2009, null, 'review', 41),
('dudu_cearense', 'Dudu Cearense', 'Dudu Cearense', '[]'::jsonb, 'vol', 8, 'Vitória', 'BR', 'Brasil', 2012, null, 'verified', 42),
('eduardo_brock', 'Eduardo Brock', 'Eduardo Brock', '[]'::jsonb, 'zag', null, 'Grêmio', 'BR', 'Brasil', 2018, null, 'incomplete', 43),
('eduardo_heuser', 'Eduardo Heuser', 'Eduardo Heuser', '[]'::jsonb, 'gol', null, null, 'BR', 'Brasil', null, null, 'incomplete', 44),
('eduardo_sasha', 'Eduardo Sasha', 'Eduardo Sasha', '[]'::jsonb, 'ata', 17, 'Internacional', 'BR', 'Brasil', 2012, null, 'verified', 45),
('egidio', 'Egídio', 'Egídio', '[]'::jsonb, 'le', 6, 'Flamengo', 'BR', 'Brasil', 2012, null, 'verified', 46),
('elvis', 'Élvis', 'Élvis', '[]'::jsonb, 'mei', 10, 'Botafogo', 'BR', 'Brasil', 2021, null, 'verified', 47),
('erik', 'Erik', 'Erik', '[]'::jsonb, 'ata', 11, 'Goiás', 'BR', 'Brasil', 2013, null, 'verified', 48),
('ernando', 'Ernando', 'Ernando', '[]'::jsonb, 'zag', 4, 'Goiás', 'BR', 'Brasil', 2006, null, 'verified', 49),
('esli_samuel_garcia_cordero', 'Esli Garcia', 'Esli Garcia', '["Esli Samuel García Cordero"]'::jsonb, 'pe', 15, 'Portuguesa FC (Venezuela)', 'VE', 'Venezuela', 2025, 'esli_garcia', 'review', 50),
('esquerdinha', 'Esquerdinha', 'Esquerdinha', '[]'::jsonb, 'le', null, null, 'BR', 'Brasil', 2003, null, 'incomplete', 51),
('evair', 'Evair', 'Evair', '[]'::jsonb, 'ata', null, 'Guarani', 'BR', 'Brasil', 2000, null, 'incomplete', 52),
('evandro', 'Evandro', 'Evandro', '[]'::jsonb, 'ata', null, 'Goiás', 'BR', 'Brasil', 1993, null, 'incomplete', 53),
('everton_morelli', 'Everton Morelli', 'Everton Morelli', '[]'::jsonb, 'vol', 40, 'Ituano', 'BR', 'Brasil', 2023, null, 'verified', 54),
('ezequiel_alves_de_oliveira_vieira', 'Ezequiel', 'Ezequiel', '["Ezequiel Alves de Oliveira Vieira"]'::jsonb, 'gol', 12, 'Cruzeiro', 'BR', 'Brasil', null, 'ezequiel', 'incomplete', 55),
('fabao', 'Fabão', 'Fabão', '[]'::jsonb, 'zag', null, 'Bahia', 'BR', 'Brasil', 2002, null, 'incomplete', 56),
('fabiano', 'Fabiano', 'Fabiano', '[]'::jsonb, 'zag', null, 'Flamengo', 'BR', 'Brasil', 2006, null, 'incomplete', 57),
('fagundes', 'Fagundes', 'Fagundes', '[]'::jsonb, 'mc', null, 'Goiânia', 'BR', 'Brasil', 1985, null, 'incomplete', 58),
('fellipe_bastos', 'Fellipe Bastos', 'Fellipe Bastos', '[]'::jsonb, 'vol', 8, 'Botafogo', 'BR', 'Brasil', 2021, null, 'verified', 59),
('fernandao', 'Fernandão', 'Fernandão', '[]'::jsonb, 'ata', 9, 'Goiás', 'BR', 'Brasil', 1996, null, 'verified', 60),
('fernando_nunes', 'Fernando Nunes', 'Fernando Nunes', '[]'::jsonb, 'le', null, null, 'BR', 'Brasil', 1999, null, 'incomplete', 61),
('geirton_marques_aires', 'Gegê', 'Gegê', '["Geirton Marques Aires"]'::jsonb, 'mc', 28, 'Botafogo', 'BR', 'Brasil', 2026, 'gege', 'verified', 62),
('gil_baiano', 'Gil Baiano', 'Gil Baiano', '[]'::jsonb, 'ld', null, 'Bahia', 'BR', 'Brasil', 2003, null, 'incomplete', 63),
('giovanni', 'Giovanni', 'Giovanni', '[]'::jsonb, 'mc', null, 'Atlético-MG', 'BR', 'Brasil', 2018, null, 'incomplete', 64),
('gonzalo_freitas', 'Gonzalo Freitas', 'Gonzalo Freitas', '[]'::jsonb, 'vol', 5, 'Bella Vista', 'UY', 'Uruguai', 2025, null, 'review', 65),
('grafite', 'Grafite', 'Grafite', '[]'::jsonb, 'ata', null, null, 'BR', 'Brasil', 2003, null, 'incomplete', 66),
('guilherme_baldoria_de_camargo', 'Baldória', 'Baldória', '["Guilherme Baldória de Camargo"]'::jsonb, 'vol', 55, 'Goiás', 'BR', 'Brasil', 2025, 'baldoria', 'verified', 67),
('gustavo', 'Gustavo', 'Gustavo', '[]'::jsonb, null, null, null, 'BR', 'Brasil', 2003, null, 'incomplete', 68),
('halerrandrio_dos_santos_feitosa', 'Halerrandrio', 'Halerrandrio', '["Halerrandrio dos Santos Feitosa"]'::jsonb, 'pd', 11, 'Goiás', 'BR', 'Brasil', 2023, 'halerrandrio', 'review', 69),
('harlei', 'Harlei', 'Harlei', '[]'::jsonb, 'gol', 1, 'Cruzeiro', 'BR', 'Brasil', 1999, null, 'verified', 70),
('hugo_identity_review', 'Hugo', 'Hugo', '[]'::jsonb, null, null, null, 'BR', 'Brasil', null, null, 'incomplete', 71),
('iarley', 'Iarley', 'Iarley', '[]'::jsonb, 'ata', null, 'Ferroviário', 'BR', 'Brasil', 2008, null, 'incomplete', 72),
('indio', 'Índio', 'Índio', '[]'::jsonb, 'ld', null, 'Nacional-SP', 'BR', 'Brasil', 1996, null, 'incomplete', 73),
('jadilson', 'Jadílson', 'Jadílson', '[]'::jsonb, 'le', 6, 'CRB', 'BR', 'Brasil', 2004, null, 'verified', 74),
('jaja', 'Jajá', 'Jajá', '[]'::jsonb, 'ata', 7, 'Athletico-PR', 'BR', 'Brasil', 2025, null, 'review', 75),
('jaques', 'Jaques', 'Jaques', '[]'::jsonb, 'ata', null, null, 'BR', 'Brasil', 1996, null, 'incomplete', 76),
('jean_carlos_alves_ferreira', 'Jean Carlos', 'Jean Carlos', '["Jean Carlos Alves Ferreira"]'::jsonb, 'mei', 21, 'Goiás', 'BR', 'Brasil', 2025, 'jean_carlos', 'verified', 77),
('joao_paulo_ferreira_lourenco', 'Lourenço', 'Lourenço', '["João Paulo Ferreira Lourenço"]'::jsonb, 'vol', 97, 'União Luziense-MG', 'BR', 'Brasil', 2026, 'lourenco', 'verified', 78),
('jorge_batata', 'Jorge Batata', 'Jorge Batata', '[]'::jsonb, 'zag', null, 'São Borja-RS', 'BR', 'Brasil', 1987, null, 'incomplete', 79),
('josue', 'Josué', 'Josué', '[]'::jsonb, 'vol', null, 'Porto-PE', 'BR', 'Brasil', 1997, null, 'incomplete', 80),
('julian_palacios', 'Julián Palacios', 'Julián Palacios', '[]'::jsonb, 'mei', 10, 'San Lorenzo', 'AR', 'Argentina', 2023, null, 'verified', 81),
('juliano', 'Juliano', 'Juliano', '[]'::jsonb, 'mei', null, null, 'BR', 'Brasil', 2005, null, 'incomplete', 82),
('julio_cesar_identity_review', 'Júlio César', 'Júlio César', '[]'::jsonb, null, null, null, 'BR', 'Brasil', null, null, 'incomplete', 83),
('julio_santos', 'Júlio Santos', 'Júlio Santos', '[]'::jsonb, 'zag', null, 'São Paulo', 'BR', 'Brasil', 2005, null, 'incomplete', 84),
('junior_vicosa', 'Júnior Viçosa', 'Júnior Viçosa', '[]'::jsonb, 'ata', null, 'Igaci', 'BR', 'Brasil', 2018, null, 'incomplete', 85),
('kleber', 'Kléber', 'Kléber', '[]'::jsonb, 'gol', null, 'Goiás', 'BR', 'Brasil', 1991, null, 'incomplete', 86),
('leandro_smith', 'Leandro Smith', 'Leandro Smith', '[]'::jsonb, 'le', null, null, 'BR', 'Brasil', 2003, null, 'incomplete', 87),
('leo_sena', 'Léo Sena', 'Léo Sena', '[]'::jsonb, 'vol', null, 'Goiás', 'BR', 'Brasil', 2016, null, 'incomplete', 88),
('leonardo', 'Leonardo', 'Leonardo', '[]'::jsonb, 'zag', null, null, 'BR', 'Brasil', 2006, null, 'incomplete', 89),
('luan_dias', 'Luan Dias', 'Luan Dias', '[]'::jsonb, 'mei', null, 'Água Santa', 'BR', 'Brasil', 2021, null, 'incomplete', 90),
('lucas_halter', 'Lucas Halter', 'Lucas Halter', '[]'::jsonb, 'zag', 3, 'Athletico-PR', 'BR', 'Brasil', 2023, null, 'verified', 91),
('lucas_lovat', 'Lucas Lovat', 'Lucas Lovat', '[]'::jsonb, 'le', 36, 'Grêmio', 'BR', 'Brasil', 2025, null, 'verified', 92),
('lucas_rafael_araujo_lima', 'Lucas Lima', 'Lucas Lima', '["Lucas Rafael Araújo Lima"]'::jsonb, 'mei', 10, 'Inter de Limeira', 'BR', 'Brasil', 2026, 'lucas_lima', 'verified', 93),
('lucas_ribeiro_dos_santos', 'Lucas Ribeiro', 'Lucas Ribeiro', '["Lucas Ribeiro dos Santos"]'::jsonb, 'zag', 14, 'Vitória', 'BR', 'Brasil', 2024, 'lucas_ribeiro', 'verified', 94),
('lucas_rodrigues_moreira_costa', 'Lucas Rodrigues', 'Lucas Rodrigues', '["Lucas Rodrigues Moreira Costa"]'::jsonb, 'vol', 35, 'Goiás', 'BR', 'Brasil', 2025, 'lucas_rodrigues', 'verified', 95),
('luciano_almeida', 'Luciano Almeida', 'Luciano Almeida', '[]'::jsonb, 'le', null, 'Caxias', 'BR', 'Brasil', 2002, null, 'incomplete', 96),
('lucio', 'Lúcio', 'Lúcio', '[]'::jsonb, 'mei', null, null, 'BR', 'Brasil', 1994, null, 'incomplete', 97),
('luis_fellipe_campos_doria', 'Luisão', 'Luisão', '["Luis Fellipe Campos Doria"]'::jsonb, 'zag', 25, 'Osasco Audax', 'BR', 'Brasil', 2026, 'luisao', 'verified', 98),
('luiz_felipe_clemente_de_almeida', 'Felipe Clemente', 'Felipe Clemente', '["Luiz Felipe Clemente de Almeida"]'::jsonb, 'ata', 11, 'América-MG', 'BR', 'Brasil', null, 'felipe_clemente', 'incomplete', 99),
('luiz_felipe_do_nascimento_dos_santos', 'Luiz Felipe', 'Luiz Felipe', '["Luiz Felipe do Nascimento dos Santos"]'::jsonb, 'zag', 3, 'Caxias', 'BR', 'Brasil', 2025, 'luiz_felipe', 'verified', 100),
('luiz_filipe_da_rosa_machado', 'Filipe Machado', 'Filipe Machado', '["Luiz Filipe da Rosa Machado"]'::jsonb, 'vol', 5, 'Grêmio', 'BR', 'Brasil', 2026, 'filipe_machado', 'verified', 101),
('luvanor', 'Luvanor', 'Luvanor', '[]'::jsonb, 'mei', null, 'Goiás', 'BR', 'Brasil', 1977, null, 'incomplete', 102),
('madison', 'Madison', 'Madison', '[]'::jsonb, 'mc', null, 'Goiás', 'BR', 'Brasil', 2018, null, 'incomplete', 103),
('maguinho', 'Maguinho', 'Maguinho', '[]'::jsonb, 'ld', 2, 'Tupi', 'BR', 'Brasil', 2022, null, 'verified', 104),
('maraba', 'Marabá', 'Marabá', '[]'::jsonb, 'vol', null, null, 'BR', 'Brasil', 1999, null, 'incomplete', 105),
('maranhao', 'Maranhão', 'Maranhão', '[]'::jsonb, 'ata', null, null, 'BR', 'Brasil', 2018, null, 'incomplete', 106),
('marcao_identity_review', 'Marcão', 'Marcão', '[]'::jsonb, null, null, null, 'BR', 'Brasil', null, null, 'incomplete', 107),
('marcelo_costa', 'Marcelo Costa', 'Marcelo Costa', '[]'::jsonb, 'mei', 17, null, 'BR', 'Brasil', 2010, null, 'incomplete', 108),
('marcelo_rangel', 'Marcelo Rangel', 'Marcelo Rangel', '[]'::jsonb, 'gol', null, null, 'BR', 'Brasil', 2017, null, 'incomplete', 109),
('marcos_vinicius_da_silva_santos', 'Marcos Vinicius', 'Marcos Vinicius', '["Marcos Vinicius da Silva Santos"]'::jsonb, 'ld', 63, 'Atlético Tubarão', 'BR', 'Brasil', 2026, 'marcos_vinicius', 'verified', 110),
('matheus_peixoto', 'Matheus Peixoto', 'Matheus Peixoto', '[]'::jsonb, 'ata', 17, 'Audax-RJ', 'BR', 'Brasil', 2023, null, 'verified', 111),
('messias', 'Messias', 'Messias', '[]'::jsonb, 'zag', 75, 'América-MG', 'BR', 'Brasil', 2024, null, 'review', 112),
('michael', 'Michael', 'Michael', '[]'::jsonb, 'ata', 11, null, 'BR', 'Brasil', 2017, null, 'incomplete', 113),
('michel_santana', 'Michel Santana', 'Michel Santana', '[]'::jsonb, 'ld', null, null, 'BR', 'Brasil', 2003, null, 'incomplete', 114),
('murillo_carvalho_victorio', 'Murillo Victorio', 'Murillo Victorio', '["Murillo Carvalho Victorio"]'::jsonb, 'gol', 32, 'Goiás', 'BR', 'Brasil', null, 'murillo_victorio', 'incomplete', 115),
('murilo_camara_saquetti_chimelo_pereira', 'Murilo Câmara', 'Murilo Câmara', '["Murilo Camara Saquetti Chimelo Pereira"]'::jsonb, 'zag', 29, 'Rio Branco-SP', 'BR', 'Brasil', 2025, 'murilo_camara', 'verified', 116),
('nenem', 'Neném', 'Neném', '[]'::jsonb, 'ld', null, 'Palmeiras', 'BR', 'Brasil', 1999, null, 'incomplete', 117),
('nicolas_vichiatto_da_silva', 'Nicolas', 'Nicolas', '["Nicolas Vichiatto da Silva"]'::jsonb, 'le', 6, 'Athletico-PR', 'BR', 'Brasil', 2026, 'nicolas', 'verified', 118),
('niltinho', 'Niltinho', 'Niltinho', '[]'::jsonb, 'ata', null, 'Goiânia', 'BR', 'Brasil', 1987, null, 'incomplete', 119),
('nonato', 'Nonato', 'Nonato', '[]'::jsonb, 'ata', null, 'Bahia', 'BR', 'Brasil', 2006, null, 'incomplete', 120),
('otacilio_neto', 'Otacílio Neto', 'Otacílio Neto', '[]'::jsonb, 'ata', 22, 'Ceará', 'BR', 'Brasil', 2010, null, 'verified', 121),
('paulo_baier', 'Paulo Baier', 'Paulo Baier', '[]'::jsonb, 'mei', 10, 'São Luiz-RS', 'BR', 'Brasil', 2004, null, 'review', 122),
('pedro_junqueira_de_oliveira', 'Pedrinho', 'Pedrinho', '["Pedro Junqueira de Oliveira"]'::jsonb, 'ata', 17, 'Goiás', 'BR', 'Brasil', 2022, 'pedrinho', 'review', 123),
('pedro_paulo', 'Pedro Paulo', 'Pedro Paulo', '[]'::jsonb, 'zag', null, null, 'BR', 'Brasil', 2003, null, 'incomplete', 124),
('pedro_raul', 'Pedro Raul', 'Pedro Raul', '[]'::jsonb, 'ata', null, 'Fluminense', 'BR', 'Brasil', 2022, null, 'incomplete', 125),
('rafael_dias', 'Rafael Dias', 'Rafael Dias', '[]'::jsonb, 'zag', null, 'Goiás', 'BR', 'Brasil', 2005, null, 'incomplete', 126),
('rafael_lacerda', 'Rafael Lacerda', 'Rafael Lacerda', '[]'::jsonb, 'zag', 13, 'Athletico-PR', 'BR', 'Brasil', 2012, null, 'review', 127),
('rafael_moura', 'Rafael Moura', 'Rafael Moura', '[]'::jsonb, 'ata', 9, 'Atlético-MG', 'BR', 'Brasil', 2010, null, 'verified', 128),
('rafael_toloi', 'Rafael Tolói', 'Rafael Tolói', '[]'::jsonb, 'zag', 3, 'Goiás', 'IT', 'Itália', 2008, null, 'verified', 129),
('ramon', 'Ramón', 'Ramón', '[]'::jsonb, 'mei', 7, 'América-MG', 'BR', 'Brasil', 2012, null, 'review', 130),
('ramon_menezes_roma', 'Ramon Menezes', 'Ramon Menezes', '["Ramon Menezes Roma"]'::jsonb, 'zag', 4, 'Vitória', 'BR', 'Brasil', 2026, 'ramon_menezes', 'verified', 131),
('reidner', 'Reidner', 'Reidner', '[]'::jsonb, 'mc', null, null, 'BR', 'Brasil', null, null, 'incomplete', 132),
('renan', 'Renan', 'Renan', '[]'::jsonb, 'gol', 12, 'Internacional', 'BR', 'Brasil', 2013, null, 'verified', 133),
('renan_oliveira', 'Renan Oliveira', 'Renan Oliveira', '[]'::jsonb, 'mei', 11, 'Atlético-MG', 'BR', 'Brasil', 2012, null, 'verified', 134),
('renato_silva', 'Renato Silva', 'Renato Silva', '[]'::jsonb, 'zag', null, 'Goiás', 'BR', 'Brasil', 2003, null, 'incomplete', 135),
('reynaldo', 'Reynaldo', 'Reynaldo', '[]'::jsonb, 'zag', 29, 'Ponte Preta', 'BR', 'Brasil', 2021, null, 'review', 136),
('ricardo_goulart', 'Ricardo Goulart', 'Ricardo Goulart', '[]'::jsonb, 'mei', 9, 'Santo André', 'BR', 'Brasil', 2012, null, 'verified', 137),
('richard', 'Richard', 'Richard', '[]'::jsonb, 'zag', null, 'Goiás', 'BR', 'Brasil', 1989, null, 'incomplete', 138),
('rodrigo', 'Rodrigo', 'Rodrigo', '[]'::jsonb, 'zag', 13, 'Ponte Preta', 'BR', 'Brasil', 2013, null, 'review', 139),
('rodrigo_alves_soares', 'Rodrigo Soares', 'Rodrigo Soares', '["Rodrigo Alves Soares"]'::jsonb, 'ld', 2, 'Atlético-GO', 'BR', 'Brasil', 2026, 'rodrigo_soares', 'verified', 140),
('rodrigo_andrade', 'Rodrigo Andrade', 'Rodrigo Andrade', '[]'::jsonb, 'vol', 32, 'Vitória', 'BR', 'Brasil', 2025, null, 'verified', 141),
('rodrigo_calaca', 'Rodrigo Calaça', 'Rodrigo Calaça', '[]'::jsonb, 'gol', null, 'Goiás', 'BR', 'Brasil', 2003, null, 'incomplete', 142),
('rodrigo_tabata', 'Rodrigo Tabata', 'Rodrigo Tabata', '[]'::jsonb, 'mei', null, 'Paulista', 'QA', 'Catar', 2004, null, 'incomplete', 143),
('rogerio_correa', 'Rogério Corrêa', 'Rogério Corrêa', '[]'::jsonb, 'zag', null, 'Goiânia', 'BR', 'Brasil', 2005, null, 'incomplete', 144),
('romerito', 'Romerito', 'Romerito', '[]'::jsonb, 'mei', 10, 'Atlético-GO', 'BR', 'Brasil', 2005, null, 'verified', 145),
('romeu', 'Romeu', 'Romeu', '[]'::jsonb, 'vol', null, null, 'BR', 'Brasil', 1994, null, 'incomplete', 146),
('roni', 'Roni', 'Roni', '[]'::jsonb, 'ata', 9, 'São Paulo', 'BR', 'Brasil', 2005, null, 'review', 147),
('sander', 'Sander', 'Sander', '[]'::jsonb, 'le', 6, 'São Luiz-RS', 'BR', 'Brasil', 2023, null, 'review', 148),
('silvio_criciuma', 'Sílvio Criciúma', 'Sílvio Criciúma', '[]'::jsonb, 'zag', null, 'Criciúma', 'BR', 'Brasil', 1998, null, 'incomplete', 149),
('simao', 'Simão', 'Simão', '[]'::jsonb, 'vol', null, 'Nacional-SP', 'BR', 'Brasil', 2003, null, 'incomplete', 150),
('souza', 'Souza', 'Souza', '[]'::jsonb, 'ata', 9, 'Madureira', 'BR', 'Brasil', 2005, null, 'verified', 151),
('tadeu_antonio_ferreira', 'Tadeu', 'Tadeu', '["Tadeu Antônio Ferreira"]'::jsonb, 'gol', 23, 'Coritiba', 'BR', 'Brasil', 2019, 'tadeu', 'review', 152),
('thiago_mendes', 'Thiago Mendes', 'Thiago Mendes', '[]'::jsonb, 'vol', 8, 'Goiás', 'BR', 'Brasil', 2011, null, 'verified', 153),
('thiago_rodrigues_de_oliveira_nogueira', 'Thiago Rodrigues', 'Thiago Rodrigues', '["Thiago Rodrigues de Oliveira Nogueira"]'::jsonb, 'gol', 1, 'Paraná Clube', 'BR', 'Brasil', 2024, 'thiago_rodrigues', 'verified', 154),
('tiago_fraga', 'Tiago Fraga', 'Tiago Fraga', '[]'::jsonb, 'vol', null, null, 'BR', 'Brasil', 2003, null, 'incomplete', 155),
('titi', 'Titi', 'Titi', '[]'::jsonb, 'zag', 4, 'Internacional', 'BR', 'Brasil', 2025, null, 'verified', 156),
('tulio_maravilha', 'Túlio Maravilha', 'Túlio Maravilha', '[]'::jsonb, 'ata', 9, 'Goiás', 'BR', 'Brasil', 1988, null, 'verified', 157),
('valmir_lucas', 'Valmir Lucas', 'Valmir Lucas', '[]'::jsonb, 'zag', 3, 'Goiás', 'BR', 'Brasil', 2011, null, 'review', 158),
('vampeta', 'Vampeta', 'Vampeta', '[]'::jsonb, 'vol', null, 'Vitória', 'BR', 'Brasil', 2006, null, 'incomplete', 159),
('vinicius', 'Vinícius', 'Vinícius', '[]'::jsonb, 'ata', 7, 'Flamengo', 'BR', 'Brasil', 2023, null, 'review', 160),
('vitor', 'Vítor', 'Vítor', '[]'::jsonb, 'ld', 2, 'CRAC', 'BR', 'Brasil', 2006, null, 'verified', 161),
('wallace', 'Wallace', 'Wallace', '[]'::jsonb, 'vol', null, null, 'BR', 'Brasil', 1988, null, 'incomplete', 162),
('walter', 'Walter', 'Walter', '[]'::jsonb, 'ata', 18, 'Internacional', 'BR', 'Brasil', 2012, null, 'verified', 163),
('wando', 'Wando', 'Wando', '[]'::jsonb, 'ata', null, null, 'BR', 'Brasil', 2003, null, 'incomplete', 164),
('wellington_saci', 'Wellington Saci', 'Wellington Saci', '[]'::jsonb, 'le', 6, 'Remo', 'BR', 'Brasil', 2010, null, 'review', 165),
('wellington_soares_da_silva', 'Wellington Rato', 'Wellington Rato', '["Wellington Soares da Silva"]'::jsonb, 'mei', 27, 'Osasco Audax', 'BR', 'Brasil', 2025, 'wellington_rato', 'verified', 166),
('welliton_identity_review', 'Welliton', 'Welliton', '[]'::jsonb, null, null, null, 'BR', 'Brasil', null, null, 'incomplete', 167),
('willean_lepo', 'Willean Lepo', 'Willean Lepo', '[]'::jsonb, 'ld', 97, 'Bahia', 'BR', 'Brasil', 2025, null, 'verified', 168),
('william_matheus', 'William Matheus', 'William Matheus', '[]'::jsonb, 'le', 6, 'Figueirense', 'BR', 'Brasil', 2013, null, 'verified', 169),
('willian_oliveira', 'Willian Oliveira', 'Willian Oliveira', '[]'::jsonb, 'vol', 12, 'Fluminense', 'BR', 'Brasil', 2023, null, 'verified', 170),
('wilson_goiano', 'Wilson Goiano', 'Wilson Goiano', '[]'::jsonb, 'ld', 2, 'Goiás', 'BR', 'Brasil', 1986, null, 'verified', 171),
('ze_hugo', 'Zé Hugo', 'Zé Hugo', '[]'::jsonb, 'ata', 71, 'Botafogo-PB', 'BR', 'Brasil', 2025, null, 'verified', 172),
('ze_ricardo', 'Zé Ricardo', 'Zé Ricardo', '[]'::jsonb, 'vol', 5, 'Fluminense', 'BR', 'Brasil', 2023, null, 'verified', 173)
on conflict (id) do nothing;

