-- ============================================================================
-- Passaporte Esmeraldino — registros administrativos/excluídos 1943-2026
-- (GERADO por tooling/esmeraldino_passport/generate_historical_import_sql.ps1,
-- não editar à mão).
--
-- Fonte: tooling/esmeraldino_passport/source/passaporte_esmeraldino_EXCLUIDOS_ADMIN.csv
-- Registros: 32
--
-- Preservados só para auditoria histórica em public.passport_matches_excluded
-- (tabela sem policy pública — nunca aparecem no Passaporte, nunca permitem
-- check-in). Ver classificação de cada um em data_notes/officiality/status.
--
-- Roda DEPOIS da migration de schema
-- (20260915000000_passport_esmeraldino_historical_schema.sql).
-- ============================================================================

insert into public.passport_matches_excluded (id, season, match_date, date_precision, status, competition, competition_code, round, opponent, club_is_home, neutral_site, home_score, away_score, club_score, opponent_score, score_display, outcome, officiality, historical_source_no, source_provider, source_match_id, source_url, dataset_origin, data_notes)
values
    ('hist-f80-0006', 1943, date '1943-09-12', 'date_only', 'SCHEDULED_UNCONFIRMED', 'Campeonato Goiano', 'GOIANO', null::text, 'Goiânia-GO', null::boolean, true, null::integer, null::integer, null::integer, null::integer, null::text, null::text, 'ADMIN_EVENT', '6', 'Futebol80', '6', 'https://www.futebol80.com.br/links/times/goias/goiasjg.htm', 'historical_futebol80', 'Não há confirmação segura de que a partida tenha sido disputada; campeonato foi interrompido. | Classificacao: Partida anunciada, mas sem confirmação segura de realização; temporada interrompida e não homologada.'),
    ('hist-f80-0065', 1948, date '1948-04-25', 'date_only', 'WO_NOT_PLAYED', 'Torneio Início do Campeonato Goiano', 'TORNEIO_INICIO_GOIANO', null::text, 'União Operária', true, false, null::integer, null::integer, null::integer, null::integer, null::text, null::text, 'ADMIN_EVENT', '65', 'Futebol80', '65', 'https://www.futebol80.com.br/links/times/goias/goiasjg.htm', 'historical_futebol80', 'União Operária não compareceu; W.O. sem partida disputada.'),
    ('hist-f80-0193', 1953, date '1953-11-08', 'date_only', 'WO_NOT_PLAYED', 'Campeonato Goiano', 'GOIANO', null::text, 'Anapolina-GO', true, false, null::integer, null::integer, null::integer, null::integer, null::text, null::text, 'ADMIN_EVENT', '193', 'Futebol80', '193', 'https://www.futebol80.com.br/links/times/goias/goiasjg.htm', 'historical_futebol80', 'Anapolina não compareceu; W.O. sem partida disputada.'),
    ('hist-f80-0239', 1955, date '1955-09-04', 'date_only', 'PLAYED', 'Torneio-GO', 'TORNEIO_GO', null::text, 'São Francisco-GO', true, false, 1, 2, 1, 2, '1 x 2', 'LOSS', 'UNKNOWN_TOURNAMENT', '239', 'Futebol80', '239', 'https://www.futebol80.com.br/links/times/goias/goiasjg.htm', 'historical_futebol80', 'Classificacao: A fonte registra apenas “Torneio-GO”; não foi localizada identificação suficiente para comprovar natureza oficial. Preservado como exceção documental e excluído do principal.'),
    ('admin-annulled-1963-11-17-goias-ferroviario', 1963, date '1963-11-17', 'date_only', 'ANNULLED', 'Campeonato Goiano', 'GOIANO', null::text, 'Ferroviário-GO', null::boolean, null::boolean, null::integer, null::integer, 1, 2, '1 x 2', 'LOSS', 'ADMIN_EVENT', null::text, 'Futebol80 replacement note', null::text, 'https://www.futebol80.com.br/links/times/goias/goiasjg.htm', 'historical_admin_reconstructed', 'Partida original de 17/11/1963 anulada; substituída pelo jogo de 26/02/1964. Placar original 1 x 2 conforme nota da fonte. | Classificacao: Evento original anulado; preservado apenas no master/auditoria e não contado no Passaporte principal.'),
    ('hist-f80-0579', 1966, date '1966-09-18', 'date_only', 'WO_NOT_PLAYED', 'Campeonato Goiano', 'GOIANO', null::text, 'Ipiranga de Anápolis-GO', false, false, null::integer, null::integer, null::integer, null::integer, null::text, null::text, 'ADMIN_EVENT', '579', 'Futebol80', '579', 'https://www.futebol80.com.br/links/times/goias/goiasjg.htm', 'historical_futebol80', 'Ipiranga de Anápolis não compareceu; W.O. sem partida disputada.'),
    ('admin-annulled-1976-12-13-goias-itumbiara', 1976, date '1976-12-13', 'date_only', 'ANNULLED', 'Torneio Centro-Oeste', 'TORNEIO_CENTRO_OESTE', null::text, 'Itumbiara-GO', null::boolean, null::boolean, null::integer, null::integer, 4, 3, '4 x 3', 'WIN', 'ADMIN_EVENT', null::text, 'Futebol80 replacement note', null::text, 'https://www.futebol80.com.br/links/times/goias/goiasjg.htm', 'historical_admin_reconstructed', 'Partida original de 13/12/1976 anulada; substituída pelo jogo de 17/12/1976. Placar original 4 x 3 conforme nota da fonte. | Classificacao: Evento original anulado; preservado apenas no master/auditoria e não contado no Passaporte principal.'),
    ('hist-f80-1249', 1978, date '1978-12-14', 'date_only', 'PLAYED', 'Torneio Renê Pompeu de Pina-GO', 'TORNEIO_REN_POMPEU_DE_PINA_GO', null::text, 'Goiânia-GO', null::boolean, true, null::integer, null::integer, 2, 1, '2 x 1', 'WIN', 'FRIENDLY_TOURNAMENT', '1249', 'Futebol80', '1249', 'https://www.futebol80.com.br/links/times/goias/goiasjg.htm', 'historical_futebol80', 'Classificacao: Torneio preservado no universo complementar/amistoso; não entra no Passaporte competitivo principal.'),
    ('hist-f80-1250', 1978, date '1978-12-17', 'date_only', 'PLAYED', 'Torneio Renê Pompeu de Pina-GO', 'TORNEIO_REN_POMPEU_DE_PINA_GO', null::text, 'Atlético-GO', null::boolean, true, null::integer, null::integer, 1, 2, '1 x 2', 'LOSS', 'FRIENDLY_TOURNAMENT', '1250', 'Futebol80', '1250', 'https://www.futebol80.com.br/links/times/goias/goiasjg.htm', 'historical_futebol80', 'Classificacao: Torneio preservado no universo complementar/amistoso; não entra no Passaporte competitivo principal.'),
    ('hist-f80-1309', 1979, date '1979-12-04', 'date_only', 'WO_NOT_PLAYED', 'Campeonato Brasileiro', 'BRASILEIRO', null::text, 'Atlético-MG', true, false, null::integer, null::integer, null::integer, null::integer, null::text, null::text, 'ADMIN_EVENT', '1309', 'Futebol80', '1309', 'https://www.futebol80.com.br/links/times/goias/goiasjg.htm', 'historical_futebol80', 'W.O. administrativo; sem partida jogada'),
    ('hist-f80-1312', 1980, date '1980-01-27', 'date_only', 'PLAYED', 'Torneio Adjair Lima-GO', 'TORNEIO_ADJAIR_LIMA_GO', null::text, 'Vila Nova-GO', null::boolean, true, null::integer, null::integer, 1, 1, '1 x 1', 'DRAW', 'FRIENDLY_TOURNAMENT', '1312', 'Futebol80', '1312', 'https://www.futebol80.com.br/links/times/goias/goiasjg.htm', 'historical_futebol80', 'Classificacao: Torneio preservado no universo complementar/amistoso; não entra no Passaporte competitivo principal.'),
    ('hist-f80-1313', 1980, date '1980-01-31', 'date_only', 'PLAYED', 'Torneio Adjair Lima-GO', 'TORNEIO_ADJAIR_LIMA_GO', null::text, 'Santos-SP', true, false, 0, 4, 0, 4, '0 x 4', 'LOSS', 'FRIENDLY_TOURNAMENT', '1313', 'Futebol80', '1313', 'https://www.futebol80.com.br/links/times/goias/goiasjg.htm', 'historical_futebol80', 'Classificacao: Torneio preservado no universo complementar/amistoso; não entra no Passaporte competitivo principal.'),
    ('hist-f80-1314', 1980, date '1980-02-03', 'date_only', 'PLAYED', 'Torneio Adjair Lima-GO', 'TORNEIO_ADJAIR_LIMA_GO', null::text, 'Goiânia-GO', null::boolean, true, null::integer, null::integer, 0, 0, '0 x 0', 'DRAW', 'FRIENDLY_TOURNAMENT', '1314', 'Futebol80', '1314', 'https://www.futebol80.com.br/links/times/goias/goiasjg.htm', 'historical_futebol80', 'Classificacao: Torneio preservado no universo complementar/amistoso; não entra no Passaporte competitivo principal.'),
    ('admin-annulled-1984-09-16-goias-jataiense', 1984, date '1984-09-16', 'date_only', 'ANNULLED', 'Campeonato Goiano', 'GOIANO', null::text, 'Jataiense-GO', null::boolean, null::boolean, 0, 0, 0, 0, '0 x 0', 'DRAW', 'ADMIN_EVENT', null::text, 'Futebol80 replacement note', null::text, 'https://www.futebol80.com.br/links/times/goias/goiasjg.htm', 'historical_admin_reconstructed', 'Partida original de 16/09/1984 anulada; substituída pelo jogo de 02/12/1984. Placar original 0 x 0 conforme nota da fonte. | Classificacao: Evento original anulado; preservado apenas no master/auditoria e não contado no Passaporte principal.'),
    ('hist-f80-1618', 1984, date '1984-11-04', 'date_only', 'DISREGARDED', 'Campeonato Goiano', 'GOIANO', null::text, 'Atlético-GO', null::boolean, true, null::integer, null::integer, 2, 1, '2 x 1', 'WIN', 'ADMIN_EVENT', '1618', 'Futebol80', '1618', 'https://www.futebol80.com.br/links/times/goias/goiasjg.htm', 'historical_futebol80', 'Classificacao: Partida efetivamente disputada, mas marcada como “Goiano (Desconsiderado)” pela fonte. Preservada para auditoria e excluída do principal.'),
    ('hist-f80-1619', 1984, date '1984-11-08', 'date_only', 'DISREGARDED', 'Campeonato Goiano', 'GOIANO', null::text, 'Vila Nova-GO', null::boolean, true, null::integer, null::integer, 1, 0, '1 x 0', 'WIN', 'ADMIN_EVENT', '1619', 'Futebol80', '1619', 'https://www.futebol80.com.br/links/times/goias/goiasjg.htm', 'historical_futebol80', 'Classificacao: Partida efetivamente disputada, mas marcada como “Goiano (Desconsiderado)” pela fonte. Preservada para auditoria e excluída do principal.'),
    ('hist-f80-1620', 1984, date '1984-11-11', 'date_only', 'DISREGARDED', 'Campeonato Goiano', 'GOIANO', null::text, 'Goiânia-GO', null::boolean, true, null::integer, null::integer, 2, 0, '2 x 0', 'WIN', 'ADMIN_EVENT', '1620', 'Futebol80', '1620', 'https://www.futebol80.com.br/links/times/goias/goiasjg.htm', 'historical_futebol80', 'Classificacao: Partida efetivamente disputada, mas marcada como “Goiano (Desconsiderado)” pela fonte. Preservada para auditoria e excluída do principal.'),
    ('hist-f80-1621', 1984, date '1984-11-15', 'date_only', 'DISREGARDED', 'Campeonato Goiano', 'GOIANO', null::text, 'Vila Nova-GO', null::boolean, true, null::integer, null::integer, 1, 2, '1 x 2', 'LOSS', 'ADMIN_EVENT', '1621', 'Futebol80', '1621', 'https://www.futebol80.com.br/links/times/goias/goiasjg.htm', 'historical_futebol80', 'Classificacao: Partida efetivamente disputada, mas marcada como “Goiano (Desconsiderado)” pela fonte. Preservada para auditoria e excluída do principal.'),
    ('hist-f80-1622', 1984, date '1984-11-18', 'date_only', 'DISREGARDED', 'Campeonato Goiano', 'GOIANO', null::text, 'Goiânia-GO', null::boolean, true, null::integer, null::integer, 0, 0, '0 x 0', 'DRAW', 'ADMIN_EVENT', '1622', 'Futebol80', '1622', 'https://www.futebol80.com.br/links/times/goias/goiasjg.htm', 'historical_futebol80', 'Classificacao: Partida efetivamente disputada, mas marcada como “Goiano (Desconsiderado)” pela fonte. Preservada para auditoria e excluída do principal.'),
    ('hist-f80-1623', 1984, date '1984-11-21', 'date_only', 'DISREGARDED', 'Campeonato Goiano', 'GOIANO', null::text, 'Atlético-GO', null::boolean, true, null::integer, null::integer, 3, 0, '3 x 0', 'WIN', 'ADMIN_EVENT', '1623', 'Futebol80', '1623', 'https://www.futebol80.com.br/links/times/goias/goiasjg.htm', 'historical_futebol80', 'Classificacao: Partida efetivamente disputada, mas marcada como “Goiano (Desconsiderado)” pela fonte. Preservada para auditoria e excluída do principal.'),
    ('hist-f80-1683', 1986, date '1986-01-31', 'date_only', 'PLAYED', 'Torneio Luiz Miguel Estêvão-GO', 'TORNEIO_LUIZ_MIGUEL_EST_V_O_GO', null::text, 'Young Boys-SUI', true, false, 2, 0, 2, 0, '2 x 0', 'WIN', 'FRIENDLY_TOURNAMENT', '1683', 'Futebol80', '1683', 'https://www.futebol80.com.br/links/times/goias/goiasjg.htm', 'historical_futebol80', 'Classificacao: Torneio preservado no universo complementar/amistoso; não entra no Passaporte competitivo principal.'),
    ('hist-f80-1684', 1986, date '1986-02-02', 'date_only', 'PLAYED', 'Torneio Luiz Miguel Estêvão-GO', 'TORNEIO_LUIZ_MIGUEL_EST_V_O_GO', null::text, 'Goiânia-GO', null::boolean, true, null::integer, null::integer, 0, 1, '0 x 1', 'LOSS', 'FRIENDLY_TOURNAMENT', '1684', 'Futebol80', '1684', 'https://www.futebol80.com.br/links/times/goias/goiasjg.htm', 'historical_futebol80', 'Classificacao: Torneio preservado no universo complementar/amistoso; não entra no Passaporte competitivo principal.'),
    ('hist-f80-2187', 1993, date '1993-10-10', 'date_only', 'PLAYED', 'Torneio Íris Rezende-GO', 'TORNEIO_RIS_REZENDE_GO', null::text, 'Piracanjuba-GO', true, false, 0, 0, 0, 0, '0 x 0', 'DRAW', 'FRIENDLY_TOURNAMENT', '2187', 'Futebol80', '2187', 'https://www.futebol80.com.br/links/times/goias/goiasjg.htm', 'historical_futebol80', 'Classificacao: Preservado como torneio amistoso/complementar. A FGF oficializou a organização em 1993, mas documentação histórica o descreve como torneio amistoso; não entra no Passaporte competitivo principal. | Fonte secundaria: https://rsssfbrasil.com/tablesfq/go1993l2.htm'),
    ('hist-f80-2189', 1993, date '1993-10-13', 'date_only', 'PLAYED', 'Torneio Íris Rezende-GO', 'TORNEIO_RIS_REZENDE_GO', null::text, 'Anápolis-GO', true, false, 4, 0, 4, 0, '4 x 0', 'WIN', 'FRIENDLY_TOURNAMENT', '2189', 'Futebol80', '2189', 'https://www.futebol80.com.br/links/times/goias/goiasjg.htm', 'historical_futebol80', 'Classificacao: Preservado como torneio amistoso/complementar. A FGF oficializou a organização em 1993, mas documentação histórica o descreve como torneio amistoso; não entra no Passaporte competitivo principal. | Fonte secundaria: https://rsssfbrasil.com/tablesfq/go1993l2.htm'),
    ('hist-f80-2191', 1993, date '1993-10-17', 'date_only', 'PLAYED', 'Torneio Íris Rezende-GO', 'TORNEIO_RIS_REZENDE_GO', null::text, 'CRAC-GO', false, false, 0, 0, 0, 0, '0 x 0', 'DRAW', 'FRIENDLY_TOURNAMENT', '2191', 'Futebol80', '2191', 'https://www.futebol80.com.br/links/times/goias/goiasjg.htm', 'historical_futebol80', 'Classificacao: Preservado como torneio amistoso/complementar. A FGF oficializou a organização em 1993, mas documentação histórica o descreve como torneio amistoso; não entra no Passaporte competitivo principal. | Fonte secundaria: https://rsssfbrasil.com/tablesfq/go1993l2.htm'),
    ('hist-f80-2194', 1993, date '1993-10-24', 'date_only', 'PLAYED', 'Torneio Íris Rezende-GO', 'TORNEIO_RIS_REZENDE_GO', null::text, 'Anapolina-GO', false, false, 1, 0, 0, 1, '0 x 1', 'LOSS', 'FRIENDLY_TOURNAMENT', '2194', 'Futebol80', '2194', 'https://www.futebol80.com.br/links/times/goias/goiasjg.htm', 'historical_futebol80', 'Classificacao: Preservado como torneio amistoso/complementar. A FGF oficializou a organização em 1993, mas documentação histórica o descreve como torneio amistoso; não entra no Passaporte competitivo principal. | Fonte secundaria: https://rsssfbrasil.com/tablesfq/go1993l2.htm'),
    ('hist-f80-2196', 1993, date '1993-11-10', 'date_only', 'PLAYED', 'Torneio Íris Rezende-GO', 'TORNEIO_RIS_REZENDE_GO', null::text, 'Vila Nova-GO', null::boolean, true, null::integer, null::integer, 3, 2, '3 x 2', 'WIN', 'FRIENDLY_TOURNAMENT', '2196', 'Futebol80', '2196', 'https://www.futebol80.com.br/links/times/goias/goiasjg.htm', 'historical_futebol80', 'Classificacao: Preservado como torneio amistoso/complementar. A FGF oficializou a organização em 1993, mas documentação histórica o descreve como torneio amistoso; não entra no Passaporte competitivo principal. | Fonte secundaria: https://rsssfbrasil.com/tablesfq/go1993l2.htm'),
    ('hist-f80-2197', 1993, date '1993-11-14', 'date_only', 'PLAYED', 'Torneio Íris Rezende-GO', 'TORNEIO_RIS_REZENDE_GO', null::text, 'Piracanjuba-GO', false, false, 1, 1, 1, 1, '1 x 1', 'DRAW', 'FRIENDLY_TOURNAMENT', '2197', 'Futebol80', '2197', 'https://www.futebol80.com.br/links/times/goias/goiasjg.htm', 'historical_futebol80', 'Classificacao: Preservado como torneio amistoso/complementar. A FGF oficializou a organização em 1993, mas documentação histórica o descreve como torneio amistoso; não entra no Passaporte competitivo principal. | Fonte secundaria: https://rsssfbrasil.com/tablesfq/go1993l2.htm'),
    ('hist-f80-2198', 1993, date '1993-11-18', 'date_only', 'PLAYED', 'Torneio Íris Rezende-GO', 'TORNEIO_RIS_REZENDE_GO', null::text, 'Anapolina-GO', true, false, 0, 1, 0, 1, '0 x 1', 'LOSS', 'FRIENDLY_TOURNAMENT', '2198', 'Futebol80', '2198', 'https://www.futebol80.com.br/links/times/goias/goiasjg.htm', 'historical_futebol80', 'Classificacao: Preservado como torneio amistoso/complementar. A FGF oficializou a organização em 1993, mas documentação histórica o descreve como torneio amistoso; não entra no Passaporte competitivo principal. | Fonte secundaria: https://rsssfbrasil.com/tablesfq/go1993l2.htm'),
    ('hist-f80-2199', 1993, date '1993-11-21', 'date_only', 'PLAYED', 'Torneio Íris Rezende-GO', 'TORNEIO_RIS_REZENDE_GO', null::text, 'CRAC-GO', true, false, 2, 1, 2, 1, '2 x 1', 'WIN', 'FRIENDLY_TOURNAMENT', '2199', 'Futebol80', '2199', 'https://www.futebol80.com.br/links/times/goias/goiasjg.htm', 'historical_futebol80', 'Classificacao: Preservado como torneio amistoso/complementar. A FGF oficializou a organização em 1993, mas documentação histórica o descreve como torneio amistoso; não entra no Passaporte competitivo principal. | Fonte secundaria: https://rsssfbrasil.com/tablesfq/go1993l2.htm'),
    ('hist-f80-2200', 1993, date '1993-11-28', 'date_only', 'PLAYED', 'Torneio Íris Rezende-GO', 'TORNEIO_RIS_REZENDE_GO', null::text, 'Anápolis-GO', false, false, 1, 4, 4, 1, '4 x 1', 'WIN', 'FRIENDLY_TOURNAMENT', '2200', 'Futebol80', '2200', 'https://www.futebol80.com.br/links/times/goias/goiasjg.htm', 'historical_futebol80', 'Classificacao: Preservado como torneio amistoso/complementar. A FGF oficializou a organização em 1993, mas documentação histórica o descreve como torneio amistoso; não entra no Passaporte competitivo principal. | Fonte secundaria: https://rsssfbrasil.com/tablesfq/go1993l2.htm'),
    ('hist-f80-2201', 1993, date '1993-12-02', 'date_only', 'PLAYED', 'Torneio Íris Rezende-GO', 'TORNEIO_RIS_REZENDE_GO', null::text, 'Vila Nova-GO', null::boolean, true, null::integer, null::integer, 1, 0, '1 x 0', 'WIN', 'FRIENDLY_TOURNAMENT', '2201', 'Futebol80', '2201', 'https://www.futebol80.com.br/links/times/goias/goiasjg.htm', 'historical_futebol80', 'Classificacao: Preservado como torneio amistoso/complementar. A FGF oficializou a organização em 1993, mas documentação histórica o descreve como torneio amistoso; não entra no Passaporte competitivo principal. | Fonte secundaria: https://rsssfbrasil.com/tablesfq/go1993l2.htm')
on conflict (id) do update set
    season = excluded.season,
    match_date = excluded.match_date,
    date_precision = excluded.date_precision,
    status = excluded.status,
    competition = excluded.competition,
    competition_code = excluded.competition_code,
    round = excluded.round,
    opponent = excluded.opponent,
    club_is_home = excluded.club_is_home,
    neutral_site = excluded.neutral_site,
    home_score = excluded.home_score,
    away_score = excluded.away_score,
    club_score = excluded.club_score,
    opponent_score = excluded.opponent_score,
    score_display = excluded.score_display,
    outcome = excluded.outcome,
    officiality = excluded.officiality,
    historical_source_no = excluded.historical_source_no,
    source_provider = excluded.source_provider,
    source_match_id = excluded.source_match_id,
    source_url = excluded.source_url,
    dataset_origin = excluded.dataset_origin,
    data_notes = excluded.data_notes,
    updated_at = now();