-- Adivinhe a Escalação do Vila Nova (lineup_matches).
-- GERADO por `node tooling/vilanova_content/generate_seed_sql.mjs` a partir de
-- docs/vila_nova_data/arena/lineups.json — não edite à mão.
--
-- Rode no projeto Supabase do VILA NOVA — NUNCA no do Goiás nem no do
-- Bragantino (a trava abaixo para se não for). Idempotente.
--
-- 15 partidas READY. Camisa (no) sempre null: nunca inferida.
-- XI reordenado por linha e da direita pra esquerda (FormationLayoutService):
--   vn_lineup_01 3-5-2: GOL | ZAG ZAG ZAG | LD VOL MC MEI LE | ATA ATA
--   vn_lineup_02 3-5-2: GOL | ZAG ZAG ZAG | LD VOL MC MEI LE | ATA ATA
--   vn_lineup_03 4-4-2: GOL | LD ZAG ZAG LE | VOL MC MEI MEI | ATA ATA
--   vn_lineup_04 4-4-2: GOL | LD ZAG ZAG LE | VOL MC MC MEI | ATA ATA
--   vn_lineup_05 4-4-2: GOL | LD ZAG ZAG LE | VOL MC MC MEI | ATA ATA
--   vn_lineup_06 4-3-3: GOL | LD ZAG ZAG LE | VOL MC MEI | PD ATA PE
--   vn_lineup_07 4-3-3: GOL | LD ZAG ZAG LE | VOL MC MC | PD ATA PE
--   vn_lineup_08 4-3-3: GOL | LD ZAG ZAG LE | VOL MC MEI | PD ATA PE
--   vn_lineup_09 4-2-3-1: GOL | LD ZAG ZAG LE | VOL MC | PD MEI PE | ATA
--   vn_lineup_10 4-3-3: GOL | LD ZAG ZAG LE | VOL MC MC | PD ATA PE
--   vn_lineup_11 4-4-2: GOL | LD ZAG ZAG LE | VOL MC MC MEI | ATA ATA
--   vn_lineup_12 4-3-3: GOL | LD ZAG ZAG LE | VOL MC MC | PD ATA PE
--   vn_lineup_13 4-3-3: GOL | LD ZAG ZAG LE | VOL MC MEI | PD ATA PE
--   vn_lineup_14 4-4-2: GOL | LD ZAG ZAG LE | VOL MC MC MEI | ATA ATA
--   vn_lineup_15 4-3-3: GOL | LD ZAG ZAG LE | VOL MC MEI | PD ATA PE

do $$
begin
  if not exists (select 1 from public.clubs where id = '3a6b1e27-8441-533d-b6b8-99fdcfdf1c3e' and slug = 'vilanova')
     or exists (select 1 from public.clubs where slug <> 'vilanova') then
    raise exception 'este nao e o projeto Supabase do Vila Nova -- PARE';
  end if;
end $$;

insert into public.lineup_matches (id, club_id, competition, season, phase, match_date, venue, home_team, away_team, home_score, away_score, formation, formation_confidence, lineup, display_order, is_active) values
  ('vn_lineup_01', '3a6b1e27-8441-533d-b6b8-99fdcfdf1c3e', 'Campeonato Brasileiro - Série C', '2015', 'Quartas de final - ida', '2015-10-07', 'Estádio Serra Dourada', 'Vila Nova', 'Portuguesa', 1, 0, '3-5-2', 'confirmed', '[{"pos":"GOL","no":null,"name":"Edson","answer":"EDSON","aliases":[]},{"pos":"ZAG","no":null,"name":"Gustavo Bastos","answer":"GUSTAVO BASTOS","aliases":[]},{"pos":"ZAG","no":null,"name":"Vítor Pio","answer":"VÍTOR PIO","aliases":["Vítor"]},{"pos":"ZAG","no":null,"name":"Vinícius Simon","answer":"VINÍCIUS SIMON","aliases":[]},{"pos":"LD","no":null,"name":"Marcelo","answer":"MARCELO","aliases":[]},{"pos":"VOL","no":null,"name":"Francesco Alvarenga da Silva","answer":"FRANCESCO","aliases":["Francesco"]},{"pos":"MC","no":null,"name":"Ramires","answer":"RAMIRES","aliases":[]},{"pos":"MEI","no":null,"name":"Robston","answer":"ROBSTON","aliases":[]},{"pos":"LE","no":null,"name":"Marinho Donizete","answer":"MARINHO DONIZETE","aliases":[]},{"pos":"ATA","no":null,"name":"Moisés Brito","answer":"MOISÉS","aliases":["Moisés"]},{"pos":"ATA","no":null,"name":"Carlos Frontini","answer":"FRONTINI","aliases":["Frontini"]}]'::jsonb, 0, true),
  ('vn_lineup_02', '3a6b1e27-8441-533d-b6b8-99fdcfdf1c3e', 'Campeonato Brasileiro - Série C', '2015', 'Quartas de final - volta (acesso à Série B)', '2015-10-17', 'Estádio do Canindé', 'Portuguesa', 'Vila Nova', 1, 2, '3-5-2', 'confirmed', '[{"pos":"GOL","no":null,"name":"Edson","answer":"EDSON","aliases":[]},{"pos":"ZAG","no":null,"name":"Gustavo Bastos","answer":"GUSTAVO BASTOS","aliases":[]},{"pos":"ZAG","no":null,"name":"Vítor Pio","answer":"VÍTOR PIO","aliases":["Vítor"]},{"pos":"ZAG","no":null,"name":"Vinícius Simon","answer":"VINÍCIUS SIMON","aliases":[]},{"pos":"LD","no":null,"name":"Marcelo","answer":"MARCELO","aliases":[]},{"pos":"VOL","no":null,"name":"Francesco Alvarenga da Silva","answer":"FRANCESCO","aliases":["Francesco"]},{"pos":"MC","no":null,"name":"Ramires","answer":"RAMIRES","aliases":[]},{"pos":"MEI","no":null,"name":"Robston","answer":"ROBSTON","aliases":[]},{"pos":"LE","no":null,"name":"Marinho Donizete","answer":"MARINHO DONIZETE","aliases":[]},{"pos":"ATA","no":null,"name":"Moisés Brito","answer":"MOISÉS","aliases":["Moisés"]},{"pos":"ATA","no":null,"name":"Carlos Frontini","answer":"FRONTINI","aliases":["Frontini"]}]'::jsonb, 1, true),
  ('vn_lineup_03', '3a6b1e27-8441-533d-b6b8-99fdcfdf1c3e', 'Campeonato Brasileiro - Série C', '2015', 'Final - jogo de volta (título)', '2015-11-21', 'Estádio Serra Dourada', 'Vila Nova', 'Londrina', 4, 1, '4-4-2', 'confirmed', '[{"pos":"GOL","no":null,"name":"Edson","answer":"EDSON","aliases":[]},{"pos":"LD","no":null,"name":"Marcelo","answer":"MARCELO","aliases":[]},{"pos":"ZAG","no":null,"name":"Vítor Pio","answer":"VÍTOR PIO","aliases":["Vítor"]},{"pos":"ZAG","no":null,"name":"Vinícius Simon","answer":"VINÍCIUS SIMON","aliases":[]},{"pos":"LE","no":null,"name":"Marinho Donizete","answer":"MARINHO DONIZETE","aliases":[]},{"pos":"VOL","no":null,"name":"Francesco Alvarenga da Silva","answer":"FRANCESCO","aliases":["Francesco"]},{"pos":"MC","no":null,"name":"Ramires","answer":"RAMIRES","aliases":[]},{"pos":"MEI","no":null,"name":"Robston","answer":"ROBSTON","aliases":[]},{"pos":"MEI","no":null,"name":"Zotti","answer":"ZOTTI","aliases":["Zotte"]},{"pos":"ATA","no":null,"name":"Carlos Frontini","answer":"FRONTINI","aliases":["Frontini"]},{"pos":"ATA","no":null,"name":"Moisés Brito","answer":"MOISÉS","aliases":["Moisés"]}]'::jsonb, 2, true),
  ('vn_lineup_04', '3a6b1e27-8441-533d-b6b8-99fdcfdf1c3e', 'Campeonato Brasileiro - Série C', '2020', 'Final - jogo de ida', '2021-01-23', 'Estádio Onésio Brasileiro Alvarenga', 'Vila Nova', 'Remo', 5, 1, '4-4-2', 'confirmed', '[{"pos":"GOL","no":null,"name":"Fabrício","answer":"FABRÍCIO","aliases":[]},{"pos":"LD","no":null,"name":"Celsinho","answer":"CELSINHO","aliases":[]},{"pos":"ZAG","no":null,"name":"Rafael Donato","answer":"RAFAEL DONATO","aliases":[]},{"pos":"ZAG","no":null,"name":"Adalberto","answer":"ADALBERTO","aliases":[]},{"pos":"LE","no":null,"name":"Willian Formiga","answer":"WILLIAN FORMIGA","aliases":[]},{"pos":"VOL","no":null,"name":"Yuri","answer":"YURI","aliases":[]},{"pos":"MC","no":null,"name":"Pablo Roberto","answer":"PABLO","aliases":["Pablo"]},{"pos":"MC","no":null,"name":"Dudu","answer":"DUDU","aliases":[]},{"pos":"MEI","no":null,"name":"Alan Mineiro","answer":"ALAN MINEIRO","aliases":[]},{"pos":"ATA","no":null,"name":"Talles","answer":"TALLES","aliases":[]},{"pos":"ATA","no":null,"name":"Henan","answer":"HENAN","aliases":[]}]'::jsonb, 3, true),
  ('vn_lineup_05', '3a6b1e27-8441-533d-b6b8-99fdcfdf1c3e', 'Campeonato Brasileiro - Série C', '2020', 'Final - jogo de volta (título)', '2021-01-30', 'Estádio Olímpico do Pará (Mangueirão)', 'Remo', 'Vila Nova', 2, 3, '4-4-2', 'confirmed', '[{"pos":"GOL","no":null,"name":"Fabrício","answer":"FABRÍCIO","aliases":[]},{"pos":"LD","no":null,"name":"Celsinho","answer":"CELSINHO","aliases":[]},{"pos":"ZAG","no":null,"name":"Rafael Donato","answer":"RAFAEL DONATO","aliases":[]},{"pos":"ZAG","no":null,"name":"Adalberto","answer":"ADALBERTO","aliases":[]},{"pos":"LE","no":null,"name":"Willian Formiga","answer":"WILLIAN FORMIGA","aliases":[]},{"pos":"VOL","no":null,"name":"Yuri","answer":"YURI","aliases":[]},{"pos":"MC","no":null,"name":"Pablo Roberto","answer":"PABLO","aliases":["Pablo"]},{"pos":"MC","no":null,"name":"Dudu","answer":"DUDU","aliases":[]},{"pos":"MEI","no":null,"name":"Alan Mineiro","answer":"ALAN MINEIRO","aliases":[]},{"pos":"ATA","no":null,"name":"Gilsinho","answer":"GILSINHO","aliases":[]},{"pos":"ATA","no":null,"name":"Henan","answer":"HENAN","aliases":[]}]'::jsonb, 4, true),
  ('vn_lineup_06', '3a6b1e27-8441-533d-b6b8-99fdcfdf1c3e', 'Copa Verde', '2021', 'Final - jogo de ida', '2021-12-08', 'Estádio Onésio Brasileiro Alvarenga', 'Vila Nova', 'Remo', 0, 0, '4-3-3', 'estimated', '[{"pos":"GOL","no":null,"name":"Georgemy","answer":"GEORGEMY","aliases":[]},{"pos":"LD","no":null,"name":"André Krobel","answer":"ANDRÉ KROBEL","aliases":[]},{"pos":"ZAG","no":null,"name":"Rafael Donato","answer":"RAFAEL DONATO","aliases":[]},{"pos":"ZAG","no":null,"name":"Renato","answer":"RENATO","aliases":[]},{"pos":"LE","no":null,"name":"Bruno Collaço","answer":"BRUNO COLLAÇO","aliases":[]},{"pos":"VOL","no":null,"name":"Pedro Bambu","answer":"PEDRO BAMBU","aliases":[]},{"pos":"MC","no":null,"name":"Moacir","answer":"MOACIR","aliases":[]},{"pos":"MEI","no":null,"name":"Tiago Real","answer":"TIAGO REAL","aliases":[]},{"pos":"PD","no":null,"name":"Diego Tavares","answer":"DIEGO TAVARES","aliases":[]},{"pos":"ATA","no":null,"name":"Clayton","answer":"CLAYTON","aliases":[]},{"pos":"PE","no":null,"name":"Alesson","answer":"ALESSON","aliases":[]}]'::jsonb, 5, true),
  ('vn_lineup_07', '3a6b1e27-8441-533d-b6b8-99fdcfdf1c3e', 'Copa Verde', '2021', 'Final - jogo de volta', '2021-12-11', 'Estádio Evandro Almeida (Baenão)', 'Remo', 'Vila Nova', 0, 0, '4-3-3', 'estimated', '[{"pos":"GOL","no":null,"name":"Georgemy","answer":"GEORGEMY","aliases":[]},{"pos":"LD","no":null,"name":"André Krobel","answer":"ANDRÉ KROBEL","aliases":[]},{"pos":"ZAG","no":null,"name":"Renato","answer":"RENATO","aliases":[]},{"pos":"ZAG","no":null,"name":"Rafael Donato","answer":"RAFAEL DONATO","aliases":[]},{"pos":"LE","no":null,"name":"Bruno Collaço","answer":"BRUNO COLLAÇO","aliases":[]},{"pos":"VOL","no":null,"name":"Moacir","answer":"MOACIR","aliases":[]},{"pos":"MC","no":null,"name":"Éder Monteiro","answer":"ÉDER MONTEIRO","aliases":[]},{"pos":"MC","no":null,"name":"Pedro Bambu","answer":"PEDRO BAMBU","aliases":[]},{"pos":"PD","no":null,"name":"Diego Tavares","answer":"DIEGO TAVARES","aliases":[]},{"pos":"ATA","no":null,"name":"Rafael Silva","answer":"RAFAEL SILVA","aliases":[]},{"pos":"PE","no":null,"name":"Clayton","answer":"CLAYTON","aliases":[]}]'::jsonb, 6, true),
  ('vn_lineup_08', '3a6b1e27-8441-533d-b6b8-99fdcfdf1c3e', 'Copa Verde', '2022', 'Final - jogo de ida', '2022-11-15', 'Estádio da Curuzu', 'Paysandu', 'Vila Nova', 0, 0, '4-3-3', 'estimated', '[{"pos":"GOL","no":null,"name":"Tony","answer":"TONY","aliases":[]},{"pos":"LD","no":null,"name":"Alex Silva","answer":"ALEX SILVA","aliases":[]},{"pos":"ZAG","no":null,"name":"Rafael Donato","answer":"RAFAEL DONATO","aliases":[]},{"pos":"ZAG","no":null,"name":"Jordan","answer":"JORDAN","aliases":[]},{"pos":"LE","no":null,"name":"Willian Formiga","answer":"WILLIAN FORMIGA","aliases":[]},{"pos":"VOL","no":null,"name":"Ralf","answer":"RALF","aliases":[]},{"pos":"MC","no":null,"name":"Sousa","answer":"SOUSA","aliases":[]},{"pos":"MEI","no":null,"name":"Wagner","answer":"WAGNER","aliases":[]},{"pos":"PD","no":null,"name":"Diego Tavares","answer":"DIEGO TAVARES","aliases":[]},{"pos":"ATA","no":null,"name":"Neto Pessoa","answer":"NETO PESSOA","aliases":[]},{"pos":"PE","no":null,"name":"Kaio Nunes","answer":"KAIO NUNES","aliases":[]}]'::jsonb, 7, true),
  ('vn_lineup_09', '3a6b1e27-8441-533d-b6b8-99fdcfdf1c3e', 'Copa Verde', '2022', 'Final - jogo de volta', '2022-11-19', 'Estádio Serra Dourada', 'Vila Nova', 'Paysandu', 1, 1, '4-2-3-1', 'estimated', '[{"pos":"GOL","no":null,"name":"Tony","answer":"TONY","aliases":[]},{"pos":"LD","no":null,"name":"Alex Silva","answer":"ALEX SILVA","aliases":[]},{"pos":"ZAG","no":null,"name":"Rafael Donato","answer":"RAFAEL DONATO","aliases":[]},{"pos":"ZAG","no":null,"name":"Jordan","answer":"JORDAN","aliases":[]},{"pos":"LE","no":null,"name":"Willian Formiga","answer":"WILLIAN FORMIGA","aliases":[]},{"pos":"VOL","no":null,"name":"Ralf","answer":"RALF","aliases":[]},{"pos":"MC","no":null,"name":"Sousa","answer":"SOUSA","aliases":[]},{"pos":"PD","no":null,"name":"Diego Tavares","answer":"DIEGO TAVARES","aliases":[]},{"pos":"MEI","no":null,"name":"Matheuzinho","answer":"MATHEUZINHO","aliases":[]},{"pos":"PE","no":null,"name":"Kaio Nunes","answer":"KAIO NUNES","aliases":[]},{"pos":"ATA","no":null,"name":"Neto Pessoa","answer":"NETO PESSOA","aliases":[]}]'::jsonb, 8, true),
  ('vn_lineup_10', '3a6b1e27-8441-533d-b6b8-99fdcfdf1c3e', 'Copa Verde', '2024', 'Quartas de final - ida', '2024-03-20', 'Estádio Onésio Brasileiro Alvarenga', 'Vila Nova', 'Goiás', 1, 0, '4-3-3', 'estimated', '[{"pos":"GOL","no":null,"name":"Dênis Júnior","answer":"DÊNIS JÚNIOR","aliases":[]},{"pos":"LD","no":null,"name":"Ruan Santos","answer":"RUAN SANTOS","aliases":[]},{"pos":"ZAG","no":null,"name":"Juan Quintero","answer":"JUAN QUINTERO","aliases":[]},{"pos":"ZAG","no":null,"name":"Anderson Conceição","answer":"ANDERSON CONCEIÇÃO","aliases":[]},{"pos":"LE","no":null,"name":"Roberto","answer":"ROBERTO","aliases":[]},{"pos":"VOL","no":null,"name":"Ralf","answer":"RALF","aliases":[]},{"pos":"MC","no":null,"name":"Bruno Matias","answer":"BRUNO MATIAS","aliases":[]},{"pos":"MC","no":null,"name":"João Vitor","answer":"JOÃO VITOR","aliases":[]},{"pos":"PD","no":null,"name":"Igor Bolt","answer":"IGOR BOLT","aliases":[]},{"pos":"ATA","no":null,"name":"Fernandão","answer":"FERNANDÃO","aliases":[]},{"pos":"PE","no":null,"name":"Alesson","answer":"ALESSON","aliases":[]}]'::jsonb, 9, true),
  ('vn_lineup_11', '3a6b1e27-8441-533d-b6b8-99fdcfdf1c3e', 'Copa Verde', '2024', 'Semifinal - jogo de volta (classificação nos pênaltis)', '2024-05-11', 'Arena Pantanal', 'Cuiabá', 'Vila Nova', 4, 2, '4-4-2', 'estimated', '[{"pos":"GOL","no":null,"name":"Dênis Júnior","answer":"DÊNIS JÚNIOR","aliases":[]},{"pos":"LD","no":null,"name":"Ruan Santos","answer":"RUAN SANTOS","aliases":[]},{"pos":"ZAG","no":null,"name":"Anderson Conceição","answer":"ANDERSON CONCEIÇÃO","aliases":[]},{"pos":"ZAG","no":null,"name":"Eric","answer":"ERIC","aliases":[]},{"pos":"LE","no":null,"name":"Roberto","answer":"ROBERTO","aliases":[]},{"pos":"VOL","no":null,"name":"Ralf","answer":"RALF","aliases":[]},{"pos":"MC","no":null,"name":"João Vitor","answer":"JOÃO VITOR","aliases":[]},{"pos":"MC","no":null,"name":"Bruno Matias","answer":"BRUNO MATIAS","aliases":[]},{"pos":"MEI","no":null,"name":"Luciano Naninho","answer":"LUCIANO NANINHO","aliases":[]},{"pos":"ATA","no":null,"name":"Henrique Almeida","answer":"HENRIQUE ALMEIDA","aliases":[]},{"pos":"ATA","no":null,"name":"Alesson","answer":"ALESSON","aliases":[]}]'::jsonb, 10, true),
  ('vn_lineup_12', '3a6b1e27-8441-533d-b6b8-99fdcfdf1c3e', 'Campeonato Brasileiro - Série B', '2024', 'Fase única - rodada 31', '2024-10-13', 'Estádio Hailé Pinheiro (Serrinha)', 'Goiás', 'Vila Nova', 0, 1, '4-3-3', 'estimated', '[{"pos":"GOL","no":null,"name":"Halls","answer":"HALLS","aliases":[]},{"pos":"LD","no":null,"name":"Elias","answer":"ELIAS","aliases":[]},{"pos":"ZAG","no":null,"name":"Dankler","answer":"DANKLER","aliases":[]},{"pos":"ZAG","no":null,"name":"Jemmes","answer":"JEMMES","aliases":[]},{"pos":"LE","no":null,"name":"Rhuan","answer":"RHUAN","aliases":[]},{"pos":"VOL","no":null,"name":"Ralf","answer":"RALF","aliases":[]},{"pos":"MC","no":null,"name":"Igor Henrique","answer":"IGOR HENRIQUE","aliases":[]},{"pos":"MC","no":null,"name":"João Lucas","answer":"JOÃO LUCAS","aliases":[]},{"pos":"PD","no":null,"name":"Júnior Todinho","answer":"JÚNIOR TODINHO","aliases":[]},{"pos":"ATA","no":null,"name":"Alesson","answer":"ALESSON","aliases":[]},{"pos":"PE","no":null,"name":"Emerson Urso","answer":"EMERSON URSO","aliases":[]}]'::jsonb, 11, true),
  ('vn_lineup_13', '3a6b1e27-8441-533d-b6b8-99fdcfdf1c3e', 'Campeonato Goiano', '2025', 'Semifinal - jogo de ida', '2025-03-09', 'Estádio Hailé Pinheiro (Serrinha)', 'Goiás', 'Vila Nova', 0, 1, '4-3-3', 'estimated', '[{"pos":"GOL","no":null,"name":"Halls","answer":"HALLS","aliases":[]},{"pos":"LD","no":null,"name":"Elias","answer":"ELIAS","aliases":[]},{"pos":"ZAG","no":null,"name":"Bernardo Schappo","answer":"BERNARDO SCHAPPO","aliases":[]},{"pos":"ZAG","no":null,"name":"Tiago Pagnussat","answer":"TIAGO PAGNUSSAT","aliases":[]},{"pos":"LE","no":null,"name":"Willian Formiga","answer":"WILLIAN FORMIGA","aliases":[]},{"pos":"VOL","no":null,"name":"João Vieira","answer":"JOÃO VIEIRA","aliases":[]},{"pos":"MC","no":null,"name":"Arilson","answer":"ARILSON","aliases":[]},{"pos":"MEI","no":null,"name":"Diego Torres","answer":"DIEGO TORRES","aliases":[]},{"pos":"PD","no":null,"name":"Júnior Todinho","answer":"JÚNIOR TODINHO","aliases":[]},{"pos":"ATA","no":null,"name":"Gabriel Poveda","answer":"GABRIEL POVEDA","aliases":[]},{"pos":"PE","no":null,"name":"Vinícius Paiva","answer":"VINÍCIUS PAIVA","aliases":[]}]'::jsonb, 12, true),
  ('vn_lineup_14', '3a6b1e27-8441-533d-b6b8-99fdcfdf1c3e', 'Campeonato Goiano', '2025', 'Final - jogo de volta (título)', '2025-03-30', 'Estádio Serra Dourada', 'Vila Nova', 'Anápolis', 3, 0, '4-4-2', 'estimated', '[{"pos":"GOL","no":null,"name":"Halls","answer":"HALLS","aliases":[]},{"pos":"LD","no":null,"name":"Elias","answer":"ELIAS","aliases":[]},{"pos":"ZAG","no":null,"name":"Bernardo Schappo","answer":"BERNARDO SCHAPPO","aliases":[]},{"pos":"ZAG","no":null,"name":"Tiago Pagnussat","answer":"TIAGO PAGNUSSAT","aliases":[]},{"pos":"LE","no":null,"name":"Willian Formiga","answer":"WILLIAN FORMIGA","aliases":[]},{"pos":"VOL","no":null,"name":"João Vieira","answer":"JOÃO VIEIRA","aliases":[]},{"pos":"MC","no":null,"name":"Jean Mota","answer":"JEAN MOTA","aliases":[]},{"pos":"MC","no":null,"name":"Igor Henrique","answer":"IGOR HENRIQUE","aliases":[]},{"pos":"MEI","no":null,"name":"Diego Torres","answer":"DIEGO TORRES","aliases":[]},{"pos":"ATA","no":null,"name":"Júnior Todinho","answer":"JÚNIOR TODINHO","aliases":[]},{"pos":"ATA","no":null,"name":"Bruno Mendes","answer":"BRUNO MENDES","aliases":[]}]'::jsonb, 13, true),
  ('vn_lineup_15', '3a6b1e27-8441-533d-b6b8-99fdcfdf1c3e', 'Campeonato Brasileiro - Série B', '2025', 'Fase única - rodada 22', '2025-08-16', 'Estádio Onésio Brasileiro Alvarenga', 'Vila Nova', 'Goiás', 2, 0, '4-3-3', 'estimated', '[{"pos":"GOL","no":null,"name":"Halls","answer":"HALLS","aliases":[]},{"pos":"LD","no":null,"name":"Elias","answer":"ELIAS","aliases":[]},{"pos":"ZAG","no":null,"name":"Tiago Pagnussat","answer":"TIAGO PAGNUSSAT","aliases":[]},{"pos":"ZAG","no":null,"name":"Weverton","answer":"WEVERTON","aliases":[]},{"pos":"LE","no":null,"name":"Willian Formiga","answer":"WILLIAN FORMIGA","aliases":[]},{"pos":"VOL","no":null,"name":"João Vieira","answer":"JOÃO VIEIRA","aliases":[]},{"pos":"MC","no":null,"name":"Ralf","answer":"RALF","aliases":[]},{"pos":"MEI","no":null,"name":"Dodô","answer":"DODÔ","aliases":[]},{"pos":"PD","no":null,"name":"Júnior Todinho","answer":"JÚNIOR TODINHO","aliases":[]},{"pos":"ATA","no":null,"name":"André Luís","answer":"ANDRÉ LUÍS","aliases":[]},{"pos":"PE","no":null,"name":"Guilherme Parede","answer":"GUILHERME PAREDE","aliases":[]}]'::jsonb, 14, true)
on conflict (id) do update set club_id = excluded.club_id, competition = excluded.competition, season = excluded.season, phase = excluded.phase, match_date = excluded.match_date, venue = excluded.venue, home_team = excluded.home_team, away_team = excluded.away_team, home_score = excluded.home_score, away_score = excluded.away_score, formation = excluded.formation, formation_confidence = excluded.formation_confidence, lineup = excluded.lineup, display_order = excluded.display_order, is_active = excluded.is_active;
