-- Passaporte do Vila Nova — temporada 2020. GERADO por
-- `node tooling/vilanova_passport/generate_passport_sql.mjs` a partir de
-- docs/vila_nova_data/passport/passport_2020.json — não edite à mão.
--
-- Rode no projeto Supabase do VILA NOVA — NUNCA no do Goiás nem no do Bragantino.
-- Ordem: vilanova_passport_infra.sql -> vilanova_passport_venues_seed.sql -> ESTE.
-- Idempotente (ON CONFLICT DO UPDATE): reexecutar atualiza, nunca duplica, e
-- não encosta em presença de usuário. 33 partidas.

do $$
begin
  if not exists (select 1 from public.clubs where slug = 'vilanova')
     or exists (select 1 from public.clubs where slug <> 'vilanova') then
    raise exception 'este nao e o projeto Supabase do Vila Nova -- PARE';
  end if;
end $$;

insert into public.passport_matches (
  id, season, match_date, match_time, status, competition, competition_code, competition_edition, round, phase_status, opponent, club_is_home, neutral_site, home_team, away_team, home_score, away_score, club_score, opponent_score, score_display, outcome, stadium, stadium_status, venue_id, weekday, day_type, day_period, kickoff_at, display_timezone, date_precision, source_provider, source_match_id, source_url, source_confidence, data_notes
) values
  ('vn_rsssf_brasil_go2020_01', 2020, '2020-01-22', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2020', 'R1', 'CONFIRMED', 'Anápolis', false, false, 'Anápolis', 'Vila Nova', 0, 0, 0, 0, '0–0', 'DRAW', null, 'UNKNOWN', null, 'quarta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'go2020_01', 'https://www.rsssfbrasil.com/tablesfq/go2020.htm', 'HIGH', null),
  ('vn_rsssf_brasil_go2020_02', 2020, '2020-01-25', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2020', 'R2', 'CONFIRMED', 'Jaraguá', true, false, 'Vila Nova', 'Jaraguá', 0, 1, 0, 1, '0–1', 'LOSS', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'go2020_02', 'https://www.rsssfbrasil.com/tablesfq/go2020.htm', 'HIGH', null),
  ('vn_rsssf_brasil_go2020_03', 2020, '2020-01-30', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2020', 'R3', 'CONFIRMED', 'Grêmio Anápolis', true, false, 'Vila Nova', 'Grêmio Anápolis', 1, 0, 1, 0, '1–0', 'WIN', null, 'UNKNOWN', null, 'quinta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'go2020_03', 'https://www.rsssfbrasil.com/tablesfq/go2020.htm', 'HIGH', null),
  ('vn_rsssf_brasil_go2020_04', 2020, '2020-02-02', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2020', 'R4', 'CONFIRMED', 'Goiás', false, false, 'Goiás', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'go2020_04', 'https://www.rsssfbrasil.com/tablesfq/go2020.htm', 'HIGH', null),
  ('vn_rsssf_brasil_go2020_05', 2020, '2020-02-09', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2020', 'R5', 'CONFIRMED', 'Goiânia', false, false, 'Goiânia', 'Vila Nova', 2, 1, 1, 2, '2–1', 'LOSS', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'go2020_05', 'https://www.rsssfbrasil.com/tablesfq/go2020.htm', 'HIGH', null),
  ('vn_cbf_ge_cdb2020_galvez', 2020, '2020-02-12', '21:30:00', 'FINISHED', 'Copa do Brasil', 'COPA_DO_BRASIL', 'Copa do Brasil 2020', '1ª fase', 'CONFIRMED', 'Galvez', false, false, 'Galvez', 'Vila Nova', 0, 1, 1, 0, '0–1', 'WIN', 'Arena da Floresta', 'MATCH_SPECIFIC', 'vn_venue_arena_floresta', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2020-02-12 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF/ge', 'cdb2020_galvez', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2020&grp=1', 'HIGH', null),
  ('vn_rsssf_brasil_go2020_06', 2020, '2020-02-17', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2020', 'R6', 'CONFIRMED', 'CRAC', true, false, 'Vila Nova', 'CRAC', 1, 0, 1, 0, '1–0', 'WIN', null, 'UNKNOWN', null, 'segunda-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'go2020_06', 'https://www.rsssfbrasil.com/tablesfq/go2020.htm', 'HIGH', null),
  ('vn_rsssf_brasil_go2020_07', 2020, '2020-02-21', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2020', 'R7', 'CONFIRMED', 'Grêmio Anápolis', false, false, 'Grêmio Anápolis', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', null, 'UNKNOWN', null, 'sexta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'go2020_07', 'https://www.rsssfbrasil.com/tablesfq/go2020.htm', 'HIGH', null),
  ('vn_cbf_814951', 2020, '2020-02-27', '21:30:00', 'FINISHED', 'Copa do Brasil', 'COPA_DO_BRASIL', 'Copa do Brasil 2020', '2ª fase', 'CONFIRMED', 'Ponte Preta', false, false, 'Ponte Preta', 'Vila Nova', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Moisés Lucarelli', 'MATCH_SPECIFIC', 'vn_venue_moises_lucarelli', 'quinta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2020-02-27 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF', '814951', 'https://www.cbf.com.br/futebol-brasileiro/jogos/copa-do-brasil/masculino/2020/433582/ponte-preta-x-vila-nova/814951?view=escala-de-arbitros', 'HIGH', '0–0 no tempo normal; Ponte Preta venceu nos pênaltis por 5–3.'),
  ('vn_rsssf_brasil_go2020_08', 2020, '2020-03-01', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2020', 'R8', 'CONFIRMED', 'Goiás', true, false, 'Vila Nova', 'Goiás', 0, 0, 0, 0, '0–0', 'DRAW', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'go2020_08', 'https://www.rsssfbrasil.com/tablesfq/go2020.htm', 'HIGH', null),
  ('vn_rsssf_brasil_go2020_09', 2020, '2020-03-07', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2020', 'R9', 'CONFIRMED', 'Jaraguá', false, false, 'Jaraguá', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'go2020_09', 'https://www.rsssfbrasil.com/tablesfq/go2020.htm', 'HIGH', null),
  ('vn_rsssf_brasil_go2020_10', 2020, '2020-03-14', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2020', 'R10', 'CONFIRMED', 'Anápolis', true, false, 'Vila Nova', 'Anápolis', 2, 0, 2, 0, '2–0', 'WIN', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'go2020_10', 'https://www.rsssfbrasil.com/tablesfq/go2020.htm', 'HIGH', null),
  ('vn_cbf_sc2020_jogo_3', 2020, '2020-08-08', '19:00:00', 'FINISHED', 'Campeonato Brasileiro Série C', 'BRASILEIRO_C', 'Série C 2020', 'Jogo 3', 'CONFIRMED', 'Manaus', false, false, 'Manaus', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', 'Arena da Amazônia', 'MATCH_SPECIFIC', 'vn_venue_arena_amazonia', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2020-08-08 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF', 'sc2020_jogo_3', 'https://www.cbf.com.br/futebol-brasileiro/times/campeonato-brasileiro/serie-c/2020/20079?tab=historico-de-partidas', 'HIGH', null),
  ('vn_cbf_sc2020_jogo_15', 2020, '2020-08-15', '17:00:00', 'FINISHED', 'Campeonato Brasileiro Série C', 'BRASILEIRO_C', 'Série C 2020', 'Jogo 15', 'CONFIRMED', 'Paysandu', true, false, 'Vila Nova', 'Paysandu', 2, 0, 2, 0, '2–0', 'WIN', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2020-08-15 17:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF', 'sc2020_jogo_15', 'https://www.cbf.com.br/futebol-brasileiro/times/campeonato-brasileiro/serie-c/2020/20079?tab=historico-de-partidas', 'HIGH', null),
  ('vn_cbf_sc2020_jogo_24', 2020, '2020-08-22', '17:00:00', 'FINISHED', 'Campeonato Brasileiro Série C', 'BRASILEIRO_C', 'Série C 2020', 'Jogo 24', 'CONFIRMED', 'Ferroviário', false, false, 'Ferroviário', 'Vila Nova', 4, 0, 0, 4, '4–0', 'LOSS', 'Estádio Governador Plácido Castelo', 'MATCH_SPECIFIC', 'vn_venue_castelao', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2020-08-22 17:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF', 'sc2020_jogo_24', 'https://www.cbf.com.br/futebol-brasileiro/times/campeonato-brasileiro/serie-c/2020/20079?tab=historico-de-partidas', 'HIGH', null),
  ('vn_cbf_sc2020_jogo_31', 2020, '2020-08-30', '18:00:00', 'FINISHED', 'Campeonato Brasileiro Série C', 'BRASILEIRO_C', 'Série C 2020', 'Jogo 31', 'CONFIRMED', 'Remo', false, false, 'Remo', 'Vila Nova', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Mangueirão', 'MATCH_SPECIFIC', 'vn_venue_mangueirao', 'domingo', 'WEEKEND', 'NIGHT', (timestamp '2020-08-30 18:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF', 'sc2020_jogo_31', 'https://www.cbf.com.br/futebol-brasileiro/times/campeonato-brasileiro/serie-c/2020/20079?tab=historico-de-partidas', 'HIGH', null),
  ('vn_cbf_sc2020_jogo_45', 2020, '2020-09-05', '19:00:00', 'FINISHED', 'Campeonato Brasileiro Série C', 'BRASILEIRO_C', 'Série C 2020', 'Jogo 45', 'CONFIRMED', 'Santa Cruz', true, false, 'Vila Nova', 'Santa Cruz', 1, 0, 1, 0, '1–0', 'WIN', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2020-09-05 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF', 'sc2020_jogo_45', 'https://www.cbf.com.br/futebol-brasileiro/times/campeonato-brasileiro/serie-c/2020/20079?tab=historico-de-partidas', 'HIGH', null),
  ('vn_cbf_sc2020_jogo_52', 2020, '2020-09-12', '17:00:00', 'FINISHED', 'Campeonato Brasileiro Série C', 'BRASILEIRO_C', 'Série C 2020', 'Jogo 52', 'CONFIRMED', 'Botafogo-PB', false, false, 'Botafogo-PB', 'Vila Nova', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio José Américo de Almeida Filho', 'MATCH_SPECIFIC', 'vn_venue_almeidao', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2020-09-12 17:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF', 'sc2020_jogo_52', 'https://www.cbf.com.br/futebol-brasileiro/times/campeonato-brasileiro/serie-c/2020/20079?tab=historico-de-partidas', 'HIGH', null),
  ('vn_cbf_sc2020_jogo_65', 2020, '2020-09-21', '20:00:00', 'FINISHED', 'Campeonato Brasileiro Série C', 'BRASILEIRO_C', 'Série C 2020', 'Jogo 65', 'CONFIRMED', 'Imperatriz', true, false, 'Vila Nova', 'Imperatriz', 3, 0, 3, 0, '3–0', 'WIN', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'segunda-feira', 'WEEKDAY', 'NIGHT', (timestamp '2020-09-21 20:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF', 'sc2020_jogo_65', 'https://www.cbf.com.br/futebol-brasileiro/times/campeonato-brasileiro/serie-c/2020/20079?tab=historico-de-partidas', 'HIGH', null),
  ('vn_cbf_sc2020_jogo_75', 2020, '2020-09-26', '19:00:00', 'FINISHED', 'Campeonato Brasileiro Série C', 'BRASILEIRO_C', 'Série C 2020', 'Jogo 75', 'CONFIRMED', 'Treze', true, false, 'Vila Nova', 'Treze', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2020-09-26 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF', 'sc2020_jogo_75', 'https://www.cbf.com.br/futebol-brasileiro/times/campeonato-brasileiro/serie-c/2020/20079?tab=historico-de-partidas', 'HIGH', null),
  ('vn_cbf_sc2020_jogo_84', 2020, '2020-10-05', '20:00:00', 'FINISHED', 'Campeonato Brasileiro Série C', 'BRASILEIRO_C', 'Série C 2020', 'Jogo 84', 'CONFIRMED', 'Jacuipense', false, false, 'Jacuipense', 'Vila Nova', 0, 3, 3, 0, '0–3', 'WIN', 'Estádio de Pituaçu', 'MATCH_SPECIFIC', 'vn_venue_pituacu', 'segunda-feira', 'WEEKDAY', 'NIGHT', (timestamp '2020-10-05 20:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF', 'sc2020_jogo_84', 'https://www.cbf.com.br/futebol-brasileiro/times/campeonato-brasileiro/serie-c/2020/20079?tab=historico-de-partidas', 'HIGH', null),
  ('vn_cbf_sc2020_jogo_95', 2020, '2020-10-12', '20:00:00', 'FINISHED', 'Campeonato Brasileiro Série C', 'BRASILEIRO_C', 'Série C 2020', 'Jogo 95', 'CONFIRMED', 'Manaus', true, false, 'Vila Nova', 'Manaus', 2, 1, 2, 1, '2–1', 'WIN', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'segunda-feira', 'WEEKDAY', 'NIGHT', (timestamp '2020-10-12 20:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF', 'sc2020_jogo_95', 'https://www.cbf.com.br/futebol-brasileiro/times/campeonato-brasileiro/serie-c/2020/20079?tab=historico-de-partidas', 'HIGH', null),
  ('vn_cbf_sc2020_jogo_101', 2020, '2020-10-18', '18:00:00', 'FINISHED', 'Campeonato Brasileiro Série C', 'BRASILEIRO_C', 'Série C 2020', 'Jogo 101', 'CONFIRMED', 'Paysandu', false, false, 'Paysandu', 'Vila Nova', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Mangueirão', 'MATCH_SPECIFIC', 'vn_venue_mangueirao', 'domingo', 'WEEKEND', 'NIGHT', (timestamp '2020-10-18 18:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF', 'sc2020_jogo_101', 'https://www.cbf.com.br/futebol-brasileiro/times/campeonato-brasileiro/serie-c/2020/20079?tab=historico-de-partidas', 'HIGH', null),
  ('vn_cbf_sc2020_jogo_115', 2020, '2020-10-26', '20:00:00', 'FINISHED', 'Campeonato Brasileiro Série C', 'BRASILEIRO_C', 'Série C 2020', 'Jogo 115', 'CONFIRMED', 'Ferroviário', true, false, 'Vila Nova', 'Ferroviário', 3, 0, 3, 0, '3–0', 'WIN', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'segunda-feira', 'WEEKDAY', 'NIGHT', (timestamp '2020-10-26 20:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF', 'sc2020_jogo_115', 'https://www.cbf.com.br/futebol-brasileiro/times/campeonato-brasileiro/serie-c/2020/20079?tab=historico-de-partidas', 'HIGH', null),
  ('vn_cbf_sc2020_jogo_125', 2020, '2020-11-01', '18:00:00', 'FINISHED', 'Campeonato Brasileiro Série C', 'BRASILEIRO_C', 'Série C 2020', 'Jogo 125', 'CONFIRMED', 'Remo', true, false, 'Vila Nova', 'Remo', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'domingo', 'WEEKEND', 'NIGHT', (timestamp '2020-11-01 18:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF', 'sc2020_jogo_125', 'https://www.cbf.com.br/futebol-brasileiro/times/campeonato-brasileiro/serie-c/2020/20079?tab=historico-de-partidas', 'HIGH', null),
  ('vn_cbf_sc2020_jogo_134', 2020, '2020-11-07', '19:00:00', 'FINISHED', 'Campeonato Brasileiro Série C', 'BRASILEIRO_C', 'Série C 2020', 'Jogo 134', 'CONFIRMED', 'Santa Cruz', false, false, 'Santa Cruz', 'Vila Nova', 2, 0, 0, 2, '2–0', 'LOSS', 'Estádio José do Rego Maciel', 'MATCH_SPECIFIC', 'vn_venue_arruda', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2020-11-07 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF', 'sc2020_jogo_134', 'https://www.cbf.com.br/futebol-brasileiro/times/campeonato-brasileiro/serie-c/2020/20079?tab=historico-de-partidas', 'HIGH', null),
  ('vn_cbf_sc2020_jogo_145', 2020, '2020-11-16', '18:00:00', 'FINISHED', 'Campeonato Brasileiro Série C', 'BRASILEIRO_C', 'Série C 2020', 'Jogo 145', 'CONFIRMED', 'Botafogo-PB', true, false, 'Vila Nova', 'Botafogo-PB', 0, 1, 0, 1, '0–1', 'LOSS', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'segunda-feira', 'WEEKDAY', 'NIGHT', (timestamp '2020-11-16 18:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF', 'sc2020_jogo_145', 'https://www.cbf.com.br/futebol-brasileiro/times/campeonato-brasileiro/serie-c/2020/20079?tab=historico-de-partidas', 'HIGH', null),
  ('vn_cbf_sc2020_jogo_153', 2020, '2020-11-21', '17:00:00', 'FINISHED', 'Campeonato Brasileiro Série C', 'BRASILEIRO_C', 'Série C 2020', 'Jogo 153', 'CONFIRMED', 'Imperatriz', false, false, 'Imperatriz', 'Vila Nova', 1, 3, 3, 1, '1–3', 'WIN', 'Estádio Frei Epifânio d''Abadia', 'MATCH_SPECIFIC', 'vn_venue_frei_epifanio', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2020-11-21 17:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF', 'sc2020_jogo_153', 'https://www.cbf.com.br/futebol-brasileiro/times/campeonato-brasileiro/serie-c/2020/20079?tab=historico-de-partidas', 'HIGH', null),
  ('vn_cbf_sc2020_jogo_162', 2020, '2020-11-28', '17:00:00', 'FINISHED', 'Campeonato Brasileiro Série C', 'BRASILEIRO_C', 'Série C 2020', 'Jogo 162', 'CONFIRMED', 'Treze', false, false, 'Treze', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Governador Ernani Sátyro', 'MATCH_SPECIFIC', 'vn_venue_amigao', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2020-11-28 17:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF', 'sc2020_jogo_162', 'https://www.cbf.com.br/futebol-brasileiro/times/campeonato-brasileiro/serie-c/2020/20079?tab=historico-de-partidas', 'HIGH', null),
  ('vn_cbf_sc2020_jogo_175', 2020, '2020-12-05', '17:00:00', 'FINISHED', 'Campeonato Brasileiro Série C', 'BRASILEIRO_C', 'Série C 2020', 'Jogo 175', 'CONFIRMED', 'Jacuipense', true, false, 'Vila Nova', 'Jacuipense', 1, 0, 1, 0, '1–0', 'WIN', 'Estádio Olímpico Pedro Ludovico Teixeira', 'MATCH_SPECIFIC', 'vn_venue_olimpico', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2020-12-05 17:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF', 'sc2020_jogo_175', 'https://www.cbf.com.br/futebol-brasileiro/times/campeonato-brasileiro/serie-c/2020/20079?tab=historico-de-partidas', 'HIGH', null),
  ('vn_cbf_sc2020_jogo_182', 2020, '2020-12-14', '20:00:00', 'FINISHED', 'Campeonato Brasileiro Série C', 'BRASILEIRO_C', 'Série C 2020', 'Jogo 182', 'CONFIRMED', 'Ituano', true, false, 'Vila Nova', 'Ituano', 1, 2, 1, 2, '1–2', 'LOSS', 'Estádio Olímpico Pedro Ludovico Teixeira', 'MATCH_SPECIFIC', 'vn_venue_olimpico', 'segunda-feira', 'WEEKDAY', 'NIGHT', (timestamp '2020-12-14 20:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF', 'sc2020_jogo_182', 'https://www.cbf.com.br/futebol-brasileiro/times/campeonato-brasileiro/serie-c/2020/20079?tab=historico-de-partidas', 'HIGH', null),
  ('vn_cbf_sc2020_jogo_185', 2020, '2020-12-19', '17:00:00', 'FINISHED', 'Campeonato Brasileiro Série C', 'BRASILEIRO_C', 'Série C 2020', 'Jogo 185', 'CONFIRMED', 'Santa Cruz', false, false, 'Santa Cruz', 'Vila Nova', 1, 2, 2, 1, '1–2', 'WIN', 'Estádio José do Rego Maciel', 'MATCH_SPECIFIC', 'vn_venue_arruda', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2020-12-19 17:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF', 'sc2020_jogo_185', 'https://www.cbf.com.br/futebol-brasileiro/times/campeonato-brasileiro/serie-c/2020/20079?tab=historico-de-partidas', 'HIGH', null),
  ('vn_cbf_sc2020_jogo_190', 2020, '2020-12-26', '21:00:00', 'FINISHED', 'Campeonato Brasileiro Série C', 'BRASILEIRO_C', 'Série C 2020', 'Jogo 190', 'CONFIRMED', 'Brusque', false, false, 'Brusque', 'Vila Nova', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Augusto Bauer', 'MATCH_SPECIFIC', 'vn_venue_augusto_bauer', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2020-12-26 21:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF', 'sc2020_jogo_190', 'https://www.cbf.com.br/futebol-brasileiro/times/campeonato-brasileiro/serie-c/2020/20079?tab=historico-de-partidas', 'HIGH', null)
on conflict (id) do update set
    season = excluded.season,
    match_date = excluded.match_date,
    match_time = excluded.match_time,
    status = excluded.status,
    competition = excluded.competition,
    competition_code = excluded.competition_code,
    competition_edition = excluded.competition_edition,
    round = excluded.round,
    phase_status = excluded.phase_status,
    opponent = excluded.opponent,
    club_is_home = excluded.club_is_home,
    neutral_site = excluded.neutral_site,
    home_team = excluded.home_team,
    away_team = excluded.away_team,
    home_score = excluded.home_score,
    away_score = excluded.away_score,
    club_score = excluded.club_score,
    opponent_score = excluded.opponent_score,
    score_display = excluded.score_display,
    outcome = excluded.outcome,
    stadium = excluded.stadium,
    stadium_status = excluded.stadium_status,
    venue_id = excluded.venue_id,
    weekday = excluded.weekday,
    day_type = excluded.day_type,
    day_period = excluded.day_period,
    kickoff_at = excluded.kickoff_at,
    display_timezone = excluded.display_timezone,
    date_precision = excluded.date_precision,
    source_provider = excluded.source_provider,
    source_match_id = excluded.source_match_id,
    source_url = excluded.source_url,
    source_confidence = excluded.source_confidence,
    data_notes = excluded.data_notes,
    updated_at = now();

do $$
declare v_orphans int;
begin
  select count(*) into v_orphans from public.passport_matches
   where season = 2020 and stadium is not null and venue_id is null;
  if v_orphans > 0 then
    raise exception 'ha % partidas de 2020 com estadio sem venue_id -- rode vilanova_passport_venues_seed.sql antes', v_orphans;
  end if;
end $$;
