-- Passaporte do Vila Nova — temporada 2015. GERADO por
-- `node tooling/vilanova_passport/generate_passport_sql.mjs` a partir de
-- docs/vila_nova_data/passport/passport_2015.json — não edite à mão.
--
-- Rode no projeto Supabase do VILA NOVA — NUNCA no do Goiás nem no do Bragantino.
-- Ordem: vilanova_passport_infra.sql -> vilanova_passport_venues_seed.sql -> ESTE.
-- Idempotente (ON CONFLICT DO UPDATE): reexecutar atualiza, nunca duplica, e
-- não encosta em presença de usuário. 38 partidas.

do $$
begin
  if not exists (select 1 from public.clubs where slug = 'vilanova')
     or exists (select 1 from public.clubs where slug <> 'vilanova') then
    raise exception 'este nao e o projeto Supabase do Vila Nova -- PARE';
  end if;
end $$;

insert into public.passport_matches (
  id, season, match_date, match_time, status, competition, competition_code, competition_edition, round, phase_status, opponent, club_is_home, neutral_site, home_team, away_team, home_score, away_score, club_score, opponent_score, score_display, outcome, stadium, stadium_status, venue_id, weekday, day_type, day_period, kickoff_at, display_timezone, date_precision, source_provider, source_match_id, source_url, source_confidence, data_notes
) values
  ('vn_rsssf_go2_2015_a1', 2015, '2015-02-21', null, 'FINISHED', 'Campeonato Goiano - 2ª Divisão', 'GOIANO_2', 'Campeonato Goiano 2ª Divisão 2015', 'Primeira fase R1', 'CONFIRMED', 'Novo Horizonte', false, false, 'Novo Horizonte', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'a1', 'https://www.rsssfbrasil.com/tablesfq/go2015l2.htm', 'HIGH', null),
  ('vn_rsssf_go2_2015_a2', 2015, '2015-02-24', null, 'FINISHED', 'Campeonato Goiano - 2ª Divisão', 'GOIANO_2', 'Campeonato Goiano 2ª Divisão 2015', 'Primeira fase R2', 'CONFIRMED', 'Itaberaí', true, false, 'Vila Nova', 'Itaberaí', 2, 0, 2, 0, '2–0', 'WIN', null, 'UNKNOWN', null, 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'a2', 'https://www.rsssfbrasil.com/tablesfq/go2015l2.htm', 'HIGH', null),
  ('vn_rsssf_go2_2015_a3', 2015, '2015-03-03', null, 'FINISHED', 'Campeonato Goiano - 2ª Divisão', 'GOIANO_2', 'Campeonato Goiano 2ª Divisão 2015', 'Primeira fase R3', 'CONFIRMED', 'Anápolis', false, false, 'Anápolis', 'Vila Nova', 1, 2, 2, 1, '1–2', 'WIN', null, 'UNKNOWN', null, 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'a3', 'https://www.rsssfbrasil.com/tablesfq/go2015l2.htm', 'HIGH', null),
  ('vn_rsssf_go2_2015_a4', 2015, '2015-03-07', null, 'FINISHED', 'Campeonato Goiano - 2ª Divisão', 'GOIANO_2', 'Campeonato Goiano 2ª Divisão 2015', 'Primeira fase R4', 'CONFIRMED', 'América-GO', true, false, 'Vila Nova', 'América-GO', 1, 1, 1, 1, '1–1', 'DRAW', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'a4', 'https://www.rsssfbrasil.com/tablesfq/go2015l2.htm', 'HIGH', null),
  ('vn_rsssf_go2_2015_a5', 2015, '2015-03-14', null, 'FINISHED', 'Campeonato Goiano - 2ª Divisão', 'GOIANO_2', 'Campeonato Goiano 2ª Divisão 2015', 'Primeira fase R5', 'CONFIRMED', 'Itaberaí', false, false, 'Itaberaí', 'Vila Nova', 0, 4, 4, 0, '0–4', 'WIN', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'a5', 'https://www.rsssfbrasil.com/tablesfq/go2015l2.htm', 'HIGH', null),
  ('vn_rsssf_go2_2015_a6', 2015, '2015-03-22', null, 'FINISHED', 'Campeonato Goiano - 2ª Divisão', 'GOIANO_2', 'Campeonato Goiano 2ª Divisão 2015', 'Primeira fase R6', 'CONFIRMED', 'Anápolis', true, false, 'Vila Nova', 'Anápolis', 3, 1, 3, 1, '3–1', 'WIN', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'a6', 'https://www.rsssfbrasil.com/tablesfq/go2015l2.htm', 'HIGH', null),
  ('vn_rsssf_go2_2015_a7', 2015, '2015-03-28', null, 'FINISHED', 'Campeonato Goiano - 2ª Divisão', 'GOIANO_2', 'Campeonato Goiano 2ª Divisão 2015', 'Primeira fase R7', 'CONFIRMED', 'América-GO', false, false, 'América-GO', 'Vila Nova', 1, 2, 2, 1, '1–2', 'WIN', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'a7', 'https://www.rsssfbrasil.com/tablesfq/go2015l2.htm', 'HIGH', null),
  ('vn_rsssf_go2_2015_a8', 2015, '2015-04-04', null, 'FINISHED', 'Campeonato Goiano - 2ª Divisão', 'GOIANO_2', 'Campeonato Goiano 2ª Divisão 2015', 'Primeira fase R8', 'CONFIRMED', 'Novo Horizonte', true, false, 'Vila Nova', 'Novo Horizonte', 2, 0, 2, 0, '2–0', 'WIN', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'a8', 'https://www.rsssfbrasil.com/tablesfq/go2015l2.htm', 'HIGH', null),
  ('vn_rsssf_go2_2015_f1', 2015, '2015-04-09', null, 'FINISHED', 'Campeonato Goiano - 2ª Divisão', 'GOIANO_2', 'Campeonato Goiano 2ª Divisão 2015', 'Fase final R1', 'CONFIRMED', 'Goiânia', false, false, 'Goiânia', 'Vila Nova', 1, 3, 3, 1, '1–3', 'WIN', null, 'UNKNOWN', null, 'quinta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'f1', 'https://www.rsssfbrasil.com/tablesfq/go2015l2.htm', 'HIGH', null),
  ('vn_rsssf_go2_2015_f2', 2015, '2015-04-14', null, 'FINISHED', 'Campeonato Goiano - 2ª Divisão', 'GOIANO_2', 'Campeonato Goiano 2ª Divisão 2015', 'Fase final R2', 'CONFIRMED', 'Anápolis', true, false, 'Vila Nova', 'Anápolis', 1, 3, 1, 3, '1–3', 'LOSS', null, 'UNKNOWN', null, 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'f2', 'https://www.rsssfbrasil.com/tablesfq/go2015l2.htm', 'HIGH', null),
  ('vn_rsssf_go2_2015_f3', 2015, '2015-04-18', null, 'FINISHED', 'Campeonato Goiano - 2ª Divisão', 'GOIANO_2', 'Campeonato Goiano 2ª Divisão 2015', 'Fase final R3', 'CONFIRMED', 'Iporá', false, false, 'Iporá', 'Vila Nova', 0, 2, 2, 0, '0–2', 'WIN', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'f3', 'https://www.rsssfbrasil.com/tablesfq/go2015l2.htm', 'HIGH', null),
  ('vn_rsssf_go2_2015_f4', 2015, '2015-04-25', null, 'FINISHED', 'Campeonato Goiano - 2ª Divisão', 'GOIANO_2', 'Campeonato Goiano 2ª Divisão 2015', 'Fase final R4', 'CONFIRMED', 'Iporá', true, false, 'Vila Nova', 'Iporá', 3, 2, 3, 2, '3–2', 'WIN', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'f4', 'https://www.rsssfbrasil.com/tablesfq/go2015l2.htm', 'HIGH', null),
  ('vn_rsssf_go2_2015_f5', 2015, '2015-04-29', null, 'FINISHED', 'Campeonato Goiano - 2ª Divisão', 'GOIANO_2', 'Campeonato Goiano 2ª Divisão 2015', 'Fase final R5', 'CONFIRMED', 'Anápolis', false, false, 'Anápolis', 'Vila Nova', 1, 3, 3, 1, '1–3', 'WIN', null, 'UNKNOWN', null, 'quarta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'f5', 'https://www.rsssfbrasil.com/tablesfq/go2015l2.htm', 'HIGH', null),
  ('vn_rsssf_go2_2015_f6', 2015, '2015-05-02', null, 'FINISHED', 'Campeonato Goiano - 2ª Divisão', 'GOIANO_2', 'Campeonato Goiano 2ª Divisão 2015', 'Fase final R6', 'CONFIRMED', 'Goiânia', true, false, 'Vila Nova', 'Goiânia', 6, 0, 6, 0, '6–0', 'WIN', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'f6', 'https://www.rsssfbrasil.com/tablesfq/go2015l2.htm', 'HIGH', null),
  ('vn_cbf_sc2015_003', 2015, '2015-05-17', '16:00:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2015', 'R01', 'CONFIRMED', 'Cuiabá', true, false, 'Vila Nova', 'Cuiabá', 1, 0, 1, 0, '1–0', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'domingo', 'WEEKEND', 'AFTERNOON', (timestamp '2015-05-17 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '003', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2015_games.json', 'HIGH', null),
  ('vn_cbf_sc2015_011', 2015, '2015-05-23', '19:30:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2015', 'R02', 'CONFIRMED', 'Fortaleza', false, false, 'Fortaleza', 'Vila Nova', 3, 2, 2, 3, '3–2', 'LOSS', 'Estádio Governador Plácido Castelo', 'MATCH_SPECIFIC', 'vn_venue_castelao', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2015-05-23 19:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '011', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2015_games.json', 'HIGH', null),
  ('vn_cbf_sc2015_021', 2015, '2015-05-31', '16:00:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2015', 'R03', 'CONFIRMED', 'Águia de Marabá', false, false, 'Águia de Marabá', 'Vila Nova', 1, 2, 2, 1, '1–2', 'WIN', 'Estádio Zinho de Oliveira', 'MATCH_SPECIFIC', 'vn_venue_zinho_de_oliveira', 'domingo', 'WEEKEND', 'AFTERNOON', (timestamp '2015-05-31 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '021', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2015_games.json', 'HIGH', null),
  ('vn_cbf_sc2015_032', 2015, '2015-06-07', '11:00:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2015', 'R04', 'CONFIRMED', 'Icasa', true, false, 'Vila Nova', 'Icasa', 2, 0, 2, 0, '2–0', 'WIN', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'domingo', 'WEEKEND', 'MORNING', (timestamp '2015-06-07 11:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '032', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2015_games.json', 'HIGH', null),
  ('vn_cbf_sc2015_042', 2015, '2015-06-27', '16:00:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2015', 'R05', 'CONFIRMED', 'América-RN', true, false, 'Vila Nova', 'América-RN', 0, 1, 0, 1, '0–1', 'LOSS', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2015-06-27 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '042', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2015_games.json', 'HIGH', null),
  ('vn_cbf_sc2015_053', 2015, '2015-07-06', '20:15:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2015', 'R06', 'CONFIRMED', 'Confiança', false, false, 'Confiança', 'Vila Nova', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Estadual Lourival Baptista', 'MATCH_SPECIFIC', 'vn_venue_estadual_lourival_baptista', 'segunda-feira', 'WEEKDAY', 'NIGHT', (timestamp '2015-07-06 20:15:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '053', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2015_games.json', 'HIGH', null),
  ('vn_cbf_sc2015_064', 2015, '2015-07-11', '19:00:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2015', 'R07', 'CONFIRMED', 'Botafogo-PB', true, false, 'Vila Nova', 'Botafogo-PB', 2, 0, 2, 0, '2–0', 'WIN', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2015-07-11 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '064', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2015_games.json', 'HIGH', null),
  ('vn_cbf_sc2015_073', 2015, '2015-07-19', '16:00:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2015', 'R08', 'CONFIRMED', 'Salgueiro', false, false, 'Salgueiro', 'Vila Nova', 0, 1, 1, 0, '0–1', 'WIN', 'Estádio Cornélio de Barros Muniz', 'MATCH_SPECIFIC', 'vn_venue_cornelio_de_barros_muniz', 'domingo', 'WEEKEND', 'AFTERNOON', (timestamp '2015-07-19 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '073', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2015_games.json', 'HIGH', null),
  ('vn_cbf_sc2015_083', 2015, '2015-07-25', '16:00:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2015', 'R09', 'CONFIRMED', 'ASA', true, false, 'Vila Nova', 'ASA', 3, 0, 3, 0, '3–0', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2015-07-25 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '083', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2015_games.json', 'HIGH', null),
  ('vn_cbf_sc2015_097', 2015, '2015-08-03', '20:15:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2015', 'R10', 'CONFIRMED', 'Cuiabá', false, false, 'Cuiabá', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', 'Arena Pantanal', 'MATCH_SPECIFIC', 'vn_venue_arena_pantanal', 'segunda-feira', 'WEEKDAY', 'NIGHT', (timestamp '2015-08-03 20:15:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '097', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2015_games.json', 'HIGH', null),
  ('vn_cbf_sc2015_102', 2015, '2015-08-08', '16:00:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2015', 'R11', 'CONFIRMED', 'Fortaleza', true, false, 'Vila Nova', 'Fortaleza', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2015-08-08 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '102', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2015_games.json', 'HIGH', null),
  ('vn_cbf_sc2015_114', 2015, '2015-08-15', '16:00:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2015', 'R12', 'CONFIRMED', 'Águia de Marabá', true, false, 'Vila Nova', 'Águia de Marabá', 1, 0, 1, 0, '1–0', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2015-08-15 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '114', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2015_games.json', 'HIGH', null),
  ('vn_cbf_sc2015_126', 2015, '2015-08-23', '18:30:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2015', 'R13', 'CONFIRMED', 'Icasa', false, false, 'Icasa', 'Vila Nova', 0, 3, 3, 0, '0–3', 'WIN', 'Estádio Mauro Sampaio', 'MATCH_SPECIFIC', 'vn_venue_mauro_sampaio', 'domingo', 'WEEKEND', 'NIGHT', (timestamp '2015-08-23 18:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '126', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2015_games.json', 'HIGH', null),
  ('vn_cbf_sc2015_133', 2015, '2015-08-30', '18:00:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2015', 'R14', 'CONFIRMED', 'América-RN', false, false, 'América-RN', 'Vila Nova', 2, 1, 1, 2, '2–1', 'LOSS', 'Arena das Dunas', 'MATCH_SPECIFIC', 'vn_venue_das_dunas', 'domingo', 'WEEKEND', 'NIGHT', (timestamp '2015-08-30 18:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '133', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2015_games.json', 'HIGH', null),
  ('vn_cbf_sc2015_158', 2015, '2015-09-12', '19:00:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2015', 'R16', 'CONFIRMED', 'Botafogo-PB', false, false, 'Botafogo-PB', 'Vila Nova', 1, 2, 2, 1, '1–2', 'WIN', 'Estádio José Américo de Almeida Filho', 'MATCH_SPECIFIC', 'vn_venue_almeidao', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2015-09-12 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '158', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2015_games.json', 'HIGH', null),
  ('vn_cbf_sc2015_142', 2015, '2015-09-17', '20:30:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2015', 'R15', 'CONFIRMED', 'Confiança', true, false, 'Vila Nova', 'Confiança', 1, 2, 1, 2, '1–2', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'quinta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2015-09-17 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '142', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2015_games.json', 'HIGH', null),
  ('vn_cbf_sc2015_161', 2015, '2015-09-21', '20:30:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2015', 'R17', 'CONFIRMED', 'Salgueiro', true, false, 'Vila Nova', 'Salgueiro', 2, 1, 2, 1, '2–1', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'segunda-feira', 'WEEKDAY', 'NIGHT', (timestamp '2015-09-21 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '161', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2015_games.json', 'HIGH', null),
  ('vn_cbf_sc2015_174', 2015, '2015-09-27', '19:00:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2015', 'R18', 'CONFIRMED', 'ASA', false, false, 'ASA', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', 'Estádio Coaracy da Mata Fonseca', 'MATCH_SPECIFIC', 'vn_venue_coaracy_da_mata_fonseca', 'domingo', 'WEEKEND', 'NIGHT', (timestamp '2015-09-27 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '174', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2015_games.json', 'HIGH', null),
  ('vn_cbf_sc2015_183', 2015, '2015-10-07', '20:30:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2015', 'Quartas - ida', 'CONFIRMED', 'Portuguesa', true, false, 'Vila Nova', 'Portuguesa', 1, 0, 1, 0, '1–0', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2015-10-07 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '183', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2015_games.json', 'HIGH', null),
  ('vn_cbf_sc2015_184', 2015, '2015-10-17', '19:00:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2015', 'Quartas - volta', 'CONFIRMED', 'Portuguesa', false, false, 'Portuguesa', 'Vila Nova', 1, 2, 2, 1, '1–2', 'WIN', 'Estádio Doutor Oswaldo Teixeira Duarte', 'MATCH_SPECIFIC', 'vn_venue_doutor_oswaldo_teixeira_duarte', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2015-10-17 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '184', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2015_games.json', 'HIGH', null),
  ('vn_cbf_sc2015_189', 2015, '2015-10-26', '19:00:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2015', 'Semifinal - ida', 'CONFIRMED', 'Brasil de Pelotas', false, false, 'Brasil de Pelotas', 'Vila Nova', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Bento Mendes de Freitas', 'MATCH_SPECIFIC', 'vn_venue_bento_mendes_freitas', 'segunda-feira', 'WEEKDAY', 'NIGHT', (timestamp '2015-10-26 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '189', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2015_games.json', 'HIGH', null),
  ('vn_cbf_sc2015_190', 2015, '2015-11-02', '19:00:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2015', 'Semifinal - volta', 'CONFIRMED', 'Brasil de Pelotas', true, false, 'Vila Nova', 'Brasil de Pelotas', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'segunda-feira', 'WEEKDAY', 'NIGHT', (timestamp '2015-11-02 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '190', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2015_games.json', 'HIGH', 'Disputa de pênaltis: Vila Nova 4–3 Brasil de Pelotas.'),
  ('vn_cbf_sc2015_193', 2015, '2015-11-08', '19:00:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2015', 'Final - ida', 'CONFIRMED', 'Londrina', false, false, 'Londrina', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', 'Estádio do Café', 'MATCH_SPECIFIC', 'vn_venue_estadio_cafe', 'domingo', 'WEEKEND', 'NIGHT', (timestamp '2015-11-08 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '193', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2015_games.json', 'HIGH', null),
  ('vn_cbf_sc2015_194', 2015, '2015-11-21', '19:30:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2015', 'Final - volta', 'CONFIRMED', 'Londrina', true, false, 'Vila Nova', 'Londrina', 4, 1, 4, 1, '4–1', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2015-11-21 19:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '194', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2015_games.json', 'HIGH', null)
on conflict (id) do update set
    season = excluded.season,
    match_date = excluded.match_date,
    match_time = excluded.match_time,
    status = excluded.status,
    competition = excluded.competition,
    competition_code = excluded.competition_code,
    competition_edition = excluded.competition_edition,
    round = excluded.round,
    phase_status = excluded.phase_status,
    opponent = excluded.opponent,
    club_is_home = excluded.club_is_home,
    neutral_site = excluded.neutral_site,
    home_team = excluded.home_team,
    away_team = excluded.away_team,
    home_score = excluded.home_score,
    away_score = excluded.away_score,
    club_score = excluded.club_score,
    opponent_score = excluded.opponent_score,
    score_display = excluded.score_display,
    outcome = excluded.outcome,
    stadium = excluded.stadium,
    stadium_status = excluded.stadium_status,
    venue_id = excluded.venue_id,
    weekday = excluded.weekday,
    day_type = excluded.day_type,
    day_period = excluded.day_period,
    kickoff_at = excluded.kickoff_at,
    display_timezone = excluded.display_timezone,
    date_precision = excluded.date_precision,
    source_provider = excluded.source_provider,
    source_match_id = excluded.source_match_id,
    source_url = excluded.source_url,
    source_confidence = excluded.source_confidence,
    data_notes = excluded.data_notes,
    updated_at = now();

do $$
declare v_orphans int;
begin
  select count(*) into v_orphans from public.passport_matches
   where season = 2015 and stadium is not null and venue_id is null;
  if v_orphans > 0 then
    raise exception 'ha % partidas de 2015 com estadio sem venue_id -- rode vilanova_passport_venues_seed.sql antes', v_orphans;
  end if;
end $$;
