-- Passaporte do Vila Nova — temporada 2022. GERADO por
-- `node tooling/vilanova_passport/generate_passport_sql.mjs` a partir de
-- docs/vila_nova_data/passport/passport_2022.json — não edite à mão.
--
-- Rode no projeto Supabase do VILA NOVA — NUNCA no do Goiás nem no do Bragantino.
-- Ordem: vilanova_passport_infra.sql -> vilanova_passport_venues_seed.sql -> ESTE.
-- Idempotente (ON CONFLICT DO UPDATE): reexecutar atualiza, nunca duplica, e
-- não encosta em presença de usuário. 62 partidas.

do $$
begin
  if not exists (select 1 from public.clubs where slug = 'vilanova')
     or exists (select 1 from public.clubs where slug <> 'vilanova') then
    raise exception 'este nao e o projeto Supabase do Vila Nova -- PARE';
  end if;
end $$;

insert into public.passport_matches (
  id, season, match_date, match_time, status, competition, competition_code, competition_edition, round, phase_status, opponent, club_is_home, neutral_site, home_team, away_team, home_score, away_score, club_score, opponent_score, score_display, outcome, stadium, stadium_status, venue_id, weekday, day_type, day_period, kickoff_at, display_timezone, date_precision, source_provider, source_match_id, source_url, source_confidence, data_notes
) values
  ('vn_rsssf_brasil_go2022_01', 2022, '2022-01-25', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2022', 'R1', 'CONFIRMED', 'Goiatuba', true, false, 'Vila Nova', 'Goiatuba', 1, 0, 1, 0, '1–0', 'WIN', null, 'UNKNOWN', null, 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'go2022_01', 'https://mail.rsssfbrasil.com/tablesfq/go2022.htm', 'HIGH', null),
  ('vn_rsssf_brasil_go2022_02', 2022, '2022-01-30', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2022', 'R2', 'CONFIRMED', 'CRAC', false, false, 'CRAC', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'go2022_02', 'https://mail.rsssfbrasil.com/tablesfq/go2022.htm', 'HIGH', null),
  ('vn_rsssf_brasil_go2022_03', 2022, '2022-02-02', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2022', 'R3', 'CONFIRMED', 'Aparecidense', false, false, 'Aparecidense', 'Vila Nova', 2, 1, 1, 2, '2–1', 'LOSS', null, 'UNKNOWN', null, 'quarta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'go2022_03', 'https://mail.rsssfbrasil.com/tablesfq/go2022.htm', 'HIGH', null),
  ('vn_rsssf_brasil_go2022_04', 2022, '2022-02-05', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2022', 'R4', 'CONFIRMED', 'Atlético-GO', true, false, 'Vila Nova', 'Atlético-GO', 3, 2, 3, 2, '3–2', 'WIN', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'go2022_04', 'https://mail.rsssfbrasil.com/tablesfq/go2022.htm', 'HIGH', null),
  ('vn_rsssf_brasil_go2022_05', 2022, '2022-02-10', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2022', 'R5', 'CONFIRMED', 'Iporá', true, false, 'Vila Nova', 'Iporá', 5, 0, 5, 0, '5–0', 'WIN', null, 'UNKNOWN', null, 'quinta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'go2022_05', 'https://mail.rsssfbrasil.com/tablesfq/go2022.htm', 'HIGH', null),
  ('vn_rsssf_brasil_go2022_06', 2022, '2022-02-13', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2022', 'R6', 'CONFIRMED', 'Iporá', false, false, 'Iporá', 'Vila Nova', 2, 0, 0, 2, '2–0', 'LOSS', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'go2022_06', 'https://mail.rsssfbrasil.com/tablesfq/go2022.htm', 'HIGH', null),
  ('vn_rsssf_brasil_go2022_07', 2022, '2022-02-16', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2022', 'R7', 'CONFIRMED', 'Aparecidense', true, false, 'Vila Nova', 'Aparecidense', 2, 0, 2, 0, '2–0', 'WIN', null, 'UNKNOWN', null, 'quarta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'go2022_07', 'https://mail.rsssfbrasil.com/tablesfq/go2022.htm', 'HIGH', null),
  ('vn_rsssf_brasil_go2022_08', 2022, '2022-02-19', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2022', 'R8', 'CONFIRMED', 'Atlético-GO', false, false, 'Atlético-GO', 'Vila Nova', 0, 2, 2, 0, '0–2', 'WIN', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'go2022_08', 'https://mail.rsssfbrasil.com/tablesfq/go2022.htm', 'HIGH', null),
  ('vn_rsssf_brasil_go2022_09', 2022, '2022-02-26', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2022', 'R9', 'CONFIRMED', 'CRAC', true, false, 'Vila Nova', 'CRAC', 1, 1, 1, 1, '1–1', 'DRAW', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'go2022_09', 'https://mail.rsssfbrasil.com/tablesfq/go2022.htm', 'HIGH', null),
  ('vn_ge_cdb2022_rio_branco', 2022, '2022-03-02', '20:00:00', 'FINISHED', 'Copa do Brasil', 'COPA_DO_BRASIL', 'Copa do Brasil 2022', '1ª fase', 'CONFIRMED', 'Rio Branco-AC', false, false, 'Rio Branco-AC', 'Vila Nova', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Antônio Aquino Lopes', 'MATCH_SPECIFIC', 'vn_venue_florestao', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2022-03-02 20:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'ge', 'cdb2022_rio_branco', 'https://ge.globo.com/ac/futebol/copa-do-brasil/noticia/2022/03/02/rio-branco-ac-x-vila-nova-veja-onde-assistir-escalacoes-desfalques-e-arbitragem.ghtml', 'HIGH', null),
  ('vn_rsssf_brasil_go2022_10', 2022, '2022-03-06', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2022', 'R10', 'CONFIRMED', 'Goiatuba', false, false, 'Goiatuba', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'go2022_10', 'https://mail.rsssfbrasil.com/tablesfq/go2022.htm', 'HIGH', null),
  ('vn_rsssf_brasil_go2022_11', 2022, '2022-03-09', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2022', 'QF1', 'CONFIRMED', 'Goianésia', false, false, 'Goianésia', 'Vila Nova', 1, 2, 2, 1, '1–2', 'WIN', null, 'UNKNOWN', null, 'quarta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'go2022_11', 'https://mail.rsssfbrasil.com/tablesfq/go2022.htm', 'HIGH', null),
  ('vn_rsssf_brasil_go2022_12', 2022, '2022-03-12', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2022', 'QF2', 'CONFIRMED', 'Goianésia', true, false, 'Vila Nova', 'Goianésia', 3, 1, 3, 1, '3–1', 'WIN', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'go2022_12', 'https://mail.rsssfbrasil.com/tablesfq/go2022.htm', 'HIGH', null),
  ('vn_cbf_zerozero_cdb2022_guarani', 2022, '2022-03-15', null, 'FINISHED', 'Copa do Brasil', 'COPA_DO_BRASIL', 'Copa do Brasil 2022', '2ª fase', 'CONFIRMED', 'Guarani', false, false, 'Guarani', 'Vila Nova', 2, 2, 2, 2, '2–2', 'DRAW', 'Estádio Brinco de Ouro da Princesa', 'MATCH_SPECIFIC', 'vn_venue_brinco_ouro', 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'cdb2022_guarani', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2022&grp=1', 'HIGH', '2–2 no tempo normal; Vila Nova venceu nos pênaltis por 5–4.'),
  ('vn_rsssf_brasil_go2022_13', 2022, '2022-03-19', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2022', 'SF1', 'CONFIRMED', 'Atlético-GO', false, false, 'Atlético-GO', 'Vila Nova', 3, 2, 2, 3, '3–2', 'LOSS', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'go2022_13', 'https://mail.rsssfbrasil.com/tablesfq/go2022.htm', 'HIGH', null),
  ('vn_rsssf_brasil_go2022_14', 2022, '2022-03-22', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2022', 'SF2', 'CONFIRMED', 'Atlético-GO', true, false, 'Vila Nova', 'Atlético-GO', 1, 1, 1, 1, '1–1', 'DRAW', null, 'UNKNOWN', null, 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'go2022_14', 'https://mail.rsssfbrasil.com/tablesfq/go2022.htm', 'HIGH', null),
  ('vn_cbf_zerozero_sb2022_r01', 2022, '2022-04-08', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2022', 'R1', 'CONFIRMED', 'Vasco', false, false, 'Vasco', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', null, 'UNKNOWN', null, 'sexta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2022_r01', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2022&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2022_r02', 2022, '2022-04-12', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2022', 'R2', 'CONFIRMED', 'Novorizontino', true, false, 'Vila Nova', 'Novorizontino', 0, 0, 0, 0, '0–0', 'DRAW', null, 'UNKNOWN', null, 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2022_r02', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2022&grp=1', 'HIGH', null),
  ('vn_cbf_cdb2022_flu_vila', 2022, '2022-04-19', '21:30:00', 'FINISHED', 'Copa do Brasil', 'COPA_DO_BRASIL', 'Copa do Brasil 2022', '3ª fase - ida', 'CONFIRMED', 'Fluminense', false, false, 'Fluminense', 'Vila Nova', 3, 2, 2, 3, '3–2', 'LOSS', 'Estádio do Maracanã', 'MATCH_SPECIFIC', 'vn_venue_maracana', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2022-04-19 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF', 'cdb2022_flu_vila', 'https://www.cbf.com.br/futebol-brasileiro/jogos/copa-do-brasil/masculino/2022/fluminense-x-vila-nova', 'HIGH', null),
  ('vn_cbf_zerozero_sb2022_r03', 2022, '2022-04-23', '19:00:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2022', 'R3', 'CONFIRMED', 'Ituano', false, false, 'Ituano', 'Vila Nova', 3, 1, 1, 3, '3–1', 'LOSS', 'Estádio Novelli Júnior', 'MATCH_SPECIFIC', 'vn_venue_novelli_junior', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2022-04-23 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF/Zerozero', 'sb2022_r03', 'https://www.cbf.com.br/futebol-brasileiro/tabelas/campeonato-brasileiro/serie-b/2022', 'HIGH', null),
  ('vn_cbf_zerozero_sb2022_r04', 2022, '2022-04-27', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2022', 'R4', 'CONFIRMED', 'Tombense', true, false, 'Vila Nova', 'Tombense', 1, 1, 1, 1, '1–1', 'DRAW', null, 'UNKNOWN', null, 'quarta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2022_r04', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2022&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2022_r05', 2022, '2022-04-29', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2022', 'R5', 'CONFIRMED', 'Londrina', false, false, 'Londrina', 'Vila Nova', 2, 2, 2, 2, '2–2', 'DRAW', null, 'UNKNOWN', null, 'sexta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2022_r05', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2022&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2022_r06', 2022, '2022-05-06', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2022', 'R6', 'CONFIRMED', 'Náutico', true, false, 'Vila Nova', 'Náutico', 2, 0, 2, 0, '2–0', 'WIN', null, 'UNKNOWN', null, 'sexta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2022_r06', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2022&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_cdb2022_vila_flu', 2022, '2022-05-11', '21:30:00', 'FINISHED', 'Copa do Brasil', 'COPA_DO_BRASIL', 'Copa do Brasil 2022', '3ª fase - volta', 'CONFIRMED', 'Fluminense', true, false, 'Vila Nova', 'Fluminense', 0, 2, 0, 2, '0–2', 'LOSS', null, 'UNKNOWN', null, 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2022-05-11 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF/Zerozero', 'cdb2022_vila_flu', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2022&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2022_r07', 2022, '2022-05-14', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2022', 'R7', 'CONFIRMED', 'Sampaio Corrêa', false, false, 'Sampaio Corrêa', 'Vila Nova', 2, 0, 0, 2, '2–0', 'LOSS', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2022_r07', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2022&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2022_r08', 2022, '2022-05-19', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2022', 'R8', 'CONFIRMED', 'Chapecoense', true, false, 'Vila Nova', 'Chapecoense', 0, 0, 0, 0, '0–0', 'DRAW', null, 'UNKNOWN', null, 'quinta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2022_r08', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2022&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2022_r09', 2022, '2022-05-29', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2022', 'R9', 'CONFIRMED', 'Grêmio', true, false, 'Vila Nova', 'Grêmio', 0, 0, 0, 0, '0–0', 'DRAW', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2022_r09', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2022&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2022_r10', 2022, '2022-06-02', '21:30:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2022', 'R10', 'CONFIRMED', 'Guarani', false, false, 'Guarani', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Brinco de Ouro da Princesa', 'MATCH_SPECIFIC', 'vn_venue_brinco_ouro', 'quinta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2022-06-02 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF/Zerozero', 'sb2022_r10', 'https://www.cbf.com.br/futebol-brasileiro/tabelas/campeonato-brasileiro/serie-b/2022', 'HIGH', null),
  ('vn_cbf_zerozero_sb2022_r11', 2022, '2022-06-07', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2022', 'R11', 'CONFIRMED', 'Brusque', true, false, 'Vila Nova', 'Brusque', 0, 2, 0, 2, '0–2', 'LOSS', null, 'UNKNOWN', null, 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2022_r11', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2022&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2022_r12', 2022, '2022-06-11', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2022', 'R12', 'CONFIRMED', 'CRB', false, false, 'CRB', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2022_r12', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2022&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2022_r13', 2022, '2022-06-17', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2022', 'R13', 'CONFIRMED', 'Operário-PR', true, false, 'Vila Nova', 'Operário-PR', 0, 0, 0, 0, '0–0', 'DRAW', null, 'UNKNOWN', null, 'sexta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2022_r13', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2022&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2022_r14', 2022, '2022-06-25', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2022', 'R14', 'CONFIRMED', 'Criciúma', false, false, 'Criciúma', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2022_r14', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2022&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2022_r15', 2022, '2022-06-29', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2022', 'R15', 'CONFIRMED', 'Ponte Preta', true, false, 'Vila Nova', 'Ponte Preta', 1, 1, 1, 1, '1–1', 'DRAW', null, 'UNKNOWN', null, 'quarta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2022_r15', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2022&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2022_r16', 2022, '2022-07-02', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2022', 'R16', 'CONFIRMED', 'Cruzeiro', false, false, 'Cruzeiro', 'Vila Nova', 2, 0, 0, 2, '2–0', 'LOSS', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2022_r16', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2022&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2022_r17', 2022, '2022-07-08', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2022', 'R17', 'CONFIRMED', 'Bahia', true, false, 'Vila Nova', 'Bahia', 1, 1, 1, 1, '1–1', 'DRAW', null, 'UNKNOWN', null, 'sexta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2022_r17', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2022&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2022_r18', 2022, '2022-07-16', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2022', 'R18', 'CONFIRMED', 'CSA', true, false, 'Vila Nova', 'CSA', 1, 2, 1, 2, '1–2', 'LOSS', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2022_r18', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2022&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2022_r19', 2022, '2022-07-19', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2022', 'R19', 'CONFIRMED', 'Sport Recife', false, false, 'Sport Recife', 'Vila Nova', 0, 0, 0, 0, '0–0', 'DRAW', null, 'UNKNOWN', null, 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2022_r19', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2022&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2022_r20', 2022, '2022-07-23', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2022', 'R20', 'CONFIRMED', 'Vasco', true, false, 'Vila Nova', 'Vasco', 1, 0, 1, 0, '1–0', 'WIN', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2022_r20', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2022&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2022_r21', 2022, '2022-07-30', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2022', 'R21', 'CONFIRMED', 'Novorizontino', false, false, 'Novorizontino', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2022_r21', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2022&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2022_r22', 2022, '2022-08-05', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2022', 'R22', 'CONFIRMED', 'Ituano', true, false, 'Vila Nova', 'Ituano', 1, 1, 1, 1, '1–1', 'DRAW', null, 'UNKNOWN', null, 'sexta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2022_r22', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2022&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2022_r23', 2022, '2022-08-10', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2022', 'R23', 'CONFIRMED', 'Tombense', false, false, 'Tombense', 'Vila Nova', 0, 0, 0, 0, '0–0', 'DRAW', null, 'UNKNOWN', null, 'quarta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2022_r23', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2022&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2022_r24', 2022, '2022-08-12', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2022', 'R24', 'CONFIRMED', 'Londrina', true, false, 'Vila Nova', 'Londrina', 0, 0, 0, 0, '0–0', 'DRAW', null, 'UNKNOWN', null, 'sexta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2022_r24', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2022&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2022_r25', 2022, '2022-08-20', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2022', 'R25', 'CONFIRMED', 'Náutico', false, false, 'Náutico', 'Vila Nova', 1, 2, 2, 1, '1–2', 'WIN', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2022_r25', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2022&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2022_r26', 2022, '2022-08-25', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2022', 'R26', 'CONFIRMED', 'Sampaio Corrêa', true, false, 'Vila Nova', 'Sampaio Corrêa', 0, 0, 0, 0, '0–0', 'DRAW', null, 'UNKNOWN', null, 'quinta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2022_r26', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2022&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2022_r27', 2022, '2022-08-30', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2022', 'R27', 'CONFIRMED', 'Chapecoense', false, false, 'Chapecoense', 'Vila Nova', 1, 2, 2, 1, '1–2', 'WIN', null, 'UNKNOWN', null, 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2022_r27', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2022&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2022_r28', 2022, '2022-09-03', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2022', 'R28', 'CONFIRMED', 'Grêmio', false, false, 'Grêmio', 'Vila Nova', 2, 1, 1, 2, '2–1', 'LOSS', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2022_r28', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2022&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2022_r29', 2022, '2022-09-07', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2022', 'R29', 'CONFIRMED', 'Guarani', true, false, 'Vila Nova', 'Guarani', 2, 1, 2, 1, '2–1', 'WIN', null, 'UNKNOWN', null, 'quarta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2022_r29', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2022&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2022_r30', 2022, '2022-09-17', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2022', 'R30', 'CONFIRMED', 'Brusque', false, false, 'Brusque', 'Vila Nova', 0, 1, 1, 0, '0–1', 'WIN', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2022_r30', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2022&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2022_r31', 2022, '2022-09-23', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2022', 'R31', 'CONFIRMED', 'CRB', true, false, 'Vila Nova', 'CRB', 1, 0, 1, 0, '1–0', 'WIN', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'sexta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2022_r31', 'https://www.cbf.com.br/futebol-brasileiro/tabelas/campeonato-brasileiro/serie-b/2022', 'HIGH', null),
  ('vn_cbf_zerozero_sb2022_r32', 2022, '2022-09-30', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2022', 'R32', 'CONFIRMED', 'Operário-PR', false, false, 'Operário-PR', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Germano Krüger', 'MATCH_SPECIFIC', 'vn_venue_germano_kr_ger', 'sexta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2022_r32', 'https://www.cbf.com.br/futebol-brasileiro/tabelas/campeonato-brasileiro/serie-b/2022', 'HIGH', null),
  ('vn_cbf_zerozero_sb2022_r33', 2022, '2022-10-04', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2022', 'R33', 'CONFIRMED', 'Criciúma', true, false, 'Vila Nova', 'Criciúma', 1, 0, 1, 0, '1–0', 'WIN', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2022_r33', 'https://www.cbf.com.br/futebol-brasileiro/tabelas/campeonato-brasileiro/serie-b/2022', 'HIGH', null),
  ('vn_cbf_zerozero_sb2022_r34', 2022, '2022-10-08', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2022', 'R34', 'CONFIRMED', 'Ponte Preta', false, false, 'Ponte Preta', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Moisés Lucarelli', 'MATCH_SPECIFIC', 'vn_venue_moises_lucarelli', 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2022_r34', 'https://www.cbf.com.br/futebol-brasileiro/tabelas/campeonato-brasileiro/serie-b/2022', 'HIGH', null),
  ('vn_cbf_zerozero_sb2022_r35', 2022, '2022-10-14', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2022', 'R35', 'CONFIRMED', 'Cruzeiro', true, false, 'Vila Nova', 'Cruzeiro', 1, 0, 1, 0, '1–0', 'WIN', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'sexta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2022_r35', 'https://www.cbf.com.br/futebol-brasileiro/tabelas/campeonato-brasileiro/serie-b/2022', 'HIGH', null),
  ('vn_cbf_zerozero_sb2022_r36', 2022, '2022-10-22', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2022', 'R36', 'CONFIRMED', 'Bahia', false, false, 'Bahia', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', 'Arena Fonte Nova', 'MATCH_SPECIFIC', 'vn_venue_fonte_nova', 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2022_r36', 'https://www.cbf.com.br/futebol-brasileiro/tabelas/campeonato-brasileiro/serie-b/2022', 'HIGH', null),
  ('vn_cbf_zerozero_sb2022_r37', 2022, '2022-10-25', '21:30:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2022', 'R37', 'CONFIRMED', 'CSA', false, false, 'CSA', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', 'Estádio Rei Pelé', 'MATCH_SPECIFIC', 'vn_venue_rei_pele', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2022-10-25 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF/Zerozero', 'sb2022_r37', 'https://www.cbf.com.br/futebol-brasileiro/tabelas/campeonato-brasileiro/serie-b/2022', 'HIGH', null),
  ('vn_cbf_zerozero_cv2022_01', 2022, '2022-10-28', null, 'FINISHED', 'Copa Verde', 'COPA_VERDE', 'Copa Verde 2022', 'Oitavas', 'CONFIRMED', 'Operário-VG', true, false, 'Vila Nova', 'Operário-VG', 2, 1, 2, 1, '2–1', 'WIN', null, 'UNKNOWN', null, 'sexta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'cv2022_01', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2022&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_cv2022_02', 2022, '2022-11-01', null, 'FINISHED', 'Copa Verde', 'COPA_VERDE', 'Copa Verde 2022', 'QF', 'CONFIRMED', 'Real Noroeste', true, false, 'Vila Nova', 'Real Noroeste', 0, 0, 0, 0, '0–0', 'DRAW', null, 'UNKNOWN', null, 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'cv2022_02', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2022&grp=1', 'HIGH', 'Resultado no tempo normal preservado como DRAW; disputa registrada separadamente. Disputa de pênaltis: Vila Nova 3–2 Real Noroeste.'),
  ('vn_cbf_zerozero_sb2022_r38', 2022, '2022-11-06', '18:30:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2022', 'R38', 'CONFIRMED', 'Sport Recife', true, false, 'Vila Nova', 'Sport Recife', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'domingo', 'WEEKEND', 'NIGHT', (timestamp '2022-11-06 18:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF/Zerozero', 'sb2022_r38', 'https://www.cbf.com.br/futebol-brasileiro/tabelas/campeonato-brasileiro/serie-b/2022', 'HIGH', null),
  ('vn_cbf_zerozero_cv2022_03', 2022, '2022-11-09', null, 'FINISHED', 'Copa Verde', 'COPA_VERDE', 'Copa Verde 2022', 'SF1', 'CONFIRMED', 'Brasiliense', false, false, 'Brasiliense', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', null, 'UNKNOWN', null, 'quarta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'cv2022_03', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2022&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_cv2022_04', 2022, '2022-11-12', null, 'FINISHED', 'Copa Verde', 'COPA_VERDE', 'Copa Verde 2022', 'SF2', 'CONFIRMED', 'Brasiliense', true, false, 'Vila Nova', 'Brasiliense', 2, 1, 2, 1, '2–1', 'WIN', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'cv2022_04', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2022&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_cv2022_05', 2022, '2022-11-15', null, 'FINISHED', 'Copa Verde', 'COPA_VERDE', 'Copa Verde 2022', 'F1', 'CONFIRMED', 'Paysandu', false, false, 'Paysandu', 'Vila Nova', 0, 0, 0, 0, '0–0', 'DRAW', null, 'UNKNOWN', null, 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'cv2022_05', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2022&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_cv2022_06', 2022, '2022-11-19', null, 'FINISHED', 'Copa Verde', 'COPA_VERDE', 'Copa Verde 2022', 'F2', 'CONFIRMED', 'Paysandu', true, false, 'Vila Nova', 'Paysandu', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'cv2022_06', 'https://www.cbf.com.br/futebol-brasileiro/times/copa-verde/masculino/2022/20079?tab=historico-de-partidas', 'HIGH', 'Resultado no tempo normal preservado como DRAW; disputa registrada separadamente. Disputa de pênaltis: Vila Nova 3–4 Paysandu.')
on conflict (id) do update set
    season = excluded.season,
    match_date = excluded.match_date,
    match_time = excluded.match_time,
    status = excluded.status,
    competition = excluded.competition,
    competition_code = excluded.competition_code,
    competition_edition = excluded.competition_edition,
    round = excluded.round,
    phase_status = excluded.phase_status,
    opponent = excluded.opponent,
    club_is_home = excluded.club_is_home,
    neutral_site = excluded.neutral_site,
    home_team = excluded.home_team,
    away_team = excluded.away_team,
    home_score = excluded.home_score,
    away_score = excluded.away_score,
    club_score = excluded.club_score,
    opponent_score = excluded.opponent_score,
    score_display = excluded.score_display,
    outcome = excluded.outcome,
    stadium = excluded.stadium,
    stadium_status = excluded.stadium_status,
    venue_id = excluded.venue_id,
    weekday = excluded.weekday,
    day_type = excluded.day_type,
    day_period = excluded.day_period,
    kickoff_at = excluded.kickoff_at,
    display_timezone = excluded.display_timezone,
    date_precision = excluded.date_precision,
    source_provider = excluded.source_provider,
    source_match_id = excluded.source_match_id,
    source_url = excluded.source_url,
    source_confidence = excluded.source_confidence,
    data_notes = excluded.data_notes,
    updated_at = now();

do $$
declare v_orphans int;
begin
  select count(*) into v_orphans from public.passport_matches
   where season = 2022 and stadium is not null and venue_id is null;
  if v_orphans > 0 then
    raise exception 'ha % partidas de 2022 com estadio sem venue_id -- rode vilanova_passport_venues_seed.sql antes', v_orphans;
  end if;
end $$;
