-- Passaporte do Vila Nova — temporada 2013. GERADO por
-- `node tooling/vilanova_passport/generate_passport_sql.mjs` a partir de
-- docs/vila_nova_data/passport/passport_2013.json — não edite à mão.
--
-- Rode no projeto Supabase do VILA NOVA — NUNCA no do Goiás nem no do Bragantino.
-- Ordem: vilanova_passport_infra.sql -> vilanova_passport_venues_seed.sql -> ESTE.
-- Idempotente (ON CONFLICT DO UPDATE): reexecutar atualiza, nunca duplica, e
-- não encosta em presença de usuário. 40 partidas.

do $$
begin
  if not exists (select 1 from public.clubs where slug = 'vilanova')
     or exists (select 1 from public.clubs where slug <> 'vilanova') then
    raise exception 'este nao e o projeto Supabase do Vila Nova -- PARE';
  end if;
end $$;

insert into public.passport_matches (
  id, season, match_date, match_time, status, competition, competition_code, competition_edition, round, phase_status, opponent, club_is_home, neutral_site, home_team, away_team, home_score, away_score, club_score, opponent_score, score_display, outcome, stadium, stadium_status, venue_id, weekday, day_type, day_period, kickoff_at, display_timezone, date_precision, source_provider, source_match_id, source_url, source_confidence, data_notes
) values
  ('vn_rsssf_go2013_r01', 2013, '2013-01-19', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2013', 'R1', 'CONFIRMED', 'Rio Verde', false, false, 'Rio Verde', 'Vila Nova', 2, 1, 1, 2, '2–1', 'LOSS', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r01', 'https://www.rsssfbrasil.com/tablesfq/go2013.htm', 'HIGH', null),
  ('vn_rsssf_go2013_r02', 2013, '2013-01-23', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2013', 'R2', 'CONFIRMED', 'CRAC', true, false, 'Vila Nova', 'CRAC', 2, 0, 2, 0, '2–0', 'WIN', null, 'UNKNOWN', null, 'quarta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r02', 'https://www.rsssfbrasil.com/tablesfq/go2013.htm', 'HIGH', null),
  ('vn_rsssf_go2013_r03', 2013, '2013-01-26', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2013', 'R3', 'CONFIRMED', 'Goianésia', true, false, 'Vila Nova', 'Goianésia', 2, 0, 2, 0, '2–0', 'WIN', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r03', 'https://www.rsssfbrasil.com/tablesfq/go2013.htm', 'HIGH', null),
  ('vn_rsssf_go2013_r04', 2013, '2013-01-30', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2013', 'R4', 'CONFIRMED', 'Anápolis', false, false, 'Anápolis', 'Vila Nova', 1, 2, 2, 1, '1–2', 'WIN', null, 'UNKNOWN', null, 'quarta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r04', 'https://www.rsssfbrasil.com/tablesfq/go2013.htm', 'HIGH', null),
  ('vn_rsssf_go2013_r05', 2013, '2013-02-02', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2013', 'R5', 'CONFIRMED', 'Goiás', false, false, 'Goiás', 'Vila Nova', 3, 0, 0, 3, '3–0', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r05', 'https://www.rsssfbrasil.com/tablesfq/go2013.htm', 'HIGH', null),
  ('vn_rsssf_go2013_r06', 2013, '2013-02-06', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2013', 'R6', 'CONFIRMED', 'Aparecidense', true, false, 'Vila Nova', 'Aparecidense', 2, 2, 2, 2, '2–2', 'DRAW', null, 'UNKNOWN', null, 'quarta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r06', 'https://www.rsssfbrasil.com/tablesfq/go2013.htm', 'HIGH', null),
  ('vn_rsssf_go2013_r07', 2013, '2013-02-16', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2013', 'R7', 'CONFIRMED', 'Atlético-GO', true, false, 'Vila Nova', 'Atlético-GO', 0, 1, 0, 1, '0–1', 'LOSS', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r07', 'https://www.rsssfbrasil.com/tablesfq/go2013.htm', 'HIGH', null),
  ('vn_rsssf_go2013_r08', 2013, '2013-02-24', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2013', 'R8', 'CONFIRMED', 'Itumbiara', false, false, 'Itumbiara', 'Vila Nova', 2, 5, 5, 2, '2–5', 'WIN', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r08', 'https://www.rsssfbrasil.com/tablesfq/go2013.htm', 'HIGH', null),
  ('vn_rsssf_go2013_r09', 2013, '2013-03-03', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2013', 'R9', 'CONFIRMED', 'Grêmio Anápolis', true, false, 'Vila Nova', 'Grêmio Anápolis', 1, 2, 1, 2, '1–2', 'LOSS', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r09', 'https://www.rsssfbrasil.com/tablesfq/go2013.htm', 'HIGH', null),
  ('vn_rsssf_go2013_r10', 2013, '2013-03-10', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2013', 'R10', 'CONFIRMED', 'Goiás', true, false, 'Vila Nova', 'Goiás', 0, 2, 0, 2, '0–2', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r10', 'https://www.rsssfbrasil.com/tablesfq/go2013.htm', 'HIGH', null),
  ('vn_rsssf_go2013_r11', 2013, '2013-03-17', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2013', 'R11', 'CONFIRMED', 'Grêmio Anápolis', false, false, 'Grêmio Anápolis', 'Vila Nova', 2, 0, 0, 2, '2–0', 'LOSS', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r11', 'https://www.rsssfbrasil.com/tablesfq/go2013.htm', 'HIGH', null),
  ('vn_rsssf_go2013_r12', 2013, '2013-03-20', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2013', 'R12', 'CONFIRMED', 'Itumbiara', true, false, 'Vila Nova', 'Itumbiara', 2, 0, 2, 0, '2–0', 'WIN', null, 'UNKNOWN', null, 'quarta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r12', 'https://www.rsssfbrasil.com/tablesfq/go2013.htm', 'HIGH', null),
  ('vn_rsssf_go2013_r13', 2013, '2013-03-23', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2013', 'R13', 'CONFIRMED', 'Atlético-GO', false, false, 'Atlético-GO', 'Vila Nova', 4, 1, 1, 4, '4–1', 'LOSS', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r13', 'https://www.rsssfbrasil.com/tablesfq/go2013.htm', 'HIGH', null),
  ('vn_rsssf_go2013_r14', 2013, '2013-03-27', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2013', 'R14', 'CONFIRMED', 'Aparecidense', false, false, 'Aparecidense', 'Vila Nova', 5, 0, 0, 5, '5–0', 'LOSS', null, 'UNKNOWN', null, 'quarta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r14', 'https://www.rsssfbrasil.com/tablesfq/go2013.htm', 'HIGH', null),
  ('vn_rsssf_go2013_r15', 2013, '2013-03-31', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2013', 'R15', 'CONFIRMED', 'Anápolis', true, false, 'Vila Nova', 'Anápolis', 2, 2, 2, 2, '2–2', 'DRAW', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r15', 'https://www.rsssfbrasil.com/tablesfq/go2013.htm', 'HIGH', null),
  ('vn_rsssf_go2013_r16', 2013, '2013-04-07', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2013', 'R16', 'CONFIRMED', 'Goianésia', false, false, 'Goianésia', 'Vila Nova', 3, 2, 2, 3, '3–2', 'LOSS', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r16', 'https://www.rsssfbrasil.com/tablesfq/go2013.htm', 'HIGH', null),
  ('vn_rsssf_go2013_r17', 2013, '2013-04-14', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2013', 'R17', 'CONFIRMED', 'CRAC', false, false, 'CRAC', 'Vila Nova', 3, 2, 2, 3, '3–2', 'LOSS', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r17', 'https://www.rsssfbrasil.com/tablesfq/go2013.htm', 'HIGH', null),
  ('vn_rsssf_go2013_r18', 2013, '2013-04-21', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2013', 'R18', 'CONFIRMED', 'Rio Verde', true, false, 'Vila Nova', 'Rio Verde', 3, 0, 3, 0, '3–0', 'WIN', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r18', 'https://www.rsssfbrasil.com/tablesfq/go2013.htm', 'HIGH', null),
  ('vn_cbf_sc2013_009', 2013, '2013-06-02', '10:00:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2013', 'R01', 'CONFIRMED', 'Grêmio Barueri', true, false, 'Vila Nova', 'Grêmio Barueri', 3, 1, 3, 1, '3–1', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'domingo', 'WEEKEND', 'MORNING', (timestamp '2013-06-02 10:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '009', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2013_games.json', 'HIGH', null),
  ('vn_cbf_sc2013_020', 2013, '2013-06-09', '10:00:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2013', 'R02', 'CONFIRMED', 'Duque de Caxias', false, false, 'Duque de Caxias', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Romário de Souza Faria', 'MATCH_SPECIFIC', 'vn_venue_romario_de_souza_faria', 'domingo', 'WEEKEND', 'MORNING', (timestamp '2013-06-09 10:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '020', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2013_games.json', 'HIGH', null),
  ('vn_cbf_sc2013_026', 2013, '2013-07-06', '18:30:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2013', 'R03', 'CONFIRMED', 'Mogi Mirim', false, false, 'Mogi Mirim', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', 'Estádio Municipal Romildo Vitor Gomes Ferreira', 'MATCH_SPECIFIC', 'vn_venue_municipal_romildo_vitor_gomes_ferreira', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2013-07-06 18:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '026', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2013_games.json', 'HIGH', null),
  ('vn_cbf_sc2013_039', 2013, '2013-07-13', '19:00:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2013', 'R04', 'CONFIRMED', 'CRAC', true, false, 'Vila Nova', 'CRAC', 1, 0, 1, 0, '1–0', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2013-07-13 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '039', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2013_games.json', 'HIGH', null),
  ('vn_cbf_sc2013_048', 2013, '2013-07-20', '15:00:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2013', 'R05', 'CONFIRMED', 'Madureira', false, false, 'Madureira', 'Vila Nova', 1, 3, 3, 1, '1–3', 'WIN', 'Estádio Aniceto Moscoso', 'MATCH_SPECIFIC', 'vn_venue_aniceto_moscoso', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2013-07-20 15:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '048', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2013_games.json', 'HIGH', null),
  ('vn_cbf_sc2013_059', 2013, '2013-07-28', '16:00:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2013', 'R06', 'CONFIRMED', 'Betim', true, false, 'Vila Nova', 'Betim', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'domingo', 'WEEKEND', 'AFTERNOON', (timestamp '2013-07-28 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '059', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2013_games.json', 'HIGH', null),
  ('vn_cbf_sc2013_069', 2013, '2013-08-04', '10:00:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2013', 'R07', 'CONFIRMED', 'Caxias', true, false, 'Vila Nova', 'Caxias', 4, 0, 4, 0, '4–0', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'domingo', 'WEEKEND', 'MORNING', (timestamp '2013-08-04 10:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '069', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2013_games.json', 'HIGH', null),
  ('vn_cbf_sc2013_077', 2013, '2013-08-08', '18:30:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2013', 'R08', 'CONFIRMED', 'Guarani', false, false, 'Guarani', 'Vila Nova', 2, 0, 0, 2, '2–0', 'LOSS', 'Estádio Brinco de Ouro da Princesa', 'MATCH_SPECIFIC', 'vn_venue_brinco_ouro', 'quinta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2013-08-08 18:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '077', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2013_games.json', 'HIGH', null),
  ('vn_cbf_sc2013_089', 2013, '2013-08-11', '10:00:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2013', 'R09', 'CONFIRMED', 'Macaé', true, false, 'Vila Nova', 'Macaé', 0, 1, 0, 1, '0–1', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'domingo', 'WEEKEND', 'MORNING', (timestamp '2013-08-11 10:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '089', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2013_games.json', 'HIGH', null),
  ('vn_cbf_sc2013_098', 2013, '2013-08-18', '16:00:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2013', 'R10', 'CONFIRMED', 'Grêmio Barueri', false, false, 'Grêmio Barueri', 'Vila Nova', 2, 3, 3, 2, '2–3', 'WIN', 'Arena Barueri', 'MATCH_SPECIFIC', 'vn_venue_arena_barueri', 'domingo', 'WEEKEND', 'AFTERNOON', (timestamp '2013-08-18 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '098', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2013_games.json', 'HIGH', null),
  ('vn_cbf_sc2013_109', 2013, '2013-08-25', '10:00:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2013', 'R11', 'CONFIRMED', 'Duque de Caxias', true, false, 'Vila Nova', 'Duque de Caxias', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'domingo', 'WEEKEND', 'MORNING', (timestamp '2013-08-25 10:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '109', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2013_games.json', 'HIGH', null),
  ('vn_cbf_sc2013_119', 2013, '2013-09-01', '10:00:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2013', 'R12', 'CONFIRMED', 'Mogi Mirim', true, false, 'Vila Nova', 'Mogi Mirim', 1, 0, 1, 0, '1–0', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'domingo', 'WEEKEND', 'MORNING', (timestamp '2013-09-01 10:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '119', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2013_games.json', 'HIGH', null),
  ('vn_cbf_sc2013_127', 2013, '2013-09-08', '16:00:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2013', 'R13', 'CONFIRMED', 'CRAC', false, false, 'CRAC', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', 'Estádio Genervino da Fonseca', 'MATCH_SPECIFIC', 'vn_venue_genervino_fonseca', 'domingo', 'WEEKEND', 'AFTERNOON', (timestamp '2013-09-08 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '127', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2013_games.json', 'HIGH', null),
  ('vn_cbf_sc2013_139', 2013, '2013-09-14', '19:00:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2013', 'R14', 'CONFIRMED', 'Madureira', true, false, 'Vila Nova', 'Madureira', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2013-09-14 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '139', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2013_games.json', 'HIGH', null),
  ('vn_cbf_sc2013_146', 2013, '2013-09-25', '20:00:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2013', 'R15', 'CONFIRMED', 'Betim', false, false, 'Betim', 'Vila Nova', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Senador Zezé Perrella', 'MATCH_SPECIFIC', 'vn_venue_senador_zeze_perrella', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2013-09-25 20:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '146', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2013_games.json', 'HIGH', null),
  ('vn_cbf_sc2013_160', 2013, '2013-09-29', '15:30:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2013', 'R16', 'CONFIRMED', 'Caxias', false, false, 'Caxias', 'Vila Nova', 2, 1, 1, 2, '2–1', 'LOSS', 'Estádio Francisco Stédile', 'MATCH_SPECIFIC', 'vn_venue_francisco_stedile', 'domingo', 'WEEKEND', 'AFTERNOON', (timestamp '2013-09-29 15:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '160', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2013_games.json', 'HIGH', null),
  ('vn_cbf_sc2013_169', 2013, '2013-10-05', '16:00:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2013', 'R17', 'CONFIRMED', 'Guarani', true, false, 'Vila Nova', 'Guarani', 1, 0, 1, 0, '1–0', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2013-10-05 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '169', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2013_games.json', 'HIGH', null),
  ('vn_cbf_sc2013_179', 2013, '2013-10-12', '19:00:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2013', 'R18', 'CONFIRMED', 'Macaé', false, false, 'Macaé', 'Vila Nova', 0, 1, 1, 0, '0–1', 'WIN', 'Estádio Cláudio Moacyr de Azevedo', 'MATCH_SPECIFIC', 'vn_venue_claudio_moacyr_de_azevedo', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2013-10-12 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '179', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2013_games.json', 'HIGH', null),
  ('vn_cbf_sc2013_185', 2013, '2013-10-20', '19:00:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2013', 'Quartas - ida', 'CONFIRMED', 'Treze', false, false, 'Treze', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', 'Estádio Presidente Vargas (Campina Grande)', 'MATCH_SPECIFIC', 'vn_venue_presidente_vargas_campina_grande', 'domingo', 'WEEKEND', 'NIGHT', (timestamp '2013-10-20 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '185', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2013_games.json', 'HIGH', null),
  ('vn_cbf_sc2013_186', 2013, '2013-10-27', '19:00:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2013', 'Quartas - volta', 'CONFIRMED', 'Treze', true, false, 'Vila Nova', 'Treze', 2, 0, 2, 0, '2–0', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'domingo', 'WEEKEND', 'NIGHT', (timestamp '2013-10-27 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '186', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2013_games.json', 'HIGH', null),
  ('vn_cbf_sc2013_215', 2013, '2013-11-02', '19:00:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2013', 'Semifinal - ida', 'CONFIRMED', 'Sampaio Corrêa', true, false, 'Vila Nova', 'Sampaio Corrêa', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2013-11-02 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '215', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2013_games.json', 'HIGH', null),
  ('vn_cbf_sc2013_216', 2013, '2013-11-09', '19:00:00', 'FINISHED', 'Série C', 'BRASILEIRO_C', 'Série C 2013', 'Semifinal - volta', 'CONFIRMED', 'Sampaio Corrêa', false, false, 'Sampaio Corrêa', 'Vila Nova', 2, 1, 1, 2, '2–1', 'LOSS', 'Estádio Governador João Castelo', 'MATCH_SPECIFIC', 'vn_venue_castelao_sao_luis', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2013-11-09 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '216', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_C_2013_games.json', 'HIGH', null)
on conflict (id) do update set
    season = excluded.season,
    match_date = excluded.match_date,
    match_time = excluded.match_time,
    status = excluded.status,
    competition = excluded.competition,
    competition_code = excluded.competition_code,
    competition_edition = excluded.competition_edition,
    round = excluded.round,
    phase_status = excluded.phase_status,
    opponent = excluded.opponent,
    club_is_home = excluded.club_is_home,
    neutral_site = excluded.neutral_site,
    home_team = excluded.home_team,
    away_team = excluded.away_team,
    home_score = excluded.home_score,
    away_score = excluded.away_score,
    club_score = excluded.club_score,
    opponent_score = excluded.opponent_score,
    score_display = excluded.score_display,
    outcome = excluded.outcome,
    stadium = excluded.stadium,
    stadium_status = excluded.stadium_status,
    venue_id = excluded.venue_id,
    weekday = excluded.weekday,
    day_type = excluded.day_type,
    day_period = excluded.day_period,
    kickoff_at = excluded.kickoff_at,
    display_timezone = excluded.display_timezone,
    date_precision = excluded.date_precision,
    source_provider = excluded.source_provider,
    source_match_id = excluded.source_match_id,
    source_url = excluded.source_url,
    source_confidence = excluded.source_confidence,
    data_notes = excluded.data_notes,
    updated_at = now();

do $$
declare v_orphans int;
begin
  select count(*) into v_orphans from public.passport_matches
   where season = 2013 and stadium is not null and venue_id is null;
  if v_orphans > 0 then
    raise exception 'ha % partidas de 2013 com estadio sem venue_id -- rode vilanova_passport_venues_seed.sql antes', v_orphans;
  end if;
end $$;
