-- Passaporte do Vila Nova — temporada 2011. GERADO por
-- `node tooling/vilanova_passport/generate_passport_sql.mjs` a partir de
-- docs/vila_nova_data/passport/passport_2011.json — não edite à mão.
--
-- Rode no projeto Supabase do VILA NOVA — NUNCA no do Goiás nem no do Bragantino.
-- Ordem: vilanova_passport_infra.sql -> vilanova_passport_venues_seed.sql -> ESTE.
-- Idempotente (ON CONFLICT DO UPDATE): reexecutar atualiza, nunca duplica, e
-- não encosta em presença de usuário. 58 partidas.

do $$
begin
  if not exists (select 1 from public.clubs where slug = 'vilanova')
     or exists (select 1 from public.clubs where slug <> 'vilanova') then
    raise exception 'este nao e o projeto Supabase do Vila Nova -- PARE';
  end if;
end $$;

insert into public.passport_matches (
  id, season, match_date, match_time, status, competition, competition_code, competition_edition, round, phase_status, opponent, club_is_home, neutral_site, home_team, away_team, home_score, away_score, club_score, opponent_score, score_display, outcome, stadium, stadium_status, venue_id, weekday, day_type, day_period, kickoff_at, display_timezone, date_precision, source_provider, source_match_id, source_url, source_confidence, data_notes
) values
  ('vn_rsssf_go2011_r01', 2011, '2011-01-16', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2011', 'R1', 'CONFIRMED', 'Goianésia', false, false, 'Goianésia', 'Vila Nova', 0, 1, 1, 0, '0–1', 'WIN', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r01', 'https://www.rsssfbrasil.com/tablesfq/go2011.htm', 'HIGH', null),
  ('vn_rsssf_go2011_r02', 2011, '2011-01-19', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2011', 'R2', 'CONFIRMED', 'Anapolina', true, false, 'Vila Nova', 'Anapolina', 1, 1, 1, 1, '1–1', 'DRAW', null, 'UNKNOWN', null, 'quarta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r02', 'https://www.rsssfbrasil.com/tablesfq/go2011.htm', 'HIGH', null),
  ('vn_rsssf_go2011_r03', 2011, '2011-01-22', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2011', 'R3', 'CONFIRMED', 'Goiás', true, false, 'Vila Nova', 'Goiás', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r03', 'https://www.rsssfbrasil.com/tablesfq/go2011.htm', 'HIGH', null),
  ('vn_rsssf_go2011_r04', 2011, '2011-01-26', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2011', 'R4', 'CONFIRMED', 'Santa Helena', false, false, 'Santa Helena', 'Vila Nova', 1, 4, 4, 1, '1–4', 'WIN', null, 'UNKNOWN', null, 'quarta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r04', 'https://www.rsssfbrasil.com/tablesfq/go2011.htm', 'HIGH', null),
  ('vn_rsssf_go2011_r05', 2011, '2011-01-30', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2011', 'R5', 'CONFIRMED', 'CRAC', false, false, 'CRAC', 'Vila Nova', 0, 2, 2, 0, '0–2', 'WIN', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r05', 'https://www.rsssfbrasil.com/tablesfq/go2011.htm', 'HIGH', null),
  ('vn_rsssf_go2011_r06', 2011, '2011-02-02', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2011', 'R6', 'CONFIRMED', 'Trindade', true, false, 'Vila Nova', 'Trindade', 2, 0, 2, 0, '2–0', 'WIN', null, 'UNKNOWN', null, 'quarta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r06', 'https://www.rsssfbrasil.com/tablesfq/go2011.htm', 'HIGH', null),
  ('vn_rsssf_go2011_r07', 2011, '2011-02-05', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2011', 'R7', 'CONFIRMED', 'Atlético-GO', false, false, 'Atlético-GO', 'Vila Nova', 2, 1, 1, 2, '2–1', 'LOSS', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r07', 'https://www.rsssfbrasil.com/tablesfq/go2011.htm', 'HIGH', null),
  ('vn_rsssf_go2011_r08', 2011, '2011-02-13', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2011', 'R8', 'CONFIRMED', 'Aparecidense', true, false, 'Vila Nova', 'Aparecidense', 3, 2, 3, 2, '3–2', 'WIN', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r08', 'https://www.rsssfbrasil.com/tablesfq/go2011.htm', 'HIGH', null),
  ('vn_rsssf_go2011_r09', 2011, '2011-02-21', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2011', 'R9', 'CONFIRMED', 'Morrinhos', true, false, 'Vila Nova', 'Morrinhos', 3, 1, 3, 1, '3–1', 'WIN', null, 'UNKNOWN', null, 'segunda-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r09', 'https://www.rsssfbrasil.com/tablesfq/go2011.htm', 'HIGH', null),
  ('vn_rsssf_go2011_r10', 2011, '2011-02-26', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2011', 'R10', 'CONFIRMED', 'Goiás', false, false, 'Goiás', 'Vila Nova', 2, 1, 1, 2, '2–1', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r10', 'https://www.rsssfbrasil.com/tablesfq/go2011.htm', 'HIGH', null),
  ('vn_rsssf_go2011_r11', 2011, '2011-03-09', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2011', 'R11', 'CONFIRMED', 'CRAC', true, false, 'Vila Nova', 'CRAC', 5, 2, 5, 2, '5–2', 'WIN', null, 'UNKNOWN', null, 'quarta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r11', 'https://www.rsssfbrasil.com/tablesfq/go2011.htm', 'HIGH', null),
  ('vn_rsssf_go2011_r12', 2011, '2011-03-14', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2011', 'R12', 'CONFIRMED', 'Trindade', false, false, 'Trindade', 'Vila Nova', 1, 3, 3, 1, '1–3', 'WIN', null, 'UNKNOWN', null, 'segunda-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r12', 'https://www.rsssfbrasil.com/tablesfq/go2011.htm', 'HIGH', null),
  ('vn_rsssf_go2011_r13', 2011, '2011-03-21', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2011', 'R13', 'CONFIRMED', 'Aparecidense', false, false, 'Aparecidense', 'Vila Nova', 2, 1, 1, 2, '2–1', 'LOSS', null, 'UNKNOWN', null, 'segunda-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r13', 'https://www.rsssfbrasil.com/tablesfq/go2011.htm', 'HIGH', null),
  ('vn_rsssf_go2011_r14', 2011, '2011-03-24', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2011', 'R14', 'CONFIRMED', 'Santa Helena', true, false, 'Vila Nova', 'Santa Helena', 1, 2, 1, 2, '1–2', 'LOSS', null, 'UNKNOWN', null, 'quinta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r14', 'https://www.rsssfbrasil.com/tablesfq/go2011.htm', 'HIGH', null),
  ('vn_rsssf_go2011_r15', 2011, '2011-03-27', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2011', 'R15', 'CONFIRMED', 'Atlético-GO', true, false, 'Vila Nova', 'Atlético-GO', 1, 0, 1, 0, '1–0', 'WIN', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r15', 'https://www.rsssfbrasil.com/tablesfq/go2011.htm', 'HIGH', null),
  ('vn_rsssf_go2011_r16', 2011, '2011-04-03', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2011', 'R16', 'CONFIRMED', 'Morrinhos', false, false, 'Morrinhos', 'Vila Nova', 2, 3, 3, 2, '2–3', 'WIN', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r16', 'https://www.rsssfbrasil.com/tablesfq/go2011.htm', 'HIGH', null),
  ('vn_rsssf_go2011_r17', 2011, '2011-04-10', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2011', 'R17', 'CONFIRMED', 'Anapolina', false, false, 'Anapolina', 'Vila Nova', 2, 2, 2, 2, '2–2', 'DRAW', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r17', 'https://www.rsssfbrasil.com/tablesfq/go2011.htm', 'HIGH', null),
  ('vn_rsssf_go2011_r18', 2011, '2011-04-17', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2011', 'R18', 'CONFIRMED', 'Goianésia', true, false, 'Vila Nova', 'Goianésia', 3, 1, 3, 1, '3–1', 'WIN', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r18', 'https://www.rsssfbrasil.com/tablesfq/go2011.htm', 'HIGH', null),
  ('vn_rsssf_go2011_sf1', 2011, '2011-04-24', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2011', 'Semifinal - ida', 'CONFIRMED', 'Goiás', false, false, 'Goiás', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'sf1', 'https://www.rsssfbrasil.com/tablesfq/go2011.htm', 'HIGH', null),
  ('vn_rsssf_go2011_sf2', 2011, '2011-05-01', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2011', 'Semifinal - volta', 'CONFIRMED', 'Goiás', true, false, 'Vila Nova', 'Goiás', 2, 2, 2, 2, '2–2', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'sf2', 'https://www.rsssfbrasil.com/tablesfq/go2011.htm', 'HIGH', null),
  ('vn_rsssf_sb2011_r01', 2011, '2011-05-21', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2011', 'R01', 'CONFIRMED', 'Vitória', false, false, 'Vitória', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', 'Estádio Manoel Barradas', 'MATCH_SPECIFIC', 'vn_venue_barradao', 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r01', 'https://www.rsssfbrasil.com/tablesae/br2011l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2011_r02', 2011, '2011-05-27', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2011', 'R02', 'CONFIRMED', 'Ponte Preta', true, false, 'Vila Nova', 'Ponte Preta', 3, 1, 3, 1, '3–1', 'WIN', null, 'UNKNOWN', null, 'sexta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r02', 'https://www.rsssfbrasil.com/tablesae/br2011l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2011_r03', 2011, '2011-06-04', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2011', 'R03', 'CONFIRMED', 'Boa Esporte', false, false, 'Boa Esporte', 'Vila Nova', 0, 0, 0, 0, '0–0', 'DRAW', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r03', 'https://www.rsssfbrasil.com/tablesae/br2011l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2011_r04', 2011, '2011-06-11', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2011', 'R04', 'CONFIRMED', 'Criciúma', true, false, 'Vila Nova', 'Criciúma', 2, 0, 2, 0, '2–0', 'WIN', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r04', 'https://www.rsssfbrasil.com/tablesae/br2011l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2011_r05', 2011, '2011-06-14', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2011', 'R05', 'CONFIRMED', 'Bragantino', false, false, 'Bragantino', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', null, 'UNKNOWN', null, 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r05', 'https://www.rsssfbrasil.com/tablesae/br2011l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2011_r06', 2011, '2011-06-18', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2011', 'R06', 'CONFIRMED', 'ABC', true, false, 'Vila Nova', 'ABC', 2, 2, 2, 2, '2–2', 'DRAW', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r06', 'https://www.rsssfbrasil.com/tablesae/br2011l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2011_r07', 2011, '2011-06-25', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2011', 'R07', 'CONFIRMED', 'ASA', false, false, 'ASA', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r07', 'https://www.rsssfbrasil.com/tablesae/br2011l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2011_r08', 2011, '2011-06-28', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2011', 'R08', 'CONFIRMED', 'Guarani', false, false, 'Guarani', 'Vila Nova', 0, 1, 1, 0, '0–1', 'WIN', null, 'UNKNOWN', null, 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r08', 'https://www.rsssfbrasil.com/tablesae/br2011l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2011_r09', 2011, '2011-07-01', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2011', 'R09', 'CONFIRMED', 'Icasa', true, false, 'Vila Nova', 'Icasa', 1, 2, 1, 2, '1–2', 'LOSS', null, 'UNKNOWN', null, 'sexta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r09', 'https://www.rsssfbrasil.com/tablesae/br2011l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2011_r10', 2011, '2011-07-08', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2011', 'R10', 'CONFIRMED', 'São Caetano', true, false, 'Vila Nova', 'São Caetano', 2, 0, 2, 0, '2–0', 'WIN', null, 'UNKNOWN', null, 'sexta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r10', 'https://www.rsssfbrasil.com/tablesae/br2011l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2011_r11', 2011, '2011-07-15', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2011', 'R11', 'CONFIRMED', 'Paraná', false, false, 'Paraná', 'Vila Nova', 2, 1, 1, 2, '2–1', 'LOSS', null, 'UNKNOWN', null, 'sexta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r11', 'https://www.rsssfbrasil.com/tablesae/br2011l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2011_r12', 2011, '2011-07-23', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2011', 'R12', 'CONFIRMED', 'Náutico', true, false, 'Vila Nova', 'Náutico', 0, 0, 0, 0, '0–0', 'DRAW', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r12', 'https://www.rsssfbrasil.com/tablesae/br2011l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2011_r13', 2011, '2011-07-26', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2011', 'R13', 'CONFIRMED', 'Grêmio Barueri', false, false, 'Grêmio Barueri', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', null, 'UNKNOWN', null, 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r13', 'https://www.rsssfbrasil.com/tablesae/br2011l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2011_r14', 2011, '2011-07-29', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2011', 'R14', 'CONFIRMED', 'Salgueiro', true, false, 'Vila Nova', 'Salgueiro', 1, 0, 1, 0, '1–0', 'WIN', null, 'UNKNOWN', null, 'sexta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r14', 'https://www.rsssfbrasil.com/tablesae/br2011l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2011_r15', 2011, '2011-08-06', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2011', 'R15', 'CONFIRMED', 'Goiás', false, false, 'Goiás', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r15', 'https://www.rsssfbrasil.com/tablesae/br2011l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2011_r16', 2011, '2011-08-09', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2011', 'R16', 'CONFIRMED', 'Duque de Caxias', true, false, 'Vila Nova', 'Duque de Caxias', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r16', 'https://www.rsssfbrasil.com/tablesae/br2011l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2011_r17', 2011, '2011-08-16', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2011', 'R17', 'CONFIRMED', 'Portuguesa', false, false, 'Portuguesa', 'Vila Nova', 0, 1, 1, 0, '0–1', 'WIN', null, 'UNKNOWN', null, 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r17', 'https://www.rsssfbrasil.com/tablesae/br2011l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2011_r18', 2011, '2011-08-20', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2011', 'R18', 'CONFIRMED', 'Americana', true, false, 'Vila Nova', 'Americana', 1, 3, 1, 3, '1–3', 'LOSS', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r18', 'https://www.rsssfbrasil.com/tablesae/br2011l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2011_r19', 2011, '2011-08-23', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2011', 'R19', 'CONFIRMED', 'Sport', false, false, 'Sport', 'Vila Nova', 2, 0, 0, 2, '2–0', 'LOSS', null, 'UNKNOWN', null, 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r19', 'https://www.rsssfbrasil.com/tablesae/br2011l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2011_r20', 2011, '2011-08-30', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2011', 'R20', 'CONFIRMED', 'Vitória', true, false, 'Vila Nova', 'Vitória', 0, 3, 0, 3, '0–3', 'LOSS', null, 'UNKNOWN', null, 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r20', 'https://www.rsssfbrasil.com/tablesae/br2011l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2011_r21', 2011, '2011-09-02', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2011', 'R21', 'CONFIRMED', 'Ponte Preta', false, false, 'Ponte Preta', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', null, 'UNKNOWN', null, 'sexta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r21', 'https://www.rsssfbrasil.com/tablesae/br2011l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2011_r22', 2011, '2011-09-10', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2011', 'R22', 'CONFIRMED', 'Boa Esporte', true, false, 'Vila Nova', 'Boa Esporte', 1, 2, 1, 2, '1–2', 'LOSS', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r22', 'https://www.rsssfbrasil.com/tablesae/br2011l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2011_r23', 2011, '2011-09-13', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2011', 'R23', 'CONFIRMED', 'Criciúma', false, false, 'Criciúma', 'Vila Nova', 3, 1, 1, 3, '3–1', 'LOSS', 'Estádio Heriberto Hülse', 'MATCH_SPECIFIC', 'vn_venue_heriberto_h_lse', 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r23', 'https://www.rsssfbrasil.com/tablesae/br2011l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2011_r24', 2011, '2011-09-16', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2011', 'R24', 'CONFIRMED', 'Bragantino', true, false, 'Vila Nova', 'Bragantino', 1, 2, 1, 2, '1–2', 'LOSS', null, 'UNKNOWN', null, 'sexta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r24', 'https://www.rsssfbrasil.com/tablesae/br2011l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2011_r25', 2011, '2011-09-20', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2011', 'R25', 'CONFIRMED', 'ABC', false, false, 'ABC', 'Vila Nova', 1, 2, 2, 1, '1–2', 'WIN', null, 'UNKNOWN', null, 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r25', 'https://www.rsssfbrasil.com/tablesae/br2011l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2011_r26', 2011, '2011-09-27', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2011', 'R26', 'CONFIRMED', 'ASA', true, false, 'Vila Nova', 'ASA', 1, 1, 1, 1, '1–1', 'DRAW', null, 'UNKNOWN', null, 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r26', 'https://www.rsssfbrasil.com/tablesae/br2011l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2011_r27', 2011, '2011-09-30', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2011', 'R27', 'CONFIRMED', 'Guarani', true, false, 'Vila Nova', 'Guarani', 0, 0, 0, 0, '0–0', 'DRAW', null, 'UNKNOWN', null, 'sexta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r27', 'https://www.rsssfbrasil.com/tablesae/br2011l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2011_r28', 2011, '2011-10-04', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2011', 'R28', 'CONFIRMED', 'Icasa', false, false, 'Icasa', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', null, 'UNKNOWN', null, 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r28', 'https://www.rsssfbrasil.com/tablesae/br2011l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2011_r29', 2011, '2011-10-07', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2011', 'R29', 'CONFIRMED', 'São Caetano', false, false, 'São Caetano', 'Vila Nova', 3, 0, 0, 3, '3–0', 'LOSS', null, 'UNKNOWN', null, 'sexta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r29', 'https://www.rsssfbrasil.com/tablesae/br2011l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2011_r30', 2011, '2011-10-15', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2011', 'R30', 'CONFIRMED', 'Paraná', true, false, 'Vila Nova', 'Paraná', 0, 1, 0, 1, '0–1', 'LOSS', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r30', 'https://www.rsssfbrasil.com/tablesae/br2011l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2011_r31', 2011, '2011-10-18', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2011', 'R31', 'CONFIRMED', 'Náutico', false, false, 'Náutico', 'Vila Nova', 4, 2, 2, 4, '4–2', 'LOSS', null, 'UNKNOWN', null, 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r31', 'https://www.rsssfbrasil.com/tablesae/br2011l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2011_r32', 2011, '2011-10-21', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2011', 'R32', 'CONFIRMED', 'Grêmio Barueri', true, false, 'Vila Nova', 'Grêmio Barueri', 2, 2, 2, 2, '2–2', 'DRAW', null, 'UNKNOWN', null, 'sexta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r32', 'https://www.rsssfbrasil.com/tablesae/br2011l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2011_r33', 2011, '2011-10-28', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2011', 'R33', 'CONFIRMED', 'Salgueiro', false, false, 'Salgueiro', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Mauro Sampaio', 'MATCH_SPECIFIC', 'vn_venue_mauro_sampaio', 'sexta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r33', 'https://www.rsssfbrasil.com/tablesae/br2011l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2011_r34', 2011, '2011-11-04', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2011', 'R34', 'CONFIRMED', 'Goiás', true, false, 'Vila Nova', 'Goiás', 2, 3, 2, 3, '2–3', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sexta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r34', 'https://www.rsssfbrasil.com/tablesae/br2011l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2011_r35', 2011, '2011-11-08', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2011', 'R35', 'CONFIRMED', 'Duque de Caxias', false, false, 'Duque de Caxias', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', null, 'UNKNOWN', null, 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r35', 'https://www.rsssfbrasil.com/tablesae/br2011l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2011_r36', 2011, '2011-11-12', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2011', 'R36', 'CONFIRMED', 'Portuguesa', true, false, 'Vila Nova', 'Portuguesa', 1, 3, 1, 3, '1–3', 'LOSS', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r36', 'https://www.rsssfbrasil.com/tablesae/br2011l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2011_r37', 2011, '2011-11-19', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2011', 'R37', 'CONFIRMED', 'Americana', false, false, 'Americana', 'Vila Nova', 2, 1, 1, 2, '2–1', 'LOSS', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r37', 'https://www.rsssfbrasil.com/tablesae/br2011l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2011_r38', 2011, '2011-11-26', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2011', 'R38', 'CONFIRMED', 'Sport', true, false, 'Vila Nova', 'Sport', 0, 1, 0, 1, '0–1', 'LOSS', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r38', 'https://www.rsssfbrasil.com/tablesae/br2011l2.htm', 'HIGH', null)
on conflict (id) do update set
    season = excluded.season,
    match_date = excluded.match_date,
    match_time = excluded.match_time,
    status = excluded.status,
    competition = excluded.competition,
    competition_code = excluded.competition_code,
    competition_edition = excluded.competition_edition,
    round = excluded.round,
    phase_status = excluded.phase_status,
    opponent = excluded.opponent,
    club_is_home = excluded.club_is_home,
    neutral_site = excluded.neutral_site,
    home_team = excluded.home_team,
    away_team = excluded.away_team,
    home_score = excluded.home_score,
    away_score = excluded.away_score,
    club_score = excluded.club_score,
    opponent_score = excluded.opponent_score,
    score_display = excluded.score_display,
    outcome = excluded.outcome,
    stadium = excluded.stadium,
    stadium_status = excluded.stadium_status,
    venue_id = excluded.venue_id,
    weekday = excluded.weekday,
    day_type = excluded.day_type,
    day_period = excluded.day_period,
    kickoff_at = excluded.kickoff_at,
    display_timezone = excluded.display_timezone,
    date_precision = excluded.date_precision,
    source_provider = excluded.source_provider,
    source_match_id = excluded.source_match_id,
    source_url = excluded.source_url,
    source_confidence = excluded.source_confidence,
    data_notes = excluded.data_notes,
    updated_at = now();

do $$
declare v_orphans int;
begin
  select count(*) into v_orphans from public.passport_matches
   where season = 2011 and stadium is not null and venue_id is null;
  if v_orphans > 0 then
    raise exception 'ha % partidas de 2011 com estadio sem venue_id -- rode vilanova_passport_venues_seed.sql antes', v_orphans;
  end if;
end $$;
