-- Passaporte do Vila Nova — temporada 2026. GERADO por
-- `node tooling/vilanova_passport/generate_passport_sql.mjs` a partir de
-- docs/vila_nova_data/passport/passport_2026.json — não edite à mão.
--
-- Rode no projeto Supabase do VILA NOVA — NUNCA no do Goiás nem no do Bragantino.
-- Ordem: vilanova_passport_infra.sql -> vilanova_passport_venues_seed.sql -> ESTE.
-- Idempotente (ON CONFLICT DO UPDATE): reexecutar atualiza, nunca duplica, e
-- não encosta em presença de usuário. 55 partidas.

do $$
begin
  if not exists (select 1 from public.clubs where slug = 'vilanova')
     or exists (select 1 from public.clubs where slug <> 'vilanova') then
    raise exception 'este nao e o projeto Supabase do Vila Nova -- PARE';
  end if;
end $$;

insert into public.passport_matches (
  id, season, match_date, match_time, status, competition, competition_code, competition_edition, round, phase_status, opponent, club_is_home, neutral_site, home_team, away_team, home_score, away_score, club_score, opponent_score, score_display, outcome, stadium, stadium_status, venue_id, weekday, day_type, day_period, kickoff_at, display_timezone, date_precision, source_provider, source_match_id, source_url, source_confidence, data_notes
) values
  ('vn_official_goiano_2026_r01', 2026, '2026-01-10', '16:00:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2026', 'R1', 'CONFIRMED', 'Abecat', false, false, 'Abecat', 'Vila Nova', 1, 2, 2, 1, '1–2', 'WIN', 'Estádio Luiz Benedito', 'MATCH_SPECIFIC', 'vn_venue_luiz_benedito', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2026-01-10 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_official_goiano_2026_r02', 2026, '2026-01-14', '20:40:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2026', 'R2', 'CONFIRMED', 'Anapolina', true, false, 'Vila Nova', 'Anapolina', 3, 2, 3, 2, '3–2', 'WIN', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-01-14 20:40:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_official_goiano_2026_r03', 2026, '2026-01-17', '16:00:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2026', 'R3', 'CONFIRMED', 'Anápolis', false, false, 'Anápolis', 'Vila Nova', 1, 3, 3, 1, '1–3', 'WIN', 'Estádio Jonas Duarte', 'MATCH_SPECIFIC', 'vn_venue_jonas_duarte', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2026-01-17 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_official_goiano_2026_r04', 2026, '2026-01-22', '20:40:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2026', 'R4', 'CONFIRMED', 'Aparecidense', true, false, 'Vila Nova', 'Aparecidense', 3, 0, 3, 0, '3–0', 'WIN', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'quinta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-01-22 20:40:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_official_goiano_2026_r05', 2026, '2026-01-25', '17:00:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2026', 'R5', 'CONFIRMED', 'Atlético-GO', true, false, 'Vila Nova', 'Atlético-GO', 1, 2, 1, 2, '1–2', 'LOSS', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'domingo', 'WEEKEND', 'AFTERNOON', (timestamp '2026-01-25 17:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_official_goiano_2026_r06', 2026, '2026-01-29', '15:30:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2026', 'R6', 'CONFIRMED', 'Centro-Oeste', false, false, 'Centro-Oeste', 'Vila Nova', 0, 2, 2, 0, '0–2', 'WIN', 'Estádio Jaime Guerra', 'MATCH_SPECIFIC', 'vn_venue_jaime_guerra', 'quinta-feira', 'WEEKDAY', 'AFTERNOON', (timestamp '2026-01-29 15:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_official_goiano_2026_r07', 2026, '2026-02-01', '18:30:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2026', 'R7', 'CONFIRMED', 'Goiás', false, false, 'Goiás', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', 'Estádio Hailé Pinheiro', 'MATCH_SPECIFIC', 'vn_venue_serrinha', 'domingo', 'WEEKEND', 'NIGHT', (timestamp '2026-02-01 18:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_official_goiano_2026_r08', 2026, '2026-02-08', '16:00:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2026', 'R8', 'CONFIRMED', 'Jataiense', true, false, 'Vila Nova', 'Jataiense', 4, 1, 4, 1, '4–1', 'WIN', 'Estádio Olímpico Pedro Ludovico Teixeira', 'MATCH_SPECIFIC', 'vn_venue_olimpico', 'domingo', 'WEEKEND', 'AFTERNOON', (timestamp '2026-02-08 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_official_goiano_2026_qf1', 2026, '2026-02-12', '21:00:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2026', 'Quartas de final — ida', 'CONFIRMED', 'Anápolis', false, false, 'Anápolis', 'Vila Nova', 0, 2, 2, 0, '0–2', 'WIN', 'Estádio Jonas Duarte', 'MATCH_SPECIFIC', 'vn_venue_jonas_duarte', 'quinta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-02-12 21:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_official_goiano_2026_qf2', 2026, '2026-02-16', '19:30:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2026', 'Quartas de final — volta', 'CONFIRMED', 'Anápolis', true, false, 'Vila Nova', 'Anápolis', 2, 2, 2, 2, '2–2', 'DRAW', 'Estádio Olímpico Pedro Ludovico Teixeira', 'MATCH_SPECIFIC', 'vn_venue_olimpico', 'segunda-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-02-16 19:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_official_goiano_2026_sf1', 2026, '2026-02-22', '17:00:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2026', 'Semifinal — ida', 'CONFIRMED', 'Atlético-GO', false, false, 'Atlético-GO', 'Vila Nova', 2, 0, 0, 2, '2–0', 'LOSS', 'Estádio Antônio Accioly', 'MATCH_SPECIFIC', 'vn_venue_ant_nio_accioly', 'domingo', 'WEEKEND', 'AFTERNOON', (timestamp '2026-02-22 17:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_official_goiano_2026_sf2', 2026, '2026-03-01', '17:00:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2026', 'Semifinal — volta', 'CONFIRMED', 'Atlético-GO', true, false, 'Vila Nova', 'Atlético-GO', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'domingo', 'WEEKEND', 'AFTERNOON', (timestamp '2026-03-01 17:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_official_cdb_2026_f2_velo', 2026, '2026-03-04', '19:00:00', 'FINISHED', 'Copa do Brasil', 'COPA_DO_BRASIL', 'Copa do Brasil 2026', '2ª fase', 'CONFIRMED', 'Velo Clube', false, false, 'Velo Clube', 'Vila Nova', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Benito Agnelo Castellano', 'MATCH_SPECIFIC', 'vn_venue_benitao', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-03-04 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', 'Disputa de pênaltis: Velo Clube 2–4 Vila Nova.'),
  ('vn_official_cdb_2026_f3_operario_ms', 2026, '2026-03-12', '19:00:00', 'FINISHED', 'Copa do Brasil', 'COPA_DO_BRASIL', 'Copa do Brasil 2026', '3ª fase', 'CONFIRMED', 'Operário-MS', true, false, 'Vila Nova', 'Operário-MS', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'quinta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-03-12 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', 'Disputa de pênaltis: Vila Nova 5–4 Operário-MS.'),
  ('vn_official_cdb_2026_f4_confianca', 2026, '2026-03-18', '19:00:00', 'FINISHED', 'Copa do Brasil', 'COPA_DO_BRASIL', 'Copa do Brasil 2026', '4ª fase', 'CONFIRMED', 'Confiança', true, false, 'Vila Nova', 'Confiança', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-03-18 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', 'Disputa de pênaltis: Vila Nova 3–5 Confiança.'),
  ('vn_official_serie_b_2026_r01', 2026, '2026-03-21', '17:00:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2026', 'R1', 'CONFIRMED', 'CRB', true, false, 'Vila Nova', 'CRB', 2, 2, 2, 2, '2–2', 'DRAW', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2026-03-21 17:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_cbf_833618', 2026, '2026-03-24', '19:00:00', 'FINISHED', 'Copa Centro-Oeste / Copa Verde', 'COPA_CENTRO_OESTE', 'Copa Verde 2026 — Copa Centro-Oeste', 'R1', 'CONFIRMED', 'Rio Branco-ES', false, false, 'Rio Branco-ES', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', 'Estádio Estadual Kleber José de Andrade', 'MATCH_SPECIFIC', 'vn_venue_kleber_andrade', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-03-24 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF', '833618', 'https://www.cbf.com.br/futebol-brasileiro/jogos/copa-verde/masculino/2026/rio-branco-a-c-saf-x-vila-nova/833618', 'HIGH', null),
  ('vn_cbf_833624', 2026, '2026-03-28', '20:30:00', 'FINISHED', 'Copa Centro-Oeste / Copa Verde', 'COPA_CENTRO_OESTE', 'Copa Verde 2026 — Copa Centro-Oeste', 'R2', 'CONFIRMED', 'Operário-MS', true, false, 'Vila Nova', 'Operário-MS', 6, 0, 6, 0, '6–0', 'WIN', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2026-03-28 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF', '833624', 'https://www.cbf.com.br/futebol-brasileiro/jogos/copa-verde/profissional/2026/vila-nova-x-operario/833624', 'HIGH', null),
  ('vn_official_serie_b_2026_r02', 2026, '2026-04-01', '19:00:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2026', 'R2', 'CONFIRMED', 'Sport', false, false, 'Sport', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Adelmar da Costa Carvalho', 'MATCH_SPECIFIC', 'vn_venue_ilha_do_retiro', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-04-01 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_official_serie_b_2026_r03', 2026, '2026-04-04', '20:00:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2026', 'R3', 'CONFIRMED', 'Atlético-GO', true, false, 'Vila Nova', 'Atlético-GO', 2, 1, 2, 1, '2–1', 'WIN', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2026-04-04 20:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_cbf_833630', 2026, '2026-04-08', '19:00:00', 'FINISHED', 'Copa Centro-Oeste / Copa Verde', 'COPA_CENTRO_OESTE', 'Copa Verde 2026 — Copa Centro-Oeste', 'R3', 'CONFIRMED', 'Primavera', false, false, 'Primavera', 'Vila Nova', 2, 2, 2, 2, '2–2', 'DRAW', 'Estádio Antônio Santo Renosto', 'MATCH_SPECIFIC', 'vn_venue_cerradao', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-04-08 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF', '833630', 'https://www.cbf.com.br/futebol-brasileiro/jogos/copa-verde/profissional/2026/primavera-atletico-clube-x-vila-nova/833630', 'HIGH', null),
  ('vn_official_serie_b_2026_r04', 2026, '2026-04-11', '18:00:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2026', 'R4', 'CONFIRMED', 'Ponte Preta', false, false, 'Ponte Preta', 'Vila Nova', 0, 1, 1, 0, '0–1', 'WIN', 'Estádio Moisés Lucarelli', 'MATCH_SPECIFIC', 'vn_venue_moises_lucarelli', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2026-04-11 18:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_cbf_833638', 2026, '2026-04-15', '21:30:00', 'FINISHED', 'Copa Centro-Oeste / Copa Verde', 'COPA_CENTRO_OESTE', 'Copa Verde 2026 — Copa Centro-Oeste', 'R4', 'CONFIRMED', 'Capital-DF', true, false, 'Vila Nova', 'Capital-DF', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-04-15 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF', '833638', 'https://www.cbf.com.br/futebol-brasileiro/jogos/copa-verde/masculino/2026/vila-nova-x-capital/833638', 'HIGH', null),
  ('vn_official_serie_b_2026_r05', 2026, '2026-04-18', '18:30:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2026', 'R5', 'CONFIRMED', 'Operário Ferroviário', true, false, 'Vila Nova', 'Operário Ferroviário', 2, 1, 2, 1, '2–1', 'WIN', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2026-04-18 18:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_official_serie_b_2026_r06', 2026, '2026-04-26', '18:00:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2026', 'R6', 'CONFIRMED', 'Ceará', false, false, 'Ceará', 'Vila Nova', 3, 3, 3, 3, '3–3', 'DRAW', 'Estádio Governador Plácido Castelo', 'MATCH_SPECIFIC', 'vn_venue_castelao', 'domingo', 'WEEKEND', 'NIGHT', (timestamp '2026-04-26 18:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_cbf_833645', 2026, '2026-04-29', '19:00:00', 'FINISHED', 'Copa Centro-Oeste / Copa Verde', 'COPA_CENTRO_OESTE', 'Copa Verde 2026 — Copa Centro-Oeste', 'R5', 'CONFIRMED', 'Araguaína', false, false, 'Araguaína', 'Vila Nova', 1, 2, 2, 1, '1–2', 'WIN', 'Estádio Leôncio de Souza Miranda', 'MATCH_SPECIFIC', 'vn_venue_mirandao', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-04-29 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF', '833645', 'https://www.cbf.com.br/futebol-brasileiro/jogos/copa-verde/profissional/2026/araguaina-futebol-e-regatas-x-vila-nova/833645', 'HIGH', null),
  ('vn_official_serie_b_2026_r07', 2026, '2026-05-04', '19:00:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2026', 'R7', 'CONFIRMED', 'Athletic', true, false, 'Vila Nova', 'Athletic', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'segunda-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-05-04 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_official_serie_b_2026_r08', 2026, '2026-05-09', '16:00:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2026', 'R8', 'CONFIRMED', 'Goiás', false, false, 'Goiás', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', 'Estádio Hailé Pinheiro', 'MATCH_SPECIFIC', 'vn_venue_serrinha', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2026-05-09 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_cbf_834357', 2026, '2026-05-13', '19:00:00', 'FINISHED', 'Copa Centro-Oeste / Copa Verde', 'COPA_CENTRO_OESTE', 'Copa Verde 2026 — Copa Centro-Oeste', 'Quartas de final', 'CONFIRMED', 'Anápolis', true, false, 'Vila Nova', 'Anápolis', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-05-13 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF', '834357', 'https://www.cbf.com.br/futebol-brasileiro/jogos/copa-verde/masculino/2026/vila-nova-x-anapolis/834357', 'HIGH', 'Disputa de pênaltis: Vila Nova 3–4 Anápolis.'),
  ('vn_official_serie_b_2026_r09', 2026, '2026-05-17', '18:00:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2026', 'R9', 'CONFIRMED', 'Avaí', true, false, 'Vila Nova', 'Avaí', 2, 0, 2, 0, '2–0', 'WIN', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'domingo', 'WEEKEND', 'NIGHT', (timestamp '2026-05-17 18:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_official_serie_b_2026_r10', 2026, '2026-05-24', '18:30:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2026', 'R10', 'CONFIRMED', 'América-MG', false, false, 'América-MG', 'Vila Nova', 1, 2, 2, 1, '1–2', 'WIN', 'Estádio Raimundo Sampaio', 'MATCH_SPECIFIC', 'vn_venue_independ_ncia', 'domingo', 'WEEKEND', 'NIGHT', (timestamp '2026-05-24 18:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_official_serie_b_2026_r11', 2026, '2026-05-31', '11:00:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2026', 'R11', 'CONFIRMED', 'Londrina', false, false, 'Londrina', 'Vila Nova', 0, 1, 1, 0, '0–1', 'WIN', 'Estádio Vitorino Gonçalves Dias', 'MATCH_SPECIFIC', 'vn_venue_vgd', 'domingo', 'WEEKEND', 'MORNING', (timestamp '2026-05-31 11:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_official_serie_b_2026_r12', 2026, '2026-06-08', '20:00:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2026', 'R12', 'CONFIRMED', 'Botafogo-SP', true, false, 'Vila Nova', 'Botafogo-SP', 1, 0, 1, 0, '1–0', 'WIN', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'segunda-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-06-08 20:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_official_serie_b_2026_r13', 2026, '2026-06-14', '17:00:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2026', 'R13', 'CONFIRMED', 'Cuiabá', false, false, 'Cuiabá', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', 'Arena Pantanal', 'MATCH_SPECIFIC', 'vn_venue_arena_pantanal', 'domingo', 'WEEKEND', 'AFTERNOON', (timestamp '2026-06-14 17:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_official_serie_b_2026_r14', 2026, '2026-06-20', '19:00:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2026', 'R14', 'CONFIRMED', 'Náutico', true, false, 'Vila Nova', 'Náutico', 4, 3, 4, 3, '4–3', 'WIN', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2026-06-20 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_official_serie_b_2026_r15', 2026, '2026-06-26', '19:00:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2026', 'R15', 'CONFIRMED', 'Novorizontino', false, false, 'Novorizontino', 'Vila Nova', 2, 1, 1, 2, '2–1', 'LOSS', 'Estádio Jorge Ismael de Biasi', 'MATCH_SPECIFIC', 'vn_venue_jorjao', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-06-26 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_official_serie_b_2026_r16', 2026, '2026-07-06', '19:00:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2026', 'R16', 'CONFIRMED', 'São Bernardo', true, false, 'Vila Nova', 'São Bernardo', 2, 1, 2, 1, '2–1', 'WIN', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'segunda-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-07-06 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_official_serie_b_2026_r17', 2026, '2026-07-10', '19:00:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2026', 'R17', 'CONFIRMED', 'Juventude', false, false, 'Juventude', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', 'Estádio Alfredo Jaconi', 'MATCH_SPECIFIC', 'vn_venue_alfredo_jaconi', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-07-10 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_official_serie_b_2026_r18', 2026, '2026-07-18', '16:00:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2026', 'R18', 'CONFIRMED', 'Criciúma', false, false, 'Criciúma', 'Vila Nova', 2, 0, 0, 2, '2–0', 'LOSS', 'Estádio Heriberto Hülse', 'MATCH_SPECIFIC', 'vn_venue_heriberto_h_lse', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2026-07-18 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_official_serie_b_2026_r19', 2026, '2026-07-21', '21:35:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2026', 'R19', 'CONFIRMED', 'Fortaleza', true, false, 'Vila Nova', 'Fortaleza', 2, 1, 2, 1, '2–1', 'WIN', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-07-21 21:35:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_official_serie_b_2026_r20', 2026, '2026-07-27', '19:30:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2026', 'R20', 'CONFIRMED', 'CRB', false, false, 'CRB', 'Vila Nova', 2, 0, 0, 2, '2–0', 'LOSS', 'Estádio Rei Pelé', 'MATCH_SPECIFIC', 'vn_venue_rei_pele', 'segunda-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-07-27 19:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_official_serie_b_2026_r21', 2026, '2026-08-08', '16:00:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2026', 'R21', 'CONFIRMED', 'Sport', true, false, 'Vila Nova', 'Sport', 0, 1, 0, 1, '0–1', 'LOSS', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2026-08-08 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_official_serie_b_2026_r22', 2026, '2026-08-15', '16:00:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2026', 'R22', 'CONFIRMED', 'Atlético-GO', false, false, 'Atlético-GO', 'Vila Nova', 0, 2, 2, 0, '0–2', 'WIN', 'Estádio Antônio Accioly', 'MATCH_SPECIFIC', 'vn_venue_ant_nio_accioly', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2026-08-15 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_official_serie_b_2026_r23', 2026, '2026-08-18', '20:30:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2026', 'R23', 'CONFIRMED', 'Ponte Preta', true, false, 'Vila Nova', 'Ponte Preta', 6, 0, 6, 0, '6–0', 'WIN', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-08-18 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_official_serie_b_2026_r24', 2026, '2026-08-23', '18:00:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2026', 'R24', 'CONFIRMED', 'Operário Ferroviário', false, false, 'Operário Ferroviário', 'Vila Nova', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Germano Krüger', 'MATCH_SPECIFIC', 'vn_venue_germano_kr_ger', 'domingo', 'WEEKEND', 'NIGHT', (timestamp '2026-08-23 18:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_official_serie_b_2026_r25', 2026, '2026-08-30', '18:30:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2026', 'R25', 'CONFIRMED', 'Ceará', true, false, 'Vila Nova', 'Ceará', 2, 0, 2, 0, '2–0', 'WIN', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'domingo', 'WEEKEND', 'NIGHT', (timestamp '2026-08-30 18:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_official_serie_b_2026_r26', 2026, '2026-09-04', '20:30:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2026', 'R26', 'CONFIRMED', 'Athletic', false, false, 'Athletic', 'Vila Nova', 5, 0, 0, 5, '5–0', 'LOSS', 'Arena Sicredi', 'MATCH_SPECIFIC', 'vn_venue_arena_sicredi', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-09-04 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_official_serie_b_2026_r27', 2026, '2026-09-10', '19:30:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2026', 'R27', 'CONFIRMED', 'Goiás', true, false, 'Vila Nova', 'Goiás', 2, 0, 2, 0, '2–0', 'WIN', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'quinta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-09-10 19:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_official_serie_b_2026_r28', 2026, '2026-09-14', '21:30:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2026', 'R28', 'CONFIRMED', 'Avaí', false, false, 'Avaí', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Aderbal Ramos da Silva', 'MATCH_SPECIFIC', 'vn_venue_ressacada', 'segunda-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-09-14 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_official_serie_b_2026_r29', 2026, '2026-09-18', '19:30:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2026', 'R29', 'CONFIRMED', 'América-MG', true, false, 'Vila Nova', 'América-MG', 1, 0, 1, 0, '1–0', 'WIN', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-09-18 19:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_official_serie_b_2026_r30', 2026, '2026-09-25', '20:30:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2026', 'R30', 'CONFIRMED', 'Londrina', true, false, 'Vila Nova', 'Londrina', 2, 0, 2, 0, '2–0', 'WIN', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-09-25 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_official_serie_b_2026_r31', 2026, '2026-10-03', '18:30:00', 'SCHEDULED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2026', 'R31', 'CONFIRMED', 'Botafogo-SP', false, false, 'Botafogo-SP', 'Vila Nova', null, null, null, null, null, null, 'Arena Nicnet', 'MATCH_SPECIFIC', 'vn_venue_santa_cruz_ribeirao', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2026-10-03 18:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_official_serie_b_2026_r32', 2026, '2026-10-07', '20:30:00', 'SCHEDULED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2026', 'R32', 'CONFIRMED', 'Cuiabá', true, false, 'Vila Nova', 'Cuiabá', null, null, null, null, null, null, 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2026-10-07 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_official_serie_b_2026_r33', 2026, '2026-10-11', '17:30:00', 'SCHEDULED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2026', 'R33', 'CONFIRMED', 'Náutico', false, false, 'Náutico', 'Vila Nova', null, null, null, null, null, null, 'Estádio Eládio de Barros Carvalho', 'MATCH_SPECIFIC', 'vn_venue_aflitos', 'domingo', 'WEEKEND', 'AFTERNOON', (timestamp '2026-10-11 17:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null),
  ('vn_official_serie_b_2026_r34', 2026, '2026-10-18', '18:00:00', 'SCHEDULED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2026', 'R34', 'CONFIRMED', 'Novorizontino', true, false, 'Vila Nova', 'Novorizontino', null, null, null, null, null, null, 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'domingo', 'WEEKEND', 'NIGHT', (timestamp '2026-10-18 18:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Vila Nova FC', null, 'https://www.vilanovafc.com.br/tabelas-de-jogos', 'HIGH', null)
on conflict (id) do update set
    season = excluded.season,
    match_date = excluded.match_date,
    match_time = excluded.match_time,
    status = excluded.status,
    competition = excluded.competition,
    competition_code = excluded.competition_code,
    competition_edition = excluded.competition_edition,
    round = excluded.round,
    phase_status = excluded.phase_status,
    opponent = excluded.opponent,
    club_is_home = excluded.club_is_home,
    neutral_site = excluded.neutral_site,
    home_team = excluded.home_team,
    away_team = excluded.away_team,
    home_score = excluded.home_score,
    away_score = excluded.away_score,
    club_score = excluded.club_score,
    opponent_score = excluded.opponent_score,
    score_display = excluded.score_display,
    outcome = excluded.outcome,
    stadium = excluded.stadium,
    stadium_status = excluded.stadium_status,
    venue_id = excluded.venue_id,
    weekday = excluded.weekday,
    day_type = excluded.day_type,
    day_period = excluded.day_period,
    kickoff_at = excluded.kickoff_at,
    display_timezone = excluded.display_timezone,
    date_precision = excluded.date_precision,
    source_provider = excluded.source_provider,
    source_match_id = excluded.source_match_id,
    source_url = excluded.source_url,
    source_confidence = excluded.source_confidence,
    data_notes = excluded.data_notes,
    updated_at = now();

do $$
declare v_orphans int;
begin
  select count(*) into v_orphans from public.passport_matches
   where season = 2026 and stadium is not null and venue_id is null;
  if v_orphans > 0 then
    raise exception 'ha % partidas de 2026 com estadio sem venue_id -- rode vilanova_passport_venues_seed.sql antes', v_orphans;
  end if;
end $$;
