-- Passaporte do Vila Nova — temporada 2016. GERADO por
-- `node tooling/vilanova_passport/generate_passport_sql.mjs` a partir de
-- docs/vila_nova_data/passport/passport_2016.json — não edite à mão.
--
-- Rode no projeto Supabase do VILA NOVA — NUNCA no do Goiás nem no do Bragantino.
-- Ordem: vilanova_passport_infra.sql -> vilanova_passport_venues_seed.sql -> ESTE.
-- Idempotente (ON CONFLICT DO UPDATE): reexecutar atualiza, nunca duplica, e
-- não encosta em presença de usuário. 60 partidas.

do $$
begin
  if not exists (select 1 from public.clubs where slug = 'vilanova')
     or exists (select 1 from public.clubs where slug <> 'vilanova') then
    raise exception 'este nao e o projeto Supabase do Vila Nova -- PARE';
  end if;
end $$;

insert into public.passport_matches (
  id, season, match_date, match_time, status, competition, competition_code, competition_edition, round, phase_status, opponent, club_is_home, neutral_site, home_team, away_team, home_score, away_score, club_score, opponent_score, score_display, outcome, stadium, stadium_status, venue_id, weekday, day_type, day_period, kickoff_at, display_timezone, date_precision, source_provider, source_match_id, source_url, source_confidence, data_notes
) values
  ('vn_rsssf_go2016_r01', 2016, '2016-01-31', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2016', 'R1', 'CONFIRMED', 'Goiás', true, false, 'Vila Nova', 'Goiás', 0, 2, 0, 2, '0–2', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r01', 'https://www.rsssfbrasil.com/tablesfq/go2016.htm', 'HIGH', null),
  ('vn_rsssf_go2016_r02', 2016, '2016-02-03', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2016', 'R2', 'CONFIRMED', 'Anápolis', false, false, 'Anápolis', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Jonas Duarte', 'MATCH_SPECIFIC', 'vn_venue_jonas_duarte', 'quarta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r02', 'https://www.rsssfbrasil.com/tablesfq/go2016.htm', 'HIGH', null),
  ('vn_rsssf_go2016_r03', 2016, '2016-02-06', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2016', 'R3', 'CONFIRMED', 'Trindade', false, false, 'Trindade', 'Vila Nova', 0, 1, 1, 0, '0–1', 'WIN', 'Estádio Abrão Manoel da Costa', 'MATCH_SPECIFIC', 'vn_venue_abrao_manoel_da_costa', 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r03', 'https://www.rsssfbrasil.com/tablesfq/go2016.htm', 'HIGH', null),
  ('vn_rsssf_go2016_r04', 2016, '2016-02-11', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2016', 'R4', 'CONFIRMED', 'CRAC', true, false, 'Vila Nova', 'CRAC', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'quinta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r04', 'https://www.rsssfbrasil.com/tablesfq/go2016.htm', 'HIGH', null),
  ('vn_rsssf_go2016_r05', 2016, '2016-02-15', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2016', 'R5', 'CONFIRMED', 'Itumbiara', false, false, 'Itumbiara', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', null, 'UNKNOWN', null, 'segunda-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r05', 'https://www.rsssfbrasil.com/tablesfq/go2016.htm', 'HIGH', null),
  ('vn_rsssf_cv2016_p1i', 2016, '2016-02-18', '20:15:00', 'FINISHED', 'Copa Verde', 'COPA_VERDE', 'Copa Verde 2016', 'Preliminar - ida', 'CONFIRMED', 'Brasília-DF', false, false, 'Brasília-DF', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Nacional de Brasília Mané Garrincha', 'MATCH_SPECIFIC', 'vn_venue_nacional_de_brasilia_mane_garrincha', 'quinta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2016-02-18 20:15:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'RSSSF Brasil', 'p1i', 'https://www.rsssfbrasil.com/tablesfq/cv2016.htm', 'HIGH', null),
  ('vn_rsssf_go2016_r06', 2016, '2016-02-21', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2016', 'R6', 'CONFIRMED', 'Trindade', true, false, 'Vila Nova', 'Trindade', 1, 0, 1, 0, '1–0', 'WIN', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r06', 'https://www.rsssfbrasil.com/tablesfq/go2016.htm', 'HIGH', null),
  ('vn_rsssf_go2016_r07', 2016, '2016-02-24', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2016', 'R7', 'CONFIRMED', 'Anápolis', true, false, 'Vila Nova', 'Anápolis', 1, 0, 1, 0, '1–0', 'WIN', null, 'UNKNOWN', null, 'quarta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r07', 'https://www.rsssfbrasil.com/tablesfq/go2016.htm', 'HIGH', null),
  ('vn_rsssf_go2016_r08', 2016, '2016-02-28', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2016', 'R8', 'CONFIRMED', 'Goiás', false, false, 'Goiás', 'Vila Nova', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r08', 'https://www.rsssfbrasil.com/tablesfq/go2016.htm', 'HIGH', null),
  ('vn_rsssf_cv2016_p1v', 2016, '2016-03-03', '21:30:00', 'FINISHED', 'Copa Verde', 'COPA_VERDE', 'Copa Verde 2016', 'Preliminar - volta', 'CONFIRMED', 'Brasília-DF', true, false, 'Vila Nova', 'Brasília-DF', 1, 0, 1, 0, '1–0', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'quinta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2016-03-03 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'RSSSF Brasil', 'p1v', 'https://www.rsssfbrasil.com/tablesfq/cv2016.htm', 'HIGH', null),
  ('vn_rsssf_go2016_r09', 2016, '2016-03-06', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2016', 'R9', 'CONFIRMED', 'CRAC', false, false, 'CRAC', 'Vila Nova', 3, 1, 1, 3, '3–1', 'LOSS', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r09', 'https://www.rsssfbrasil.com/tablesfq/go2016.htm', 'HIGH', null),
  ('vn_rsssf_cv2016_r1i', 2016, '2016-03-10', '21:30:00', 'FINISHED', 'Copa Verde', 'COPA_VERDE', 'Copa Verde 2016', '1ª fase - ida', 'CONFIRMED', 'Luverdense', true, false, 'Vila Nova', 'Luverdense', 4, 0, 4, 0, '4–0', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'quinta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2016-03-10 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'RSSSF Brasil', 'r1i', 'https://www.rsssfbrasil.com/tablesfq/cv2016.htm', 'HIGH', null),
  ('vn_rsssf_go2016_r10', 2016, '2016-03-13', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2016', 'R10', 'CONFIRMED', 'Itumbiara', true, false, 'Vila Nova', 'Itumbiara', 0, 2, 0, 2, '0–2', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r10', 'https://www.rsssfbrasil.com/tablesfq/go2016.htm', 'HIGH', null),
  ('vn_rsssf_cv2016_r1v', 2016, '2016-03-17', '21:30:00', 'FINISHED', 'Copa Verde', 'COPA_VERDE', 'Copa Verde 2016', '1ª fase - volta', 'CONFIRMED', 'Luverdense', false, false, 'Luverdense', 'Vila Nova', 0, 1, 1, 0, '0–1', 'WIN', 'Estádio Passo das Emas', 'MATCH_SPECIFIC', 'vn_venue_passo_das_emas', 'quinta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2016-03-17 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'RSSSF Brasil', 'r1v', 'https://www.rsssfbrasil.com/tablesfq/cv2016.htm', 'HIGH', null),
  ('vn_rsssf_go2016_r11', 2016, '2016-03-21', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2016', 'R11', 'CONFIRMED', 'Goianésia', true, false, 'Vila Nova', 'Goianésia', 0, 0, 0, 0, '0–0', 'DRAW', null, 'UNKNOWN', null, 'segunda-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r11', 'https://www.rsssfbrasil.com/tablesfq/go2016.htm', 'HIGH', null),
  ('vn_rsssf_cv2016_qfi', 2016, '2016-03-24', '19:00:00', 'FINISHED', 'Copa Verde', 'COPA_VERDE', 'Copa Verde 2016', 'Quartas - ida', 'CONFIRMED', 'Gama', true, false, 'Vila Nova', 'Gama', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'quinta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2016-03-24 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'RSSSF Brasil', 'qfi', 'https://www.rsssfbrasil.com/tablesfq/cv2016.htm', 'HIGH', null),
  ('vn_rsssf_go2016_r12', 2016, '2016-03-27', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2016', 'R12', 'CONFIRMED', 'Atlético-GO', false, false, 'Atlético-GO', 'Vila Nova', 0, 1, 1, 0, '0–1', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r12', 'https://www.rsssfbrasil.com/tablesfq/go2016.htm', 'HIGH', null),
  ('vn_rsssf_go2016_r13', 2016, '2016-03-30', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2016', 'R13', 'CONFIRMED', 'Anapolina', false, false, 'Anapolina', 'Vila Nova', 0, 2, 2, 0, '0–2', 'WIN', 'Estádio Jonas Duarte', 'MATCH_SPECIFIC', 'vn_venue_jonas_duarte', 'quarta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r13', 'https://www.rsssfbrasil.com/tablesfq/go2016.htm', 'HIGH', null),
  ('vn_rsssf_go2016_r14', 2016, '2016-04-03', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2016', 'R14', 'CONFIRMED', 'Aparecidense', true, false, 'Vila Nova', 'Aparecidense', 1, 1, 1, 1, '1–1', 'DRAW', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r14', 'https://www.rsssfbrasil.com/tablesfq/go2016.htm', 'HIGH', null),
  ('vn_rsssf_cv2016_qfv', 2016, '2016-04-07', '19:00:00', 'FINISHED', 'Copa Verde', 'COPA_VERDE', 'Copa Verde 2016', 'Quartas - volta', 'CONFIRMED', 'Gama', false, false, 'Gama', 'Vila Nova', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Valmir Campelo Bezerra', 'MATCH_SPECIFIC', 'vn_venue_valmir_campelo_bezerra', 'quinta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2016-04-07 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'RSSSF Brasil', 'qfv', 'https://www.rsssfbrasil.com/tablesfq/cv2016.htm', 'HIGH', 'Disputa de pênaltis: Gama 4–3 Vila Nova.'),
  ('vn_rsssf_go2016_sf1', 2016, '2016-04-17', '16:00:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2016', 'Semifinal - ida', 'CONFIRMED', 'Goiás', true, false, 'Vila Nova', 'Goiás', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'domingo', 'WEEKEND', 'AFTERNOON', (timestamp '2016-04-17 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'RSSSF Brasil', 'sf1', 'https://www.rsssfbrasil.com/tablesfq/go2016.htm', 'HIGH', 'Data resolvida como 17/04/2016 por fonte local match-specific; RSSSF lista 18/04.'),
  ('vn_rsssf_go2016_sf2', 2016, '2016-04-24', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2016', 'Semifinal - volta', 'CONFIRMED', 'Goiás', false, false, 'Goiás', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'sf2', 'https://www.rsssfbrasil.com/tablesfq/go2016.htm', 'HIGH', null),
  ('vn_cbf_sb2016_005', 2016, '2016-05-13', '19:15:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2016', 'R01', 'CONFIRMED', 'Bragantino', true, false, 'Vila Nova', 'Bragantino', 3, 1, 3, 1, '3–1', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2016-05-13 19:15:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '005', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2016_games.json', 'HIGH', null),
  ('vn_cbf_sb2016_011', 2016, '2016-05-17', '21:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2016', 'R02', 'CONFIRMED', 'Náutico', false, false, 'Náutico', 'Vila Nova', 3, 2, 2, 3, '3–2', 'LOSS', 'Arena de Pernambuco', 'MATCH_SPECIFIC', 'vn_venue_arena_pernambuco', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2016-05-17 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '011', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2016_games.json', 'HIGH', null),
  ('vn_cbf_sb2016_025', 2016, '2016-05-24', '21:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2016', 'R03', 'CONFIRMED', 'Vasco da Gama', true, false, 'Vila Nova', 'Vasco da Gama', 0, 2, 0, 2, '0–2', 'LOSS', 'Estádio Nacional de Brasília Mané Garrincha', 'MATCH_SPECIFIC', 'vn_venue_nacional_de_brasilia_mane_garrincha', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2016-05-24 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '025', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2016_games.json', 'HIGH', null),
  ('vn_cbf_sb2016_037', 2016, '2016-05-28', '16:00:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2016', 'R04', 'CONFIRMED', 'Atlético-GO', false, false, 'Atlético-GO', 'Vila Nova', 2, 1, 1, 2, '2–1', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2016-05-28 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '037', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2016_games.json', 'HIGH', null),
  ('vn_cbf_sb2016_045', 2016, '2016-05-31', '19:15:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2016', 'R05', 'CONFIRMED', 'CRB', true, false, 'Vila Nova', 'CRB', 1, 2, 1, 2, '1–2', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2016-05-31 19:15:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '045', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2016_games.json', 'HIGH', null),
  ('vn_cbf_sb2016_055', 2016, '2016-06-03', '20:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2016', 'R06', 'CONFIRMED', 'Paraná', true, false, 'Vila Nova', 'Paraná', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2016-06-03 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '055', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2016_games.json', 'HIGH', null),
  ('vn_cbf_sb2016_066', 2016, '2016-06-07', '21:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2016', 'R07', 'CONFIRMED', 'Luverdense', false, false, 'Luverdense', 'Vila Nova', 0, 2, 2, 0, '0–2', 'WIN', 'Estádio Passo das Emas', 'MATCH_SPECIFIC', 'vn_venue_passo_das_emas', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2016-06-07 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '066', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2016_games.json', 'HIGH', null),
  ('vn_cbf_sb2016_079', 2016, '2016-06-11', '16:00:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2016', 'R08', 'CONFIRMED', 'Londrina', false, false, 'Londrina', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', 'Estádio do Café', 'MATCH_SPECIFIC', 'vn_venue_estadio_cafe', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2016-06-11 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '079', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2016_games.json', 'HIGH', null),
  ('vn_cbf_sb2016_085', 2016, '2016-06-14', '19:15:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2016', 'R09', 'CONFIRMED', 'Sampaio Corrêa', true, false, 'Vila Nova', 'Sampaio Corrêa', 1, 0, 1, 0, '1–0', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2016-06-14 19:15:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '085', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2016_games.json', 'HIGH', null),
  ('vn_cbf_sb2016_094', 2016, '2016-06-18', '21:00:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2016', 'R10', 'CONFIRMED', 'Oeste', false, false, 'Oeste', 'Vila Nova', 1, 3, 3, 1, '1–3', 'WIN', 'Arena Barueri', 'MATCH_SPECIFIC', 'vn_venue_arena_barueri', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2016-06-18 21:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '094', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2016_games.json', 'HIGH', null),
  ('vn_cbf_sb2016_105', 2016, '2016-06-21', '21:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2016', 'R11', 'CONFIRMED', 'Criciúma', true, false, 'Vila Nova', 'Criciúma', 2, 3, 2, 3, '2–3', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2016-06-21 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '105', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2016_games.json', 'HIGH', null),
  ('vn_cbf_sb2016_115', 2016, '2016-06-25', '16:00:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2016', 'R12', 'CONFIRMED', 'Goiás', true, false, 'Vila Nova', 'Goiás', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2016-06-25 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '115', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2016_games.json', 'HIGH', null),
  ('vn_cbf_sb2016_130', 2016, '2016-06-28', '19:15:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2016', 'R13', 'CONFIRMED', 'Avaí', false, false, 'Avaí', 'Vila Nova', 3, 1, 1, 3, '3–1', 'LOSS', 'Estádio Aderbal Ramos da Silva', 'MATCH_SPECIFIC', 'vn_venue_ressacada', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2016-06-28 19:15:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '130', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2016_games.json', 'HIGH', null),
  ('vn_cbf_sb2016_135', 2016, '2016-07-01', '20:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2016', 'R14', 'CONFIRMED', 'Tupi', true, false, 'Vila Nova', 'Tupi', 1, 0, 1, 0, '1–0', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2016-07-01 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '135', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2016_games.json', 'HIGH', null),
  ('vn_cbf_sb2016_142', 2016, '2016-07-05', '21:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2016', 'R15', 'CONFIRMED', 'Bahia', false, false, 'Bahia', 'Vila Nova', 0, 1, 1, 0, '0–1', 'WIN', 'Estádio Octávio Mangabeira', 'MATCH_SPECIFIC', 'vn_venue_octavio_mangabeira', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2016-07-05 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '142', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2016_games.json', 'HIGH', null),
  ('vn_cbf_sb2016_158', 2016, '2016-07-16', '16:00:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2016', 'R16', 'CONFIRMED', 'Brasil de Pelotas', false, false, 'Brasil de Pelotas', 'Vila Nova', 2, 2, 2, 2, '2–2', 'DRAW', 'Estádio Bento Mendes de Freitas', 'MATCH_SPECIFIC', 'vn_venue_bento_mendes_freitas', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2016-07-16 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '158', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2016_games.json', 'HIGH', null),
  ('vn_cbf_sb2016_165', 2016, '2016-07-23', '16:00:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2016', 'R17', 'CONFIRMED', 'Ceará', true, false, 'Vila Nova', 'Ceará', 3, 4, 3, 4, '3–4', 'LOSS', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2016-07-23 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '165', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2016_games.json', 'HIGH', null),
  ('vn_cbf_sb2016_173', 2016, '2016-07-30', '18:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2016', 'R18', 'CONFIRMED', 'Paysandu', false, false, 'Paysandu', 'Vila Nova', 2, 2, 2, 2, '2–2', 'DRAW', 'Curuzu', 'MATCH_SPECIFIC', 'vn_venue_curuzu', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2016-07-30 18:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '173', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2016_games.json', 'HIGH', null),
  ('vn_cbf_sb2016_185', 2016, '2016-08-02', '19:15:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2016', 'R19', 'CONFIRMED', 'Joinville', true, false, 'Vila Nova', 'Joinville', 2, 1, 2, 1, '2–1', 'WIN', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2016-08-02 19:15:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '185', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2016_games.json', 'HIGH', null),
  ('vn_cbf_sb2016_194', 2016, '2016-08-19', '20:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2016', 'R20', 'CONFIRMED', 'Bragantino', false, false, 'Bragantino', 'Vila Nova', 2, 2, 2, 2, '2–2', 'DRAW', 'Estádio Nabi Abi Chedid', 'MATCH_SPECIFIC', 'vn_venue_nabi_abi_chedid', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2016-08-19 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '194', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2016_games.json', 'HIGH', null),
  ('vn_cbf_sb2016_205', 2016, '2016-08-27', '16:20:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2016', 'R21', 'CONFIRMED', 'Náutico', true, false, 'Vila Nova', 'Náutico', 0, 2, 0, 2, '0–2', 'LOSS', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2016-08-27 16:20:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '205', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2016_games.json', 'HIGH', null),
  ('vn_cbf_sb2016_216', 2016, '2016-08-30', '20:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2016', 'R22', 'CONFIRMED', 'Vasco da Gama', false, false, 'Vasco da Gama', 'Vila Nova', 1, 2, 2, 1, '1–2', 'WIN', 'Estádio São Januário', 'MATCH_SPECIFIC', 'vn_venue_sao_januario', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2016-08-30 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '216', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2016_games.json', 'HIGH', null),
  ('vn_cbf_sb2016_225', 2016, '2016-09-03', '16:00:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2016', 'R23', 'CONFIRMED', 'Atlético-GO', true, false, 'Vila Nova', 'Atlético-GO', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2016-09-03 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '225', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2016_games.json', 'HIGH', null),
  ('vn_cbf_sb2016_232', 2016, '2016-09-10', '21:00:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2016', 'R24', 'CONFIRMED', 'CRB', false, false, 'CRB', 'Vila Nova', 1, 2, 2, 1, '1–2', 'WIN', 'Estádio Rei Pelé', 'MATCH_SPECIFIC', 'vn_venue_rei_pele', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2016-09-10 21:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '232', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2016_games.json', 'HIGH', null),
  ('vn_cbf_sb2016_249', 2016, '2016-09-13', '19:15:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2016', 'R25', 'CONFIRMED', 'Paraná', false, false, 'Paraná', 'Vila Nova', 1, 2, 2, 1, '1–2', 'WIN', 'Estádio Durival Britto e Silva', 'MATCH_SPECIFIC', 'vn_venue_durival_britto', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2016-09-13 19:15:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '249', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2016_games.json', 'HIGH', null),
  ('vn_cbf_sb2016_255', 2016, '2016-09-16', '20:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2016', 'R26', 'CONFIRMED', 'Luverdense', true, false, 'Vila Nova', 'Luverdense', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2016-09-16 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '255', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2016_games.json', 'HIGH', null),
  ('vn_cbf_sb2016_265', 2016, '2016-09-24', '16:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2016', 'R27', 'CONFIRMED', 'Londrina', true, false, 'Vila Nova', 'Londrina', 1, 2, 1, 2, '1–2', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2016-09-24 16:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '265', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2016_games.json', 'HIGH', null),
  ('vn_cbf_sb2016_285', 2016, '2016-10-04', '20:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2016', 'R29', 'CONFIRMED', 'Oeste', true, false, 'Vila Nova', 'Oeste', 1, 0, 1, 0, '1–0', 'WIN', 'Estádio Olímpico Pedro Ludovico Teixeira', 'MATCH_SPECIFIC', 'vn_venue_olimpico', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2016-10-04 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '285', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2016_games.json', 'HIGH', null),
  ('vn_cbf_sb2016_300', 2016, '2016-10-07', '20:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2016', 'R30', 'CONFIRMED', 'Criciúma', false, false, 'Criciúma', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', 'Estádio Heriberto Hülse', 'MATCH_SPECIFIC', 'vn_venue_heriberto_h_lse', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2016-10-07 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '300', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2016_games.json', 'HIGH', null),
  ('vn_cbf_sb2016_305', 2016, '2016-10-15', '16:00:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2016', 'R31', 'CONFIRMED', 'Goiás', false, false, 'Goiás', 'Vila Nova', 1, 2, 2, 1, '1–2', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2016-10-15 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '305', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2016_games.json', 'HIGH', null),
  ('vn_cbf_sb2016_315', 2016, '2016-10-18', '19:15:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2016', 'R32', 'CONFIRMED', 'Avaí', true, false, 'Vila Nova', 'Avaí', 1, 2, 1, 2, '1–2', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2016-10-18 19:15:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '315', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2016_games.json', 'HIGH', null),
  ('vn_cbf_sb2016_273', 2016, '2016-10-25', '20:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2016', 'R28', 'CONFIRMED', 'Sampaio Corrêa', false, false, 'Sampaio Corrêa', 'Vila Nova', 0, 3, 3, 0, '0–3', 'WIN', 'Estádio Governador João Castelo', 'MATCH_SPECIFIC', 'vn_venue_castelao_sao_luis', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2016-10-25 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '273', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2016_games.json', 'HIGH', null),
  ('vn_cbf_sb2016_327', 2016, '2016-10-29', '17:00:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2016', 'R33', 'CONFIRMED', 'Tupi', false, false, 'Tupi', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', 'Estádio Municipal Radialista Mário Helênio', 'MATCH_SPECIFIC', 'vn_venue_municipal_radialista_mario_helenio', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2016-10-29 17:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '327', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2016_games.json', 'HIGH', null),
  ('vn_cbf_sb2016_335', 2016, '2016-11-04', '21:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2016', 'R34', 'CONFIRMED', 'Bahia', true, false, 'Vila Nova', 'Bahia', 0, 1, 0, 1, '0–1', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2016-11-04 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '335', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2016_games.json', 'HIGH', null),
  ('vn_cbf_sb2016_345', 2016, '2016-11-08', '20:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2016', 'R35', 'CONFIRMED', 'Brasil de Pelotas', true, false, 'Vila Nova', 'Brasil de Pelotas', 3, 1, 3, 1, '3–1', 'WIN', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2016-11-08 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '345', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2016_games.json', 'HIGH', null),
  ('vn_cbf_sb2016_351', 2016, '2016-11-12', '17:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2016', 'R36', 'CONFIRMED', 'Ceará', false, false, 'Ceará', 'Vila Nova', 2, 3, 3, 2, '2–3', 'WIN', 'Estádio Governador Plácido Castelo', 'MATCH_SPECIFIC', 'vn_venue_castelao', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2016-11-12 17:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '351', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2016_games.json', 'HIGH', null),
  ('vn_cbf_sb2016_365', 2016, '2016-11-19', '17:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2016', 'R37', 'CONFIRMED', 'Paysandu', true, false, 'Vila Nova', 'Paysandu', 2, 2, 2, 2, '2–2', 'DRAW', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2016-11-19 17:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '365', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2016_games.json', 'HIGH', null),
  ('vn_cbf_sb2016_378', 2016, '2016-11-26', '17:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2016', 'R38', 'CONFIRMED', 'Joinville', false, false, 'Joinville', 'Vila Nova', 4, 2, 2, 4, '4–2', 'LOSS', 'Arena Joinville', 'MATCH_SPECIFIC', 'vn_venue_joinville', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2016-11-26 17:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '378', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2016_games.json', 'HIGH', null)
on conflict (id) do update set
    season = excluded.season,
    match_date = excluded.match_date,
    match_time = excluded.match_time,
    status = excluded.status,
    competition = excluded.competition,
    competition_code = excluded.competition_code,
    competition_edition = excluded.competition_edition,
    round = excluded.round,
    phase_status = excluded.phase_status,
    opponent = excluded.opponent,
    club_is_home = excluded.club_is_home,
    neutral_site = excluded.neutral_site,
    home_team = excluded.home_team,
    away_team = excluded.away_team,
    home_score = excluded.home_score,
    away_score = excluded.away_score,
    club_score = excluded.club_score,
    opponent_score = excluded.opponent_score,
    score_display = excluded.score_display,
    outcome = excluded.outcome,
    stadium = excluded.stadium,
    stadium_status = excluded.stadium_status,
    venue_id = excluded.venue_id,
    weekday = excluded.weekday,
    day_type = excluded.day_type,
    day_period = excluded.day_period,
    kickoff_at = excluded.kickoff_at,
    display_timezone = excluded.display_timezone,
    date_precision = excluded.date_precision,
    source_provider = excluded.source_provider,
    source_match_id = excluded.source_match_id,
    source_url = excluded.source_url,
    source_confidence = excluded.source_confidence,
    data_notes = excluded.data_notes,
    updated_at = now();

do $$
declare v_orphans int;
begin
  select count(*) into v_orphans from public.passport_matches
   where season = 2016 and stadium is not null and venue_id is null;
  if v_orphans > 0 then
    raise exception 'ha % partidas de 2016 com estadio sem venue_id -- rode vilanova_passport_venues_seed.sql antes', v_orphans;
  end if;
end $$;
