-- Passaporte do Vila Nova — temporada 2021. GERADO por
-- `node tooling/vilanova_passport/generate_passport_sql.mjs` a partir de
-- docs/vila_nova_data/passport/passport_2021.json — não edite à mão.
--
-- Rode no projeto Supabase do VILA NOVA — NUNCA no do Goiás nem no do Bragantino.
-- Ordem: vilanova_passport_infra.sql -> vilanova_passport_venues_seed.sql -> ESTE.
-- Idempotente (ON CONFLICT DO UPDATE): reexecutar atualiza, nunca duplica, e
-- não encosta em presença de usuário. 78 partidas.

do $$
begin
  if not exists (select 1 from public.clubs where slug = 'vilanova')
     or exists (select 1 from public.clubs where slug <> 'vilanova') then
    raise exception 'este nao e o projeto Supabase do Vila Nova -- PARE';
  end if;
end $$;

insert into public.passport_matches (
  id, season, match_date, match_time, status, competition, competition_code, competition_edition, round, phase_status, opponent, club_is_home, neutral_site, home_team, away_team, home_score, away_score, club_score, opponent_score, score_display, outcome, stadium, stadium_status, venue_id, weekday, day_type, day_period, kickoff_at, display_timezone, date_precision, source_provider, source_match_id, source_url, source_confidence, data_notes
) values
  ('vn_cbf_sc2020_jogo_194', 2021, '2021-01-02', '17:00:00', 'FINISHED', 'Campeonato Brasileiro Série C', 'BRASILEIRO_C', 'Série C 2020', 'Fase final 1', 'CONFIRMED', 'Brusque', true, false, 'Vila Nova', 'Brusque', 0, 3, 0, 3, '0–3', 'LOSS', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2021-01-02 17:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF', 'sc2020_jogo_194', 'https://www.cbf.com.br/futebol-brasileiro/times/campeonato-brasileiro/serie-c/2020/20079?tab=historico-de-partidas', 'HIGH', null),
  ('vn_cbf_sc2020_jogo_197', 2021, '2021-01-09', '17:00:00', 'FINISHED', 'Campeonato Brasileiro Série C', 'BRASILEIRO_C', 'Série C 2020', 'Fase final 2', 'CONFIRMED', 'Santa Cruz', true, false, 'Vila Nova', 'Santa Cruz', 2, 1, 2, 1, '2–1', 'WIN', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2021-01-09 17:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF', 'sc2020_jogo_197', 'https://www.cbf.com.br/futebol-brasileiro/times/campeonato-brasileiro/serie-c/2020/20079?tab=historico-de-partidas', 'HIGH', null),
  ('vn_cbf_sc2020_jogo_202', 2021, '2021-01-17', '18:00:00', 'FINISHED', 'Campeonato Brasileiro Série C', 'BRASILEIRO_C', 'Série C 2020', 'Fase final 3', 'CONFIRMED', 'Ituano', false, false, 'Ituano', 'Vila Nova', 0, 1, 1, 0, '0–1', 'WIN', 'Estádio Novelli Júnior', 'MATCH_SPECIFIC', 'vn_venue_novelli_junior', 'domingo', 'WEEKEND', 'NIGHT', (timestamp '2021-01-17 18:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF', 'sc2020_jogo_202', 'https://www.cbf.com.br/futebol-brasileiro/times/campeonato-brasileiro/serie-c/2020/20079?tab=historico-de-partidas', 'HIGH', null),
  ('vn_rsssf_brasil_go2020_carry_1', 2021, '2021-01-21', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2020', 'R11', 'CONFIRMED', 'CRAC', false, false, 'CRAC', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', null, 'UNKNOWN', null, 'quinta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'go2020_carry_1', 'https://www.rsssfbrasil.com/tablesfq/go2020.htm', 'HIGH', null),
  ('vn_cbf_sc2020_jogo_205', 2021, '2021-01-23', '17:00:00', 'FINISHED', 'Campeonato Brasileiro Série C', 'BRASILEIRO_C', 'Série C 2020', 'Fase final 4', 'CONFIRMED', 'Remo', true, false, 'Vila Nova', 'Remo', 5, 1, 5, 1, '5–1', 'WIN', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2021-01-23 17:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF', 'sc2020_jogo_205', 'https://www.cbf.com.br/futebol-brasileiro/times/campeonato-brasileiro/serie-c/2020/20079?tab=historico-de-partidas', 'HIGH', null),
  ('vn_rsssf_brasil_go2020_carry_2', 2021, '2021-01-28', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2020', 'R12', 'CONFIRMED', 'Goiânia', true, false, 'Vila Nova', 'Goiânia', 6, 0, 6, 0, '6–0', 'WIN', null, 'UNKNOWN', null, 'quinta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'go2020_carry_2', 'https://www.rsssfbrasil.com/tablesfq/go2020.htm', 'HIGH', null),
  ('vn_cbf_sc2020_jogo_206', 2021, '2021-01-30', '17:00:00', 'FINISHED', 'Campeonato Brasileiro Série C', 'BRASILEIRO_C', 'Série C 2020', 'Fase final 5', 'CONFIRMED', 'Remo', false, false, 'Remo', 'Vila Nova', 2, 3, 3, 2, '2–3', 'WIN', 'Estádio Mangueirão', 'MATCH_SPECIFIC', 'vn_venue_mangueirao', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2021-01-30 17:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF', 'sc2020_jogo_206', 'https://www.cbf.com.br/futebol-brasileiro/times/campeonato-brasileiro/serie-c/2020/20079?tab=historico-de-partidas', 'HIGH', null),
  ('vn_cbf_zerozero_cv2020_carry_1', 2021, '2021-02-02', null, 'FINISHED', 'Copa Verde', 'COPA_VERDE', 'Copa Verde 2020', 'Oitavas', 'CONFIRMED', 'Palmas', true, false, 'Vila Nova', 'Palmas', 3, 1, 3, 1, '3–1', 'WIN', null, 'UNKNOWN', null, 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'cv2020_carry_1', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2021&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_cv2020_carry_2', 2021, '2021-02-05', null, 'FINISHED', 'Copa Verde', 'COPA_VERDE', 'Copa Verde 2020', 'QF1', 'CONFIRMED', 'Cuiabá', false, false, 'Cuiabá', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', null, 'UNKNOWN', null, 'sexta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'cv2020_carry_2', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2021&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_cv2020_carry_3', 2021, '2021-02-08', '19:00:00', 'FINISHED', 'Copa Verde', 'COPA_VERDE', 'Copa Verde 2020', 'QF2', 'CONFIRMED', 'Cuiabá', true, false, 'Vila Nova', 'Cuiabá', 3, 0, 3, 0, '3–0', 'WIN', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'segunda-feira', 'WEEKDAY', 'NIGHT', (timestamp '2021-02-08 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF/Zerozero', 'cv2020_carry_3', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2021&grp=1', 'HIGH', null),
  ('vn_rsssf_brasil_go2020_carry_3', 2021, '2021-02-11', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2020', 'QF', 'CONFIRMED', 'Jaraguá', false, false, 'Jaraguá', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', null, 'UNKNOWN', null, 'quinta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'go2020_carry_3', 'https://www.rsssfbrasil.com/tablesfq/go2020.htm', 'HIGH', null),
  ('vn_cbf_zerozero_cv2020_carry_4', 2021, '2021-02-14', '16:00:00', 'FINISHED', 'Copa Verde', 'COPA_VERDE', 'Copa Verde 2020', 'SF1', 'CONFIRMED', 'Brasiliense', true, false, 'Vila Nova', 'Brasiliense', 0, 2, 0, 2, '0–2', 'LOSS', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'domingo', 'WEEKEND', 'AFTERNOON', (timestamp '2021-02-14 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF/Zerozero', 'cv2020_carry_4', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2021&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_cv2020_carry_5', 2021, '2021-02-18', '15:30:00', 'FINISHED', 'Copa Verde', 'COPA_VERDE', 'Copa Verde 2020', 'SF2', 'CONFIRMED', 'Brasiliense', false, false, 'Brasiliense', 'Vila Nova', 1, 3, 3, 1, '1–3', 'WIN', 'Estádio Elmo Serejo Farias', 'MATCH_SPECIFIC', 'vn_venue_elmo_serejo', 'quinta-feira', 'WEEKDAY', 'AFTERNOON', (timestamp '2021-02-18 15:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF/Zerozero', 'cv2020_carry_5', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2021&grp=1', 'HIGH', 'Vila Nova venceu 3–1 no tempo normal; Brasiliense avançou nos pênaltis por 5–3. outcome=WIN pelo tempo normal.'),
  ('vn_rsssf_brasil_go2021_01', 2021, '2021-02-28', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2021', 'R1', 'CONFIRMED', 'Jaraguá', true, false, 'Vila Nova', 'Jaraguá', 1, 0, 1, 0, '1–0', 'WIN', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'go2021_01', 'https://www.rsssfbrasil.com/tablesfq/go2021.htm', 'HIGH', null),
  ('vn_rsssf_brasil_go2021_02', 2021, '2021-03-04', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2021', 'R2', 'CONFIRMED', 'Aparecidense', false, false, 'Aparecidense', 'Vila Nova', 0, 0, 0, 0, '0–0', 'DRAW', null, 'UNKNOWN', null, 'quinta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'go2021_02', 'https://www.rsssfbrasil.com/tablesfq/go2021.htm', 'HIGH', null),
  ('vn_rsssf_brasil_go2021_03', 2021, '2021-03-07', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2021', 'R3', 'CONFIRMED', 'Goiás', false, false, 'Goiás', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'go2021_03', 'https://www.rsssfbrasil.com/tablesfq/go2021.htm', 'HIGH', null),
  ('vn_rsssf_brasil_go2021_04', 2021, '2021-03-13', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2021', 'R4', 'CONFIRMED', 'Iporá', true, false, 'Vila Nova', 'Iporá', 5, 0, 5, 0, '5–0', 'WIN', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'go2021_04', 'https://www.rsssfbrasil.com/tablesfq/go2021.htm', 'HIGH', null),
  ('vn_cbf_cdb2021_jogo_24', 2021, '2021-03-17', '17:00:00', 'FINISHED', 'Copa do Brasil', 'COPA_DO_BRASIL', 'Copa do Brasil 2021', '1ª fase', 'CONFIRMED', 'Atlético Alagoinhas', false, false, 'Atlético Alagoinhas', 'Vila Nova', 0, 3, 3, 0, '0–3', 'WIN', 'Estádio Antônio Carneiro', 'MATCH_SPECIFIC', 'vn_venue_antonio_carneiro', 'quarta-feira', 'WEEKDAY', 'AFTERNOON', (timestamp '2021-03-17 17:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF', 'cdb2021_jogo_24', 'https://www.cbf.com.br/futebol-brasileiro/times/copa-do-brasil/masculino/2021/20079?tab=historico-de-partidas', 'HIGH', null),
  ('vn_rsssf_brasil_go2021_05', 2021, '2021-04-01', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2021', 'R5', 'CONFIRMED', 'Goianésia', false, false, 'Goianésia', 'Vila Nova', 0, 1, 1, 0, '0–1', 'WIN', null, 'UNKNOWN', null, 'quinta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'go2021_05', 'https://www.rsssfbrasil.com/tablesfq/go2021.htm', 'HIGH', null),
  ('vn_rsssf_brasil_go2021_06', 2021, '2021-04-04', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2021', 'R6', 'CONFIRMED', 'Goianésia', true, false, 'Vila Nova', 'Goianésia', 0, 2, 0, 2, '0–2', 'LOSS', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'go2021_06', 'https://www.rsssfbrasil.com/tablesfq/go2021.htm', 'HIGH', null),
  ('vn_cbf_cdb2021_jogo_51', 2021, '2021-04-08', '21:30:00', 'FINISHED', 'Copa do Brasil', 'COPA_DO_BRASIL', 'Copa do Brasil 2021', '2ª fase', 'CONFIRMED', 'Juventude', true, false, 'Vila Nova', 'Juventude', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'quinta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2021-04-08 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF', 'cdb2021_jogo_51', 'https://www.cbf.com.br/futebol-brasileiro/times/copa-do-brasil/masculino/2021/20079?tab=historico-de-partidas', 'HIGH', '1–1 no tempo normal; Vila Nova venceu nos pênaltis por 4–3.'),
  ('vn_rsssf_brasil_go2021_07', 2021, '2021-04-11', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2021', 'R7', 'CONFIRMED', 'Goiás', true, false, 'Vila Nova', 'Goiás', 2, 1, 2, 1, '2–1', 'WIN', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'go2021_07', 'https://www.rsssfbrasil.com/tablesfq/go2021.htm', 'HIGH', null),
  ('vn_rsssf_brasil_go2021_08', 2021, '2021-04-14', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2021', 'R8', 'CONFIRMED', 'Iporá', false, false, 'Iporá', 'Vila Nova', 0, 0, 0, 0, '0–0', 'DRAW', null, 'UNKNOWN', null, 'quarta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'go2021_08', 'https://www.rsssfbrasil.com/tablesfq/go2021.htm', 'HIGH', null),
  ('vn_rsssf_brasil_go2021_09', 2021, '2021-04-18', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2021', 'R9', 'CONFIRMED', 'Aparecidense', true, false, 'Vila Nova', 'Aparecidense', 2, 1, 2, 1, '2–1', 'WIN', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'go2021_09', 'https://www.rsssfbrasil.com/tablesfq/go2021.htm', 'HIGH', null),
  ('vn_rsssf_brasil_go2021_10', 2021, '2021-04-22', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2021', 'R10', 'CONFIRMED', 'Jaraguá', false, false, 'Jaraguá', 'Vila Nova', 2, 0, 0, 2, '2–0', 'LOSS', null, 'UNKNOWN', null, 'quinta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'go2021_10', 'https://www.rsssfbrasil.com/tablesfq/go2021.htm', 'HIGH', null),
  ('vn_rsssf_brasil_go2021_11', 2021, '2021-04-25', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2021', 'QF1', 'CONFIRMED', 'Anápolis', false, false, 'Anápolis', 'Vila Nova', 0, 3, 3, 0, '0–3', 'WIN', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'go2021_11', 'https://www.rsssfbrasil.com/tablesfq/go2021.htm', 'HIGH', null),
  ('vn_rsssf_brasil_go2021_12', 2021, '2021-04-30', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2021', 'QF2', 'CONFIRMED', 'Anápolis', true, false, 'Vila Nova', 'Anápolis', 3, 1, 3, 1, '3–1', 'WIN', null, 'UNKNOWN', null, 'sexta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'go2021_12', 'https://www.rsssfbrasil.com/tablesfq/go2021.htm', 'HIGH', null),
  ('vn_rsssf_brasil_go2021_13', 2021, '2021-05-05', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2021', 'SF1', 'CONFIRMED', 'Aparecidense', true, false, 'Vila Nova', 'Aparecidense', 1, 1, 1, 1, '1–1', 'DRAW', null, 'UNKNOWN', null, 'quarta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'go2021_13', 'https://www.rsssfbrasil.com/tablesfq/go2021.htm', 'HIGH', null),
  ('vn_rsssf_brasil_go2021_14', 2021, '2021-05-08', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2021', 'SF2', 'CONFIRMED', 'Aparecidense', false, false, 'Aparecidense', 'Vila Nova', 0, 1, 1, 0, '0–1', 'WIN', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'go2021_14', 'https://www.rsssfbrasil.com/tablesfq/go2021.htm', 'HIGH', null),
  ('vn_rsssf_brasil_go2021_15', 2021, '2021-05-16', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2021', 'F1', 'CONFIRMED', 'Grêmio Anápolis', false, false, 'Grêmio Anápolis', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'go2021_15', 'https://www.rsssfbrasil.com/tablesfq/go2021.htm', 'HIGH', null),
  ('vn_rsssf_brasil_go2021_16', 2021, '2021-05-23', '16:00:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2021', 'F2', 'CONFIRMED', 'Grêmio Anápolis', true, false, 'Vila Nova', 'Grêmio Anápolis', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'domingo', 'WEEKEND', 'AFTERNOON', (timestamp '2021-05-23 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'RSSSF Brasil', 'go2021_16', 'https://www.rsssfbrasil.com/tablesfq/go2021.htm', 'HIGH', '1–1 no tempo normal; Grêmio Anápolis venceu nos pênaltis por 5–4.'),
  ('vn_cbf_zerozero_sb2021_r01', 2021, '2021-05-28', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2021', 'R1', 'CONFIRMED', 'Botafogo-RJ', true, false, 'Vila Nova', 'Botafogo-RJ', 1, 1, 1, 1, '1–1', 'DRAW', null, 'UNKNOWN', null, 'sexta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2021_r01', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2021&grp=1', 'HIGH', null),
  ('vn_cbf_cdb2021_jogo_62', 2021, '2021-06-01', '16:30:00', 'FINISHED', 'Copa do Brasil', 'COPA_DO_BRASIL', 'Copa do Brasil 2021', '3ª fase - ida', 'CONFIRMED', 'Bahia', true, false, 'Vila Nova', 'Bahia', 0, 1, 0, 1, '0–1', 'LOSS', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'terça-feira', 'WEEKDAY', 'AFTERNOON', (timestamp '2021-06-01 16:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF', 'cdb2021_jogo_62', 'https://www.cbf.com.br/futebol-brasileiro/times/copa-do-brasil/masculino/2021/20079?tab=historico-de-partidas', 'HIGH', null),
  ('vn_cbf_zerozero_sb2021_r02', 2021, '2021-06-06', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2021', 'R2', 'CONFIRMED', 'Avaí', false, false, 'Avaí', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2021_r02', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2021&grp=1', 'HIGH', null),
  ('vn_cbf_cdb2021_jogo_78', 2021, '2021-06-09', '19:00:00', 'FINISHED', 'Copa do Brasil', 'COPA_DO_BRASIL', 'Copa do Brasil 2021', '3ª fase - volta', 'CONFIRMED', 'Bahia', false, false, 'Bahia', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', 'Estádio de Pituaçu', 'MATCH_SPECIFIC', 'vn_venue_pituacu', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2021-06-09 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF', 'cdb2021_jogo_78', 'https://www.cbf.com.br/futebol-brasileiro/times/copa-do-brasil/masculino/2021/20079?tab=historico-de-partidas', 'HIGH', null),
  ('vn_cbf_zerozero_sb2021_r03', 2021, '2021-06-12', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2021', 'R3', 'CONFIRMED', 'CSA', true, false, 'Vila Nova', 'CSA', 1, 0, 1, 0, '1–0', 'WIN', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2021_r03', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2021&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2021_r04', 2021, '2021-06-15', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2021', 'R4', 'CONFIRMED', 'Náutico', false, false, 'Náutico', 'Vila Nova', 2, 0, 0, 2, '2–0', 'LOSS', null, 'UNKNOWN', null, 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2021_r04', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2021&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2021_r05', 2021, '2021-06-19', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2021', 'R5', 'CONFIRMED', 'Coritiba', true, false, 'Vila Nova', 'Coritiba', 0, 1, 0, 1, '0–1', 'LOSS', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2021_r05', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2021&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2021_r06', 2021, '2021-06-22', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2021', 'R6', 'CONFIRMED', 'Confiança', false, false, 'Confiança', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', null, 'UNKNOWN', null, 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2021_r06', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2021&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2021_r07', 2021, '2021-06-25', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2021', 'R7', 'CONFIRMED', 'Goiás', true, false, 'Vila Nova', 'Goiás', 0, 0, 0, 0, '0–0', 'DRAW', null, 'UNKNOWN', null, 'sexta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2021_r07', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2021&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2021_r08', 2021, '2021-06-28', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2021', 'R8', 'CONFIRMED', 'Operário-PR', false, false, 'Operário-PR', 'Vila Nova', 1, 2, 2, 1, '1–2', 'WIN', null, 'UNKNOWN', null, 'segunda-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2021_r08', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2021&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2021_r09', 2021, '2021-07-03', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2021', 'R9', 'CONFIRMED', 'Ponte Preta', true, false, 'Vila Nova', 'Ponte Preta', 0, 0, 0, 0, '0–0', 'DRAW', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2021_r09', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2021&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2021_r10', 2021, '2021-07-08', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2021', 'R10', 'CONFIRMED', 'Remo', false, false, 'Remo', 'Vila Nova', 0, 1, 1, 0, '0–1', 'WIN', null, 'UNKNOWN', null, 'quinta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2021_r10', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2021&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2021_r11', 2021, '2021-07-13', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2021', 'R11', 'CONFIRMED', 'Brasil de Pelotas', true, false, 'Vila Nova', 'Brasil de Pelotas', 0, 0, 0, 0, '0–0', 'DRAW', null, 'UNKNOWN', null, 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2021_r11', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2021&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2021_r12', 2021, '2021-07-18', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2021', 'R12', 'CONFIRMED', 'CRB', false, false, 'CRB', 'Vila Nova', 2, 1, 1, 2, '2–1', 'LOSS', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2021_r12', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2021&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2021_r13', 2021, '2021-07-21', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2021', 'R13', 'CONFIRMED', 'Brusque', true, false, 'Vila Nova', 'Brusque', 0, 1, 0, 1, '0–1', 'LOSS', null, 'UNKNOWN', null, 'quarta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2021_r13', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2021&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2021_r14', 2021, '2021-07-24', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2021', 'R14', 'CONFIRMED', 'Cruzeiro', true, false, 'Vila Nova', 'Cruzeiro', 0, 0, 0, 0, '0–0', 'DRAW', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2021_r14', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2021&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2021_r15', 2021, '2021-07-31', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2021', 'R15', 'CONFIRMED', 'Guarani', false, false, 'Guarani', 'Vila Nova', 1, 4, 4, 1, '1–4', 'WIN', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2021_r15', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2021&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2021_r16', 2021, '2021-08-07', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2021', 'R16', 'CONFIRMED', 'Sampaio Corrêa', true, false, 'Vila Nova', 'Sampaio Corrêa', 0, 2, 0, 2, '0–2', 'LOSS', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2021_r16', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2021&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2021_r17', 2021, '2021-08-10', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2021', 'R17', 'CONFIRMED', 'Vasco', false, false, 'Vasco', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', null, 'UNKNOWN', null, 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2021_r17', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2021&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2021_r18', 2021, '2021-08-15', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2021', 'R18', 'CONFIRMED', 'Londrina', false, false, 'Londrina', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2021_r18', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2021&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2021_r19', 2021, '2021-08-18', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2021', 'R19', 'CONFIRMED', 'Vitória', true, false, 'Vila Nova', 'Vitória', 0, 0, 0, 0, '0–0', 'DRAW', null, 'UNKNOWN', null, 'quarta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2021_r19', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2021&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2021_r20', 2021, '2021-08-22', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2021', 'R20', 'CONFIRMED', 'Botafogo-RJ', false, false, 'Botafogo-RJ', 'Vila Nova', 3, 2, 2, 3, '3–2', 'LOSS', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2021_r20', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2021&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2021_r21', 2021, '2021-08-25', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2021', 'R21', 'CONFIRMED', 'Avaí', true, false, 'Vila Nova', 'Avaí', 1, 0, 1, 0, '1–0', 'WIN', null, 'UNKNOWN', null, 'quarta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2021_r21', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2021&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2021_r22', 2021, '2021-09-03', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2021', 'R22', 'CONFIRMED', 'CSA', false, false, 'CSA', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', null, 'UNKNOWN', null, 'sexta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2021_r22', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2021&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2021_r23', 2021, '2021-09-10', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2021', 'R23', 'CONFIRMED', 'Náutico', true, false, 'Vila Nova', 'Náutico', 1, 0, 1, 0, '1–0', 'WIN', null, 'UNKNOWN', null, 'sexta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2021_r23', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2021&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2021_r24', 2021, '2021-09-17', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2021', 'R24', 'CONFIRMED', 'Coritiba', false, false, 'Coritiba', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', null, 'UNKNOWN', null, 'sexta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2021_r24', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2021&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2021_r25', 2021, '2021-09-21', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2021', 'R25', 'CONFIRMED', 'Confiança', true, false, 'Vila Nova', 'Confiança', 0, 0, 0, 0, '0–0', 'DRAW', null, 'UNKNOWN', null, 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2021_r25', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2021&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2021_r26', 2021, '2021-09-24', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2021', 'R26', 'CONFIRMED', 'Goiás', false, false, 'Goiás', 'Vila Nova', 1, 2, 2, 1, '1–2', 'WIN', null, 'UNKNOWN', null, 'sexta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2021_r26', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2021&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2021_r27', 2021, '2021-09-28', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2021', 'R27', 'CONFIRMED', 'Operário-PR', true, false, 'Vila Nova', 'Operário-PR', 2, 1, 2, 1, '2–1', 'WIN', null, 'UNKNOWN', null, 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2021_r27', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2021&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2021_r28', 2021, '2021-10-02', '21:00:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2021', 'R28', 'CONFIRMED', 'Ponte Preta', false, false, 'Ponte Preta', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Moisés Lucarelli', 'MATCH_SPECIFIC', 'vn_venue_moises_lucarelli', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2021-10-02 21:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF/Zerozero', 'sb2021_r28', 'https://www.cbf.com.br/futebol-brasileiro/tabelas/campeonato-brasileiro/serie-b/2021', 'HIGH', null),
  ('vn_cbf_zerozero_sb2021_r29', 2021, '2021-10-08', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2021', 'R29', 'CONFIRMED', 'Remo', true, false, 'Vila Nova', 'Remo', 1, 0, 1, 0, '1–0', 'WIN', null, 'UNKNOWN', null, 'sexta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2021_r29', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2021&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2021_r30', 2021, '2021-10-16', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2021', 'R30', 'CONFIRMED', 'Brasil de Pelotas', false, false, 'Brasil de Pelotas', 'Vila Nova', 2, 2, 2, 2, '2–2', 'DRAW', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2021_r30', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2021&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2021_r31', 2021, '2021-10-18', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2021', 'R31', 'CONFIRMED', 'CRB', true, false, 'Vila Nova', 'CRB', 0, 0, 0, 0, '0–0', 'DRAW', null, 'UNKNOWN', null, 'segunda-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2021_r31', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2021&grp=1', 'HIGH', null),
  ('vn_cbf_cv2021_01', 2021, '2021-10-21', null, 'FINISHED', 'Copa Verde', 'COPA_VERDE', 'Copa Verde 2021', 'Oitavas', 'CONFIRMED', 'Rio Branco-VN', true, false, 'Vila Nova', 'Rio Branco-VN', 3, 0, 3, 0, '3–0', 'WIN', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'quinta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF', 'cv2021_01', 'https://www.cbf.com.br/futebol-brasileiro/times/copa-verde/profissional/2021/20079?tab=historico-de-partidas', 'HIGH', null),
  ('vn_cbf_zerozero_sb2021_r32', 2021, '2021-10-24', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2021', 'R32', 'CONFIRMED', 'Brusque', false, false, 'Brusque', 'Vila Nova', 2, 3, 3, 2, '2–3', 'WIN', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2021_r32', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2021&grp=1', 'HIGH', null),
  ('vn_cbf_cv2021_02', 2021, '2021-10-28', null, 'FINISHED', 'Copa Verde', 'COPA_VERDE', 'Copa Verde 2021', 'QF1', 'CONFIRMED', 'Aquidauanense', false, false, 'Aquidauanense', 'Vila Nova', 0, 1, 1, 0, '0–1', 'WIN', 'Estádio Noroeste', 'MATCH_SPECIFIC', 'vn_venue_noroeste', 'quinta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF', 'cv2021_02', 'https://www.cbf.com.br/futebol-brasileiro/times/copa-verde/profissional/2021/20079?tab=historico-de-partidas', 'HIGH', null),
  ('vn_cbf_zerozero_sb2021_r33', 2021, '2021-11-01', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2021', 'R33', 'CONFIRMED', 'Cruzeiro', false, false, 'Cruzeiro', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', null, 'UNKNOWN', null, 'segunda-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2021_r33', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2021&grp=1', 'HIGH', null),
  ('vn_cbf_cv2021_03', 2021, '2021-11-04', null, 'FINISHED', 'Copa Verde', 'COPA_VERDE', 'Copa Verde 2021', 'QF2', 'CONFIRMED', 'Aquidauanense', true, false, 'Vila Nova', 'Aquidauanense', 7, 0, 7, 0, '7–0', 'WIN', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'quinta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF', 'cv2021_03', 'https://www.cbf.com.br/futebol-brasileiro/times/copa-verde/profissional/2021/20079?tab=historico-de-partidas', 'HIGH', null),
  ('vn_cbf_zerozero_sb2021_r34', 2021, '2021-11-07', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2021', 'R34', 'CONFIRMED', 'Guarani', true, false, 'Vila Nova', 'Guarani', 2, 2, 2, 2, '2–2', 'DRAW', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2021_r34', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2021&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2021_r35', 2021, '2021-11-11', null, 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2021', 'R35', 'CONFIRMED', 'Sampaio Corrêa', false, false, 'Sampaio Corrêa', 'Vila Nova', 3, 0, 0, 3, '3–0', 'LOSS', null, 'UNKNOWN', null, 'quinta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF/Zerozero', 'sb2021_r35', 'https://www.zerozero.pt/equipa/vila-nova/3532/jogos?ano=2021&grp=1', 'HIGH', null),
  ('vn_cbf_zerozero_sb2021_r36', 2021, '2021-11-15', '18:00:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2021', 'R36', 'CONFIRMED', 'Vasco', true, false, 'Vila Nova', 'Vasco', 2, 2, 2, 2, '2–2', 'DRAW', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'segunda-feira', 'WEEKDAY', 'NIGHT', (timestamp '2021-11-15 18:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF/Zerozero', 'sb2021_r36', 'https://www.cbf.com.br/futebol-brasileiro/tabelas/campeonato-brasileiro/serie-b/2021', 'HIGH', null),
  ('vn_cbf_zerozero_sb2021_r37', 2021, '2021-11-19', '21:30:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2021', 'R37', 'CONFIRMED', 'Londrina', true, false, 'Vila Nova', 'Londrina', 2, 1, 2, 1, '2–1', 'WIN', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2021-11-19 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF/Zerozero', 'sb2021_r37', 'https://www.cbf.com.br/futebol-brasileiro/tabelas/campeonato-brasileiro/serie-b/2021', 'HIGH', null),
  ('vn_cbf_cv2021_04', 2021, '2021-11-24', null, 'FINISHED', 'Copa Verde', 'COPA_VERDE', 'Copa Verde 2021', 'SF1', 'CONFIRMED', 'Nova Mutum', true, false, 'Vila Nova', 'Nova Mutum', 3, 0, 3, 0, '3–0', 'WIN', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'quarta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF', 'cv2021_04', 'https://www.cbf.com.br/futebol-brasileiro/times/copa-verde/profissional/2021/20079?tab=historico-de-partidas', 'HIGH', null),
  ('vn_cbf_zerozero_sb2021_r38', 2021, '2021-11-28', '16:00:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2021', 'R38', 'CONFIRMED', 'Vitória', false, false, 'Vitória', 'Vila Nova', 0, 1, 1, 0, '0–1', 'WIN', 'Estádio Manoel Barradas', 'MATCH_SPECIFIC', 'vn_venue_barradao', 'domingo', 'WEEKEND', 'AFTERNOON', (timestamp '2021-11-28 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF/Zerozero', 'sb2021_r38', 'https://www.cbf.com.br/futebol-brasileiro/tabelas/campeonato-brasileiro/serie-b/2021', 'HIGH', null),
  ('vn_cbf_cv2021_05', 2021, '2021-12-02', null, 'FINISHED', 'Copa Verde', 'COPA_VERDE', 'Copa Verde 2021', 'SF2', 'CONFIRMED', 'Nova Mutum', false, false, 'Nova Mutum', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Valdir Doilho Wons', 'MATCH_SPECIFIC', 'vn_venue_valdir_wons', 'quinta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'CBF', 'cv2021_05', 'https://www.cbf.com.br/futebol-brasileiro/times/copa-verde/profissional/2021/20079?tab=historico-de-partidas', 'HIGH', null),
  ('vn_cbf_cv2021_06', 2021, '2021-12-08', '20:00:00', 'FINISHED', 'Copa Verde', 'COPA_VERDE', 'Copa Verde 2021', 'F1', 'CONFIRMED', 'Remo', true, false, 'Vila Nova', 'Remo', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2021-12-08 20:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF', 'cv2021_06', 'https://www.cbf.com.br/futebol-brasileiro/times/copa-verde/profissional/2021/20079?tab=historico-de-partidas', 'HIGH', null),
  ('vn_cbf_cv2021_07', 2021, '2021-12-11', '17:00:00', 'FINISHED', 'Copa Verde', 'COPA_VERDE', 'Copa Verde 2021', 'F2', 'CONFIRMED', 'Remo', false, false, 'Remo', 'Vila Nova', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Evandro Almeida', 'MATCH_SPECIFIC', 'vn_venue_baenao', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2021-12-11 17:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'CBF', 'cv2021_07', 'https://www.cbf.com.br/futebol-brasileiro/times/copa-verde/profissional/2021/20079?tab=historico-de-partidas', 'HIGH', '0–0 no tempo normal; Remo venceu nos pênaltis por 4–2.')
on conflict (id) do update set
    season = excluded.season,
    match_date = excluded.match_date,
    match_time = excluded.match_time,
    status = excluded.status,
    competition = excluded.competition,
    competition_code = excluded.competition_code,
    competition_edition = excluded.competition_edition,
    round = excluded.round,
    phase_status = excluded.phase_status,
    opponent = excluded.opponent,
    club_is_home = excluded.club_is_home,
    neutral_site = excluded.neutral_site,
    home_team = excluded.home_team,
    away_team = excluded.away_team,
    home_score = excluded.home_score,
    away_score = excluded.away_score,
    club_score = excluded.club_score,
    opponent_score = excluded.opponent_score,
    score_display = excluded.score_display,
    outcome = excluded.outcome,
    stadium = excluded.stadium,
    stadium_status = excluded.stadium_status,
    venue_id = excluded.venue_id,
    weekday = excluded.weekday,
    day_type = excluded.day_type,
    day_period = excluded.day_period,
    kickoff_at = excluded.kickoff_at,
    display_timezone = excluded.display_timezone,
    date_precision = excluded.date_precision,
    source_provider = excluded.source_provider,
    source_match_id = excluded.source_match_id,
    source_url = excluded.source_url,
    source_confidence = excluded.source_confidence,
    data_notes = excluded.data_notes,
    updated_at = now();

do $$
declare v_orphans int;
begin
  select count(*) into v_orphans from public.passport_matches
   where season = 2021 and stadium is not null and venue_id is null;
  if v_orphans > 0 then
    raise exception 'ha % partidas de 2021 com estadio sem venue_id -- rode vilanova_passport_venues_seed.sql antes', v_orphans;
  end if;
end $$;
