-- Passaporte do Vila Nova — temporada 2019. GERADO por
-- `node tooling/vilanova_passport/generate_passport_sql.mjs` a partir de
-- docs/vila_nova_data/passport/passport_2019.json — não edite à mão.
--
-- Rode no projeto Supabase do VILA NOVA — NUNCA no do Goiás nem no do Bragantino.
-- Ordem: vilanova_passport_infra.sql -> vilanova_passport_venues_seed.sql -> ESTE.
-- Idempotente (ON CONFLICT DO UPDATE): reexecutar atualiza, nunca duplica, e
-- não encosta em presença de usuário. 60 partidas.

do $$
begin
  if not exists (select 1 from public.clubs where slug = 'vilanova')
     or exists (select 1 from public.clubs where slug <> 'vilanova') then
    raise exception 'este nao e o projeto Supabase do Vila Nova -- PARE';
  end if;
end $$;

insert into public.passport_matches (
  id, season, match_date, match_time, status, competition, competition_code, competition_edition, round, phase_status, opponent, club_is_home, neutral_site, home_team, away_team, home_score, away_score, club_score, opponent_score, score_display, outcome, stadium, stadium_status, venue_id, weekday, day_type, day_period, kickoff_at, display_timezone, date_precision, source_provider, source_match_id, source_url, source_confidence, data_notes
) values
  ('vn_eg_go2019_r01', 2019, '2019-01-19', '17:00:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2019', 'R1', 'CONFIRMED', 'Aparecidense', true, false, 'Vila Nova', 'Aparecidense', 1, 0, 1, 0, '1–0', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2019-01-19 17:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'eg_go2019_r01', 'https://esportegoiano.com.br/tabela-do-campeonato-goiano-de-futebol-2019/', 'HIGH', null),
  ('vn_eg_go2019_r02', 2019, '2019-01-23', '20:30:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2019', 'R2', 'CONFIRMED', 'Anapolina', false, false, 'Anapolina', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Jonas Duarte', 'MATCH_SPECIFIC', 'vn_venue_jonas_duarte', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2019-01-23 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'eg_go2019_r02', 'https://esportegoiano.com.br/tabela-do-campeonato-goiano-de-futebol-2019/', 'HIGH', null),
  ('vn_eg_go2019_r03', 2019, '2019-01-27', '17:00:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2019', 'R3', 'CONFIRMED', 'Goiás', false, false, 'Goiás', 'Vila Nova', 2, 0, 0, 2, '2–0', 'LOSS', 'Estádio Hailé Pinheiro', 'MATCH_SPECIFIC', 'vn_venue_serrinha', 'domingo', 'WEEKEND', 'AFTERNOON', (timestamp '2019-01-27 17:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'eg_go2019_r03', 'https://esportegoiano.com.br/tabela-do-campeonato-goiano-de-futebol-2019/', 'HIGH', null),
  ('vn_eg_go2019_r04', 2019, '2019-01-31', '20:30:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2019', 'R4', 'CONFIRMED', 'CRAC', true, false, 'Vila Nova', 'CRAC', 3, 0, 3, 0, '3–0', 'WIN', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'quinta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2019-01-31 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'eg_go2019_r04', 'https://esportegoiano.com.br/tabela-do-campeonato-goiano-de-futebol-2019/', 'HIGH', null),
  ('vn_eg_go2019_r05', 2019, '2019-02-03', '17:00:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2019', 'R5', 'CONFIRMED', 'Itumbiara', false, false, 'Itumbiara', 'Vila Nova', 0, 1, 1, 0, '0–1', 'WIN', 'Estádio Municipal Juscelino Kubitschek de Oliveira', 'MATCH_SPECIFIC', 'vn_venue_jk_itumbiara', 'domingo', 'WEEKEND', 'AFTERNOON', (timestamp '2019-02-03 17:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'eg_go2019_r05', 'https://esportegoiano.com.br/tabela-do-campeonato-goiano-de-futebol-2019/', 'HIGH', null),
  ('vn_eg_go2019_r06', 2019, '2019-02-10', '17:00:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2019', 'R6', 'CONFIRMED', 'Goianésia', true, false, 'Vila Nova', 'Goianésia', 2, 2, 2, 2, '2–2', 'DRAW', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'domingo', 'WEEKEND', 'AFTERNOON', (timestamp '2019-02-10 17:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'eg_go2019_r06', 'https://esportegoiano.com.br/tabela-do-campeonato-goiano-de-futebol-2019/', 'HIGH', null),
  ('vn_eg_go2019_r07', 2019, '2019-02-16', '18:00:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2019', 'R7', 'CONFIRMED', 'Aparecidense', false, false, 'Aparecidense', 'Vila Nova', 1, 2, 2, 1, '1–2', 'WIN', 'Estádio Aníbal Batista de Toledo', 'MATCH_SPECIFIC', 'vn_venue_anibal_toledo', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2019-02-16 18:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'eg_go2019_r07', 'https://esportegoiano.com.br/tabela-do-campeonato-goiano-de-futebol-2019/', 'HIGH', null),
  ('vn_eg_go2019_r08', 2019, '2019-02-24', '17:00:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2019', 'R8', 'CONFIRMED', 'Goiás', true, false, 'Vila Nova', 'Goiás', 0, 1, 0, 1, '0–1', 'LOSS', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'domingo', 'WEEKEND', 'AFTERNOON', (timestamp '2019-02-24 17:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'eg_go2019_r08', 'https://esportegoiano.com.br/tabela-do-campeonato-goiano-de-futebol-2019/', 'HIGH', null),
  ('vn_eg_go2019_r09', 2019, '2019-03-02', '16:00:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2019', 'R9', 'CONFIRMED', 'CRAC', false, false, 'CRAC', 'Vila Nova', 2, 2, 2, 2, '2–2', 'DRAW', 'Estádio Genervino da Fonseca', 'MATCH_SPECIFIC', 'vn_venue_genervino_fonseca', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2019-03-02 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'eg_go2019_r09', 'https://esportegoiano.com.br/tabela-do-campeonato-goiano-de-futebol-2019/', 'HIGH', null),
  ('vn_eg_go2019_r10', 2019, '2019-03-10', '16:00:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2019', 'R10', 'CONFIRMED', 'Anapolina', true, false, 'Vila Nova', 'Anapolina', 3, 2, 3, 2, '3–2', 'WIN', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'domingo', 'WEEKEND', 'AFTERNOON', (timestamp '2019-03-10 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'eg_go2019_r10', 'https://esportegoiano.com.br/tabela-do-campeonato-goiano-de-futebol-2019/', 'HIGH', null),
  ('vn_ge_go2019_r11', 2019, '2019-03-16', '16:00:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2019', 'R11', 'CONFIRMED', 'Itumbiara', true, false, 'Vila Nova', 'Itumbiara', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2019-03-16 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'ge', 'ge_go2019_r11', 'https://app.globoesporte.globo.com/futebol/publico-no-brasil/2019/campeonato-goiano/', 'HIGH', 'Conflito de estádio resolvido: ge/Esporte Goiano registram OBA; Sofascore registra Serra Dourada. Usado OBA.'),
  ('vn_eg_go2019_r12', 2019, '2019-03-20', '21:30:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2019', 'R12', 'CONFIRMED', 'Goianésia', false, false, 'Goianésia', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', 'Estádio Valdeir José de Oliveira', 'MATCH_SPECIFIC', 'vn_venue_valdeir_jose', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2019-03-20 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'eg_go2019_r12', 'https://esportegoiano.com.br/tabela-do-campeonato-goiano-de-futebol-2019/', 'HIGH', null),
  ('vn_eg_go2019_qf1', 2019, '2019-03-23', '16:00:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2019', 'QF1', 'CONFIRMED', 'CRAC', true, false, 'Vila Nova', 'CRAC', 2, 0, 2, 0, '2–0', 'WIN', 'Estádio Olímpico Pedro Ludovico Teixeira', 'MATCH_SPECIFIC', 'vn_venue_olimpico', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2019-03-23 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'eg_go2019_qf1', 'https://esportegoiano.com.br/tabela-do-campeonato-goiano-de-futebol-2019/', 'HIGH', null),
  ('vn_eg_go2019_qf2', 2019, '2019-03-27', '20:30:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2019', 'QF2', 'CONFIRMED', 'CRAC', false, false, 'CRAC', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', 'Estádio Genervino da Fonseca', 'MATCH_SPECIFIC', 'vn_venue_genervino_fonseca', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2019-03-27 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'eg_go2019_qf2', 'https://esportegoiano.com.br/tabela-do-campeonato-goiano-de-futebol-2019/', 'HIGH', null),
  ('vn_eg_go2019_sf1', 2019, '2019-03-31', '16:00:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2019', 'SF1', 'CONFIRMED', 'Atlético-GO', true, false, 'Vila Nova', 'Atlético-GO', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Olímpico Pedro Ludovico Teixeira', 'MATCH_SPECIFIC', 'vn_venue_olimpico', 'domingo', 'WEEKEND', 'AFTERNOON', (timestamp '2019-03-31 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'eg_go2019_sf1', 'https://esportegoiano.com.br/tabela-do-campeonato-goiano-de-futebol-2019/', 'HIGH', null),
  ('vn_fgf_go2019_sf2', 2019, '2019-04-07', '16:00:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2019', 'SF2', 'CONFIRMED', 'Atlético-GO', false, false, 'Atlético-GO', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', 'Estádio Antônio Accioly', 'MATCH_SPECIFIC', 'vn_venue_ant_nio_accioly', 'domingo', 'WEEKEND', 'AFTERNOON', (timestamp '2019-04-07 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Federação Goiana de Futebol', 'fgf_go2019_sf2', 'https://www.tjdgo.com.br/wp-content/uploads/2019/04/ATLETICO-C.-G.-X-VILA-NOVA-F.-C.-07.04.2019.pdf', 'HIGH', 'Conflito de estádio resolvido: tabela do Esporte Goiano registra Olímpico, mas a súmula da FGF e o ge registram Antônio Accioly. Usado Antônio Accioly.'),
  ('vn_ge_cdb2019_01', 2019, '2019-02-13', '22:30:00', 'FINISHED', 'Copa do Brasil', 'COPA_DO_BRASIL', 'Copa do Brasil 2019', '1ª fase', 'CONFIRMED', 'Manaus', false, false, 'Manaus', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Ismael Benigno', 'MATCH_SPECIFIC', 'vn_venue_ismael_benigno', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2019-02-13 22:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'ge', 'ge_cdb2019_01', 'https://app.globoesporte.globo.com/futebol/publico-no-brasil/2019/copa-do-brasil/', 'HIGH', null),
  ('vn_eg_cdb2019_02', 2019, '2019-02-27', '21:30:00', 'FINISHED', 'Copa do Brasil', 'COPA_DO_BRASIL', 'Copa do Brasil 2019', '2ª fase', 'CONFIRMED', 'URT', false, false, 'URT', 'Vila Nova', 2, 2, 2, 2, '2–2', 'DRAW', 'Estádio Zama Maciel', 'MATCH_SPECIFIC', 'vn_venue_zama_maciel', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2019-02-27 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'eg_cdb2019_02', 'https://esportegoiano.com.br/27-02-19-urt-vila/', 'HIGH', '2–2 no tempo normal; Vila Nova venceu a disputa de pênaltis por 5–4. outcome=DRAW pelo placar principal.'),
  ('vn_ge_cdb2019_03', 2019, '2019-04-16', '20:00:00', 'FINISHED', 'Copa do Brasil', 'COPA_DO_BRASIL', 'Copa do Brasil 2019', '3ª fase - ida', 'CONFIRMED', 'Bragantino-PA', true, false, 'Vila Nova', 'Bragantino-PA', 2, 0, 2, 0, '2–0', 'WIN', 'Estádio Olímpico Pedro Ludovico Teixeira', 'MATCH_SPECIFIC', 'vn_venue_olimpico', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2019-04-16 20:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'ge', 'ge_cdb2019_03', 'https://app.globoesporte.globo.com/futebol/publico-no-brasil/2019/copa-do-brasil/', 'HIGH', null),
  ('vn_ge_cdb2019_04', 2019, '2019-04-20', '16:00:00', 'FINISHED', 'Copa do Brasil', 'COPA_DO_BRASIL', 'Copa do Brasil 2019', '3ª fase - volta', 'CONFIRMED', 'Bragantino-PA', false, false, 'Bragantino-PA', 'Vila Nova', 2, 1, 1, 2, '2–1', 'LOSS', 'Estádio Mangueirão', 'MATCH_SPECIFIC', 'vn_venue_mangueirao', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2019-04-20 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'ge', 'ge_cdb2019_04', 'https://app.globoesporte.globo.com/futebol/publico-no-brasil/2019/copa-do-brasil/', 'HIGH', null),
  ('vn_ge_cdb2019_05', 2019, '2019-04-24', '21:30:00', 'FINISHED', 'Copa do Brasil', 'COPA_DO_BRASIL', 'Copa do Brasil 2019', '4ª fase - ida', 'CONFIRMED', 'Juventude', false, false, 'Juventude', 'Vila Nova', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Alfredo Jaconi', 'MATCH_SPECIFIC', 'vn_venue_alfredo_jaconi', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2019-04-24 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'ge', 'ge_cdb2019_05', 'https://app.globoesporte.globo.com/futebol/publico-no-brasil/2019/copa-do-brasil/', 'HIGH', null),
  ('vn_rsssf_cdb2019_06', 2019, '2019-05-07', '21:30:00', 'FINISHED', 'Copa do Brasil', 'COPA_DO_BRASIL', 'Copa do Brasil 2019', '4ª fase - volta', 'CONFIRMED', 'Juventude', true, false, 'Vila Nova', 'Juventude', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2019-05-07 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'RSSSF Brasil / ge', 'rsssf_cdb2019_06', 'https://www.rsssfbrasil.com.chancedegol.com.br/tablesae/cbr2019.htm', 'HIGH', '0–0 no tempo normal; Juventude venceu a disputa de pênaltis por 4–3. Estádio/horário confirmados na base de público do ge. outcome=DRAW pelo placar principal.'),
  ('vn_superesportes_sb2019_r01', 2019, '2019-04-27', '21:00:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2019', 'R1', 'CONFIRMED', 'Paraná', true, false, 'Vila Nova', 'Paraná', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Olímpico Pedro Ludovico Teixeira', 'MATCH_SPECIFIC', 'vn_venue_olimpico', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2019-04-27 21:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Superesportes', 'superesportes_sb2019_r01', 'https://www.superesportes.com.br/campeonatos/2019/brasileirao/serie-b/', 'HIGH', null),
  ('vn_superesportes_sb2019_r02', 2019, '2019-05-04', '16:30:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2019', 'R2', 'CONFIRMED', 'Vitória', false, false, 'Vitória', 'Vila Nova', 2, 1, 1, 2, '2–1', 'LOSS', 'Estádio Manoel Barradas', 'MATCH_SPECIFIC', 'vn_venue_barradao', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2019-05-04 16:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Superesportes', 'superesportes_sb2019_r02', 'https://www.superesportes.com.br/campeonatos/2019/brasileirao/serie-b/', 'HIGH', null),
  ('vn_superesportes_sb2019_r03', 2019, '2019-05-10', '21:30:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2019', 'R3', 'CONFIRMED', 'Ponte Preta', true, false, 'Vila Nova', 'Ponte Preta', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2019-05-10 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Superesportes', 'superesportes_sb2019_r03', 'https://www.superesportes.com.br/campeonatos/2019/brasileirao/serie-b/', 'HIGH', null),
  ('vn_superesportes_sb2019_r04', 2019, '2019-05-18', '19:00:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2019', 'R4', 'CONFIRMED', 'Botafogo-SP', false, false, 'Botafogo-SP', 'Vila Nova', 0, 1, 1, 0, '0–1', 'WIN', 'Estádio Santa Cruz', 'MATCH_SPECIFIC', 'vn_venue_santa_cruz_ribeirao', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2019-05-18 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Superesportes', 'superesportes_sb2019_r04', 'https://www.superesportes.com.br/campeonatos/2019/brasileirao/serie-b/', 'HIGH', null),
  ('vn_superesportes_sb2019_r05', 2019, '2019-05-24', '19:15:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2019', 'R5', 'CONFIRMED', 'CRB', false, false, 'CRB', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Rei Pelé', 'MATCH_SPECIFIC', 'vn_venue_rei_pele', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2019-05-24 19:15:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Superesportes', 'superesportes_sb2019_r05', 'https://www.superesportes.com.br/campeonatos/2019/brasileirao/serie-b/', 'HIGH', null),
  ('vn_superesportes_sb2019_r06', 2019, '2019-06-01', '16:30:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2019', 'R6', 'CONFIRMED', 'Londrina', true, false, 'Vila Nova', 'Londrina', 0, 1, 0, 1, '0–1', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2019-06-01 16:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Superesportes', 'superesportes_sb2019_r06', 'https://www.superesportes.com.br/campeonatos/2019/brasileirao/serie-b/', 'HIGH', null),
  ('vn_superesportes_sb2019_r07', 2019, '2019-06-08', '16:30:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2019', 'R7', 'CONFIRMED', 'Criciúma', false, false, 'Criciúma', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Heriberto Hülse', 'MATCH_SPECIFIC', 'vn_venue_heriberto_h_lse', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2019-06-08 16:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Superesportes', 'superesportes_sb2019_r07', 'https://www.superesportes.com.br/campeonatos/2019/brasileirao/serie-b/', 'HIGH', null),
  ('vn_superesportes_sb2019_r08', 2019, '2019-06-11', '19:15:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2019', 'R8', 'CONFIRMED', 'São Bento', true, false, 'Vila Nova', 'São Bento', 1, 0, 1, 0, '1–0', 'WIN', 'Estádio Olímpico Pedro Ludovico Teixeira', 'MATCH_SPECIFIC', 'vn_venue_olimpico', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2019-06-11 19:15:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Superesportes', 'superesportes_sb2019_r08', 'https://www.superesportes.com.br/campeonatos/2019/brasileirao/serie-b/', 'HIGH', null),
  ('vn_ge_sb2019_r09', 2019, '2019-07-13', '16:30:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2019', 'R9', 'CONFIRMED', 'Atlético-GO', false, false, 'Atlético-GO', 'Vila Nova', 2, 0, 0, 2, '2–0', 'LOSS', 'Estádio Antônio Accioly', 'MATCH_SPECIFIC', 'vn_venue_ant_nio_accioly', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2019-07-13 16:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'ge', 'ge_sb2019_r09', 'https://ge.globo.com/go/futebol/brasileirao-serie-b/noticia/atletico-go-x-vila-nova-tudo-o-que-voce-precisa-saber-sobre-o-classico-da-rodada-9-da-serie-b.ghtml', 'HIGH', 'Conflito de estádio resolvido: Superesportes registra Serra Dourada; ge e Futebol de Goyaz registram Antônio Accioly. Usado Antônio Accioly.'),
  ('vn_superesportes_sb2019_r10', 2019, '2019-07-20', '16:30:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2019', 'R10', 'CONFIRMED', 'América-MG', true, false, 'Vila Nova', 'América-MG', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2019-07-20 16:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Superesportes', 'superesportes_sb2019_r10', 'https://www.superesportes.com.br/campeonatos/2019/brasileirao/serie-b/', 'HIGH', null),
  ('vn_superesportes_sb2019_r11', 2019, '2019-07-23', '19:15:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2019', 'R11', 'CONFIRMED', 'Coritiba', false, false, 'Coritiba', 'Vila Nova', 2, 0, 0, 2, '2–0', 'LOSS', 'Estádio Couto Pereira', 'MATCH_SPECIFIC', 'vn_venue_couto_pereira', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2019-07-23 19:15:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Superesportes', 'superesportes_sb2019_r11', 'https://www.superesportes.com.br/campeonatos/2019/brasileirao/serie-b/', 'HIGH', null),
  ('vn_superesportes_sb2019_r12', 2019, '2019-07-27', '19:00:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2019', 'R12', 'CONFIRMED', 'Bragantino', true, false, 'Vila Nova', 'Bragantino', 0, 1, 0, 1, '0–1', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2019-07-27 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Superesportes', 'superesportes_sb2019_r12', 'https://www.superesportes.com.br/campeonatos/2019/brasileirao/serie-b/', 'HIGH', null),
  ('vn_superesportes_sb2019_r13', 2019, '2019-07-30', '19:15:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2019', 'R13', 'CONFIRMED', 'Brasil de Pelotas', false, false, 'Brasil de Pelotas', 'Vila Nova', 0, 2, 2, 0, '0–2', 'WIN', 'Estádio Bento Mendes de Freitas', 'MATCH_SPECIFIC', 'vn_venue_bento_mendes_freitas', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2019-07-30 19:15:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Superesportes', 'superesportes_sb2019_r13', 'https://www.superesportes.com.br/campeonatos/2019/brasileirao/serie-b/', 'HIGH', null),
  ('vn_superesportes_sb2019_r14', 2019, '2019-08-03', '19:15:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2019', 'R14', 'CONFIRMED', 'Figueirense', true, false, 'Vila Nova', 'Figueirense', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2019-08-03 19:15:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Superesportes', 'superesportes_sb2019_r14', 'https://www.superesportes.com.br/campeonatos/2019/brasileirao/serie-b/', 'HIGH', null),
  ('vn_superesportes_sb2019_r15', 2019, '2019-08-09', '19:15:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2019', 'R15', 'CONFIRMED', 'Operário-PR', false, false, 'Operário-PR', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', 'Estádio Germano Krüger', 'MATCH_SPECIFIC', 'vn_venue_germano_kr_ger', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2019-08-09 19:15:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Superesportes', 'superesportes_sb2019_r15', 'https://www.superesportes.com.br/campeonatos/2019/brasileirao/serie-b/', 'HIGH', null),
  ('vn_superesportes_sb2019_r16', 2019, '2019-08-16', '21:30:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2019', 'R16', 'CONFIRMED', 'Guarani', false, false, 'Guarani', 'Vila Nova', 0, 2, 2, 0, '0–2', 'WIN', 'Estádio Brinco de Ouro da Princesa', 'MATCH_SPECIFIC', 'vn_venue_brinco_ouro', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2019-08-16 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Superesportes', 'superesportes_sb2019_r16', 'https://www.superesportes.com.br/campeonatos/2019/brasileirao/serie-b/', 'HIGH', null),
  ('vn_superesportes_sb2019_r17', 2019, '2019-08-20', '21:30:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2019', 'R17', 'CONFIRMED', 'Sport', true, false, 'Vila Nova', 'Sport', 0, 2, 0, 2, '0–2', 'LOSS', 'Estádio Olímpico Pedro Ludovico Teixeira', 'MATCH_SPECIFIC', 'vn_venue_olimpico', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2019-08-20 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Superesportes', 'superesportes_sb2019_r17', 'https://www.superesportes.com.br/campeonatos/2019/brasileirao/serie-b/', 'HIGH', null),
  ('vn_superesportes_sb2019_r18', 2019, '2019-08-24', '16:30:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2019', 'R18', 'CONFIRMED', 'Oeste', false, false, 'Oeste', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', 'Arena Barueri', 'MATCH_SPECIFIC', 'vn_venue_arena_barueri', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2019-08-24 16:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Superesportes', 'superesportes_sb2019_r18', 'https://www.superesportes.com.br/campeonatos/2019/brasileirao/serie-b/', 'HIGH', null),
  ('vn_superesportes_sb2019_r19', 2019, '2019-08-27', '19:15:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2019', 'R19', 'CONFIRMED', 'Cuiabá', true, false, 'Vila Nova', 'Cuiabá', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Olímpico Pedro Ludovico Teixeira', 'MATCH_SPECIFIC', 'vn_venue_olimpico', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2019-08-27 19:15:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Superesportes', 'superesportes_sb2019_r19', 'https://www.superesportes.com.br/campeonatos/2019/brasileirao/serie-b/', 'HIGH', null),
  ('vn_superesportes_sb2019_r20', 2019, '2019-08-30', '19:15:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2019', 'R20', 'CONFIRMED', 'Paraná', false, false, 'Paraná', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Durival Britto e Silva', 'MATCH_SPECIFIC', 'vn_venue_durival_britto', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2019-08-30 19:15:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Superesportes', 'superesportes_sb2019_r20', 'https://www.superesportes.com.br/campeonatos/2019/brasileirao/serie-b/', 'HIGH', null),
  ('vn_superesportes_sb2019_r21', 2019, '2019-09-03', '19:15:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2019', 'R21', 'CONFIRMED', 'Vitória', true, false, 'Vila Nova', 'Vitória', 0, 2, 0, 2, '0–2', 'LOSS', 'Estádio Olímpico Pedro Ludovico Teixeira', 'MATCH_SPECIFIC', 'vn_venue_olimpico', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2019-09-03 19:15:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Superesportes', 'superesportes_sb2019_r21', 'https://www.superesportes.com.br/campeonatos/2019/brasileirao/serie-b/', 'HIGH', null),
  ('vn_superesportes_sb2019_r22', 2019, '2019-09-12', '21:30:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2019', 'R22', 'CONFIRMED', 'Ponte Preta', false, false, 'Ponte Preta', 'Vila Nova', 0, 1, 1, 0, '0–1', 'WIN', 'Estádio Moisés Lucarelli', 'MATCH_SPECIFIC', 'vn_venue_moises_lucarelli', 'quinta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2019-09-12 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Superesportes', 'superesportes_sb2019_r22', 'https://www.superesportes.com.br/campeonatos/2019/brasileirao/serie-b/', 'HIGH', null),
  ('vn_superesportes_sb2019_r23', 2019, '2019-09-17', '19:15:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2019', 'R23', 'CONFIRMED', 'Botafogo-SP', true, false, 'Vila Nova', 'Botafogo-SP', 0, 2, 0, 2, '0–2', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2019-09-17 19:15:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Superesportes', 'superesportes_sb2019_r23', 'https://www.superesportes.com.br/campeonatos/2019/brasileirao/serie-b/', 'HIGH', null),
  ('vn_superesportes_sb2019_r24', 2019, '2019-09-24', '20:30:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2019', 'R24', 'CONFIRMED', 'CRB', true, false, 'Vila Nova', 'CRB', 2, 2, 2, 2, '2–2', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2019-09-24 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Superesportes', 'superesportes_sb2019_r24', 'https://www.superesportes.com.br/campeonatos/2019/brasileirao/serie-b/', 'HIGH', null),
  ('vn_superesportes_sb2019_r25', 2019, '2019-09-27', '19:15:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2019', 'R25', 'CONFIRMED', 'Londrina', false, false, 'Londrina', 'Vila Nova', 0, 1, 1, 0, '0–1', 'WIN', 'Estádio do Café', 'MATCH_SPECIFIC', 'vn_venue_estadio_cafe', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2019-09-27 19:15:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Superesportes', 'superesportes_sb2019_r25', 'https://www.superesportes.com.br/campeonatos/2019/brasileirao/serie-b/', 'HIGH', null),
  ('vn_superesportes_sb2019_r26', 2019, '2019-10-01', '19:15:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2019', 'R26', 'CONFIRMED', 'Criciúma', true, false, 'Vila Nova', 'Criciúma', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2019-10-01 19:15:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Superesportes', 'superesportes_sb2019_r26', 'https://www.superesportes.com.br/campeonatos/2019/brasileirao/serie-b/', 'HIGH', null),
  ('vn_superesportes_sb2019_r27', 2019, '2019-10-07', '20:00:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2019', 'R27', 'CONFIRMED', 'São Bento', false, false, 'São Bento', 'Vila Nova', 3, 1, 1, 3, '3–1', 'LOSS', 'Estádio Municipal Walter Ribeiro', 'MATCH_SPECIFIC', 'vn_venue_walter_ribeiro', 'segunda-feira', 'WEEKDAY', 'NIGHT', (timestamp '2019-10-07 20:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Superesportes', 'superesportes_sb2019_r27', 'https://www.superesportes.com.br/campeonatos/2019/brasileirao/serie-b/', 'HIGH', null),
  ('vn_superesportes_sb2019_r28', 2019, '2019-10-11', '19:15:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2019', 'R28', 'CONFIRMED', 'Atlético-GO', true, false, 'Vila Nova', 'Atlético-GO', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2019-10-11 19:15:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Superesportes', 'superesportes_sb2019_r28', 'https://www.superesportes.com.br/campeonatos/2019/brasileirao/serie-b/', 'HIGH', null),
  ('vn_superesportes_sb2019_r29', 2019, '2019-10-15', '20:30:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2019', 'R29', 'CONFIRMED', 'América-MG', false, false, 'América-MG', 'Vila Nova', 2, 0, 0, 2, '2–0', 'LOSS', 'Estádio Raimundo Sampaio', 'MATCH_SPECIFIC', 'vn_venue_independ_ncia', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2019-10-15 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Superesportes', 'superesportes_sb2019_r29', 'https://www.superesportes.com.br/campeonatos/2019/brasileirao/serie-b/', 'HIGH', null),
  ('vn_superesportes_sb2019_r30', 2019, '2019-10-19', '16:30:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2019', 'R30', 'CONFIRMED', 'Coritiba', true, false, 'Vila Nova', 'Coritiba', 2, 2, 2, 2, '2–2', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2019-10-19 16:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Superesportes', 'superesportes_sb2019_r30', 'https://www.superesportes.com.br/campeonatos/2019/brasileirao/serie-b/', 'HIGH', null),
  ('vn_superesportes_sb2019_r31', 2019, '2019-10-25', '21:30:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2019', 'R31', 'CONFIRMED', 'Bragantino', false, false, 'Bragantino', 'Vila Nova', 3, 1, 1, 3, '3–1', 'LOSS', 'Estádio Nabi Abi Chedid', 'MATCH_SPECIFIC', 'vn_venue_nabi_abi_chedid', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2019-10-25 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Superesportes', 'superesportes_sb2019_r31', 'https://www.superesportes.com.br/campeonatos/2019/brasileirao/serie-b/', 'HIGH', null),
  ('vn_superesportes_sb2019_r32', 2019, '2019-10-29', '19:15:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2019', 'R32', 'CONFIRMED', 'Brasil de Pelotas', true, false, 'Vila Nova', 'Brasil de Pelotas', 0, 2, 0, 2, '0–2', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2019-10-29 19:15:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Superesportes', 'superesportes_sb2019_r32', 'https://www.superesportes.com.br/campeonatos/2019/brasileirao/serie-b/', 'HIGH', null),
  ('vn_superesportes_sb2019_r33', 2019, '2019-11-05', '20:30:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2019', 'R33', 'CONFIRMED', 'Figueirense', false, false, 'Figueirense', 'Vila Nova', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Orlando Scarpelli', 'MATCH_SPECIFIC', 'vn_venue_orlando_scarpelli', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2019-11-05 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Superesportes', 'superesportes_sb2019_r33', 'https://www.superesportes.com.br/campeonatos/2019/brasileirao/serie-b/', 'HIGH', null),
  ('vn_superesportes_sb2019_r34', 2019, '2019-11-08', '20:30:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2019', 'R34', 'CONFIRMED', 'Operário-PR', true, false, 'Vila Nova', 'Operário-PR', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2019-11-08 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Superesportes', 'superesportes_sb2019_r34', 'https://www.superesportes.com.br/campeonatos/2019/brasileirao/serie-b/', 'HIGH', null),
  ('vn_superesportes_sb2019_r35', 2019, '2019-11-13', '19:15:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2019', 'R35', 'CONFIRMED', 'Guarani', true, false, 'Vila Nova', 'Guarani', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2019-11-13 19:15:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Superesportes', 'superesportes_sb2019_r35', 'https://www.superesportes.com.br/campeonatos/2019/brasileirao/serie-b/', 'HIGH', null),
  ('vn_superesportes_sb2019_r36', 2019, '2019-11-17', '16:00:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2019', 'R36', 'CONFIRMED', 'Sport', false, false, 'Sport', 'Vila Nova', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Adelmar da Costa Carvalho', 'MATCH_SPECIFIC', 'vn_venue_ilha_do_retiro', 'domingo', 'WEEKEND', 'AFTERNOON', (timestamp '2019-11-17 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Superesportes', 'superesportes_sb2019_r36', 'https://www.superesportes.com.br/campeonatos/2019/brasileirao/serie-b/', 'HIGH', null),
  ('vn_superesportes_sb2019_r37', 2019, '2019-11-20', '19:15:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2019', 'R37', 'CONFIRMED', 'Oeste', true, false, 'Vila Nova', 'Oeste', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2019-11-20 19:15:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Superesportes', 'superesportes_sb2019_r37', 'https://www.superesportes.com.br/campeonatos/2019/brasileirao/serie-b/', 'HIGH', null),
  ('vn_superesportes_sb2019_r38', 2019, '2019-11-30', '16:30:00', 'FINISHED', 'Campeonato Brasileiro Série B', 'BRASILEIRO_B', 'Série B 2019', 'R38', 'CONFIRMED', 'Cuiabá', false, false, 'Cuiabá', 'Vila Nova', 1, 2, 2, 1, '1–2', 'WIN', 'Arena Pantanal', 'MATCH_SPECIFIC', 'vn_venue_arena_pantanal', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2019-11-30 16:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Superesportes', 'superesportes_sb2019_r38', 'https://www.superesportes.com.br/campeonatos/2019/brasileirao/serie-b/', 'HIGH', null)
on conflict (id) do update set
    season = excluded.season,
    match_date = excluded.match_date,
    match_time = excluded.match_time,
    status = excluded.status,
    competition = excluded.competition,
    competition_code = excluded.competition_code,
    competition_edition = excluded.competition_edition,
    round = excluded.round,
    phase_status = excluded.phase_status,
    opponent = excluded.opponent,
    club_is_home = excluded.club_is_home,
    neutral_site = excluded.neutral_site,
    home_team = excluded.home_team,
    away_team = excluded.away_team,
    home_score = excluded.home_score,
    away_score = excluded.away_score,
    club_score = excluded.club_score,
    opponent_score = excluded.opponent_score,
    score_display = excluded.score_display,
    outcome = excluded.outcome,
    stadium = excluded.stadium,
    stadium_status = excluded.stadium_status,
    venue_id = excluded.venue_id,
    weekday = excluded.weekday,
    day_type = excluded.day_type,
    day_period = excluded.day_period,
    kickoff_at = excluded.kickoff_at,
    display_timezone = excluded.display_timezone,
    date_precision = excluded.date_precision,
    source_provider = excluded.source_provider,
    source_match_id = excluded.source_match_id,
    source_url = excluded.source_url,
    source_confidence = excluded.source_confidence,
    data_notes = excluded.data_notes,
    updated_at = now();

do $$
declare v_orphans int;
begin
  select count(*) into v_orphans from public.passport_matches
   where season = 2019 and stadium is not null and venue_id is null;
  if v_orphans > 0 then
    raise exception 'ha % partidas de 2019 com estadio sem venue_id -- rode vilanova_passport_venues_seed.sql antes', v_orphans;
  end if;
end $$;
