-- Passaporte do Vila Nova — temporada 2017. GERADO por
-- `node tooling/vilanova_passport/generate_passport_sql.mjs` a partir de
-- docs/vila_nova_data/passport/passport_2017.json — não edite à mão.
--
-- Rode no projeto Supabase do VILA NOVA — NUNCA no do Goiás nem no do Bragantino.
-- Ordem: vilanova_passport_infra.sql -> vilanova_passport_venues_seed.sql -> ESTE.
-- Idempotente (ON CONFLICT DO UPDATE): reexecutar atualiza, nunca duplica, e
-- não encosta em presença de usuário. 58 partidas.

do $$
begin
  if not exists (select 1 from public.clubs where slug = 'vilanova')
     or exists (select 1 from public.clubs where slug <> 'vilanova') then
    raise exception 'este nao e o projeto Supabase do Vila Nova -- PARE';
  end if;
end $$;

insert into public.passport_matches (
  id, season, match_date, match_time, status, competition, competition_code, competition_edition, round, phase_status, opponent, club_is_home, neutral_site, home_team, away_team, home_score, away_score, club_score, opponent_score, score_display, outcome, stadium, stadium_status, venue_id, weekday, day_type, day_period, kickoff_at, display_timezone, date_precision, source_provider, source_match_id, source_url, source_confidence, data_notes
) values
  ('vn_eg_go2017_r01', 2017, '2017-01-28', '16:30:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2017', 'R1', 'CONFIRMED', 'Atlético-GO', false, false, 'Atlético-GO', 'Vila Nova', 0, 1, 1, 0, '0–1', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2017-01-28 16:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'r01', 'https://esportegoiano.com.br/campeonato-goiano-de-futebol-2017/', 'HIGH', null),
  ('vn_eg_go2017_r02', 2017, '2017-02-02', '20:30:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2017', 'R2', 'CONFIRMED', 'Anápolis', true, false, 'Vila Nova', 'Anápolis', 3, 0, 3, 0, '3–0', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'quinta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2017-02-02 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'r02', 'https://esportegoiano.com.br/campeonato-goiano-de-futebol-2017/', 'HIGH', null),
  ('vn_eg_go2017_r03', 2017, '2017-02-06', '20:00:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2017', 'R3', 'CONFIRMED', 'Goianésia', true, false, 'Vila Nova', 'Goianésia', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'segunda-feira', 'WEEKDAY', 'NIGHT', (timestamp '2017-02-06 20:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'r03', 'https://esportegoiano.com.br/campeonato-goiano-de-futebol-2017/', 'HIGH', null),
  ('vn_eg_go2017_r04', 2017, '2017-02-09', '20:30:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2017', 'R4', 'CONFIRMED', 'Aparecidense', false, false, 'Aparecidense', 'Vila Nova', 1, 2, 2, 1, '1–2', 'WIN', 'Estádio Aníbal Batista de Toledo', 'MATCH_SPECIFIC', 'vn_venue_anibal_toledo', 'quinta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2017-02-09 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'r04', 'https://esportegoiano.com.br/campeonato-goiano-de-futebol-2017/', 'HIGH', null),
  ('vn_eg_go2017_r05', 2017, '2017-02-12', '17:00:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2017', 'R5', 'CONFIRMED', 'Rio Verde', false, false, 'Rio Verde', 'Vila Nova', 3, 3, 3, 3, '3–3', 'DRAW', 'Estádio Mozart Veloso do Carmo', 'MATCH_SPECIFIC', 'vn_venue_mozart_veloso_do_carmo', 'domingo', 'WEEKEND', 'AFTERNOON', (timestamp '2017-02-12 17:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'r05', 'https://esportegoiano.com.br/campeonato-goiano-de-futebol-2017/', 'HIGH', null),
  ('vn_cbf_cdb2017_040', 2017, '2017-02-16', '22:30:00', 'FINISHED', 'Copa do Brasil', 'COPA_DO_BRASIL', 'Copa do Brasil 2017', '1ª fase', 'CONFIRMED', 'Fast Clube', false, false, 'Fast Clube', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', 'Arena da Amazônia', 'MATCH_SPECIFIC', 'vn_venue_arena_amazonia', 'quinta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2017-02-16 22:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '040', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/CdB_2017_games.json', 'HIGH', null),
  ('vn_eg_go2017_r06', 2017, '2017-02-19', '17:00:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2017', 'R6', 'CONFIRMED', 'Atlético-GO', true, false, 'Vila Nova', 'Atlético-GO', 0, 1, 0, 1, '0–1', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'domingo', 'WEEKEND', 'AFTERNOON', (timestamp '2017-02-19 17:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'r06', 'https://esportegoiano.com.br/campeonato-goiano-de-futebol-2017/', 'HIGH', null),
  ('vn_eg_go2017_r07', 2017, '2017-02-25', '16:30:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2017', 'R7', 'CONFIRMED', 'Anápolis', false, false, 'Anápolis', 'Vila Nova', 0, 1, 1, 0, '0–1', 'WIN', 'Estádio Jonas Duarte', 'MATCH_SPECIFIC', 'vn_venue_jonas_duarte', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2017-02-25 16:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'r07', 'https://esportegoiano.com.br/campeonato-goiano-de-futebol-2017/', 'HIGH', null),
  ('vn_cbf_cdb2017_060', 2017, '2017-03-01', '21:45:00', 'FINISHED', 'Copa do Brasil', 'COPA_DO_BRASIL', 'Copa do Brasil 2017', '2ª fase', 'CONFIRMED', 'Vasco da Gama', true, false, 'Vila Nova', 'Vasco da Gama', 1, 2, 1, 2, '1–2', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2017-03-01 21:45:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '060', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/CdB_2017_games.json', 'HIGH', null),
  ('vn_eg_go2017_r08', 2017, '2017-03-05', '16:00:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2017', 'R8', 'CONFIRMED', 'Rio Verde', true, false, 'Vila Nova', 'Rio Verde', 2, 1, 2, 1, '2–1', 'WIN', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'domingo', 'WEEKEND', 'AFTERNOON', (timestamp '2017-03-05 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'r08', 'https://esportegoiano.com.br/campeonato-goiano-de-futebol-2017/', 'HIGH', null),
  ('vn_eg_go2017_r09', 2017, '2017-03-12', '16:00:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2017', 'R9', 'CONFIRMED', 'Goianésia', false, false, 'Goianésia', 'Vila Nova', 5, 1, 1, 5, '5–1', 'LOSS', 'Estádio Valdeir José de Oliveira', 'MATCH_SPECIFIC', 'vn_venue_valdeir_jose', 'domingo', 'WEEKEND', 'AFTERNOON', (timestamp '2017-03-12 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'r09', 'https://esportegoiano.com.br/campeonato-goiano-de-futebol-2017/', 'HIGH', null),
  ('vn_eg_go2017_r10', 2017, '2017-03-18', '16:00:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2017', 'R10', 'CONFIRMED', 'Aparecidense', true, false, 'Vila Nova', 'Aparecidense', 0, 1, 0, 1, '0–1', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2017-03-18 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'r10', 'https://esportegoiano.com.br/campeonato-goiano-de-futebol-2017/', 'HIGH', null),
  ('vn_eg_go2017_r11', 2017, '2017-03-22', '19:30:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2017', 'R11', 'CONFIRMED', 'Iporá', false, false, 'Iporá', 'Vila Nova', 0, 1, 1, 0, '0–1', 'WIN', 'Estádio Francisco José Ferreira', 'MATCH_SPECIFIC', 'vn_venue_francisco_jose_ferreira', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2017-03-22 19:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'r11', 'https://esportegoiano.com.br/campeonato-goiano-de-futebol-2017/', 'HIGH', null),
  ('vn_eg_go2017_r12', 2017, '2017-03-26', '16:00:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2017', 'R12', 'CONFIRMED', 'Goiás', true, false, 'Vila Nova', 'Goiás', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'domingo', 'WEEKEND', 'AFTERNOON', (timestamp '2017-03-26 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'r12', 'https://esportegoiano.com.br/campeonato-goiano-de-futebol-2017/', 'HIGH', null),
  ('vn_eg_go2017_r14', 2017, '2017-04-02', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2017', 'R14', 'CONFIRMED', 'Itumbiara', true, false, 'Vila Nova', 'Itumbiara', 2, 3, 2, 3, '2–3', 'LOSS', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'Esporte Goiano', 'r14', 'https://esportegoiano.com.br/campeonato-goiano-de-futebol-2017/', 'HIGH', null),
  ('vn_eg_go2017_r15', 2017, '2017-04-09', '16:00:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2017', 'R15', 'CONFIRMED', 'CRAC', false, false, 'CRAC', 'Vila Nova', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Genervino da Fonseca', 'MATCH_SPECIFIC', 'vn_venue_genervino_fonseca', 'domingo', 'WEEKEND', 'AFTERNOON', (timestamp '2017-04-09 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'r15', 'https://esportegoiano.com.br/campeonato-goiano-de-futebol-2017/', 'HIGH', null),
  ('vn_eg_go2017_sf1', 2017, '2017-04-17', '20:00:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2017', 'Semifinal - ida', 'CONFIRMED', 'Aparecidense', true, false, 'Vila Nova', 'Aparecidense', 2, 1, 2, 1, '2–1', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'segunda-feira', 'WEEKDAY', 'NIGHT', (timestamp '2017-04-17 20:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'sf1', 'https://esportegoiano.com.br/campeonato-goiano-de-futebol-2017/', 'HIGH', null),
  ('vn_eg_go2017_sf2', 2017, '2017-04-24', '20:00:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2017', 'Semifinal - volta', 'CONFIRMED', 'Aparecidense', false, false, 'Aparecidense', 'Vila Nova', 2, 2, 2, 2, '2–2', 'DRAW', 'Estádio Aníbal Batista de Toledo', 'MATCH_SPECIFIC', 'vn_venue_anibal_toledo', 'segunda-feira', 'WEEKDAY', 'NIGHT', (timestamp '2017-04-24 20:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'sf2', 'https://esportegoiano.com.br/campeonato-goiano-de-futebol-2017/', 'HIGH', null),
  ('vn_eg_go2017_f1', 2017, '2017-04-30', '16:00:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2017', 'Final - ida', 'CONFIRMED', 'Goiás', true, false, 'Vila Nova', 'Goiás', 0, 3, 0, 3, '0–3', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'domingo', 'WEEKEND', 'AFTERNOON', (timestamp '2017-04-30 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'f1', 'https://esportegoiano.com.br/campeonato-goiano-de-futebol-2017/', 'HIGH', null),
  ('vn_eg_go2017_f2', 2017, '2017-05-07', '16:00:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2017', 'Final - volta', 'CONFIRMED', 'Goiás', false, false, 'Goiás', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'domingo', 'WEEKEND', 'AFTERNOON', (timestamp '2017-05-07 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'f2', 'https://esportegoiano.com.br/campeonato-goiano-de-futebol-2017/', 'HIGH', null),
  ('vn_cbf_sb2017_008', 2017, '2017-05-13', '16:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2017', 'R01', 'CONFIRMED', 'Boa Esporte', false, false, 'Boa Esporte', 'Vila Nova', 0, 1, 1, 0, '0–1', 'WIN', 'Estádio Dilzon Luiz de Melo', 'MATCH_SPECIFIC', 'vn_venue_dilzon_luiz_de_melo', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2017-05-13 16:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '008', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2017_games.json', 'HIGH', null),
  ('vn_cbf_sb2017_014', 2017, '2017-05-19', '20:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2017', 'R02', 'CONFIRMED', 'Juventude', true, false, 'Vila Nova', 'Juventude', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2017-05-19 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '014', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2017_games.json', 'HIGH', null),
  ('vn_cbf_sb2017_021', 2017, '2017-05-27', '16:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2017', 'R03', 'CONFIRMED', 'ABC', false, false, 'ABC', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', 'Estádio Maria Lamas Farache', 'MATCH_SPECIFIC', 'vn_venue_frasqueirao', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2017-05-27 16:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '021', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2017_games.json', 'HIGH', null),
  ('vn_cbf_sb2017_034', 2017, '2017-06-03', '16:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2017', 'R04', 'CONFIRMED', 'Guarani', true, false, 'Vila Nova', 'Guarani', 3, 1, 3, 1, '3–1', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2017-06-03 16:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '034', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2017_games.json', 'HIGH', null),
  ('vn_cbf_sb2017_049', 2017, '2017-06-06', '21:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2017', 'R05', 'CONFIRMED', 'Luverdense', false, false, 'Luverdense', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', 'Arena Pantanal', 'MATCH_SPECIFIC', 'vn_venue_arena_pantanal', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2017-06-06 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '049', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2017_games.json', 'HIGH', null),
  ('vn_cbf_sb2017_054', 2017, '2017-06-09', '20:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2017', 'R06', 'CONFIRMED', 'América-MG', true, false, 'Vila Nova', 'América-MG', 2, 0, 2, 0, '2–0', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2017-06-09 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '054', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2017_games.json', 'HIGH', null),
  ('vn_cbf_sb2017_070', 2017, '2017-06-13', '20:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2017', 'R07', 'CONFIRMED', 'CRB', false, false, 'CRB', 'Vila Nova', 1, 2, 2, 1, '1–2', 'WIN', 'Estádio Rei Pelé', 'MATCH_SPECIFIC', 'vn_venue_rei_pele', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2017-06-13 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '070', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2017_games.json', 'HIGH', null),
  ('vn_cbf_sb2017_076', 2017, '2017-06-17', '19:00:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2017', 'R08', 'CONFIRMED', 'Brasil de Pelotas', false, false, 'Brasil de Pelotas', 'Vila Nova', 3, 0, 0, 3, '3–0', 'LOSS', 'Estádio Bento Mendes de Freitas', 'MATCH_SPECIFIC', 'vn_venue_bento_mendes_freitas', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2017-06-17 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '076', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2017_games.json', 'HIGH', null),
  ('vn_cbf_sb2017_084', 2017, '2017-06-20', '21:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2017', 'R09', 'CONFIRMED', 'Ceará', true, false, 'Vila Nova', 'Ceará', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2017-06-20 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '084', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2017_games.json', 'HIGH', null),
  ('vn_cbf_sb2017_094', 2017, '2017-06-24', '16:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2017', 'R10', 'CONFIRMED', 'Goiás', false, false, 'Goiás', 'Vila Nova', 0, 2, 2, 0, '0–2', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2017-06-24 16:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '094', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2017_games.json', 'HIGH', null),
  ('vn_cbf_sb2017_104', 2017, '2017-06-30', '20:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2017', 'R11', 'CONFIRMED', 'Criciúma', true, false, 'Vila Nova', 'Criciúma', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Olímpico Pedro Ludovico Teixeira', 'MATCH_SPECIFIC', 'vn_venue_olimpico', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2017-06-30 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '104', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2017_games.json', 'HIGH', null),
  ('vn_cbf_sb2017_115', 2017, '2017-07-08', '19:00:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2017', 'R12', 'CONFIRMED', 'Oeste', false, false, 'Oeste', 'Vila Nova', 2, 2, 2, 2, '2–2', 'DRAW', 'Arena Barueri', 'MATCH_SPECIFIC', 'vn_venue_arena_barueri', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2017-07-08 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '115', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2017_games.json', 'HIGH', null),
  ('vn_cbf_sb2017_124', 2017, '2017-07-11', '20:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2017', 'R13', 'CONFIRMED', 'Paraná', true, false, 'Vila Nova', 'Paraná', 3, 2, 3, 2, '3–2', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2017-07-11 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '124', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2017_games.json', 'HIGH', null),
  ('vn_cbf_sb2017_134', 2017, '2017-07-15', '16:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2017', 'R14', 'CONFIRMED', 'Paysandu', true, false, 'Vila Nova', 'Paysandu', 1, 2, 1, 2, '1–2', 'LOSS', 'Estádio Municipal Juscelino Kubitschek de Oliveira', 'MATCH_SPECIFIC', 'vn_venue_jk_itumbiara', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2017-07-15 16:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '134', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2017_games.json', 'HIGH', null),
  ('vn_cbf_sb2017_142', 2017, '2017-07-18', '20:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2017', 'R15', 'CONFIRMED', 'Santa Cruz', false, false, 'Santa Cruz', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', 'Arena de Pernambuco', 'MATCH_SPECIFIC', 'vn_venue_arena_pernambuco', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2017-07-18 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '142', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2017_games.json', 'HIGH', null),
  ('vn_cbf_sb2017_154', 2017, '2017-07-22', '16:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2017', 'R16', 'CONFIRMED', 'Internacional', true, false, 'Vila Nova', 'Internacional', 2, 1, 2, 1, '2–1', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2017-07-22 16:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '154', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2017_games.json', 'HIGH', null),
  ('vn_cbf_sb2017_163', 2017, '2017-07-29', '16:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2017', 'R17', 'CONFIRMED', 'Figueirense', false, false, 'Figueirense', 'Vila Nova', 0, 1, 1, 0, '0–1', 'WIN', 'Estádio Orlando Scarpelli', 'MATCH_SPECIFIC', 'vn_venue_orlando_scarpelli', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2017-07-29 16:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '163', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2017_games.json', 'HIGH', null),
  ('vn_cbf_sb2017_174', 2017, '2017-08-01', '20:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2017', 'R18', 'CONFIRMED', 'Náutico', true, false, 'Vila Nova', 'Náutico', 0, 1, 0, 1, '0–1', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2017-08-01 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '174', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2017_games.json', 'HIGH', null),
  ('vn_cbf_sb2017_187', 2017, '2017-08-07', '20:00:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2017', 'R19', 'CONFIRMED', 'Londrina', false, false, 'Londrina', 'Vila Nova', 0, 1, 1, 0, '0–1', 'WIN', 'Estádio do Café', 'MATCH_SPECIFIC', 'vn_venue_estadio_cafe', 'segunda-feira', 'WEEKDAY', 'NIGHT', (timestamp '2017-08-07 20:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '187', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2017_games.json', 'HIGH', null),
  ('vn_cbf_sb2017_194', 2017, '2017-08-11', '20:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2017', 'R20', 'CONFIRMED', 'Boa Esporte', true, false, 'Vila Nova', 'Boa Esporte', 1, 0, 1, 0, '1–0', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2017-08-11 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '194', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2017_games.json', 'HIGH', null),
  ('vn_cbf_sb2017_210', 2017, '2017-08-18', '19:15:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2017', 'R21', 'CONFIRMED', 'Juventude', false, false, 'Juventude', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', 'Estádio Alfredo Jaconi', 'MATCH_SPECIFIC', 'vn_venue_alfredo_jaconi', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2017-08-18 19:15:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '210', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2017_games.json', 'HIGH', null),
  ('vn_cbf_sb2017_214', 2017, '2017-08-26', '16:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2017', 'R22', 'CONFIRMED', 'ABC', true, false, 'Vila Nova', 'ABC', 2, 0, 2, 0, '2–0', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2017-08-26 16:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '214', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2017_games.json', 'HIGH', null),
  ('vn_cbf_sb2017_221', 2017, '2017-09-04', '20:00:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2017', 'R23', 'CONFIRMED', 'Guarani', false, false, 'Guarani', 'Vila Nova', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Brinco de Ouro da Princesa', 'MATCH_SPECIFIC', 'vn_venue_brinco_ouro', 'segunda-feira', 'WEEKDAY', 'NIGHT', (timestamp '2017-09-04 20:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '221', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2017_games.json', 'HIGH', null),
  ('vn_cbf_sb2017_234', 2017, '2017-09-16', '16:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2017', 'R24', 'CONFIRMED', 'Luverdense', true, false, 'Vila Nova', 'Luverdense', 2, 1, 2, 1, '2–1', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2017-09-16 16:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '234', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2017_games.json', 'HIGH', null),
  ('vn_cbf_sb2017_241', 2017, '2017-09-19', '19:15:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2017', 'R25', 'CONFIRMED', 'América-MG', false, false, 'América-MG', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', 'Estádio Raimundo Sampaio', 'MATCH_SPECIFIC', 'vn_venue_independ_ncia', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2017-09-19 19:15:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '241', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2017_games.json', 'HIGH', null),
  ('vn_cbf_sb2017_254', 2017, '2017-09-26', '20:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2017', 'R26', 'CONFIRMED', 'CRB', true, false, 'Vila Nova', 'CRB', 3, 0, 3, 0, '3–0', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2017-09-26 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '254', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2017_games.json', 'HIGH', null),
  ('vn_cbf_sb2017_266', 2017, '2017-09-30', '16:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2017', 'R27', 'CONFIRMED', 'Brasil de Pelotas', true, false, 'Vila Nova', 'Brasil de Pelotas', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2017-09-30 16:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '266', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2017_games.json', 'HIGH', null),
  ('vn_cbf_sb2017_271', 2017, '2017-10-03', '19:15:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2017', 'R28', 'CONFIRMED', 'Ceará', false, false, 'Ceará', 'Vila Nova', 2, 0, 0, 2, '2–0', 'LOSS', 'Estádio Governador Plácido Castelo', 'MATCH_SPECIFIC', 'vn_venue_castelao', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2017-10-03 19:15:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '271', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2017_games.json', 'HIGH', null),
  ('vn_cbf_sb2017_289', 2017, '2017-10-14', '16:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2017', 'R29', 'CONFIRMED', 'Goiás', true, false, 'Vila Nova', 'Goiás', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2017-10-14 16:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '289', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2017_games.json', 'HIGH', null),
  ('vn_cbf_sb2017_296', 2017, '2017-10-17', '20:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2017', 'R30', 'CONFIRMED', 'Criciúma', false, false, 'Criciúma', 'Vila Nova', 0, 1, 1, 0, '0–1', 'WIN', 'Estádio Heriberto Hülse', 'MATCH_SPECIFIC', 'vn_venue_heriberto_h_lse', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2017-10-17 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '296', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2017_games.json', 'HIGH', null),
  ('vn_cbf_sb2017_306', 2017, '2017-10-21', '17:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2017', 'R31', 'CONFIRMED', 'Oeste', true, false, 'Vila Nova', 'Oeste', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2017-10-21 17:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '306', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2017_games.json', 'HIGH', null),
  ('vn_cbf_sb2017_312', 2017, '2017-10-24', '21:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2017', 'R32', 'CONFIRMED', 'Paraná', false, false, 'Paraná', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', 'Estádio Durival Britto e Silva', 'MATCH_SPECIFIC', 'vn_venue_durival_britto', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2017-10-24 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '312', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2017_games.json', 'HIGH', null),
  ('vn_cbf_sb2017_325', 2017, '2017-11-03', '21:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2017', 'R33', 'CONFIRMED', 'Paysandu', false, false, 'Paysandu', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', 'Curuzu', 'MATCH_SPECIFIC', 'vn_venue_curuzu', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2017-11-03 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '325', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2017_games.json', 'HIGH', null),
  ('vn_cbf_sb2017_338', 2017, '2017-11-07', '19:15:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2017', 'R34', 'CONFIRMED', 'Santa Cruz', true, false, 'Vila Nova', 'Santa Cruz', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2017-11-07 19:15:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '338', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2017_games.json', 'HIGH', null),
  ('vn_cbf_sb2017_344', 2017, '2017-11-11', '16:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2017', 'R35', 'CONFIRMED', 'Internacional', false, false, 'Internacional', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio José Pinheiro Borda', 'MATCH_SPECIFIC', 'vn_venue_jose_pinheiro_borda', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2017-11-11 16:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '344', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2017_games.json', 'HIGH', null),
  ('vn_cbf_sb2017_354', 2017, '2017-11-14', '20:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2017', 'R36', 'CONFIRMED', 'Figueirense', true, false, 'Vila Nova', 'Figueirense', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2017-11-14 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '354', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2017_games.json', 'HIGH', null),
  ('vn_cbf_sb2017_367', 2017, '2017-11-18', '17:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2017', 'R37', 'CONFIRMED', 'Náutico', false, false, 'Náutico', 'Vila Nova', 1, 2, 2, 1, '1–2', 'WIN', 'Estádio José do Rego Maciel', 'MATCH_SPECIFIC', 'vn_venue_arruda', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2017-11-18 17:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '367', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2017_games.json', 'HIGH', null),
  ('vn_cbf_sb2017_374', 2017, '2017-11-25', '17:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2017', 'R38', 'CONFIRMED', 'Londrina', true, false, 'Vila Nova', 'Londrina', 0, 1, 0, 1, '0–1', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2017-11-25 17:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '374', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2017_games.json', 'HIGH', null)
on conflict (id) do update set
    season = excluded.season,
    match_date = excluded.match_date,
    match_time = excluded.match_time,
    status = excluded.status,
    competition = excluded.competition,
    competition_code = excluded.competition_code,
    competition_edition = excluded.competition_edition,
    round = excluded.round,
    phase_status = excluded.phase_status,
    opponent = excluded.opponent,
    club_is_home = excluded.club_is_home,
    neutral_site = excluded.neutral_site,
    home_team = excluded.home_team,
    away_team = excluded.away_team,
    home_score = excluded.home_score,
    away_score = excluded.away_score,
    club_score = excluded.club_score,
    opponent_score = excluded.opponent_score,
    score_display = excluded.score_display,
    outcome = excluded.outcome,
    stadium = excluded.stadium,
    stadium_status = excluded.stadium_status,
    venue_id = excluded.venue_id,
    weekday = excluded.weekday,
    day_type = excluded.day_type,
    day_period = excluded.day_period,
    kickoff_at = excluded.kickoff_at,
    display_timezone = excluded.display_timezone,
    date_precision = excluded.date_precision,
    source_provider = excluded.source_provider,
    source_match_id = excluded.source_match_id,
    source_url = excluded.source_url,
    source_confidence = excluded.source_confidence,
    data_notes = excluded.data_notes,
    updated_at = now();

do $$
declare v_orphans int;
begin
  select count(*) into v_orphans from public.passport_matches
   where season = 2017 and stadium is not null and venue_id is null;
  if v_orphans > 0 then
    raise exception 'ha % partidas de 2017 com estadio sem venue_id -- rode vilanova_passport_venues_seed.sql antes', v_orphans;
  end if;
end $$;
