-- Passaporte do Vila Nova — temporada 2018. GERADO por
-- `node tooling/vilanova_passport/generate_passport_sql.mjs` a partir de
-- docs/vila_nova_data/passport/passport_2018.json — não edite à mão.
--
-- Rode no projeto Supabase do VILA NOVA — NUNCA no do Goiás nem no do Bragantino.
-- Ordem: vilanova_passport_infra.sql -> vilanova_passport_venues_seed.sql -> ESTE.
-- Idempotente (ON CONFLICT DO UPDATE): reexecutar atualiza, nunca duplica, e
-- não encosta em presença de usuário. 58 partidas.

do $$
begin
  if not exists (select 1 from public.clubs where slug = 'vilanova')
     or exists (select 1 from public.clubs where slug <> 'vilanova') then
    raise exception 'este nao e o projeto Supabase do Vila Nova -- PARE';
  end if;
end $$;

insert into public.passport_matches (
  id, season, match_date, match_time, status, competition, competition_code, competition_edition, round, phase_status, opponent, club_is_home, neutral_site, home_team, away_team, home_score, away_score, club_score, opponent_score, score_display, outcome, stadium, stadium_status, venue_id, weekday, day_type, day_period, kickoff_at, display_timezone, date_precision, source_provider, source_match_id, source_url, source_confidence, data_notes
) values
  ('vn_eg_go2018_r01', 2018, '2018-01-18', '19:30:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2018', 'R1', 'CONFIRMED', 'Iporá', true, false, 'Vila Nova', 'Iporá', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Olímpico Pedro Ludovico Teixeira', 'MATCH_SPECIFIC', 'vn_venue_olimpico', 'quinta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2018-01-18 19:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'r01', 'https://esportegoiano.com.br/tag/goianao-2018/', 'HIGH', null),
  ('vn_eg_go2018_r02', 2018, '2018-01-21', '17:00:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2018', 'R2', 'CONFIRMED', 'Goiás', false, false, 'Goiás', 'Vila Nova', 0, 1, 1, 0, '0–1', 'WIN', 'Estádio Olímpico Pedro Ludovico Teixeira', 'MATCH_SPECIFIC', 'vn_venue_olimpico', 'domingo', 'WEEKEND', 'AFTERNOON', (timestamp '2018-01-21 17:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'r02', 'https://esportegoiano.com.br/tag/goianao-2018/', 'HIGH', null),
  ('vn_eg_go2018_r03', 2018, '2018-01-24', '20:30:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2018', 'R3', 'CONFIRMED', 'Anapolina', false, false, 'Anapolina', 'Vila Nova', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Jonas Duarte', 'MATCH_SPECIFIC', 'vn_venue_jonas_duarte', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2018-01-24 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'r03', 'https://esportegoiano.com.br/tag/goianao-2018/', 'HIGH', null),
  ('vn_eg_go2018_r04', 2018, '2018-01-27', '17:00:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2018', 'R4', 'CONFIRMED', 'Atlético-GO', true, false, 'Vila Nova', 'Atlético-GO', 2, 1, 2, 1, '2–1', 'WIN', 'Estádio Olímpico Pedro Ludovico Teixeira', 'MATCH_SPECIFIC', 'vn_venue_olimpico', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2018-01-27 17:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'r04', 'https://esportegoiano.com.br/tag/goianao-2018/', 'HIGH', null),
  ('vn_eg_go2018_r05', 2018, '2018-01-31', '20:30:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2018', 'R5', 'CONFIRMED', 'Rio Verde', false, false, 'Rio Verde', 'Vila Nova', 1, 2, 2, 1, '1–2', 'WIN', 'Estádio Mozart Veloso do Carmo', 'MATCH_SPECIFIC', 'vn_venue_mozart_veloso_do_carmo', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2018-01-31 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'r05', 'https://esportegoiano.com.br/tag/goianao-2018/', 'HIGH', null),
  ('vn_eg_go2018_r06', 2018, '2018-02-03', '17:00:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2018', 'R6', 'CONFIRMED', 'Goiás', true, false, 'Vila Nova', 'Goiás', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Olímpico Pedro Ludovico Teixeira', 'MATCH_SPECIFIC', 'vn_venue_olimpico', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2018-02-03 17:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'r06', 'https://esportegoiano.com.br/tag/goianao-2018/', 'HIGH', null),
  ('vn_cbf_cdb2018_040', 2018, '2018-02-07', '22:30:00', 'FINISHED', 'Copa do Brasil', 'COPA_DO_BRASIL', 'Copa do Brasil 2018', '1ª fase', 'CONFIRMED', 'São Raimundo-RR', false, false, 'São Raimundo-RR', 'Vila Nova', 0, 1, 1, 0, '0–1', 'WIN', 'Estádio Raimundo Ribeiro de Souza', 'MATCH_SPECIFIC', 'vn_venue_raimundo_ribeiro_de_souza', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2018-02-07 22:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '040', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/CdB_2018_games.json', 'HIGH', null),
  ('vn_eg_go2018_r07', 2018, '2018-02-10', '16:30:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2018', 'R7', 'CONFIRMED', 'Iporá', false, false, 'Iporá', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Francisco José Ferreira', 'MATCH_SPECIFIC', 'vn_venue_francisco_jose_ferreira', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2018-02-10 16:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'r07', 'https://esportegoiano.com.br/tag/goianao-2018/', 'HIGH', null),
  ('vn_eg_go2018_r08', 2018, '2018-02-15', '19:30:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2018', 'R8', 'CONFIRMED', 'Anapolina', true, false, 'Vila Nova', 'Anapolina', 1, 0, 1, 0, '1–0', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'quinta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2018-02-15 19:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'r08', 'https://esportegoiano.com.br/tag/goianao-2018/', 'HIGH', null),
  ('vn_eg_go2018_r09', 2018, '2018-02-18', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2018', 'R9', 'CONFIRMED', 'Rio Verde', true, false, 'Vila Nova', 'Rio Verde', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'Esporte Goiano', 'r09', 'https://esportegoiano.com.br/tag/goianao-2018/', 'HIGH', null),
  ('vn_cbf_cdb2018_053', 2018, '2018-02-22', '19:15:00', 'FINISHED', 'Copa do Brasil', 'COPA_DO_BRASIL', 'Copa do Brasil 2018', '2ª fase', 'CONFIRMED', 'Joinville', true, false, 'Vila Nova', 'Joinville', 2, 2, 2, 2, '2–2', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'quinta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2018-02-22 19:15:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '053', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/CdB_2018_games.json', 'HIGH', 'Disputa de pênaltis: Vila Nova 4–2 Joinville.'),
  ('vn_eg_go2018_r10', 2018, '2018-02-25', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2018', 'R10', 'CONFIRMED', 'Atlético-GO', false, false, 'Atlético-GO', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'Esporte Goiano', 'r10', 'https://esportegoiano.com.br/tag/goianao-2018/', 'HIGH', null),
  ('vn_cbf_cdb2018_067', 2018, '2018-02-28', '20:30:00', 'FINISHED', 'Copa do Brasil', 'COPA_DO_BRASIL', 'Copa do Brasil 2018', '3ª fase - ida', 'CONFIRMED', 'Ferroviário-CE', false, false, 'Ferroviário-CE', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Presidente Vargas', 'MATCH_SPECIFIC', 'vn_venue_presidente_vargas', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2018-02-28 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '067', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/CdB_2018_games.json', 'HIGH', null),
  ('vn_eg_go2018_r11', 2018, '2018-03-04', '17:00:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2018', 'R11', 'CONFIRMED', 'Aparecidense', true, false, 'Vila Nova', 'Aparecidense', 1, 3, 1, 3, '1–3', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'domingo', 'WEEKEND', 'AFTERNOON', (timestamp '2018-03-04 17:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'r11', 'https://esportegoiano.com.br/tag/goianao-2018/', 'HIGH', null),
  ('vn_eg_go2018_r12', 2018, '2018-03-07', '19:30:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2018', 'R12', 'CONFIRMED', 'Itumbiara', false, false, 'Itumbiara', 'Vila Nova', 0, 1, 1, 0, '0–1', 'WIN', 'Estádio Municipal Juscelino Kubitschek de Oliveira', 'MATCH_SPECIFIC', 'vn_venue_jk_itumbiara', 'quarta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2018-03-07 19:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'r12', 'https://esportegoiano.com.br/tag/goianao-2018/', 'HIGH', null),
  ('vn_eg_go2018_r13', 2018, '2018-03-10', '16:00:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2018', 'R13', 'CONFIRMED', 'Grêmio Anápolis', true, false, 'Vila Nova', 'Grêmio Anápolis', 2, 1, 2, 1, '2–1', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2018-03-10 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'r13', 'https://esportegoiano.com.br/tag/goianao-2018/', 'HIGH', null),
  ('vn_cbf_cdb2018_079', 2018, '2018-03-15', '20:30:00', 'FINISHED', 'Copa do Brasil', 'COPA_DO_BRASIL', 'Copa do Brasil 2018', '3ª fase - volta', 'CONFIRMED', 'Ferroviário-CE', true, false, 'Vila Nova', 'Ferroviário-CE', 0, 1, 0, 1, '0–1', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'quinta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2018-03-15 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '079', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/CdB_2018_games.json', 'HIGH', null),
  ('vn_eg_go2018_r14', 2018, '2018-03-21', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2018', 'R14', 'CONFIRMED', 'Anápolis', false, false, 'Anápolis', 'Vila Nova', 2, 0, 0, 2, '2–0', 'LOSS', 'Estádio Jonas Duarte', 'MATCH_SPECIFIC', 'vn_venue_jonas_duarte', 'quarta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'Esporte Goiano', 'r14', 'https://esportegoiano.com.br/tag/goianao-2018/', 'HIGH', null),
  ('vn_eg_go2018_sf1', 2018, '2018-03-24', '16:00:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2018', 'Semifinal - ida', 'CONFIRMED', 'Aparecidense', false, false, 'Aparecidense', 'Vila Nova', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Aníbal Batista de Toledo', 'MATCH_SPECIFIC', 'vn_venue_anibal_toledo', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2018-03-24 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'sf1', 'https://esportegoiano.com.br/tag/goianao-2018/', 'HIGH', null),
  ('vn_eg_go2018_sf2', 2018, '2018-03-27', '20:30:00', 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2018', 'Semifinal - volta', 'CONFIRMED', 'Aparecidense', true, false, 'Vila Nova', 'Aparecidense', 2, 2, 2, 2, '2–2', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2018-03-27 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'Esporte Goiano', 'sf2', 'https://esportegoiano.com.br/tag/goianao-2018/', 'HIGH', 'Disputa de pênaltis: Vila Nova 2–4 Aparecidense.'),
  ('vn_cbf_sb2018_006', 2018, '2018-04-14', '16:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2018', 'R01', 'CONFIRMED', 'Avaí', true, false, 'Vila Nova', 'Avaí', 1, 0, 1, 0, '1–0', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2018-04-14 16:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '006', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2018_games.json', 'HIGH', null),
  ('vn_cbf_sb2018_018', 2018, '2018-04-21', '16:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2018', 'R02', 'CONFIRMED', 'CRB', false, false, 'CRB', 'Vila Nova', 0, 1, 1, 0, '0–1', 'WIN', 'Estádio Rei Pelé', 'MATCH_SPECIFIC', 'vn_venue_rei_pele', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2018-04-21 16:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '018', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2018_games.json', 'HIGH', null),
  ('vn_cbf_sb2018_026', 2018, '2018-04-28', '16:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2018', 'R03', 'CONFIRMED', 'Sampaio Corrêa', true, false, 'Vila Nova', 'Sampaio Corrêa', 3, 1, 3, 1, '3–1', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2018-04-28 16:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '026', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2018_games.json', 'HIGH', null),
  ('vn_cbf_sb2018_036', 2018, '2018-05-05', '16:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2018', 'R04', 'CONFIRMED', 'Goiás', false, false, 'Goiás', 'Vila Nova', 1, 3, 3, 1, '1–3', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2018-05-05 16:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '036', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2018_games.json', 'HIGH', null),
  ('vn_cbf_sb2018_046', 2018, '2018-05-13', '16:00:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2018', 'R05', 'CONFIRMED', 'Ponte Preta', true, false, 'Vila Nova', 'Ponte Preta', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'domingo', 'WEEKEND', 'AFTERNOON', (timestamp '2018-05-13 16:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '046', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2018_games.json', 'HIGH', null),
  ('vn_cbf_sb2018_052', 2018, '2018-05-19', '16:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2018', 'R06', 'CONFIRMED', 'Oeste', false, false, 'Oeste', 'Vila Nova', 2, 0, 0, 2, '2–0', 'LOSS', 'Arena Barueri', 'MATCH_SPECIFIC', 'vn_venue_arena_barueri', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2018-05-19 16:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '052', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2018_games.json', 'HIGH', null),
  ('vn_cbf_sb2018_069', 2018, '2018-05-25', '21:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2018', 'R07', 'CONFIRMED', 'Coritiba', false, false, 'Coritiba', 'Vila Nova', 2, 0, 0, 2, '2–0', 'LOSS', 'Estádio Couto Pereira', 'MATCH_SPECIFIC', 'vn_venue_couto_pereira', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2018-05-25 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '069', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2018_games.json', 'HIGH', null),
  ('vn_cbf_sb2018_076', 2018, '2018-06-01', '20:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2018', 'R08', 'CONFIRMED', 'CSA', true, false, 'Vila Nova', 'CSA', 0, 1, 0, 1, '0–1', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2018-06-01 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '076', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2018_games.json', 'HIGH', null),
  ('vn_cbf_sb2018_086', 2018, '2018-06-05', '21:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2018', 'R09', 'CONFIRMED', 'Fortaleza', true, false, 'Vila Nova', 'Fortaleza', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2018-06-05 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '086', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2018_games.json', 'HIGH', null),
  ('vn_cbf_sb2018_091', 2018, '2018-06-09', '16:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2018', 'R10', 'CONFIRMED', 'Guarani', false, false, 'Guarani', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Brinco de Ouro da Princesa', 'MATCH_SPECIFIC', 'vn_venue_brinco_ouro', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2018-06-09 16:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '091', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2018_games.json', 'HIGH', null),
  ('vn_cbf_sb2018_106', 2018, '2018-06-16', '18:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2018', 'R11', 'CONFIRMED', 'Atlético-GO', true, false, 'Vila Nova', 'Atlético-GO', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2018-06-16 18:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '106', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2018_games.json', 'HIGH', null),
  ('vn_cbf_sb2018_117', 2018, '2018-06-23', '19:00:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2018', 'R12', 'CONFIRMED', 'Boa Esporte', false, false, 'Boa Esporte', 'Vila Nova', 0, 2, 2, 0, '0–2', 'WIN', 'Estádio Dilzon Luiz de Melo', 'MATCH_SPECIFIC', 'vn_venue_dilzon_luiz_de_melo', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2018-06-23 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '117', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2018_games.json', 'HIGH', null),
  ('vn_cbf_sb2018_123', 2018, '2018-06-26', '19:15:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2018', 'R13', 'CONFIRMED', 'Juventude', false, false, 'Juventude', 'Vila Nova', 0, 1, 1, 0, '0–1', 'WIN', 'Estádio Alfredo Jaconi', 'MATCH_SPECIFIC', 'vn_venue_alfredo_jaconi', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2018-06-26 19:15:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '123', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2018_games.json', 'HIGH', null),
  ('vn_cbf_sb2018_136', 2018, '2018-07-05', '20:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2018', 'R14', 'CONFIRMED', 'Londrina', true, false, 'Vila Nova', 'Londrina', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'quinta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2018-07-05 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '136', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2018_games.json', 'HIGH', null),
  ('vn_cbf_sb2018_150', 2018, '2018-07-12', '20:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2018', 'R15', 'CONFIRMED', 'Paysandu', false, false, 'Paysandu', 'Vila Nova', 1, 2, 2, 1, '1–2', 'WIN', 'Curuzu', 'MATCH_SPECIFIC', 'vn_venue_curuzu', 'quinta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2018-07-12 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '150', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2018_games.json', 'HIGH', null),
  ('vn_cbf_sb2018_156', 2018, '2018-07-17', '20:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2018', 'R16', 'CONFIRMED', 'Brasil de Pelotas', true, false, 'Vila Nova', 'Brasil de Pelotas', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2018-07-17 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '156', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2018_games.json', 'HIGH', null),
  ('vn_cbf_sb2018_164', 2018, '2018-07-24', '19:15:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2018', 'R17', 'CONFIRMED', 'Figueirense', false, false, 'Figueirense', 'Vila Nova', 2, 1, 1, 2, '2–1', 'LOSS', 'Estádio Orlando Scarpelli', 'MATCH_SPECIFIC', 'vn_venue_orlando_scarpelli', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2018-07-24 19:15:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '164', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2018_games.json', 'HIGH', null),
  ('vn_cbf_sb2018_175', 2018, '2018-07-28', '19:00:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2018', 'R18', 'CONFIRMED', 'Criciúma', false, false, 'Criciúma', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', 'Estádio Heriberto Hülse', 'MATCH_SPECIFIC', 'vn_venue_heriberto_h_lse', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2018-07-28 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '175', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2018_games.json', 'HIGH', null),
  ('vn_cbf_sb2018_186', 2018, '2018-08-04', '16:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2018', 'R19', 'CONFIRMED', 'São Bento', true, false, 'Vila Nova', 'São Bento', 1, 0, 1, 0, '1–0', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2018-08-04 16:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '186', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2018_games.json', 'HIGH', null),
  ('vn_cbf_sb2018_191', 2018, '2018-08-07', '19:15:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2018', 'R20', 'CONFIRMED', 'Avaí', false, false, 'Avaí', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', 'Estádio Aderbal Ramos da Silva', 'MATCH_SPECIFIC', 'vn_venue_ressacada', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2018-08-07 19:15:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '191', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2018_games.json', 'HIGH', null),
  ('vn_cbf_sb2018_204', 2018, '2018-08-17', '20:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2018', 'R21', 'CONFIRMED', 'CRB', true, false, 'Vila Nova', 'CRB', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2018-08-17 20:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '204', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2018_games.json', 'HIGH', null),
  ('vn_cbf_sb2018_219', 2018, '2018-08-21', '21:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2018', 'R22', 'CONFIRMED', 'Sampaio Corrêa', false, false, 'Sampaio Corrêa', 'Vila Nova', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Governador João Castelo', 'MATCH_SPECIFIC', 'vn_venue_castelao_sao_luis', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2018-08-21 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '219', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2018_games.json', 'HIGH', null),
  ('vn_cbf_sb2018_227', 2018, '2018-08-25', '16:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2018', 'R23', 'CONFIRMED', 'Goiás', true, false, 'Vila Nova', 'Goiás', 3, 0, 3, 0, '3–0', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2018-08-25 16:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '227', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2018_games.json', 'HIGH', null),
  ('vn_cbf_sb2018_234', 2018, '2018-08-31', '21:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2018', 'R24', 'CONFIRMED', 'Ponte Preta', false, false, 'Ponte Preta', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Moisés Lucarelli', 'MATCH_SPECIFIC', 'vn_venue_moises_lucarelli', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2018-08-31 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '234', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2018_games.json', 'HIGH', null),
  ('vn_cbf_sb2018_241', 2018, '2018-09-03', '20:00:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2018', 'R25', 'CONFIRMED', 'Oeste', true, false, 'Vila Nova', 'Oeste', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'segunda-feira', 'WEEKDAY', 'NIGHT', (timestamp '2018-09-03 20:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '241', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2018_games.json', 'HIGH', null),
  ('vn_cbf_sb2018_260', 2018, '2018-09-08', '21:00:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2018', 'R26', 'CONFIRMED', 'Coritiba', true, false, 'Vila Nova', 'Coritiba', 2, 1, 2, 1, '2–1', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2018-09-08 21:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '260', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2018_games.json', 'HIGH', null),
  ('vn_cbf_sb2018_261', 2018, '2018-09-11', '19:00:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2018', 'R27', 'CONFIRMED', 'CSA', false, false, 'CSA', 'Vila Nova', 1, 2, 2, 1, '1–2', 'WIN', 'Estádio Rei Pelé', 'MATCH_SPECIFIC', 'vn_venue_rei_pele', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2018-09-11 19:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '261', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2018_games.json', 'HIGH', null),
  ('vn_cbf_sb2018_277', 2018, '2018-09-21', '21:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2018', 'R28', 'CONFIRMED', 'Fortaleza', false, false, 'Fortaleza', 'Vila Nova', 2, 0, 0, 2, '2–0', 'LOSS', 'Estádio Governador Plácido Castelo', 'MATCH_SPECIFIC', 'vn_venue_castelao', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2018-09-21 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '277', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2018_games.json', 'HIGH', null),
  ('vn_cbf_sb2018_285', 2018, '2018-09-28', '21:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2018', 'R29', 'CONFIRMED', 'Guarani', true, false, 'Vila Nova', 'Guarani', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2018-09-28 21:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '285', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2018_games.json', 'HIGH', null),
  ('vn_cbf_sb2018_299', 2018, '2018-10-06', '16:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2018', 'R30', 'CONFIRMED', 'Atlético-GO', false, false, 'Atlético-GO', 'Vila Nova', 2, 2, 2, 2, '2–2', 'DRAW', 'Estádio Antônio Accioly', 'MATCH_SPECIFIC', 'vn_venue_ant_nio_accioly', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2018-10-06 16:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '299', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2018_games.json', 'HIGH', null),
  ('vn_cbf_sb2018_308', 2018, '2018-10-13', '16:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2018', 'R31', 'CONFIRMED', 'Boa Esporte', true, false, 'Vila Nova', 'Boa Esporte', 2, 0, 2, 0, '2–0', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2018-10-13 16:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '308', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2018_games.json', 'HIGH', null),
  ('vn_cbf_sb2018_311', 2018, '2018-10-20', '16:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2018', 'R32', 'CONFIRMED', 'Juventude', true, false, 'Vila Nova', 'Juventude', 1, 0, 1, 0, '1–0', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2018-10-20 16:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '311', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2018_games.json', 'HIGH', null),
  ('vn_cbf_sb2018_325', 2018, '2018-10-26', '19:15:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2018', 'R33', 'CONFIRMED', 'Londrina', false, false, 'Londrina', 'Vila Nova', 3, 2, 2, 3, '3–2', 'LOSS', 'Estádio do Café', 'MATCH_SPECIFIC', 'vn_venue_estadio_cafe', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2018-10-26 19:15:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '325', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2018_games.json', 'HIGH', null),
  ('vn_cbf_sb2018_333', 2018, '2018-11-02', '19:15:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2018', 'R34', 'CONFIRMED', 'Paysandu', true, false, 'Vila Nova', 'Paysandu', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2018-11-02 19:15:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '333', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2018_games.json', 'HIGH', null),
  ('vn_cbf_sb2018_342', 2018, '2018-11-06', '19:15:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2018', 'R35', 'CONFIRMED', 'Brasil de Pelotas', false, false, 'Brasil de Pelotas', 'Vila Nova', 5, 0, 0, 5, '5–0', 'LOSS', 'Estádio Bento Mendes de Freitas', 'MATCH_SPECIFIC', 'vn_venue_bento_mendes_freitas', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2018-11-06 19:15:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '342', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2018_games.json', 'HIGH', null),
  ('vn_cbf_sb2018_357', 2018, '2018-11-09', '19:15:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2018', 'R36', 'CONFIRMED', 'Figueirense', true, false, 'Vila Nova', 'Figueirense', 3, 1, 3, 1, '3–1', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2018-11-09 19:15:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '357', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2018_games.json', 'HIGH', null),
  ('vn_cbf_sb2018_369', 2018, '2018-11-17', '19:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2018', 'R37', 'CONFIRMED', 'Criciúma', true, false, 'Vila Nova', 'Criciúma', 2, 2, 2, 2, '2–2', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2018-11-17 19:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '369', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2018_games.json', 'HIGH', null),
  ('vn_cbf_sb2018_372', 2018, '2018-11-24', '17:00:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2018', 'R38', 'CONFIRMED', 'São Bento', false, false, 'São Bento', 'Vila Nova', 2, 2, 2, 2, '2–2', 'DRAW', 'Estádio Municipal Walter Ribeiro', 'MATCH_SPECIFIC', 'vn_venue_walter_ribeiro', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2018-11-24 17:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '372', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2018_games.json', 'HIGH', null)
on conflict (id) do update set
    season = excluded.season,
    match_date = excluded.match_date,
    match_time = excluded.match_time,
    status = excluded.status,
    competition = excluded.competition,
    competition_code = excluded.competition_code,
    competition_edition = excluded.competition_edition,
    round = excluded.round,
    phase_status = excluded.phase_status,
    opponent = excluded.opponent,
    club_is_home = excluded.club_is_home,
    neutral_site = excluded.neutral_site,
    home_team = excluded.home_team,
    away_team = excluded.away_team,
    home_score = excluded.home_score,
    away_score = excluded.away_score,
    club_score = excluded.club_score,
    opponent_score = excluded.opponent_score,
    score_display = excluded.score_display,
    outcome = excluded.outcome,
    stadium = excluded.stadium,
    stadium_status = excluded.stadium_status,
    venue_id = excluded.venue_id,
    weekday = excluded.weekday,
    day_type = excluded.day_type,
    day_period = excluded.day_period,
    kickoff_at = excluded.kickoff_at,
    display_timezone = excluded.display_timezone,
    date_precision = excluded.date_precision,
    source_provider = excluded.source_provider,
    source_match_id = excluded.source_match_id,
    source_url = excluded.source_url,
    source_confidence = excluded.source_confidence,
    data_notes = excluded.data_notes,
    updated_at = now();

do $$
declare v_orphans int;
begin
  select count(*) into v_orphans from public.passport_matches
   where season = 2018 and stadium is not null and venue_id is null;
  if v_orphans > 0 then
    raise exception 'ha % partidas de 2018 com estadio sem venue_id -- rode vilanova_passport_venues_seed.sql antes', v_orphans;
  end if;
end $$;
