-- Passaporte do Vila Nova — temporada 2010. GERADO por
-- `node tooling/vilanova_passport/generate_passport_sql.mjs` a partir de
-- docs/vila_nova_data/passport/passport_2010.json — não edite à mão.
--
-- Rode no projeto Supabase do VILA NOVA — NUNCA no do Goiás nem no do Bragantino.
-- Ordem: vilanova_passport_infra.sql -> vilanova_passport_venues_seed.sql -> ESTE.
-- Idempotente (ON CONFLICT DO UPDATE): reexecutar atualiza, nunca duplica, e
-- não encosta em presença de usuário. 58 partidas.

do $$
begin
  if not exists (select 1 from public.clubs where slug = 'vilanova')
     or exists (select 1 from public.clubs where slug <> 'vilanova') then
    raise exception 'este nao e o projeto Supabase do Vila Nova -- PARE';
  end if;
end $$;

insert into public.passport_matches (
  id, season, match_date, match_time, status, competition, competition_code, competition_edition, round, phase_status, opponent, club_is_home, neutral_site, home_team, away_team, home_score, away_score, club_score, opponent_score, score_display, outcome, stadium, stadium_status, venue_id, weekday, day_type, day_period, kickoff_at, display_timezone, date_precision, source_provider, source_match_id, source_url, source_confidence, data_notes
) values
  ('vn_rsssf_go2010_r01', 2010, '2010-01-18', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2010', 'R1', 'CONFIRMED', 'Santa Helena', true, false, 'Vila Nova', 'Santa Helena', 1, 1, 1, 1, '1–1', 'DRAW', null, 'UNKNOWN', null, 'segunda-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r01', 'https://www.rsssfbrasil.com/tablesfq/go2010.htm', 'HIGH', null),
  ('vn_rsssf_go2010_r02', 2010, '2010-01-21', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2010', 'R2', 'CONFIRMED', 'Trindade', false, false, 'Trindade', 'Vila Nova', 0, 1, 1, 0, '0–1', 'WIN', null, 'UNKNOWN', null, 'quinta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r02', 'https://www.rsssfbrasil.com/tablesfq/go2010.htm', 'HIGH', null),
  ('vn_rsssf_go2010_r03', 2010, '2010-01-24', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2010', 'R3', 'CONFIRMED', 'Itumbiara', false, false, 'Itumbiara', 'Vila Nova', 3, 1, 1, 3, '3–1', 'LOSS', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r03', 'https://www.rsssfbrasil.com/tablesfq/go2010.htm', 'HIGH', null),
  ('vn_rsssf_go2010_r04', 2010, '2010-01-27', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2010', 'R4', 'CONFIRMED', 'Morrinhos', true, false, 'Vila Nova', 'Morrinhos', 2, 1, 2, 1, '2–1', 'WIN', null, 'UNKNOWN', null, 'quarta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r04', 'https://www.rsssfbrasil.com/tablesfq/go2010.htm', 'HIGH', null),
  ('vn_rsssf_go2010_r05', 2010, '2010-01-30', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2010', 'R5', 'CONFIRMED', 'Goiás', false, false, 'Goiás', 'Vila Nova', 2, 0, 0, 2, '2–0', 'LOSS', 'Estádio Hailé Pinheiro', 'MATCH_SPECIFIC', 'vn_venue_serrinha', 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r05', 'https://www.rsssfbrasil.com/tablesfq/go2010.htm', 'HIGH', null),
  ('vn_rsssf_go2010_r06', 2010, '2010-02-03', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2010', 'R6', 'CONFIRMED', 'Canedense', true, false, 'Vila Nova', 'Canedense', 2, 0, 2, 0, '2–0', 'WIN', null, 'UNKNOWN', null, 'quarta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r06', 'https://www.rsssfbrasil.com/tablesfq/go2010.htm', 'HIGH', null),
  ('vn_rsssf_go2010_r07', 2010, '2010-02-06', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2010', 'R7', 'CONFIRMED', 'Atlético-GO', true, false, 'Vila Nova', 'Atlético-GO', 1, 3, 1, 3, '1–3', 'LOSS', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r07', 'https://www.rsssfbrasil.com/tablesfq/go2010.htm', 'HIGH', null),
  ('vn_rsssf_go2010_r08', 2010, '2010-02-13', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2010', 'R8', 'CONFIRMED', 'Anapolina', false, false, 'Anapolina', 'Vila Nova', 0, 0, 0, 0, '0–0', 'DRAW', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r08', 'https://www.rsssfbrasil.com/tablesfq/go2010.htm', 'HIGH', null),
  ('vn_rsssf_go2010_r09', 2010, '2010-02-17', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2010', 'R9', 'CONFIRMED', 'CRAC', true, false, 'Vila Nova', 'CRAC', 4, 0, 4, 0, '4–0', 'WIN', null, 'UNKNOWN', null, 'quarta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r09', 'https://www.rsssfbrasil.com/tablesfq/go2010.htm', 'HIGH', null),
  ('vn_rsssf_go2010_r10', 2010, '2010-02-22', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2010', 'R10', 'CONFIRMED', 'CRAC', false, false, 'CRAC', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', null, 'UNKNOWN', null, 'segunda-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r10', 'https://www.rsssfbrasil.com/tablesfq/go2010.htm', 'HIGH', null),
  ('vn_rsssf_go2010_r11', 2010, '2010-02-28', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2010', 'R11', 'CONFIRMED', 'Morrinhos', false, false, 'Morrinhos', 'Vila Nova', 4, 2, 2, 4, '4–2', 'LOSS', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r11', 'https://www.rsssfbrasil.com/tablesfq/go2010.htm', 'HIGH', null),
  ('vn_rsssf_go2010_r12', 2010, '2010-03-03', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2010', 'R12', 'CONFIRMED', 'Itumbiara', true, false, 'Vila Nova', 'Itumbiara', 1, 2, 1, 2, '1–2', 'LOSS', null, 'UNKNOWN', null, 'quarta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r12', 'https://www.rsssfbrasil.com/tablesfq/go2010.htm', 'HIGH', null),
  ('vn_rsssf_go2010_r13', 2010, '2010-03-06', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2010', 'R13', 'CONFIRMED', 'Atlético-GO', false, false, 'Atlético-GO', 'Vila Nova', 3, 2, 2, 3, '3–2', 'LOSS', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r13', 'https://www.rsssfbrasil.com/tablesfq/go2010.htm', 'HIGH', null),
  ('vn_rsssf_go2010_r14', 2010, '2010-03-15', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2010', 'R14', 'CONFIRMED', 'Canedense', false, false, 'Canedense', 'Vila Nova', 1, 2, 2, 1, '1–2', 'WIN', null, 'UNKNOWN', null, 'segunda-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r14', 'https://www.rsssfbrasil.com/tablesfq/go2010.htm', 'HIGH', null),
  ('vn_rsssf_go2010_r15', 2010, '2010-03-21', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2010', 'R15', 'CONFIRMED', 'Trindade', true, false, 'Vila Nova', 'Trindade', 2, 1, 2, 1, '2–1', 'WIN', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r15', 'https://www.rsssfbrasil.com/tablesfq/go2010.htm', 'HIGH', null),
  ('vn_rsssf_go2010_r16', 2010, '2010-03-24', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2010', 'R16', 'CONFIRMED', 'Anapolina', true, false, 'Vila Nova', 'Anapolina', 3, 0, 3, 0, '3–0', 'WIN', null, 'UNKNOWN', null, 'quarta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r16', 'https://www.rsssfbrasil.com/tablesfq/go2010.htm', 'HIGH', null),
  ('vn_rsssf_go2010_r17', 2010, '2010-03-28', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2010', 'R17', 'CONFIRMED', 'Goiás', true, false, 'Vila Nova', 'Goiás', 2, 1, 2, 1, '2–1', 'WIN', 'Estádio Onésio Brasileiro Alvarenga', 'MATCH_SPECIFIC', 'vn_venue_oba', 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r17', 'https://www.rsssfbrasil.com/tablesfq/go2010.htm', 'HIGH', null),
  ('vn_rsssf_go2010_r18', 2010, '2010-04-04', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2010', 'R18', 'CONFIRMED', 'Santa Helena', false, false, 'Santa Helena', 'Vila Nova', 1, 4, 4, 1, '1–4', 'WIN', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r18', 'https://www.rsssfbrasil.com/tablesfq/go2010.htm', 'HIGH', null),
  ('vn_rsssf_go2010_sf1', 2010, '2010-04-11', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2010', 'Semifinal - ida', 'CONFIRMED', 'Santa Helena', true, false, 'Vila Nova', 'Santa Helena', 1, 3, 1, 3, '1–3', 'LOSS', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'sf1', 'https://www.rsssfbrasil.com/tablesfq/go2010.htm', 'HIGH', null),
  ('vn_rsssf_go2010_sf2', 2010, '2010-04-17', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2010', 'Semifinal - volta', 'CONFIRMED', 'Santa Helena', false, false, 'Santa Helena', 'Vila Nova', 4, 2, 2, 4, '4–2', 'LOSS', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'sf2', 'https://www.rsssfbrasil.com/tablesfq/go2010.htm', 'HIGH', null),
  ('vn_rsssf_sb2010_r01', 2010, '2010-05-07', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2010', 'R01', 'CONFIRMED', 'Portuguesa', false, false, 'Portuguesa', 'Vila Nova', 4, 1, 1, 4, '4–1', 'LOSS', null, 'UNKNOWN', null, 'sexta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r01', 'https://www.rsssfbrasil.com/tablesae/br2010l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2010_r02', 2010, '2010-05-14', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2010', 'R02', 'CONFIRMED', 'Icasa', true, false, 'Vila Nova', 'Icasa', 1, 0, 1, 0, '1–0', 'WIN', null, 'UNKNOWN', null, 'sexta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r02', 'https://www.rsssfbrasil.com/tablesae/br2010l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2010_r03', 2010, '2010-05-21', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2010', 'R03', 'CONFIRMED', 'Guaratinguetá', false, false, 'Guaratinguetá', 'Vila Nova', 2, 1, 1, 2, '2–1', 'LOSS', 'Estádio Dario Rodrigues Leite', 'MATCH_SPECIFIC', 'vn_venue_dario_rodrigues_leite', 'sexta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r03', 'https://www.rsssfbrasil.com/tablesae/br2010l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2010_r04', 2010, '2010-05-25', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2010', 'R04', 'CONFIRMED', 'Bahia', true, false, 'Vila Nova', 'Bahia', 0, 4, 0, 4, '0–4', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r04', 'https://www.rsssfbrasil.com/tablesae/br2010l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2010_r05', 2010, '2010-05-28', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2010', 'R05', 'CONFIRMED', 'Paraná', false, false, 'Paraná', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', 'Estádio Durival Britto e Silva', 'MATCH_SPECIFIC', 'vn_venue_durival_britto', 'sexta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r05', 'https://www.rsssfbrasil.com/tablesae/br2010l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2010_r06', 2010, '2010-06-01', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2010', 'R06', 'CONFIRMED', 'Santo André', true, false, 'Vila Nova', 'Santo André', 0, 3, 0, 3, '0–3', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r06', 'https://www.rsssfbrasil.com/tablesae/br2010l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2010_r07', 2010, '2010-06-05', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2010', 'R07', 'CONFIRMED', 'América-MG', false, false, 'América-MG', 'Vila Nova', 2, 0, 0, 2, '2–0', 'LOSS', 'Mineirão', 'MATCH_SPECIFIC', 'vn_venue_mineirao', 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r07', 'https://www.rsssfbrasil.com/tablesae/br2010l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2010_r08', 2010, '2010-07-13', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2010', 'R08', 'CONFIRMED', 'Figueirense', false, false, 'Figueirense', 'Vila Nova', 2, 0, 0, 2, '2–0', 'LOSS', 'Estádio Orlando Scarpelli', 'MATCH_SPECIFIC', 'vn_venue_orlando_scarpelli', 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r08', 'https://www.rsssfbrasil.com/tablesae/br2010l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2010_r09', 2010, '2010-07-17', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2010', 'R09', 'CONFIRMED', 'Ipatinga', true, false, 'Vila Nova', 'Ipatinga', 2, 2, 2, 2, '2–2', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r09', 'https://www.rsssfbrasil.com/tablesae/br2010l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2010_r10', 2010, '2010-07-24', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2010', 'R10', 'CONFIRMED', 'Duque de Caxias', false, false, 'Duque de Caxias', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', 'Estádio Olímpico Nilton Santos', 'MATCH_SPECIFIC', 'vn_venue_olimpico_nilton_santos', 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r10', 'https://www.rsssfbrasil.com/tablesae/br2010l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2010_r11', 2010, '2010-07-30', '21:00:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2010', 'R11', 'CONFIRMED', 'Coritiba', true, false, 'Vila Nova', 'Coritiba', 0, 1, 0, 1, '0–1', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2010-07-30 21:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'RSSSF Brasil', 'r11', 'https://www.rsssfbrasil.com/tablesae/br2010l2.htm', 'HIGH', 'Data confirmada como 30/07/2010 por múltiplas fontes contemporâneas; uma base secundária consultada durante a auditoria exibiu 27/07.'),
  ('vn_rsssf_sb2010_r12', 2010, '2010-08-07', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2010', 'R12', 'CONFIRMED', 'Brasiliense', false, false, 'Brasiliense', 'Vila Nova', 3, 0, 0, 3, '3–0', 'LOSS', 'Estádio Elmo Serejo Farias', 'MATCH_SPECIFIC', 'vn_venue_elmo_serejo', 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r12', 'https://www.rsssfbrasil.com/tablesae/br2010l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2010_r13', 2010, '2010-08-10', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2010', 'R13', 'CONFIRMED', 'Ponte Preta', true, false, 'Vila Nova', 'Ponte Preta', 1, 2, 1, 2, '1–2', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r13', 'https://www.rsssfbrasil.com/tablesae/br2010l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2010_r14', 2010, '2010-08-14', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2010', 'R14', 'CONFIRMED', 'América-RN', false, false, 'América-RN', 'Vila Nova', 1, 2, 2, 1, '1–2', 'WIN', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r14', 'https://www.rsssfbrasil.com/tablesae/br2010l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2010_r15', 2010, '2010-08-20', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2010', 'R15', 'CONFIRMED', 'ASA', true, false, 'Vila Nova', 'ASA', 2, 3, 2, 3, '2–3', 'LOSS', null, 'UNKNOWN', null, 'sexta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r15', 'https://www.rsssfbrasil.com/tablesae/br2010l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2010_r16', 2010, '2010-08-24', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2010', 'R16', 'CONFIRMED', 'Sport', false, false, 'Sport', 'Vila Nova', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Adelmar da Costa Carvalho', 'MATCH_SPECIFIC', 'vn_venue_ilha_do_retiro', 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r16', 'https://www.rsssfbrasil.com/tablesae/br2010l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2010_r17', 2010, '2010-08-28', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2010', 'R17', 'CONFIRMED', 'Bragantino', true, false, 'Vila Nova', 'Bragantino', 3, 1, 3, 1, '3–1', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r17', 'https://www.rsssfbrasil.com/tablesae/br2010l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2010_r18', 2010, '2010-08-31', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2010', 'R18', 'CONFIRMED', 'Náutico', true, false, 'Vila Nova', 'Náutico', 2, 1, 2, 1, '2–1', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r18', 'https://www.rsssfbrasil.com/tablesae/br2010l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2010_r19', 2010, '2010-09-03', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2010', 'R19', 'CONFIRMED', 'São Caetano', false, false, 'São Caetano', 'Vila Nova', 1, 2, 2, 1, '1–2', 'WIN', 'Estádio Anacleto Campanella', 'MATCH_SPECIFIC', 'vn_venue_anacleto_campanella', 'sexta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r19', 'https://www.rsssfbrasil.com/tablesae/br2010l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2010_r20', 2010, '2010-09-07', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2010', 'R20', 'CONFIRMED', 'Portuguesa', true, false, 'Vila Nova', 'Portuguesa', 2, 1, 2, 1, '2–1', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r20', 'https://www.rsssfbrasil.com/tablesae/br2010l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2010_r21', 2010, '2010-09-11', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2010', 'R21', 'CONFIRMED', 'Icasa', false, false, 'Icasa', 'Vila Nova', 1, 4, 4, 1, '1–4', 'WIN', 'Estádio Mauro Sampaio', 'MATCH_SPECIFIC', 'vn_venue_mauro_sampaio', 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r21', 'https://www.rsssfbrasil.com/tablesae/br2010l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2010_r22', 2010, '2010-09-17', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2010', 'R22', 'CONFIRMED', 'Guaratinguetá', true, false, 'Vila Nova', 'Guaratinguetá', 1, 0, 1, 0, '1–0', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sexta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r22', 'https://www.rsssfbrasil.com/tablesae/br2010l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2010_r23', 2010, '2010-09-21', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2010', 'R23', 'CONFIRMED', 'Bahia', false, false, 'Bahia', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', null, 'UNKNOWN', null, 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r23', 'https://www.rsssfbrasil.com/tablesae/br2010l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2010_r24', 2010, '2010-09-24', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2010', 'R24', 'CONFIRMED', 'Paraná', true, false, 'Vila Nova', 'Paraná', 2, 2, 2, 2, '2–2', 'DRAW', null, 'UNKNOWN', null, 'sexta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r24', 'https://www.rsssfbrasil.com/tablesae/br2010l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2010_r25', 2010, '2010-09-28', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2010', 'R25', 'CONFIRMED', 'Santo André', false, false, 'Santo André', 'Vila Nova', 0, 0, 0, 0, '0–0', 'DRAW', null, 'UNKNOWN', null, 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r25', 'https://www.rsssfbrasil.com/tablesae/br2010l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2010_r26', 2010, '2010-10-01', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2010', 'R26', 'CONFIRMED', 'América-MG', true, false, 'Vila Nova', 'América-MG', 2, 4, 2, 4, '2–4', 'LOSS', null, 'UNKNOWN', null, 'sexta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r26', 'https://www.rsssfbrasil.com/tablesae/br2010l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2010_r27', 2010, '2010-10-09', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2010', 'R27', 'CONFIRMED', 'Figueirense', true, false, 'Vila Nova', 'Figueirense', 3, 1, 3, 1, '3–1', 'WIN', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r27', 'https://www.rsssfbrasil.com/tablesae/br2010l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2010_r28', 2010, '2010-10-12', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2010', 'R28', 'CONFIRMED', 'Ipatinga', false, false, 'Ipatinga', 'Vila Nova', 2, 0, 0, 2, '2–0', 'LOSS', null, 'UNKNOWN', null, 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r28', 'https://www.rsssfbrasil.com/tablesae/br2010l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2010_r29', 2010, '2010-10-16', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2010', 'R29', 'CONFIRMED', 'Duque de Caxias', true, false, 'Vila Nova', 'Duque de Caxias', 3, 1, 3, 1, '3–1', 'WIN', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r29', 'https://www.rsssfbrasil.com/tablesae/br2010l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2010_r30', 2010, '2010-10-19', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2010', 'R30', 'CONFIRMED', 'Coritiba', false, false, 'Coritiba', 'Vila Nova', 5, 1, 1, 5, '5–1', 'LOSS', 'Estádio Couto Pereira', 'MATCH_SPECIFIC', 'vn_venue_couto_pereira', 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r30', 'https://www.rsssfbrasil.com/tablesae/br2010l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2010_r31', 2010, '2010-10-23', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2010', 'R31', 'CONFIRMED', 'Brasiliense', true, false, 'Vila Nova', 'Brasiliense', 4, 0, 4, 0, '4–0', 'WIN', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r31', 'https://www.rsssfbrasil.com/tablesae/br2010l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2010_r32', 2010, '2010-10-26', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2010', 'R32', 'CONFIRMED', 'Ponte Preta', false, false, 'Ponte Preta', 'Vila Nova', 2, 2, 2, 2, '2–2', 'DRAW', null, 'UNKNOWN', null, 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r32', 'https://www.rsssfbrasil.com/tablesae/br2010l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2010_r33', 2010, '2010-11-02', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2010', 'R33', 'CONFIRMED', 'América-RN', true, false, 'Vila Nova', 'América-RN', 2, 1, 2, 1, '2–1', 'WIN', null, 'UNKNOWN', null, 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r33', 'https://www.rsssfbrasil.com/tablesae/br2010l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2010_r34', 2010, '2010-11-06', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2010', 'R34', 'CONFIRMED', 'ASA', false, false, 'ASA', 'Vila Nova', 2, 1, 1, 2, '2–1', 'LOSS', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r34', 'https://www.rsssfbrasil.com/tablesae/br2010l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2010_r35', 2010, '2010-11-09', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2010', 'R35', 'CONFIRMED', 'Sport', true, false, 'Vila Nova', 'Sport', 1, 1, 1, 1, '1–1', 'DRAW', null, 'UNKNOWN', null, 'terça-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r35', 'https://www.rsssfbrasil.com/tablesae/br2010l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2010_r36', 2010, '2010-11-12', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2010', 'R36', 'CONFIRMED', 'Bragantino', false, false, 'Bragantino', 'Vila Nova', 5, 1, 1, 5, '5–1', 'LOSS', null, 'UNKNOWN', null, 'sexta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r36', 'https://www.rsssfbrasil.com/tablesae/br2010l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2010_r37', 2010, '2010-11-20', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2010', 'R37', 'CONFIRMED', 'Náutico', false, false, 'Náutico', 'Vila Nova', 4, 1, 1, 4, '4–1', 'LOSS', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r37', 'https://www.rsssfbrasil.com/tablesae/br2010l2.htm', 'HIGH', null),
  ('vn_rsssf_sb2010_r38', 2010, '2010-11-27', null, 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2010', 'R38', 'CONFIRMED', 'São Caetano', true, false, 'Vila Nova', 'São Caetano', 2, 1, 2, 1, '2–1', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r38', 'https://www.rsssfbrasil.com/tablesae/br2010l2.htm', 'HIGH', null)
on conflict (id) do update set
    season = excluded.season,
    match_date = excluded.match_date,
    match_time = excluded.match_time,
    status = excluded.status,
    competition = excluded.competition,
    competition_code = excluded.competition_code,
    competition_edition = excluded.competition_edition,
    round = excluded.round,
    phase_status = excluded.phase_status,
    opponent = excluded.opponent,
    club_is_home = excluded.club_is_home,
    neutral_site = excluded.neutral_site,
    home_team = excluded.home_team,
    away_team = excluded.away_team,
    home_score = excluded.home_score,
    away_score = excluded.away_score,
    club_score = excluded.club_score,
    opponent_score = excluded.opponent_score,
    score_display = excluded.score_display,
    outcome = excluded.outcome,
    stadium = excluded.stadium,
    stadium_status = excluded.stadium_status,
    venue_id = excluded.venue_id,
    weekday = excluded.weekday,
    day_type = excluded.day_type,
    day_period = excluded.day_period,
    kickoff_at = excluded.kickoff_at,
    display_timezone = excluded.display_timezone,
    date_precision = excluded.date_precision,
    source_provider = excluded.source_provider,
    source_match_id = excluded.source_match_id,
    source_url = excluded.source_url,
    source_confidence = excluded.source_confidence,
    data_notes = excluded.data_notes,
    updated_at = now();

do $$
declare v_orphans int;
begin
  select count(*) into v_orphans from public.passport_matches
   where season = 2010 and stadium is not null and venue_id is null;
  if v_orphans > 0 then
    raise exception 'ha % partidas de 2010 com estadio sem venue_id -- rode vilanova_passport_venues_seed.sql antes', v_orphans;
  end if;
end $$;
