-- Passaporte do Vila Nova — temporada 2014. GERADO por
-- `node tooling/vilanova_passport/generate_passport_sql.mjs` a partir de
-- docs/vila_nova_data/passport/passport_2014.json — não edite à mão.
--
-- Rode no projeto Supabase do VILA NOVA — NUNCA no do Goiás nem no do Bragantino.
-- Ordem: vilanova_passport_infra.sql -> vilanova_passport_venues_seed.sql -> ESTE.
-- Idempotente (ON CONFLICT DO UPDATE): reexecutar atualiza, nunca duplica, e
-- não encosta em presença de usuário. 52 partidas.

do $$
begin
  if not exists (select 1 from public.clubs where slug = 'vilanova')
     or exists (select 1 from public.clubs where slug <> 'vilanova') then
    raise exception 'este nao e o projeto Supabase do Vila Nova -- PARE';
  end if;
end $$;

insert into public.passport_matches (
  id, season, match_date, match_time, status, competition, competition_code, competition_edition, round, phase_status, opponent, club_is_home, neutral_site, home_team, away_team, home_score, away_score, club_score, opponent_score, score_display, outcome, stadium, stadium_status, venue_id, weekday, day_type, day_period, kickoff_at, display_timezone, date_precision, source_provider, source_match_id, source_url, source_confidence, data_notes
) values
  ('vn_rsssf_go2014_r01', 2014, '2014-01-19', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2014', 'R1', 'CONFIRMED', 'Anápolis', true, false, 'Vila Nova', 'Anápolis', 0, 0, 0, 0, '0–0', 'DRAW', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r01', 'https://www.rsssfbrasil.com/tablesfq/go2014.htm', 'HIGH', null),
  ('vn_rsssf_go2014_r02', 2014, '2014-01-22', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2014', 'R2', 'CONFIRMED', 'Trindade', false, false, 'Trindade', 'Vila Nova', 0, 2, 2, 0, '0–2', 'WIN', null, 'UNKNOWN', null, 'quarta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r02', 'https://www.rsssfbrasil.com/tablesfq/go2014.htm', 'HIGH', null),
  ('vn_rsssf_go2014_r03', 2014, '2014-01-26', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2014', 'R3', 'CONFIRMED', 'Goiás', false, false, 'Goiás', 'Vila Nova', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r03', 'https://www.rsssfbrasil.com/tablesfq/go2014.htm', 'HIGH', null),
  ('vn_rsssf_go2014_r04', 2014, '2014-01-29', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2014', 'R4', 'CONFIRMED', 'CRAC', true, false, 'Vila Nova', 'CRAC', 0, 0, 0, 0, '0–0', 'DRAW', null, 'UNKNOWN', null, 'quarta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r04', 'https://www.rsssfbrasil.com/tablesfq/go2014.htm', 'HIGH', null),
  ('vn_rsssf_go2014_r05', 2014, '2014-02-02', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2014', 'R5', 'CONFIRMED', 'Atlético-GO', false, false, 'Atlético-GO', 'Vila Nova', 0, 1, 1, 0, '0–1', 'WIN', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r05', 'https://www.rsssfbrasil.com/tablesfq/go2014.htm', 'HIGH', null),
  ('vn_rsssf_go2014_r06', 2014, '2014-02-05', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2014', 'R6', 'CONFIRMED', 'Anápolis', false, false, 'Anápolis', 'Vila Nova', 1, 1, 1, 1, '1–1', 'DRAW', null, 'UNKNOWN', null, 'quarta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r06', 'https://www.rsssfbrasil.com/tablesfq/go2014.htm', 'HIGH', null),
  ('vn_rsssf_go2014_r07', 2014, '2014-02-09', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2014', 'R7', 'CONFIRMED', 'Trindade', true, false, 'Vila Nova', 'Trindade', 0, 1, 0, 1, '0–1', 'LOSS', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r07', 'https://www.rsssfbrasil.com/tablesfq/go2014.htm', 'HIGH', null),
  ('vn_rsssf_go2014_r08', 2014, '2014-02-15', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2014', 'R8', 'CONFIRMED', 'Goiás', true, false, 'Vila Nova', 'Goiás', 1, 3, 1, 3, '1–3', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r08', 'https://www.rsssfbrasil.com/tablesfq/go2014.htm', 'HIGH', null),
  ('vn_rsssf_go2014_r09', 2014, '2014-02-19', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2014', 'R9', 'CONFIRMED', 'CRAC', false, false, 'CRAC', 'Vila Nova', 2, 0, 0, 2, '2–0', 'LOSS', null, 'UNKNOWN', null, 'quarta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r09', 'https://www.rsssfbrasil.com/tablesfq/go2014.htm', 'HIGH', null),
  ('vn_rsssf_go2014_r10', 2014, '2014-02-22', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2014', 'R10', 'CONFIRMED', 'Atlético-GO', true, false, 'Vila Nova', 'Atlético-GO', 0, 2, 0, 2, '0–2', 'LOSS', null, 'UNKNOWN', null, 'sábado', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r10', 'https://www.rsssfbrasil.com/tablesfq/go2014.htm', 'HIGH', null),
  ('vn_rsssf_go2014_r11', 2014, '2014-02-27', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2014', 'R11', 'CONFIRMED', 'Goianésia', true, false, 'Vila Nova', 'Goianésia', 1, 3, 1, 3, '1–3', 'LOSS', null, 'UNKNOWN', null, 'quinta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r11', 'https://www.rsssfbrasil.com/tablesfq/go2014.htm', 'HIGH', null),
  ('vn_rsssf_go2014_r12', 2014, '2014-03-05', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2014', 'R12', 'CONFIRMED', 'Anapolina', false, false, 'Anapolina', 'Vila Nova', 3, 2, 2, 3, '3–2', 'LOSS', null, 'UNKNOWN', null, 'quarta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r12', 'https://www.rsssfbrasil.com/tablesfq/go2014.htm', 'HIGH', null),
  ('vn_rsssf_go2014_r14', 2014, '2014-03-16', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2014', 'R14', 'CONFIRMED', 'Aparecidense', false, false, 'Aparecidense', 'Vila Nova', 2, 0, 0, 2, '2–0', 'LOSS', null, 'UNKNOWN', null, 'domingo', 'WEEKEND', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r14', 'https://www.rsssfbrasil.com/tablesfq/go2014.htm', 'HIGH', null),
  ('vn_rsssf_go2014_r15', 2014, '2014-03-19', null, 'FINISHED', 'Campeonato Goiano', 'GOIANO', 'Campeonato Goiano 2014', 'R15', 'CONFIRMED', 'Grêmio Anápolis', true, false, 'Vila Nova', 'Grêmio Anápolis', 3, 2, 3, 2, '3–2', 'WIN', null, 'UNKNOWN', null, 'quarta-feira', 'WEEKDAY', 'UNKNOWN', null, 'America/Sao_Paulo', 'date_only', 'RSSSF Brasil', 'r15', 'https://www.rsssfbrasil.com/tablesfq/go2014.htm', 'HIGH', null),
  ('vn_cbf_sb2014_008', 2014, '2014-04-18', '19:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2014', 'R01', 'CONFIRMED', 'Luverdense', true, false, 'Vila Nova', 'Luverdense', 0, 0, 0, 0, '0–0', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2014-04-18 19:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '008', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2014_games.json', 'HIGH', null),
  ('vn_cbf_sb2014_014', 2014, '2014-04-26', '16:20:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2014', 'R02', 'CONFIRMED', 'Náutico', false, false, 'Náutico', 'Vila Nova', 2, 0, 0, 2, '2–0', 'LOSS', 'Arena de Pernambuco', 'MATCH_SPECIFIC', 'vn_venue_arena_pernambuco', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2014-04-26 16:20:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '014', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2014_games.json', 'HIGH', null),
  ('vn_cbf_sb2014_028', 2014, '2014-05-03', '21:00:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2014', 'R03', 'CONFIRMED', 'Avaí', true, false, 'Vila Nova', 'Avaí', 0, 1, 0, 1, '0–1', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2014-05-03 21:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '028', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2014_games.json', 'HIGH', null),
  ('vn_cbf_sb2014_038', 2014, '2014-05-09', '21:00:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2014', 'R04', 'CONFIRMED', 'Icasa', true, false, 'Vila Nova', 'Icasa', 0, 1, 0, 1, '0–1', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2014-05-09 21:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '038', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2014_games.json', 'HIGH', null),
  ('vn_cbf_sb2014_050', 2014, '2014-05-17', '16:20:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2014', 'R05', 'CONFIRMED', 'América-MG', false, false, 'América-MG', 'Vila Nova', 2, 0, 0, 2, '2–0', 'LOSS', 'Estádio Raimundo Sampaio', 'MATCH_SPECIFIC', 'vn_venue_independ_ncia', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2014-05-17 16:20:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '050', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2014_games.json', 'HIGH', null),
  ('vn_cbf_sb2014_052', 2014, '2014-05-20', '19:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2014', 'R06', 'CONFIRMED', 'Ponte Preta', false, false, 'Ponte Preta', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', 'Estádio Moisés Lucarelli', 'MATCH_SPECIFIC', 'vn_venue_moises_lucarelli', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2014-05-20 19:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '052', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2014_games.json', 'HIGH', null),
  ('vn_cbf_sb2014_068', 2014, '2014-05-24', '16:20:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2014', 'R07', 'CONFIRMED', 'América-RN', true, false, 'Vila Nova', 'América-RN', 1, 3, 1, 3, '1–3', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2014-05-24 16:20:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '068', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2014_games.json', 'HIGH', null),
  ('vn_cbf_sb2014_076', 2014, '2014-05-27', '21:50:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2014', 'R08', 'CONFIRMED', 'Ceará', false, false, 'Ceará', 'Vila Nova', 4, 0, 0, 4, '4–0', 'LOSS', 'Estádio Horácio Domingos de Sousa', 'MATCH_SPECIFIC', 'vn_venue_horacio_domingos_de_sousa', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2014-05-27 21:50:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '076', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2014_games.json', 'HIGH', null),
  ('vn_cbf_sb2014_088', 2014, '2014-05-31', '21:00:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2014', 'R09', 'CONFIRMED', 'Bragantino', true, false, 'Vila Nova', 'Bragantino', 1, 1, 1, 1, '1–1', 'DRAW', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2014-05-31 21:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '088', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2014_games.json', 'HIGH', null),
  ('vn_cbf_sb2014_097', 2014, '2014-06-06', '19:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2014', 'R10', 'CONFIRMED', 'Joinville', false, false, 'Joinville', 'Vila Nova', 1, 0, 0, 1, '1–0', 'LOSS', 'Arena Joinville', 'MATCH_SPECIFIC', 'vn_venue_joinville', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2014-06-06 19:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '097', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2014_games.json', 'HIGH', null),
  ('vn_cbf_sb2014_108', 2014, '2014-07-15', '19:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2014', 'R11', 'CONFIRMED', 'Boa Esporte', true, false, 'Vila Nova', 'Boa Esporte', 0, 2, 0, 2, '0–2', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2014-07-15 19:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '108', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2014_games.json', 'HIGH', null),
  ('vn_cbf_sb2014_118', 2014, '2014-07-19', '16:20:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2014', 'R12', 'CONFIRMED', 'Santa Cruz', true, false, 'Vila Nova', 'Santa Cruz', 3, 2, 3, 2, '3–2', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2014-07-19 16:20:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '118', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2014_games.json', 'HIGH', null),
  ('vn_cbf_sb2014_125', 2014, '2014-07-26', '21:00:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2014', 'R13', 'CONFIRMED', 'Sampaio Corrêa', false, false, 'Sampaio Corrêa', 'Vila Nova', 2, 0, 0, 2, '2–0', 'LOSS', 'Estádio Governador João Castelo', 'MATCH_SPECIFIC', 'vn_venue_castelao_sao_luis', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2014-07-26 21:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '125', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2014_games.json', 'HIGH', null),
  ('vn_cbf_sb2014_138', 2014, '2014-08-01', '21:00:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2014', 'R14', 'CONFIRMED', 'Atlético-GO', true, false, 'Vila Nova', 'Atlético-GO', 0, 2, 0, 2, '0–2', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2014-08-01 21:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '138', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2014_games.json', 'HIGH', null),
  ('vn_cbf_sb2014_143', 2014, '2014-08-09', '16:20:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2014', 'R15', 'CONFIRMED', 'Paraná', false, false, 'Paraná', 'Vila Nova', 3, 1, 1, 3, '3–1', 'LOSS', 'Estádio Durival Britto e Silva', 'MATCH_SPECIFIC', 'vn_venue_durival_britto', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2014-08-09 16:20:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '143', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2014_games.json', 'HIGH', null),
  ('vn_cbf_sb2014_151', 2014, '2014-08-16', '21:00:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2014', 'R16', 'CONFIRMED', 'Oeste', false, false, 'Oeste', 'Vila Nova', 1, 3, 3, 1, '1–3', 'WIN', 'Estádio Municipal dos Amaros', 'MATCH_SPECIFIC', 'vn_venue_municipal_dos_amaros', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2014-08-16 21:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '151', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2014_games.json', 'HIGH', null),
  ('vn_cbf_sb2014_168', 2014, '2014-08-19', '21:50:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2014', 'R17', 'CONFIRMED', 'Vasco da Gama', true, false, 'Vila Nova', 'Vasco da Gama', 2, 1, 2, 1, '2–1', 'WIN', 'Estádio Nacional de Brasília Mané Garrincha', 'MATCH_SPECIFIC', 'vn_venue_nacional_de_brasilia_mane_garrincha', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2014-08-19 21:50:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '168', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2014_games.json', 'HIGH', null),
  ('vn_cbf_sb2014_179', 2014, '2014-08-23', '21:00:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2014', 'R18', 'CONFIRMED', 'ABC', false, false, 'ABC', 'Vila Nova', 0, 2, 2, 0, '0–2', 'WIN', 'Estádio Maria Lamas Farache', 'MATCH_SPECIFIC', 'vn_venue_frasqueirao', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2014-08-23 21:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '179', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2014_games.json', 'HIGH', null),
  ('vn_cbf_sb2014_188', 2014, '2014-08-26', '21:50:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2014', 'R19', 'CONFIRMED', 'Portuguesa', true, false, 'Vila Nova', 'Portuguesa', 1, 2, 1, 2, '1–2', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2014-08-26 21:50:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '188', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2014_games.json', 'HIGH', null),
  ('vn_cbf_sb2014_195', 2014, '2014-09-06', '21:00:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2014', 'R20', 'CONFIRMED', 'Luverdense', false, false, 'Luverdense', 'Vila Nova', 2, 0, 0, 2, '2–0', 'LOSS', 'Estádio Passo das Emas', 'MATCH_SPECIFIC', 'vn_venue_passo_das_emas', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2014-09-06 21:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '195', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2014_games.json', 'HIGH', null),
  ('vn_cbf_sb2014_208', 2014, '2014-09-09', '19:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2014', 'R21', 'CONFIRMED', 'Náutico', true, false, 'Vila Nova', 'Náutico', 0, 1, 0, 1, '0–1', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2014-09-09 19:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '208', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2014_games.json', 'HIGH', null),
  ('vn_cbf_sb2014_217', 2014, '2014-09-13', '21:00:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2014', 'R22', 'CONFIRMED', 'Avaí', false, false, 'Avaí', 'Vila Nova', 2, 1, 1, 2, '2–1', 'LOSS', 'Estádio Aderbal Ramos da Silva', 'MATCH_SPECIFIC', 'vn_venue_ressacada', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2014-09-13 21:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '217', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2014_games.json', 'HIGH', null),
  ('vn_cbf_sb2014_226', 2014, '2014-09-16', '21:50:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2014', 'R23', 'CONFIRMED', 'Icasa', false, false, 'Icasa', 'Vila Nova', 0, 1, 1, 0, '0–1', 'WIN', 'Estádio Mauro Sampaio', 'MATCH_SPECIFIC', 'vn_venue_mauro_sampaio', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2014-09-16 21:50:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '226', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2014_games.json', 'HIGH', null),
  ('vn_cbf_sb2014_238', 2014, '2014-09-20', '16:10:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2014', 'R24', 'CONFIRMED', 'América-MG', true, false, 'Vila Nova', 'América-MG', 0, 1, 0, 1, '0–1', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'AFTERNOON', (timestamp '2014-09-20 16:10:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '238', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2014_games.json', 'HIGH', null),
  ('vn_cbf_sb2014_248', 2014, '2014-09-23', '19:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2014', 'R25', 'CONFIRMED', 'Ponte Preta', true, false, 'Vila Nova', 'Ponte Preta', 0, 3, 0, 3, '0–3', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2014-09-23 19:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '248', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2014_games.json', 'HIGH', null),
  ('vn_cbf_sb2014_259', 2014, '2014-09-26', '19:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2014', 'R26', 'CONFIRMED', 'América-RN', false, false, 'América-RN', 'Vila Nova', 0, 1, 1, 0, '0–1', 'WIN', 'Arena das Dunas', 'MATCH_SPECIFIC', 'vn_venue_das_dunas', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2014-09-26 19:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '259', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2014_games.json', 'HIGH', null),
  ('vn_cbf_sb2014_268', 2014, '2014-09-30', '19:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2014', 'R27', 'CONFIRMED', 'Ceará', true, false, 'Vila Nova', 'Ceará', 1, 5, 1, 5, '1–5', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2014-09-30 19:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '268', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2014_games.json', 'HIGH', null),
  ('vn_cbf_sb2014_271', 2014, '2014-10-07', '19:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2014', 'R28', 'CONFIRMED', 'Bragantino', false, false, 'Bragantino', 'Vila Nova', 1, 2, 2, 1, '1–2', 'WIN', 'Estádio Nabi Abi Chedid', 'MATCH_SPECIFIC', 'vn_venue_nabi_abi_chedid', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2014-10-07 19:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '271', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2014_games.json', 'HIGH', null),
  ('vn_cbf_sb2014_288', 2014, '2014-10-10', '19:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2014', 'R29', 'CONFIRMED', 'Joinville', true, false, 'Vila Nova', 'Joinville', 0, 1, 0, 1, '0–1', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2014-10-10 19:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '288', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2014_games.json', 'HIGH', null),
  ('vn_cbf_sb2014_300', 2014, '2014-10-14', '19:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2014', 'R30', 'CONFIRMED', 'Boa Esporte', false, false, 'Boa Esporte', 'Vila Nova', 3, 0, 0, 3, '3–0', 'LOSS', 'Estádio Dilzon Luiz de Melo', 'MATCH_SPECIFIC', 'vn_venue_dilzon_luiz_de_melo', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2014-10-14 19:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '300', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2014_games.json', 'HIGH', null),
  ('vn_cbf_sb2014_318', 2014, '2014-10-25', '21:00:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2014', 'R32', 'CONFIRMED', 'Sampaio Corrêa', true, false, 'Vila Nova', 'Sampaio Corrêa', 4, 1, 4, 1, '4–1', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2014-10-25 21:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '318', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2014_games.json', 'HIGH', null),
  ('vn_cbf_sb2014_304', 2014, '2014-10-28', '19:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2014', 'R31', 'CONFIRMED', 'Santa Cruz', false, false, 'Santa Cruz', 'Vila Nova', 5, 1, 1, 5, '5–1', 'LOSS', 'Arena de Pernambuco', 'MATCH_SPECIFIC', 'vn_venue_arena_pernambuco', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2014-10-28 19:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '304', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2014_games.json', 'HIGH', null),
  ('vn_cbf_sb2014_328', 2014, '2014-10-31', '19:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2014', 'R33', 'CONFIRMED', 'Atlético-GO', false, false, 'Atlético-GO', 'Vila Nova', 3, 1, 1, 3, '3–1', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2014-10-31 19:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '328', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2014_games.json', 'HIGH', null),
  ('vn_cbf_sb2014_338', 2014, '2014-11-08', '21:00:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2014', 'R34', 'CONFIRMED', 'Paraná', true, false, 'Vila Nova', 'Paraná', 2, 0, 2, 0, '2–0', 'WIN', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sábado', 'WEEKEND', 'NIGHT', (timestamp '2014-11-08 21:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '338', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2014_games.json', 'HIGH', null),
  ('vn_cbf_sb2014_348', 2014, '2014-11-14', '19:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2014', 'R35', 'CONFIRMED', 'Oeste', true, false, 'Vila Nova', 'Oeste', 0, 1, 0, 1, '0–1', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2014-11-14 19:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '348', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2014_games.json', 'HIGH', null),
  ('vn_cbf_sb2014_353', 2014, '2014-11-18', '21:50:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2014', 'R36', 'CONFIRMED', 'Vasco da Gama', false, false, 'Vasco da Gama', 'Vila Nova', 3, 1, 1, 3, '3–1', 'LOSS', 'Estádio São Januário', 'MATCH_SPECIFIC', 'vn_venue_sao_januario', 'terça-feira', 'WEEKDAY', 'NIGHT', (timestamp '2014-11-18 21:50:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '353', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2014_games.json', 'HIGH', null),
  ('vn_cbf_sb2014_368', 2014, '2014-11-21', '21:00:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2014', 'R37', 'CONFIRMED', 'ABC', true, false, 'Vila Nova', 'ABC', 3, 5, 3, 5, '3–5', 'LOSS', 'Estádio Serra Dourada', 'MATCH_SPECIFIC', 'vn_venue_serra_dourada', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2014-11-21 21:00:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '368', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2014_games.json', 'HIGH', null),
  ('vn_cbf_sb2014_372', 2014, '2014-11-28', '19:30:00', 'FINISHED', 'Série B', 'BRASILEIRO_B', 'Série B 2014', 'R38', 'CONFIRMED', 'Portuguesa', false, false, 'Portuguesa', 'Vila Nova', 2, 3, 3, 2, '2–3', 'WIN', 'Estádio Doutor Oswaldo Teixeira Duarte', 'MATCH_SPECIFIC', 'vn_venue_doutor_oswaldo_teixeira_duarte', 'sexta-feira', 'WEEKDAY', 'NIGHT', (timestamp '2014-11-28 19:30:00' at time zone 'America/Sao_Paulo'), 'America/Sao_Paulo', 'datetime', 'BrazilianFootball/Data (dados CBF)', '372', 'https://github.com/BrazilianFootball/Data/blob/main/results/processed/Serie_B_2014_games.json', 'HIGH', null)
on conflict (id) do update set
    season = excluded.season,
    match_date = excluded.match_date,
    match_time = excluded.match_time,
    status = excluded.status,
    competition = excluded.competition,
    competition_code = excluded.competition_code,
    competition_edition = excluded.competition_edition,
    round = excluded.round,
    phase_status = excluded.phase_status,
    opponent = excluded.opponent,
    club_is_home = excluded.club_is_home,
    neutral_site = excluded.neutral_site,
    home_team = excluded.home_team,
    away_team = excluded.away_team,
    home_score = excluded.home_score,
    away_score = excluded.away_score,
    club_score = excluded.club_score,
    opponent_score = excluded.opponent_score,
    score_display = excluded.score_display,
    outcome = excluded.outcome,
    stadium = excluded.stadium,
    stadium_status = excluded.stadium_status,
    venue_id = excluded.venue_id,
    weekday = excluded.weekday,
    day_type = excluded.day_type,
    day_period = excluded.day_period,
    kickoff_at = excluded.kickoff_at,
    display_timezone = excluded.display_timezone,
    date_precision = excluded.date_precision,
    source_provider = excluded.source_provider,
    source_match_id = excluded.source_match_id,
    source_url = excluded.source_url,
    source_confidence = excluded.source_confidence,
    data_notes = excluded.data_notes,
    updated_at = now();

do $$
declare v_orphans int;
begin
  select count(*) into v_orphans from public.passport_matches
   where season = 2014 and stadium is not null and venue_id is null;
  if v_orphans > 0 then
    raise exception 'ha % partidas de 2014 com estadio sem venue_id -- rode vilanova_passport_venues_seed.sql antes', v_orphans;
  end if;
end $$;
