name: goias_app
description: "Goiás EC - o ecossistema digital do torcedor esmeraldino."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8

  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  get_it: ^8.0.3
  go_router: ^15.1.2
  flutter_svg: ^2.2.1
  cached_network_image: ^3.4.1
  dio: ^5.9.0
  timezone: ^0.10.1
  url_launcher: ^6.3.2
  supabase_flutter: ^2.17.2
  image_picker: ^1.2.3
  shared_preferences: ^2.5.5
  flame: ^1.38.0
  share_plus: ^13.3.0
  video_player: ^2.14.0
  pdf: ^3.11.3
  printing: ^5.14.2
  just_audio: ^0.10.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.8

flutter:
  uses-material-design: true
  generate: true

  assets:
    - lib/assets/
    - lib/assets/legal/
    - lib/assets/content/
    - lib/assets/sponsors/
    - lib/assets/branding/
    - lib/assets/games/guess_player/
    - lib/assets/games/penalty/
    - lib/assets/squad/
    - lib/assets/store/products/uniform_01_female_fan/
    - lib/assets/store/products/uniform_03_male/
    - lib/assets/store/products/uniform_02_youth/
    - lib/assets/store/products/uniform_01_male_player/
    - lib/assets/store/products/uniform_02_male_player/
    - lib/assets/store/products/uniform_02_female_fan/
    - lib/assets/store/products/uniform_03_kids/
    - lib/assets/store/products/goalkeeper_01_male_fan/
    - lib/assets/store/products/shin_guard_kids_black/
    - lib/assets/store/products/uniform_01_male_fan/
    - lib/assets/store/products/uniform_02_male_fan/
    - lib/assets/store/products/uniform_01_female_player/
    - lib/assets/store/products/uniform_02_female_player/
    - lib/assets/store/products/uniform_01_kids_fan/
    - lib/assets/store/products/uniform_01_kids_player/
    - lib/assets/store/products/uniform_01_youth_fan/
    - lib/assets/store/products/uniform_01_youth_player/
    - lib/assets/store/products/uniform_02_kids_player/
    - lib/assets/store/products/goalkeeper_01_male_player/
    - lib/assets/store/products/goalkeeper_02_male_player/
    - lib/assets/store/products/goalkeeper_01_female_fan/
    - lib/assets/store/products/goalkeeper_02_female_player/
    - lib/assets/store/products/goalkeeper_01_kids_player/
    - lib/assets/store/products/goalkeeper_01_youth_fan/
    - lib/assets/store/products/goalkeeper_02_youth_player/
    - lib/assets/store/products/bag_lateral_goias/
    - lib/assets/store/products/bag_lateral_goias_alviverde_preta/
    - lib/assets/store/products/bag_lateral_goias_cafe/
    - lib/assets/store/products/bola_de_futebol_goias_padrao/
    - lib/assets/store/products/bola_de_futebol_n_05_goias_e_c/
    - lib/assets/store/products/bola_de_futebol_protech_goias_e_c/
    - lib/assets/store/products/bola_de_futevolei_protech_goias_e_c/
    - lib/assets/store/products/bolsa_esportiva_goias_verde/
    - lib/assets/store/products/boneco_colecionavel_mascote_goias_periquito/
    - lib/assets/store/products/caneca_estadio_goias_e_c/
    - lib/assets/store/products/caneca_goias_gel_peca_verde/
    - lib/assets/store/products/caneca_termica_goias_inox_verde_700ml/
    - lib/assets/store/products/carteira_goias_de_luxo_verde/
    - lib/assets/store/products/carteira_goias_de_luxo_vertical_alviverde/
    - lib/assets/store/products/carteira_goias_de_luxo_vertical_alviverde_preta/
    - lib/assets/store/products/carteira_goias_tradicional_preta/
    - lib/assets/store/products/chaveiro_abridor_goias_retangular/
    - lib/assets/store/products/chaveiro_goias_camisa/
    - lib/assets/store/products/chaveiro_goias_chuteira/
    - lib/assets/store/products/chaveiro_goias_mosquetao_resinado/
    - lib/assets/store/products/chaveiro_goias_redondo_e_giratorio/
    - lib/assets/store/products/chinelo_slide_goias_branca/
    - lib/assets/store/products/chinelo_slide_goias_preta/
    - lib/assets/store/products/chinelo_slide_goias_verde/
    - lib/assets/store/products/cooler_goias_10_latas/
    - lib/assets/store/products/copo_termico_goias_sleek_473ml/
    - lib/assets/store/products/copo_termico_goias_sleek_off_white_473ml/
    - lib/assets/store/products/copo_termico_goias_tulipinha_354ml/
    - lib/assets/store/products/garrafa_termica_oasis_goias_black_750ml/
    - lib/assets/store/products/garrafa_termica_oasis_goias_off_white_750ml/
    - lib/assets/store/products/kit_cartao_goias_caixa_havanna/
    - lib/assets/store/products/kit_cartao_goias_caixa_verde/
    - lib/assets/store/products/kit_porta_cartao_preto/
    - lib/assets/store/products/luvas_de_goleiro_infantil_goias/
    - lib/assets/store/products/meiao_goias_branco_adulto/
    - lib/assets/store/products/meiao_goias_branco_infantil/
    - lib/assets/store/products/meiao_goias_branco_juvenil/
    - lib/assets/store/products/meiao_goias_branco_verde/
    - lib/assets/store/products/meiao_goias_verde_juvenil/
    - lib/assets/store/products/mini_bola_de_futebol_goias_e_c/
    - lib/assets/store/products/mochila_goias_verde/
    - lib/assets/store/products/mochila_pequena_preta_goias/
    - lib/assets/store/products/pelucia_goias_periquito_mod_p/
    - lib/assets/store/products/squeeze_garrafa_goias_aluminio_verde_700ml/
    - lib/assets/store/products/squeeze_garrafa_goias_plastica_500ml/
    - lib/assets/store/products/squeeze_goias_aluminio_verde_500ml/
    - lib/assets/store/products/squeeze_plastica_garrafa_goias_verde_500ml/
    - lib/assets/store/products/squeeze_plastica_garrafa_goias_verde_com_alca_500ml/
    - lib/assets/store/products/squeeze_plastica_garrafa_goias_verde_rosqueavel_500ml/
    - lib/assets/store/products/camisa_reserva_goias_alviverde_branca/
    - lib/assets/store/products/camisa_reserva_goias_alviverde/
    - lib/assets/store/products/camisa_reserva_goias_escudo/
    - lib/assets/store/products/camiseta_reserva_goias_coracao_esmeraldino_preta/
    - lib/assets/store/products/camiseta_reserva_goias_forca_esmeraldino_cinza/
    - lib/assets/store/products/camiseta_reserva_goias_pica_pau_esmeraldino_branca/
    - lib/assets/store/products/camisa_uniforme_03_goias_feminino/
    - lib/assets/store/products/camisa_goias_uniforme_03_goleiro_jogador_masculina/
    - lib/assets/store/products/camisa_goias_uniforme_01_goleiro_juvenil_jogador/
    - lib/assets/store/products/chaveiro_goias_cortador_de_unha/
    - lib/assets/store/products/chaveiro_goias_garrafa_abridor/
    - lib/assets/store/products/chaveiro_goias_luva/
    - lib/assets/store/products/meiao_goias_verde_infantil/
    - lib/assets/store/products/bone_03_goias/
    - lib/assets/store/products/bone_goias/
    - lib/assets/store/products/colar_goias_coracao_foleado_dourado/
    - lib/assets/store/products/colar_goias_escudo_foleado_prata/
    - lib/assets/store/products/colar_goias_g_cravejado/
    - lib/assets/store/products/colar_goias_g_cravejado_dourado/
    - lib/assets/store/products/colar_goias_g_foleado_prata/
    - lib/assets/store/products/colar_goias_quadro_coracao_foleado_prata/
    - lib/assets/store/products/copo_termico_goias_sleek_salmao_473ml/
    - lib/assets/store/products/cordao_goias_de_chavei_nada_pode_abalar/
    - lib/assets/store/products/flamula_goias_triangular/
    - lib/assets/store/products/relogio_goias_classic_k_branco/
    - lib/assets/store/products/relogio_goias_classic_k_verde/
    - lib/assets/store/products/relogio_goias_esmeraldino_k_branco/
    - lib/assets/store/products/relogio_goias_esmeraldino_k_verde/
    - lib/assets/store/products/relogio_goias_tempo_de_jogo_green_k_branco/
    - lib/assets/store/products/relogio_goias_tempo_de_jogo_green_k_verde/
    - lib/assets/store/promo/
    - lib/assets/videos/
    - lib/assets/audio/club/hinos/
    - lib/assets/audio/club/musicas/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets_gen/app_icon.png"
  adaptive_icon_background: "#004C1B"
  adaptive_icon_foreground: "assets_gen/app_icon_foreground.png"
  web:
    generate: true
    image_path: "assets_gen/app_icon.png"
    background_color: "#004C1B"
    theme_color: "#004C1B"

flutter_native_splash:
  color: "#F6F8F7"
  android_12:
    color: "#F6F8F7"
  web: false
