name: goias_app
description: "Goiás EC - o ecossistema digital do torcedor esmeraldino."
publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8

  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  get_it: ^8.0.3
  go_router: ^18.0.0
  flutter_svg: ^2.2.1
  cached_network_image: ^3.4.1
  dio: ^5.9.0
  timezone: ^0.10.1
  url_launcher: ^6.3.2
  supabase_flutter: ^2.17.2
  image_picker: ^1.2.3
  shared_preferences: ^2.5.5
  flame: ^1.38.0
  share_plus: ^13.3.0
  video_player: ^2.14.0
  pdf: ^3.11.3
  printing: ^5.14.2
  just_audio: ^0.10.6
  sentry_flutter: 9.28.0
  sentry_dio: 9.28.0
  http: ^1.6.0
  package_info_plus: ^10.2.1
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.6
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.8
  supabase: ^2.16.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - lib/assets/
    - lib/assets/fonts/
    - lib/assets/legal/
    - lib/assets/content/
    - lib/assets/content/bragantino/
    - lib/assets/sponsors/
    - lib/assets/branding/goias/
    - lib/assets/branding/bragantino/
    - lib/assets/branding/bragantino/idols/
    - lib/assets/club/titles/campeonato-goiano/
    - lib/assets/club/titles/copa-centro-oeste/
    - lib/assets/club/titles/serie-b/
    - lib/assets/club/titles/copa-verde/
    - lib/assets/club/titles/copa-do-brasil-1990/
    - lib/assets/club/titles/libertadores-2006/
    - lib/assets/club/titles/sula-2010/
    - lib/assets/club/titles/brasileirao-2005/
    - lib/assets/games/guess_player/goias/
    - lib/assets/games/guess_player/bragantino/
    - lib/assets/games/penalty/
    - lib/assets/squad/
    - lib/assets/store/products/uniform_01_female_fan/
    - lib/assets/store/products/uniform_03_male/
    - lib/assets/store/products/uniform_02_youth/
    - lib/assets/store/products/uniform_01_male_player/
    - lib/assets/store/products/uniform_02_male_player/
    - lib/assets/store/products/uniform_02_female_fan/
    - lib/assets/store/products/uniform_03_kids/
    - lib/assets/store/products/goalkeeper_01_male_fan/
    - lib/assets/store/products/shin_guard_kids_black/
    - lib/assets/store/products/uniform_01_male_fan/
    - lib/assets/store/products/uniform_02_male_fan/
    - lib/assets/store/products/uniform_01_female_player/
    - lib/assets/store/products/uniform_02_female_player/
    - lib/assets/store/products/uniform_01_kids_fan/
    - lib/assets/store/products/uniform_01_kids_player/
    - lib/assets/store/products/uniform_01_youth_fan/
    - lib/assets/store/products/uniform_01_youth_player/
    - lib/assets/store/products/uniform_02_kids_player/
    - lib/assets/store/products/goalkeeper_01_male_player/
    - lib/assets/store/products/goalkeeper_02_male_player/
    - lib/assets/store/products/goalkeeper_01_female_fan/
    - lib/assets/store/products/goalkeeper_02_female_player/
    - lib/assets/store/products/goalkeeper_01_kids_player/
    - lib/assets/store/products/goalkeeper_01_youth_fan/
    - lib/assets/store/products/goalkeeper_02_youth_player/
    - lib/assets/store/products/bag_lateral_goias/
    - lib/assets/store/products/bag_lateral_goias_alviverde_preta/
    - lib/assets/store/products/bag_lateral_goias_cafe/
    - lib/assets/store/products/bola_de_futebol_goias_padrao/
    - lib/assets/store/products/bola_de_futebol_n_05_goias_e_c/
    - lib/assets/store/products/bola_de_futebol_protech_goias_e_c/
    - lib/assets/store/products/bola_de_futevolei_protech_goias_e_c/
    - lib/assets/store/products/bolsa_esportiva_goias_verde/
    - lib/assets/store/products/boneco_colecionavel_mascote_goias_periquito/
    - lib/assets/store/products/caneca_estadio_goias_e_c/
    - lib/assets/store/products/caneca_goias_gel_peca_verde/
    - lib/assets/store/products/caneca_termica_goias_inox_verde_700ml/
    - lib/assets/store/products/carteira_goias_de_luxo_verde/
    - lib/assets/store/products/carteira_goias_de_luxo_vertical_alviverde/
    - lib/assets/store/products/carteira_goias_de_luxo_vertical_alviverde_preta/
    - lib/assets/store/products/carteira_goias_tradicional_preta/
    - lib/assets/store/products/chaveiro_abridor_goias_retangular/
    - lib/assets/store/products/chaveiro_goias_camisa/
    - lib/assets/store/products/chaveiro_goias_chuteira/
    - lib/assets/store/products/chaveiro_goias_mosquetao_resinado/
    - lib/assets/store/products/chaveiro_goias_redondo_e_giratorio/
    - lib/assets/store/products/chinelo_slide_goias_branca/
    - lib/assets/store/products/chinelo_slide_goias_preta/
    - lib/assets/store/products/chinelo_slide_goias_verde/
    - lib/assets/store/products/cooler_goias_10_latas/
    - lib/assets/store/products/copo_termico_goias_sleek_473ml/
    - lib/assets/store/products/copo_termico_goias_sleek_off_white_473ml/
    - lib/assets/store/products/copo_termico_goias_tulipinha_354ml/
    - lib/assets/store/products/garrafa_termica_oasis_goias_black_750ml/
    - lib/assets/store/products/garrafa_termica_oasis_goias_off_white_750ml/
    - lib/assets/store/products/kit_cartao_goias_caixa_havanna/
    - lib/assets/store/products/kit_cartao_goias_caixa_verde/
    - lib/assets/store/products/kit_porta_cartao_preto/
    - lib/assets/store/products/luvas_de_goleiro_infantil_goias/
    - lib/assets/store/products/meiao_goias_branco_adulto/
    - lib/assets/store/products/meiao_goias_branco_infantil/
    - lib/assets/store/products/meiao_goias_branco_juvenil/
    - lib/assets/store/products/meiao_goias_branco_verde/
    - lib/assets/store/products/meiao_goias_verde_juvenil/
    - lib/assets/store/products/mini_bola_de_futebol_goias_e_c/
    - lib/assets/store/products/mochila_goias_verde/
    - lib/assets/store/products/mochila_pequena_preta_goias/
    - lib/assets/store/products/pelucia_goias_periquito_mod_p/
    - lib/assets/store/products/squeeze_garrafa_goias_aluminio_verde_700ml/
    - lib/assets/store/products/squeeze_garrafa_goias_plastica_500ml/
    - lib/assets/store/products/squeeze_goias_aluminio_verde_500ml/
    - lib/assets/store/products/squeeze_plastica_garrafa_goias_verde_500ml/
    - lib/assets/store/products/squeeze_plastica_garrafa_goias_verde_com_alca_500ml/
    - lib/assets/store/products/squeeze_plastica_garrafa_goias_verde_rosqueavel_500ml/
    - lib/assets/store/products/camisa_reserva_goias_alviverde_branca/
    - lib/assets/store/products/camisa_reserva_goias_alviverde/
    - lib/assets/store/products/camisa_reserva_goias_escudo/
    - lib/assets/store/products/camiseta_reserva_goias_coracao_esmeraldino_preta/
    - lib/assets/store/products/camiseta_reserva_goias_forca_esmeraldino_cinza/
    - lib/assets/store/products/camiseta_reserva_goias_pica_pau_esmeraldino_branca/
    - lib/assets/store/products/camisa_uniforme_03_goias_feminino/
    - lib/assets/store/products/camisa_goias_uniforme_03_goleiro_jogador_masculina/
    - lib/assets/store/products/camisa_goias_uniforme_01_goleiro_juvenil_jogador/
    - lib/assets/store/products/chaveiro_goias_cortador_de_unha/
    - lib/assets/store/products/chaveiro_goias_garrafa_abridor/
    - lib/assets/store/products/chaveiro_goias_luva/
    - lib/assets/store/products/meiao_goias_verde_infantil/
    - lib/assets/store/products/bone_03_goias/
    - lib/assets/store/products/bone_goias/
    - lib/assets/store/products/colar_goias_coracao_foleado_dourado/
    - lib/assets/store/products/colar_goias_escudo_foleado_prata/
    - lib/assets/store/products/colar_goias_g_cravejado/
    - lib/assets/store/products/colar_goias_g_cravejado_dourado/
    - lib/assets/store/products/colar_goias_g_foleado_prata/
    - lib/assets/store/products/colar_goias_quadro_coracao_foleado_prata/
    - lib/assets/store/products/copo_termico_goias_sleek_salmao_473ml/
    - lib/assets/store/products/cordao_goias_de_chavei_nada_pode_abalar/
    - lib/assets/store/products/flamula_goias_triangular/
    - lib/assets/store/products/relogio_goias_classic_k_branco/
    - lib/assets/store/products/relogio_goias_classic_k_verde/
    - lib/assets/store/products/relogio_goias_esmeraldino_k_branco/
    - lib/assets/store/products/relogio_goias_esmeraldino_k_verde/
    - lib/assets/store/products/relogio_goias_tempo_de_jogo_green_k_branco/
    - lib/assets/store/products/relogio_goias_tempo_de_jogo_green_k_verde/
    - lib/assets/store/products/bragantino/629040860/
    - lib/assets/store/products/bragantino/629040875/
    - lib/assets/store/products/bragantino/629040876/
    - lib/assets/store/products/bragantino/629040877/
    - lib/assets/store/products/bragantino/629040878/
    - lib/assets/store/products/bragantino/629041000/
    - lib/assets/store/products/bragantino/629041001/
    - lib/assets/store/products/bragantino/629041002/
    - lib/assets/store/products/bragantino/629041161/
    - lib/assets/store/products/bragantino/629041265/
    - lib/assets/store/products/bragantino/629041688/
    - lib/assets/store/products/bragantino/629041692/
    - lib/assets/store/products/bragantino/629041693/
    - lib/assets/store/products/bragantino/629041696/
    - lib/assets/store/products/bragantino/629041698/
    - lib/assets/store/products/bragantino/629041699/
    - lib/assets/store/products/bragantino/629041701/
    - lib/assets/store/products/bragantino/629041710/
    - lib/assets/store/products/bragantino/629041712/
    - lib/assets/store/products/bragantino/629041714/
    - lib/assets/store/products/bragantino/629041715/
    - lib/assets/store/products/bragantino/629041716/
    - lib/assets/store/products/bragantino/629041717/
    - lib/assets/store/products/bragantino/629041718/
    - lib/assets/store/products/bragantino/629041719/
    - lib/assets/store/products/bragantino/629041720/
    - lib/assets/store/products/bragantino/629041721/
    - lib/assets/store/products/bragantino/629041722/
    - lib/assets/store/products/bragantino/629041723/
    - lib/assets/store/products/bragantino/629041724/
    - lib/assets/store/products/bragantino/629041726/
    - lib/assets/store/products/bragantino/629041727/
    - lib/assets/store/products/bragantino/629041729/
    - lib/assets/store/products/bragantino/629041730/
    - lib/assets/store/products/bragantino/629041731/
    - lib/assets/store/products/bragantino/629041732/
    - lib/assets/store/products/bragantino/629041734/
    - lib/assets/store/products/bragantino/629041735/
    - lib/assets/store/products/bragantino/629041737/
    - lib/assets/store/products/bragantino/629041738/
    - lib/assets/store/products/bragantino/629041740/
    - lib/assets/store/products/bragantino/629041741/
    - lib/assets/store/products/bragantino/629041743/
    - lib/assets/store/products/bragantino/629041744/
    - lib/assets/store/products/bragantino/629041745/
    - lib/assets/store/products/bragantino/629041746/
    - lib/assets/store/products/bragantino/629041747/
    - lib/assets/store/products/bragantino/629041748/
    - lib/assets/store/products/bragantino/629041749/
    - lib/assets/store/products/bragantino/629041759/
    - lib/assets/store/products/bragantino/629041761/
    - lib/assets/store/products/bragantino/629041762/
    - lib/assets/store/products/bragantino/629041763/
    - lib/assets/store/products/bragantino/629041764/
    - lib/assets/store/products/bragantino/629041765/
    - lib/assets/store/products/bragantino/629041766/
    - lib/assets/store/products/bragantino/629041767/
    - lib/assets/store/products/bragantino/629041774/
    - lib/assets/store/products/bragantino/629041775/
    - lib/assets/store/products/bragantino/629041776/
    - lib/assets/store/products/bragantino/629041777/
    - lib/assets/store/products/bragantino/629041778/
    - lib/assets/store/products/bragantino/629041796/
    - lib/assets/store/products/bragantino/629041797/
    - lib/assets/store/products/bragantino/629041799/
    - lib/assets/store/products/bragantino/629041800/
    - lib/assets/store/products/bragantino/629041801/
    - lib/assets/store/products/bragantino/629041802/
    - lib/assets/store/products/bragantino/629041803/
    - lib/assets/store/products/bragantino/629041806/
    - lib/assets/store/products/bragantino/629041807/
    - lib/assets/store/products/bragantino/629041808/
    - lib/assets/store/products/bragantino/629041825/
    - lib/assets/store/products/bragantino/629041826/
    - lib/assets/store/products/bragantino/629041827/
    - lib/assets/store/products/bragantino/629041828/
    - lib/assets/store/products/bragantino/629041829/
    - lib/assets/store/products/bragantino/629041830/
    - lib/assets/store/products/bragantino/629041831/
    - lib/assets/store/products/bragantino/629041832/
    - lib/assets/store/products/bragantino/629041833/
    - lib/assets/store/products/bragantino/629041834/
    - lib/assets/store/products/bragantino/629041845/
    - lib/assets/store/products/bragantino/629041846/
    - lib/assets/store/products/bragantino/629041847/
    - lib/assets/store/products/bragantino/629041848/
    - lib/assets/store/products/bragantino/629041849/
    - lib/assets/store/products/bragantino/629041850/
    - lib/assets/store/products/bragantino/629041851/
    - lib/assets/store/products/bragantino/629041852/
    - lib/assets/store/products/bragantino/629041853/
    - lib/assets/store/products/bragantino/629041856/
    - lib/assets/store/products/bragantino/629041859/
    - lib/assets/store/products/bragantino/629041937/
    - lib/assets/store/products/bragantino/629041938/
    - lib/assets/store/products/bragantino/629041962/
    - lib/assets/store/products/bragantino/629042008/
    - lib/assets/store/products/bragantino/629042011/
    - lib/assets/store/products/bragantino/629042018/
    - lib/assets/store/products/bragantino/629042020/
    - lib/assets/store/products/bragantino/629042024/
    - lib/assets/store/products/bragantino/629042027/
    - lib/assets/store/products/bragantino/629042030/
    - lib/assets/store/products/bragantino/629042033/
    - lib/assets/store/products/bragantino/629042034/
    - lib/assets/store/products/bragantino/629042035/
    - lib/assets/store/products/bragantino/629042036/
    - lib/assets/store/products/bragantino/629042037/
    - lib/assets/store/products/bragantino/629042038/
    - lib/assets/store/products/bragantino/629042039/
    - lib/assets/store/products/bragantino/629042043/
    - lib/assets/store/products/bragantino/629042044/
    - lib/assets/store/products/bragantino/629042045/
    - lib/assets/store/products/bragantino/629042046/
    - lib/assets/store/products/bragantino/629042049/
    - lib/assets/store/products/bragantino/629042050/
    - lib/assets/store/products/bragantino/629042051/
    - lib/assets/store/products/bragantino/629042052/
    - lib/assets/store/products/bragantino/629042053/
    - lib/assets/store/products/bragantino/629042054/
    - lib/assets/store/products/bragantino/629042055/
    - lib/assets/store/products/bragantino/629042578/
    - lib/assets/store/products/bragantino/629042579/
    - lib/assets/store/products/bragantino/629042580/
    - lib/assets/store/products/bragantino/629042581/
    - lib/assets/store/products/bragantino/629042582/
    - lib/assets/store/products/bragantino/629042584/
    - lib/assets/store/products/bragantino/629042585/
    - lib/assets/store/products/bragantino/629042586/
    - lib/assets/store/products/bragantino/629042671/
    - lib/assets/store/products/bragantino/629042672/
    - lib/assets/store/products/bragantino/629042673/
    - lib/assets/store/products/bragantino/629042678/
    - lib/assets/store/products/bragantino/629042679/
    - lib/assets/store/products/bragantino/629042680/
    - lib/assets/store/products/bragantino/629042681/
    - lib/assets/store/products/bragantino/629042709/
    - lib/assets/store/products/bragantino/629042853/
    - lib/assets/store/products/bragantino/629042854/
    - lib/assets/store/products/bragantino/629042855/
    - lib/assets/store/products/bragantino/629042856/
    - lib/assets/store/products/bragantino/629042857/
    - lib/assets/store/products/bragantino/629042858/
    - lib/assets/store/banners/bragantino/
    - lib/assets/store/promo/
    - lib/assets/videos/
    - lib/assets/audio/club/hinos/
    - lib/assets/audio/club/musicas/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets_gen/app_icon.png"
  adaptive_icon_background: "#004C1B"
  adaptive_icon_foreground: "assets_gen/app_icon_foreground.png"
  web:
    generate: true
    image_path: "assets_gen/app_icon.png"
    background_color: "#004C1B"
    theme_color: "#004C1B"

flutter_native_splash:
  color: "#F6F8F7"
  android_12:
    color: "#F6F8F7"
  web: false
