/// Fotos do elenco embutidas no app (offline, sem depender de URL externa).
/// Chave = id do jogador (mesmo usado em squad_members e no goias_squad do
/// jogo de escalação); valor = caminho do asset.
const squadPhotoAssets = {
  'tadeu': 'lib/assets/squad/goias/tadeu.jpg',
  'ezequiel': 'lib/assets/squad/goias/ezequiel.jpg',
  'murillo_victorio': 'lib/assets/squad/goias/murillo_victorio.jpg',
  'thiago_rodrigues': 'lib/assets/squad/goias/thiago_rodrigues.jpg',
  'luisao': 'lib/assets/squad/goias/luisao.jpg',
  'lucas_ribeiro': 'lib/assets/squad/goias/lucas_ribeiro.jpg',
  'luiz_felipe': 'lib/assets/squad/goias/luiz_felipe.jpg',
  'ramon_menezes': 'lib/assets/squad/goias/ramon_menezes.jpg',
  'murilo_camara': 'lib/assets/squad/goias/murilo_camara.jpg',
  'rodrigo_soares': 'lib/assets/squad/goias/rodrigo_soares.jpg',
  'marcos_vinicius': 'lib/assets/squad/goias/marcos_vinicius.jpg',
  'nicolas': 'lib/assets/squad/goias/nicolas.jpg',
  'danilo': 'lib/assets/squad/goias/danilo.jpg',
  'djalma': 'lib/assets/squad/goias/djalma.jpg',
  'lourenco': 'lib/assets/squad/goias/lourenco.jpg',
  'filipe_machado': 'lib/assets/squad/goias/filipe_machado.jpg',
  'baldoria': 'lib/assets/squad/goias/baldoria.jpg',
  'juninho': 'lib/assets/squad/goias/juninho.jpg',
  'lucas_rodrigues': 'lib/assets/squad/goias/lucas_rodrigues.jpg',
  'gege': 'lib/assets/squad/goias/gege.jpg',
  'lucas_lima': 'lib/assets/squad/goias/lucas_lima.jpg',
  'brayann': 'lib/assets/squad/goias/brayann.jpg',
  'wellington_rato': 'lib/assets/squad/goias/wellington_rato.jpg',
  'pedrinho': 'lib/assets/squad/goias/pedrinho.jpg',
  'anselmo_ramon': 'lib/assets/squad/goias/anselmo_ramon.jpg',
  'cadu': 'lib/assets/squad/goias/cadu.jpg',
  'felipe_clemente': 'lib/assets/squad/goias/felipe_clemente.jpg',
  'jean_carlos': 'lib/assets/squad/goias/jean_carlos.jpg',
  'halerrandrio': 'lib/assets/squad/goias/halerrandrio.jpg',
  'esli_garcia': 'lib/assets/squad/goias/esli_garcia.jpg',
  'kadu_sousa': 'lib/assets/squad/goias/kadu_sousa.jpg',
};
