/// Fotos do elenco embutidas no app (offline, sem depender de URL externa).
/// Chave = id do jogador (mesmo usado em squad_members e no goias_squad do
/// jogo de escalação); valor = caminho do asset.
const squadPhotoAssets = {
  'tadeu': 'lib/assets/squad/tadeu.jpg',
  'ezequiel': 'lib/assets/squad/ezequiel.jpg',
  'murillo_victorio': 'lib/assets/squad/murillo_victorio.jpg',
  'thiago_rodrigues': 'lib/assets/squad/thiago_rodrigues.jpg',
  'luisao': 'lib/assets/squad/luisao.jpg',
  'lucas_ribeiro': 'lib/assets/squad/lucas_ribeiro.jpg',
  'luiz_felipe': 'lib/assets/squad/luiz_felipe.jpg',
  'ramon_menezes': 'lib/assets/squad/ramon_menezes.jpg',
  'murilo_camara': 'lib/assets/squad/murilo_camara.jpg',
  'rodrigo_soares': 'lib/assets/squad/rodrigo_soares.jpg',
  'marcos_vinicius': 'lib/assets/squad/marcos_vinicius.jpg',
  'nicolas': 'lib/assets/squad/nicolas.jpg',
  'danilo': 'lib/assets/squad/danilo.jpg',
  'djalma': 'lib/assets/squad/djalma.jpg',
  'lourenco': 'lib/assets/squad/lourenco.jpg',
  'filipe_machado': 'lib/assets/squad/filipe_machado.jpg',
  'baldoria': 'lib/assets/squad/baldoria.jpg',
  'juninho': 'lib/assets/squad/juninho.jpg',
  'lucas_rodrigues': 'lib/assets/squad/lucas_rodrigues.jpg',
  'gege': 'lib/assets/squad/gege.jpg',
  'lucas_lima': 'lib/assets/squad/lucas_lima.jpg',
  'brayann': 'lib/assets/squad/brayann.jpg',
  'wellington_rato': 'lib/assets/squad/wellington_rato.jpg',
  'pedrinho': 'lib/assets/squad/pedrinho.jpg',
  'anselmo_ramon': 'lib/assets/squad/anselmo_ramon.jpg',
  'cadu': 'lib/assets/squad/cadu.jpg',
  'felipe_clemente': 'lib/assets/squad/felipe_clemente.jpg',
  'jean_carlos': 'lib/assets/squad/jean_carlos.jpg',
  'halerrandrio': 'lib/assets/squad/halerrandrio.jpg',
  'esli_garcia': 'lib/assets/squad/esli_garcia.jpg',
  'kadu_sousa': 'lib/assets/squad/kadu_sousa.jpg',
};
