class GoiasPlayer {
  const GoiasPlayer({required this.name, this.personId, this.aliases = const []});

  final String name;

  /// Identidade canônica paralela (`people.id`) quando a Etapa F6
  /// conseguiu resolver com segurança — `null` pros casos ambíguos/não
  /// resolvidos (a maioria: só 41/215 tem personId hoje). Nunca usado no
  /// gameplay (isso continua sendo `acceptedAnswers`), só como metadado
  /// pra futuras integrações e pra detectar colisão de texto entre
  /// pessoas diferentes no autocomplete.
  final String? personId;
  final List<String> aliases;
}

const goiasPlayers = <GoiasPlayer>[
  GoiasPlayer(name: 'Lumumba'),
  GoiasPlayer(name: 'Triel'),
  GoiasPlayer(name: 'Emílio'),
  GoiasPlayer(name: 'Matinha'),
  GoiasPlayer(name: 'Cláudio'),
  GoiasPlayer(name: 'Tuíra'),
  GoiasPlayer(name: 'Hertz'),
  GoiasPlayer(name: 'Paghetti'),
  GoiasPlayer(name: 'Lucinho'),
  GoiasPlayer(name: 'Lincoln', aliases: ['Leão da Serra']),
  GoiasPlayer(name: 'Raimundinho'),
  GoiasPlayer(name: 'Macalé'),
  GoiasPlayer(name: 'Luvanor'),
  GoiasPlayer(name: 'Niltinho'),
  GoiasPlayer(name: 'Túlio Maravilha', aliases: ['Túlio']),
  GoiasPlayer(name: 'Eduardo Heuser'),
  GoiasPlayer(name: 'Wilson Goiano'),
  GoiasPlayer(name: 'Richard'),
  GoiasPlayer(name: 'Jorge Batata', aliases: ['Batata']),
  GoiasPlayer(name: 'Dalton'),
  GoiasPlayer(name: 'Wallace'),
  GoiasPlayer(name: 'Fagundes'),
  GoiasPlayer(name: 'Kléber'),
  GoiasPlayer(name: 'Índio'),
  GoiasPlayer(name: 'Sílvio Criciúma'),
  GoiasPlayer(name: 'Augusto'),
  GoiasPlayer(name: 'Reidner'),
  GoiasPlayer(name: 'Lúcio'),
  GoiasPlayer(name: 'Alex Dias'),
  GoiasPlayer(name: 'Jaques'),
  GoiasPlayer(name: 'Evandro'),
  GoiasPlayer(name: 'Neném'),
  GoiasPlayer(name: 'Álvaro'),
  GoiasPlayer(name: 'Fernando Nunes'),
  GoiasPlayer(name: 'Cacá'),
  GoiasPlayer(name: 'Marcelo Batista'),
  GoiasPlayer(name: 'Lira'),
  GoiasPlayer(name: 'Alexandre'),
  GoiasPlayer(name: 'Fabão'),
  GoiasPlayer(name: 'Leandro Smith'),
  GoiasPlayer(name: 'Michel Santana'),
  GoiasPlayer(name: 'Marabá'),
  GoiasPlayer(name: 'Tiago Fraga'),
  GoiasPlayer(name: 'Caíco'),
  GoiasPlayer(name: 'Dimba'),
  GoiasPlayer(name: 'Pedro Paulo'),
  GoiasPlayer(name: 'Esquerdinha'),
  GoiasPlayer(name: 'Gustavo'),
  GoiasPlayer(name: 'Cléber Goiano'),
  GoiasPlayer(name: 'Danilo Portugal'),
  GoiasPlayer(name: 'Tácio'),
  GoiasPlayer(name: 'Gil Baiano'),
  GoiasPlayer(name: 'Wando'),
  GoiasPlayer(name: 'Rodrigo Calaça', aliases: ['Calaça']),
  GoiasPlayer(name: 'Rafael Dias'),
  GoiasPlayer(name: 'Júlio Santos'),
  GoiasPlayer(name: 'André Dias'),
  GoiasPlayer(name: 'Andrezinho'),
  GoiasPlayer(name: 'Rogério Corrêa'),
  GoiasPlayer(name: 'Aldo'),
  GoiasPlayer(name: 'João Paulo'),
  GoiasPlayer(name: 'Luciano Almeida'),
  GoiasPlayer(name: 'André Leone'),
  GoiasPlayer(name: 'Rômulo'),
  GoiasPlayer(name: 'Cléber Gaúcho'),
  GoiasPlayer(name: 'Juliano'),
  GoiasPlayer(name: 'Mário Jardel', aliases: ['Jardel']),
  GoiasPlayer(name: 'Romerito'),
  GoiasPlayer(name: 'Wendell Lira'),
  GoiasPlayer(name: 'Edmílson Matias'),
  GoiasPlayer(name: 'Marcelo Carioca'),
  GoiasPlayer(name: 'Danilo Dias'),
  GoiasPlayer(name: 'Ramalho'),
  GoiasPlayer(name: 'Fernando'),
  GoiasPlayer(name: 'Henrique'),
  GoiasPlayer(name: 'Alex Terra'),
  GoiasPlayer(name: 'Paulo Henrique'),
  GoiasPlayer(name: 'Anderson Aquino'),
  GoiasPlayer(name: 'Pituca'),
  GoiasPlayer(name: 'Schwenck'),
  GoiasPlayer(name: 'Felipe'),
  GoiasPlayer(name: 'Rinaldo'),
  GoiasPlayer(name: 'Frontini'),
  GoiasPlayer(name: 'Fábio Bahia'),
  GoiasPlayer(name: 'Alex Ferreira'),
  GoiasPlayer(name: 'Rafael Marques'),
  GoiasPlayer(name: 'Leandro Euzébio'),
  GoiasPlayer(name: 'Wellington Monteiro'),
  GoiasPlayer(name: 'Valmir Lucas', personId: '64af0c2c-ea56-5ea9-871d-59b6a4892570'),
  GoiasPlayer(name: 'Marcão'),
  GoiasPlayer(name: 'Carlos Alberto', personId: '02a0df33-8a89-5b78-8011-00868b240029'),
  GoiasPlayer(name: 'Bernardo'),
  GoiasPlayer(name: 'Hugo'),
  GoiasPlayer(name: 'Éverton Santos'),
  GoiasPlayer(name: 'Otacílio Neto', personId: '22588c95-9663-569a-9616-e2b1d7a0cb76'),
  GoiasPlayer(name: 'Bruno Meneghel'),
  GoiasPlayer(name: 'Wellington Saci', personId: '9a4c2c66-0936-5921-8714-95714db79daa', aliases: ['Saci']),
  GoiasPlayer(name: 'Renan Brito'),
  GoiasPlayer(name: 'Édson'),
  GoiasPlayer(name: 'Ramón', personId: 'e8b6e0ec-2a1a-52d5-b399-aee42c146690'),
  GoiasPlayer(name: 'Renan Oliveira', personId: '8a55a430-aff6-5611-8ae8-d21b6c6a06ee'),
  GoiasPlayer(name: 'Thiago Mendes', personId: '67bdde7d-fad6-516d-9a0b-ff81a3f6c765'),
  GoiasPlayer(name: 'Felipe Amorim'),
  GoiasPlayer(name: 'Júnior Viçosa', aliases: ['Viçosa']),
  GoiasPlayer(name: 'Eduardo Sasha', personId: 'cd2285a5-82d6-59a5-bb5b-88b88b1afa8d', aliases: ['Sasha']),
  GoiasPlayer(name: 'William Matheus', personId: '03fca98b-17cd-5484-838d-6690bb677f70'),
  GoiasPlayer(name: 'David', personId: '68880467-49ea-5661-8f08-2a177a060558'),
  GoiasPlayer(name: 'Jackson'),
  GoiasPlayer(name: 'Wallinson'),
  GoiasPlayer(name: 'Alex Alves'),
  GoiasPlayer(name: 'Felipe Macedo'),
  GoiasPlayer(name: 'Léo Veloso'),
  GoiasPlayer(name: 'Lucas Lima', personId: 'd58d5ae2-85c7-5336-80b6-0f4c0ed0a24b'),
  GoiasPlayer(name: 'Mário Sérgio'),
  GoiasPlayer(name: 'Clayton'),
  GoiasPlayer(name: 'Moisés'),
  GoiasPlayer(name: 'Abuda'),
  GoiasPlayer(name: 'Tiago Real'),
  GoiasPlayer(name: 'Raphael Luz'),
  GoiasPlayer(name: 'Assuério'),
  GoiasPlayer(name: 'Murilo Henrique'),
  GoiasPlayer(name: 'Liniker'),
  GoiasPlayer(name: 'Samuel Rosa'),
  GoiasPlayer(name: 'Léo Bonatini'),
  GoiasPlayer(name: 'Bruno Mineiro'),
  GoiasPlayer(name: 'Márcio'),
  GoiasPlayer(name: 'Ivan'),
  GoiasPlayer(name: 'Fred'),
  GoiasPlayer(name: 'Anderson Salles'),
  GoiasPlayer(name: 'Rafael Forster'),
  GoiasPlayer(name: 'Artur Vieira'),
  GoiasPlayer(name: 'Wesley Matos'),
  GoiasPlayer(name: 'David Duarte'),
  GoiasPlayer(name: 'Juninho', personId: 'b9d994d7-3605-5e6e-89ca-7d223f87d14a'),
  GoiasPlayer(name: 'Diogo Barbosa'),
  GoiasPlayer(name: 'Willian Oliveira', personId: '3390bf06-81e1-55dc-ae35-70bd3306b0ef'),
  GoiasPlayer(name: 'Ramires'),
  GoiasPlayer(name: 'Léo Sena'),
  GoiasPlayer(name: 'Patrick'),
  GoiasPlayer(name: 'Arthur Rezende'),
  GoiasPlayer(name: 'Wendel'),
  GoiasPlayer(name: 'Jhon Cley'),
  GoiasPlayer(name: 'Léo Lima'),
  GoiasPlayer(name: 'Daniel Carvalho'),
  GoiasPlayer(name: 'Higor Leite'),
  GoiasPlayer(name: 'Léo Gamalho'),
  GoiasPlayer(name: 'Rossi'),
  GoiasPlayer(name: 'Carlos Eduardo'),
  GoiasPlayer(name: 'Cléo'),
  GoiasPlayer(name: 'Sueliton'),
  GoiasPlayer(name: 'Eduardo Brock'),
  GoiasPlayer(name: 'Victor Ramos'),
  GoiasPlayer(name: 'Renato Cajá'),
  GoiasPlayer(name: 'Sidão'),
  GoiasPlayer(name: 'Rafael Vaz'),
  GoiasPlayer(name: 'Fábio Sanches'),
  GoiasPlayer(name: 'Paulo Ricardo'),
  GoiasPlayer(name: 'Iago Mendonça'),
  GoiasPlayer(name: 'Heron'),
  GoiasPlayer(name: 'Marcelo Hermes'),
  GoiasPlayer(name: 'Alan Ruschel'),
  GoiasPlayer(name: 'Yago Felipe'),
  GoiasPlayer(name: 'Giovanni Augusto'),
  GoiasPlayer(name: 'Marlone'),
  GoiasPlayer(name: 'Leandro Barcia'),
  GoiasPlayer(name: 'Vinícius Lopes'),
  GoiasPlayer(name: 'Kayke'),
  GoiasPlayer(name: 'Brenner'),
  GoiasPlayer(name: 'Junior Brandão'),
  GoiasPlayer(name: 'Rafael Elias'),
  GoiasPlayer(name: 'Daniel Bessa'),
  GoiasPlayer(name: 'Sandro'),
  GoiasPlayer(name: 'Reynaldo'),
  GoiasPlayer(name: 'Artur', personId: 'd8600945-4f69-5c47-a42d-662921fa9557'),
  GoiasPlayer(name: 'Dieguinho', personId: '79902fc2-167c-5af2-a303-8044dbc6cff5'),
  GoiasPlayer(name: 'Élvis', personId: '9548aabb-4559-55f4-9bff-bd3c8b1984b9'),
  GoiasPlayer(name: 'Caio Vinícius', personId: '12b59f80-07bb-584d-a7eb-976739c07c6c'),
  GoiasPlayer(name: 'Dadá Belmonte', personId: 'dbedb80d-a764-52a6-905f-ff01f9a3cdea', aliases: ['Dadá']),
  GoiasPlayer(name: 'Nicolas'),
  GoiasPlayer(name: 'Fellipe Bastos', personId: '0da8b2fc-a261-554a-a35f-4ad3ef422112'),
  GoiasPlayer(name: 'Maguinho', personId: 'bef7397d-fe4d-5d35-ac92-46c450198b3c'),
  GoiasPlayer(name: 'Lucas Halter', personId: '14bbaa8e-4309-56a6-9e1c-e387dcdbfde8'),
  GoiasPlayer(name: 'Bruno Melo', personId: 'd274fa09-a83e-5526-86cd-2caf8244a4d3'),
  GoiasPlayer(name: 'Sander', personId: '662105cf-1e18-5af3-a24d-e5afb7f37b6d'),
  GoiasPlayer(name: 'Zé Ricardo', personId: 'd5256bb9-5c40-5354-87d0-38d304523039'),
  GoiasPlayer(name: 'Everton Morelli', personId: '9c4d1f1b-de75-5e63-8bda-ffab87d20969', aliases: ['Morelli']),
  GoiasPlayer(name: 'Julián Palacios', personId: 'c6483fa7-ac39-52c9-9bbd-01ede638ba97', aliases: ['Palacios']),
  GoiasPlayer(name: 'Matheus Peixoto', personId: 'd1caad47-b1a6-5d1f-b0e3-c7fad9a8212d', aliases: ['Peixoto']),
  GoiasPlayer(name: 'Diego Gonçalves', personId: '9f51dcb7-51c8-5f95-8b11-fc17e327b1f3'),
  GoiasPlayer(name: 'Bruno Santos'),
  GoiasPlayer(name: 'Alesson'),
  GoiasPlayer(name: 'Eduardo Simioni', aliases: ['Simioni']),
  GoiasPlayer(name: 'Thiago Rodrigues', personId: '0b374c05-3edd-5cbb-9ddf-71b1b37e79ba'),
  GoiasPlayer(name: 'Lucas Ribeiro', personId: '36ed37b5-02be-5117-91d6-a62d5236505f'),
  GoiasPlayer(name: 'Messias', personId: '2b370606-4dd7-585c-867d-0bf3b2fcd0de'),
  GoiasPlayer(name: 'Martín Rea'),
  GoiasPlayer(name: 'Yan Souto'),
  GoiasPlayer(name: 'Sidimar'),
  GoiasPlayer(name: 'David Braz'),
  GoiasPlayer(name: 'Matheus Babi'),
  GoiasPlayer(name: 'Higor Meritão'),
  GoiasPlayer(name: 'Régis'),
  GoiasPlayer(name: 'Paulo Baya', aliases: ['Baya']),
  GoiasPlayer(name: 'Thiago Galhardo'),
  GoiasPlayer(name: 'Rafael Gava'),
  GoiasPlayer(name: 'Wellington Rato', personId: '4dd73b43-f2ac-536a-8b22-ab4f7c125c68', aliases: ['Rato']),
  GoiasPlayer(name: 'Jajá', personId: '12aff9c4-2a6e-595a-a725-cf66adc7ba88'),
  GoiasPlayer(name: 'Anselmo Ramon', personId: 'e277edea-70b1-5092-ad39-48be1a5297d6'),
  GoiasPlayer(name: 'Pedrinho', personId: '879326ba-8353-5fc8-ab0f-c6ca4646a143'),
  GoiasPlayer(name: 'Diego Caito', personId: '9a740e1a-b0c0-53c9-9adf-f675f0cba5ca', aliases: ['Caito']),
  GoiasPlayer(name: 'Luisão', personId: '91e2722f-6fce-535e-9bd9-d2420889b1af'),
  GoiasPlayer(name: 'Filipe Machado', personId: 'ce0c99ff-f0a3-5743-9bf6-3cfb7ecfcf5f'),
  GoiasPlayer(name: 'Gegê', personId: '88a5f4a0-ed1a-5a0f-b2d9-0294157789dd'),
  GoiasPlayer(name: 'Lourenço', personId: 'be72ef65-0fdc-5f2a-b09a-ff8da6a279fb'),
  GoiasPlayer(name: 'Jean Carlos', personId: '424f8724-6855-58d6-ad36-24e2d9bdd7f6'),
];
