class GoiasPlayer {
  const GoiasPlayer({required this.name, this.aliases = const []});

  final String name;
  final List<String> aliases;
}

const goiasPlayers = <GoiasPlayer>[
  GoiasPlayer(name: 'Lumumba'),
  GoiasPlayer(name: 'Triel'),
  GoiasPlayer(name: 'Emílio'),
  GoiasPlayer(name: 'Matinha'),
  GoiasPlayer(name: 'Cláudio'),
  GoiasPlayer(name: 'Tuíra'),
  GoiasPlayer(name: 'Hertz'),
  GoiasPlayer(name: 'Paghetti'),
  GoiasPlayer(name: 'Lucinho'),
  GoiasPlayer(name: 'Lincoln', aliases: ['Leão da Serra']),
  GoiasPlayer(name: 'Raimundinho'),
  GoiasPlayer(name: 'Macalé'),
  GoiasPlayer(name: 'Luvanor'),
  GoiasPlayer(name: 'Niltinho'),
  GoiasPlayer(name: 'Túlio Maravilha', aliases: ['Túlio']),
  GoiasPlayer(name: 'Eduardo Heuser'),
  GoiasPlayer(name: 'Wilson Goiano'),
  GoiasPlayer(name: 'Richard'),
  GoiasPlayer(name: 'Jorge Batata', aliases: ['Batata']),
  GoiasPlayer(name: 'Dalton'),
  GoiasPlayer(name: 'Wallace'),
  GoiasPlayer(name: 'Fagundes'),
  GoiasPlayer(name: 'Kléber'),
  GoiasPlayer(name: 'Índio'),
  GoiasPlayer(name: 'Sílvio Criciúma'),
  GoiasPlayer(name: 'Augusto'),
  GoiasPlayer(name: 'Reidner'),
  GoiasPlayer(name: 'Lúcio'),
  GoiasPlayer(name: 'Alex Dias'),
  GoiasPlayer(name: 'Jaques'),
  GoiasPlayer(name: 'Evandro'),
  GoiasPlayer(name: 'Neném'),
  GoiasPlayer(name: 'Álvaro'),
  GoiasPlayer(name: 'Fernando Nunes'),
  GoiasPlayer(name: 'Cacá'),
  GoiasPlayer(name: 'Marcelo Batista'),
  GoiasPlayer(name: 'Lira'),
  GoiasPlayer(name: 'Alexandre'),
  GoiasPlayer(name: 'Fabão'),
  GoiasPlayer(name: 'Leandro Smith'),
  GoiasPlayer(name: 'Michel Santana'),
  GoiasPlayer(name: 'Marabá'),
  GoiasPlayer(name: 'Tiago Fraga'),
  GoiasPlayer(name: 'Caíco'),
  GoiasPlayer(name: 'Dimba'),
  GoiasPlayer(name: 'Pedro Paulo'),
  GoiasPlayer(name: 'Esquerdinha'),
  GoiasPlayer(name: 'Gustavo'),
  GoiasPlayer(name: 'Cléber Goiano'),
  GoiasPlayer(name: 'Danilo Portugal'),
  GoiasPlayer(name: 'Tácio'),
  GoiasPlayer(name: 'Gil Baiano'),
  GoiasPlayer(name: 'Wando'),
  GoiasPlayer(name: 'Rodrigo Calaça', aliases: ['Calaça']),
  GoiasPlayer(name: 'Rafael Dias'),
  GoiasPlayer(name: 'Júlio Santos'),
  GoiasPlayer(name: 'André Dias'),
  GoiasPlayer(name: 'Andrezinho'),
  GoiasPlayer(name: 'Rogério Corrêa'),
  GoiasPlayer(name: 'Aldo'),
  GoiasPlayer(name: 'João Paulo'),
  GoiasPlayer(name: 'Luciano Almeida'),
  GoiasPlayer(name: 'André Leone'),
  GoiasPlayer(name: 'Rômulo'),
  GoiasPlayer(name: 'Cléber Gaúcho'),
  GoiasPlayer(name: 'Juliano'),
  GoiasPlayer(name: 'Mário Jardel', aliases: ['Jardel']),
  GoiasPlayer(name: 'Romerito'),
  GoiasPlayer(name: 'Wendell Lira'),
  GoiasPlayer(name: 'Edmílson Matias'),
  GoiasPlayer(name: 'Marcelo Carioca'),
  GoiasPlayer(name: 'Danilo Dias'),
  GoiasPlayer(name: 'Ramalho'),
  GoiasPlayer(name: 'Fernando'),
  GoiasPlayer(name: 'Henrique'),
  GoiasPlayer(name: 'Alex Terra'),
  GoiasPlayer(name: 'Paulo Henrique'),
  GoiasPlayer(name: 'Anderson Aquino'),
  GoiasPlayer(name: 'Pituca'),
  GoiasPlayer(name: 'Schwenck'),
  GoiasPlayer(name: 'Felipe'),
  GoiasPlayer(name: 'Rinaldo'),
  GoiasPlayer(name: 'Frontini'),
  GoiasPlayer(name: 'Fábio Bahia'),
  GoiasPlayer(name: 'Alex Ferreira'),
  GoiasPlayer(name: 'Rafael Marques'),
  GoiasPlayer(name: 'Leandro Euzébio'),
  GoiasPlayer(name: 'Wellington Monteiro'),
  GoiasPlayer(name: 'Valmir Lucas'),
  GoiasPlayer(name: 'Marcão'),
  GoiasPlayer(name: 'Carlos Alberto'),
  GoiasPlayer(name: 'Bernardo'),
  GoiasPlayer(name: 'Hugo'),
  GoiasPlayer(name: 'Éverton Santos'),
  GoiasPlayer(name: 'Otacílio Neto'),
  GoiasPlayer(name: 'Bruno Meneghel'),
  GoiasPlayer(name: 'Wellington Saci', aliases: ['Saci']),
  GoiasPlayer(name: 'Renan Brito'),
  GoiasPlayer(name: 'Édson'),
  GoiasPlayer(name: 'Ramón'),
  GoiasPlayer(name: 'Renan Oliveira'),
  GoiasPlayer(name: 'Thiago Mendes'),
  GoiasPlayer(name: 'Felipe Amorim'),
  GoiasPlayer(name: 'Júnior Viçosa', aliases: ['Viçosa']),
  GoiasPlayer(name: 'Eduardo Sasha', aliases: ['Sasha']),
  GoiasPlayer(name: 'William Matheus'),
  GoiasPlayer(name: 'David'),
  GoiasPlayer(name: 'Jackson'),
  GoiasPlayer(name: 'Wallinson'),
  GoiasPlayer(name: 'Alex Alves'),
  GoiasPlayer(name: 'Felipe Macedo'),
  GoiasPlayer(name: 'Léo Veloso'),
  GoiasPlayer(name: 'Lucas Lima'),
  GoiasPlayer(name: 'Mário Sérgio'),
  GoiasPlayer(name: 'Clayton'),
  GoiasPlayer(name: 'Moisés'),
  GoiasPlayer(name: 'Abuda'),
  GoiasPlayer(name: 'Tiago Real'),
  GoiasPlayer(name: 'Raphael Luz'),
  GoiasPlayer(name: 'Assuério'),
  GoiasPlayer(name: 'Murilo Henrique'),
  GoiasPlayer(name: 'Liniker'),
  GoiasPlayer(name: 'Samuel Rosa'),
  GoiasPlayer(name: 'Léo Bonatini'),
  GoiasPlayer(name: 'Bruno Mineiro'),
  GoiasPlayer(name: 'Márcio'),
  GoiasPlayer(name: 'Ivan'),
  GoiasPlayer(name: 'Fred'),
  GoiasPlayer(name: 'Anderson Salles'),
  GoiasPlayer(name: 'Rafael Forster'),
  GoiasPlayer(name: 'Artur Vieira'),
  GoiasPlayer(name: 'Wesley Matos'),
  GoiasPlayer(name: 'David Duarte'),
  GoiasPlayer(name: 'Juninho'),
  GoiasPlayer(name: 'Diogo Barbosa'),
  GoiasPlayer(name: 'Willian Oliveira'),
  GoiasPlayer(name: 'Ramires'),
  GoiasPlayer(name: 'Léo Sena'),
  GoiasPlayer(name: 'Patrick'),
  GoiasPlayer(name: 'Arthur Rezende'),
  GoiasPlayer(name: 'Wendel'),
  GoiasPlayer(name: 'Jhon Cley'),
  GoiasPlayer(name: 'Léo Lima'),
  GoiasPlayer(name: 'Daniel Carvalho'),
  GoiasPlayer(name: 'Higor Leite'),
  GoiasPlayer(name: 'Léo Gamalho'),
  GoiasPlayer(name: 'Rossi'),
  GoiasPlayer(name: 'Carlos Eduardo'),
  GoiasPlayer(name: 'Cléo'),
  GoiasPlayer(name: 'Sueliton'),
  GoiasPlayer(name: 'Eduardo Brock'),
  GoiasPlayer(name: 'Victor Ramos'),
  GoiasPlayer(name: 'Renato Cajá'),
  GoiasPlayer(name: 'Sidão'),
  GoiasPlayer(name: 'Rafael Vaz'),
  GoiasPlayer(name: 'Fábio Sanches'),
  GoiasPlayer(name: 'Paulo Ricardo'),
  GoiasPlayer(name: 'Iago Mendonça'),
  GoiasPlayer(name: 'Heron'),
  GoiasPlayer(name: 'Marcelo Hermes'),
  GoiasPlayer(name: 'Alan Ruschel'),
  GoiasPlayer(name: 'Yago Felipe'),
  GoiasPlayer(name: 'Giovanni Augusto'),
  GoiasPlayer(name: 'Marlone'),
  GoiasPlayer(name: 'Leandro Barcia'),
  GoiasPlayer(name: 'Vinícius Lopes'),
  GoiasPlayer(name: 'Kayke'),
  GoiasPlayer(name: 'Brenner'),
  GoiasPlayer(name: 'Junior Brandão'),
  GoiasPlayer(name: 'Rafael Elias'),
  GoiasPlayer(name: 'Daniel Bessa'),
  GoiasPlayer(name: 'Sandro'),
  GoiasPlayer(name: 'Reynaldo'),
  GoiasPlayer(name: 'Artur'),
  GoiasPlayer(name: 'Dieguinho'),
  GoiasPlayer(name: 'Élvis'),
  GoiasPlayer(name: 'Caio Vinícius'),
  GoiasPlayer(name: 'Dadá Belmonte', aliases: ['Dadá']),
  GoiasPlayer(name: 'Nicolas'),
  GoiasPlayer(name: 'Fellipe Bastos'),
  GoiasPlayer(name: 'Maguinho'),
  GoiasPlayer(name: 'Lucas Halter'),
  GoiasPlayer(name: 'Bruno Melo'),
  GoiasPlayer(name: 'Sander'),
  GoiasPlayer(name: 'Zé Ricardo'),
  GoiasPlayer(name: 'Everton Morelli', aliases: ['Morelli']),
  GoiasPlayer(name: 'Julián Palacios', aliases: ['Palacios']),
  GoiasPlayer(name: 'Matheus Peixoto', aliases: ['Peixoto']),
  GoiasPlayer(name: 'Diego Gonçalves'),
  GoiasPlayer(name: 'Bruno Santos'),
  GoiasPlayer(name: 'Alesson'),
  GoiasPlayer(name: 'Eduardo Simioni', aliases: ['Simioni']),
  GoiasPlayer(name: 'Thiago Rodrigues'),
  GoiasPlayer(name: 'Lucas Ribeiro'),
  GoiasPlayer(name: 'Messias'),
  GoiasPlayer(name: 'Martín Rea'),
  GoiasPlayer(name: 'Yan Souto'),
  GoiasPlayer(name: 'Sidimar'),
  GoiasPlayer(name: 'David Braz'),
  GoiasPlayer(name: 'Matheus Babi'),
  GoiasPlayer(name: 'Higor Meritão'),
  GoiasPlayer(name: 'Régis'),
  GoiasPlayer(name: 'Paulo Baya', aliases: ['Baya']),
  GoiasPlayer(name: 'Thiago Galhardo'),
  GoiasPlayer(name: 'Rafael Gava'),
  GoiasPlayer(name: 'Wellington Rato', aliases: ['Rato']),
  GoiasPlayer(name: 'Jajá'),
  GoiasPlayer(name: 'Anselmo Ramon'),
  GoiasPlayer(name: 'Pedrinho'),
  GoiasPlayer(name: 'Diego Caito', aliases: ['Caito']),
  GoiasPlayer(name: 'Luisão'),
  GoiasPlayer(name: 'Filipe Machado'),
  GoiasPlayer(name: 'Gegê'),
  GoiasPlayer(name: 'Lourenço'),
  GoiasPlayer(name: 'Jean Carlos'),
];
