import 'package:goias_app/features/arena/games/player_identity/domain/player_identity_models.dart';

/// As 21 referências históricas de jogadores usadas pelo jogo "Que craque
/// esmeraldino é você?" — RECALIBRADO (v2, 2026-09-01) a partir do dataset
/// original de 19: removidos Pedro Raul e Egídio, adicionados Rafael Tolói,
/// Uidemar, Douglas Pereira dos Santos e Erik.
///
/// IMPORTANTE (repetido do pedido original, pra quem for mexer aqui
/// depois): os valores 0–100 NÃO são ratings de qualidade geral — são
/// vetores EDITORIAIS usados só pra representar o ESTILO de cada jogador
/// dentro da experiência. NUNCA alterar esses números durante uma
/// implementação; qualquer recalibração é decisão explícita, feita aqui e
/// em nenhum outro lugar (a UI nunca deve depender do valor exato, só
/// consumir esta lista). Fotos ficam fora desta v1 de propósito
/// (`assetPath`/`imageUrl` sempre `null`).
///
/// v2 usa uma escala RECENTRADA em torno de ~50 (não ~75-85 como a
/// primeira tentativa) — a média por dimensão do dataset foi calibrada
/// pra ficar perto da média que o PRÓPRIO motor de perguntas produz pra um
/// usuário real (calculado empiricamente sobre as 4^10 combinações, ver
/// `tool/player_identity_calibration.dart`). Uma cartela de referência
/// centrada muito mais alto que o que o questionário consegue de fato
/// gerar faz a comparação (mesmo com z-score) favorecer sistematicamente
/// quem estiver com o perfil mais "baixo/moderado" entre as referências,
/// não necessariamente quem é mais parecido — foi exatamente essa
/// descoberta que motivou a recentragem.
const playerIdentityReferences = <PlayerIdentityReference>[
  PlayerIdentityReference(
    id: 'harlei',
    name: 'Harlei',
    period: '1999–2014',
    creativity: 27,
    definition: 16,
    leadership: 87,
    intensity: 45,
    technique: 34,
    tactics: 80,
    confidence: 'high',
  ),
  PlayerIdentityReference(
    id: 'tadeu',
    name: 'Tadeu',
    period: 'desde 2019',
    creativity: 17,
    definition: 15,
    leadership: 84,
    intensity: 50,
    technique: 39,
    tactics: 75,
    confidence: 'high',
  ),
  PlayerIdentityReference(
    id: 'silvio_criciuma',
    name: 'Sílvio Criciúma',
    period: '1996–2001',
    creativity: 17,
    definition: 15,
    leadership: 85,
    intensity: 55,
    technique: 24,
    tactics: 77,
    confidence: 'high',
  ),
  PlayerIdentityReference(
    id: 'rafael_toloi',
    name: 'Rafael Tolói',
    period: 'formado na base',
    creativity: 17,
    definition: 15,
    leadership: 54,
    intensity: 67,
    technique: 34,
    tactics: 73,
    confidence: 'medium',
  ),
  PlayerIdentityReference(
    id: 'josue',
    name: 'Josué',
    period: '1997–2004',
    creativity: 37,
    definition: 21,
    leadership: 64,
    intensity: 65,
    technique: 39,
    tactics: 78,
    confidence: 'high',
  ),
  PlayerIdentityReference(
    id: 'uidemar',
    name: 'Uidemar',
    period: '1986–1989 / 1995',
    creativity: 42,
    definition: 21,
    leadership: 49,
    intensity: 40,
    technique: 59,
    tactics: 75,
    confidence: 'medium',
  ),
  PlayerIdentityReference(
    id: 'amaral',
    name: 'Amaral',
    period: 'anos 2010',
    creativity: 32,
    definition: 31,
    leadership: 74,
    intensity: 63,
    technique: 34,
    tactics: 70,
    confidence: 'high',
  ),
  PlayerIdentityReference(
    id: 'douglas_pereira',
    name: 'Douglas Pereira dos Santos',
    period: 'anos 2010',
    creativity: 47,
    definition: 51,
    leadership: 29,
    intensity: 65,
    technique: 54,
    tactics: 30,
    confidence: 'medium',
  ),
  PlayerIdentityReference(
    id: 'paulo_baier',
    name: 'Paulo Baier',
    period: '2004–2005 / 2007–2008',
    creativity: 87,
    definition: 66,
    leadership: 69,
    intensity: 30,
    technique: 74,
    tactics: 65,
    confidence: 'high',
  ),
  PlayerIdentityReference(
    id: 'rodrigo_tabata',
    name: 'Rodrigo Tabata',
    period: '2004–2005',
    creativity: 90,
    definition: 51,
    leadership: 34,
    intensity: 35,
    technique: 75,
    tactics: 40,
    confidence: 'medium',
  ),
  PlayerIdentityReference(
    id: 'fernandao',
    name: 'Fernandão',
    period: '1995–2001 / 2009–2010',
    creativity: 67,
    definition: 71,
    leadership: 84,
    intensity: 55,
    technique: 64,
    tactics: 67,
    confidence: 'high',
  ),
  PlayerIdentityReference(
    id: 'araujo',
    name: 'Araújo',
    period: '1997–2003 / 2013–2014',
    creativity: 52,
    definition: 81,
    leadership: 54,
    intensity: 50,
    technique: 59,
    tactics: 45,
    confidence: 'high',
  ),
  PlayerIdentityReference(
    id: 'dill',
    name: 'Dill',
    period: '1994–2001',
    creativity: 37,
    definition: 76,
    leadership: 44,
    intensity: 45,
    technique: 49,
    tactics: 35,
    confidence: 'high',
  ),
  PlayerIdentityReference(
    id: 'dimba',
    name: 'Dimba',
    period: '2003',
    creativity: 25,
    definition: 84,
    leadership: 32,
    intensity: 38,
    technique: 32,
    tactics: 22,
    confidence: 'high',
  ),
  PlayerIdentityReference(
    id: 'iarley',
    name: 'Iarley',
    period: '2008–2009 / 2011–2012',
    creativity: 77,
    definition: 61,
    leadership: 59,
    intensity: 53,
    technique: 67,
    tactics: 50,
    confidence: 'high',
  ),
  PlayerIdentityReference(
    id: 'walter',
    name: 'Walter',
    period: '2012–2013 / 2016–2017',
    creativity: 80,
    definition: 68,
    leadership: 34,
    intensity: 25,
    technique: 74,
    tactics: 40,
    confidence: 'high',
  ),
  PlayerIdentityReference(
    id: 'erik',
    name: 'Erik',
    period: '2013–2015',
    creativity: 37,
    definition: 66,
    leadership: 24,
    intensity: 70,
    technique: 44,
    tactics: 25,
    confidence: 'medium',
  ),
  PlayerIdentityReference(
    id: 'michael',
    name: 'Michael',
    period: '2017–2019',
    creativity: 89,
    definition: 46,
    leadership: 29,
    intensity: 63,
    technique: 71,
    tactics: 20,
    confidence: 'high',
  ),
  PlayerIdentityReference(
    id: 'ricardo_goulart',
    name: 'Ricardo Goulart',
    period: '2012',
    creativity: 72,
    definition: 74,
    leadership: 49,
    intensity: 45,
    technique: 69,
    tactics: 45,
    confidence: 'high',
  ),
  PlayerIdentityReference(
    id: 'rafael_moura',
    name: 'Rafael Moura',
    period: 'múltiplas passagens',
    creativity: 42,
    definition: 71,
    leadership: 59,
    intensity: 55,
    technique: 44,
    tactics: 53,
    confidence: 'medium',
  ),
  PlayerIdentityReference(
    id: 'luvanor',
    name: 'Luvanor',
    period: '1977–1982',
    creativity: 74,
    definition: 64,
    leadership: 54,
    intensity: 35,
    technique: 64,
    tactics: 40,
    confidence: 'medium',
  ),
];
