import 'package:goias_app/features/arena/games/player_identity/domain/player_identity_models.dart';

/// As 19 referências históricas de jogadores usadas pelo jogo "Que craque
/// esmeraldino é você?".
///
/// IMPORTANTE (repetido do pedido original, pra quem for mexer aqui
/// depois): os valores 0–100 NÃO são ratings de qualidade geral — são
/// vetores EDITORIAIS usados só pra representar o ESTILO de cada jogador
/// dentro da experiência. NUNCA alterar esses números durante uma
/// implementação; qualquer recalibração é decisão explícita, feita aqui e
/// em nenhum outro lugar (a UI nunca deve depender do valor exato, só
/// consumir esta lista). Fotos ficam fora desta v1 de propósito
/// (`assetPath`/`imageUrl` sempre `null`).
const playerIdentityReferences = <PlayerIdentityReference>[
  PlayerIdentityReference(
    id: 'harlei',
    name: 'Harlei',
    period: '1999–2014',
    creativity: 45,
    definition: 45,
    leadership: 98,
    intensity: 76,
    technique: 82,
    tactics: 94,
    confidence: 'high',
  ),
  PlayerIdentityReference(
    id: 'tadeu',
    name: 'Tadeu',
    period: 'desde 2019',
    creativity: 62,
    definition: 72,
    leadership: 96,
    intensity: 82,
    technique: 88,
    tactics: 91,
    confidence: 'high',
  ),
  PlayerIdentityReference(
    id: 'silvio_criciuma',
    name: 'Sílvio Criciúma',
    period: '1996–2001',
    creativity: 45,
    definition: 48,
    leadership: 97,
    intensity: 88,
    technique: 68,
    tactics: 93,
    confidence: 'high',
  ),
  PlayerIdentityReference(
    id: 'josue',
    name: 'Josué',
    period: '1997–2004',
    creativity: 67,
    definition: 52,
    leadership: 89,
    intensity: 92,
    technique: 82,
    tactics: 96,
    confidence: 'high',
  ),
  PlayerIdentityReference(
    id: 'amaral',
    name: 'Amaral',
    period: 'anos 2010',
    creativity: 50,
    definition: 68,
    leadership: 92,
    intensity: 90,
    technique: 70,
    tactics: 92,
    confidence: 'high',
  ),
  PlayerIdentityReference(
    id: 'paulo_baier',
    name: 'Paulo Baier',
    period: '2007–2008',
    creativity: 92,
    definition: 87,
    leadership: 88,
    intensity: 70,
    technique: 96,
    tactics: 88,
    confidence: 'high',
  ),
  PlayerIdentityReference(
    id: 'rodrigo_tabata',
    name: 'Rodrigo Tabata',
    period: '2004–2005',
    creativity: 94,
    definition: 82,
    leadership: 68,
    intensity: 78,
    technique: 95,
    tactics: 72,
    confidence: 'medium',
  ),
  PlayerIdentityReference(
    id: 'fernandao',
    name: 'Fernandão',
    period: '1995–2001 / 2009',
    creativity: 84,
    definition: 88,
    leadership: 98,
    intensity: 86,
    technique: 90,
    tactics: 90,
    confidence: 'high',
  ),
  PlayerIdentityReference(
    id: 'araujo',
    name: 'Araújo',
    period: '1997–2003 / 2013–2014',
    creativity: 82,
    definition: 96,
    leadership: 78,
    intensity: 83,
    technique: 92,
    tactics: 77,
    confidence: 'high',
  ),
  PlayerIdentityReference(
    id: 'dill',
    name: 'Dill',
    period: '1994–2001',
    creativity: 65,
    definition: 98,
    leadership: 74,
    intensity: 84,
    technique: 86,
    tactics: 70,
    confidence: 'high',
  ),
  PlayerIdentityReference(
    id: 'dimba',
    name: 'Dimba',
    period: '2002–2004',
    creativity: 62,
    definition: 98,
    leadership: 72,
    intensity: 86,
    technique: 84,
    tactics: 68,
    confidence: 'high',
  ),
  PlayerIdentityReference(
    id: 'iarley',
    name: 'Iarley',
    period: '2008–2009 / 2011–2012',
    creativity: 90,
    definition: 84,
    leadership: 88,
    intensity: 84,
    technique: 93,
    tactics: 85,
    confidence: 'high',
  ),
  PlayerIdentityReference(
    id: 'walter',
    name: 'Walter',
    period: '2012–2013 / 2019',
    creativity: 91,
    definition: 91,
    leadership: 70,
    intensity: 62,
    technique: 97,
    tactics: 80,
    confidence: 'high',
  ),
  PlayerIdentityReference(
    id: 'michael',
    name: 'Michael',
    period: '2017–2019',
    creativity: 96,
    definition: 80,
    leadership: 65,
    intensity: 97,
    technique: 93,
    tactics: 68,
    confidence: 'high',
  ),
  PlayerIdentityReference(
    id: 'ricardo_goulart',
    name: 'Ricardo Goulart',
    period: '2012',
    creativity: 82,
    definition: 94,
    leadership: 76,
    intensity: 88,
    technique: 91,
    tactics: 81,
    confidence: 'high',
  ),
  PlayerIdentityReference(
    id: 'pedro_raul',
    name: 'Pedro Raul',
    period: '2022',
    creativity: 61,
    definition: 97,
    leadership: 78,
    intensity: 84,
    technique: 82,
    tactics: 82,
    confidence: 'high',
  ),
  PlayerIdentityReference(
    id: 'rafael_moura',
    name: 'Rafael Moura',
    period: 'múltiplas passagens',
    creativity: 62,
    definition: 92,
    leadership: 86,
    intensity: 86,
    technique: 80,
    tactics: 83,
    confidence: 'medium',
  ),
  PlayerIdentityReference(
    id: 'egidio',
    name: 'Egídio',
    period: '2012',
    creativity: 86,
    definition: 72,
    leadership: 68,
    intensity: 94,
    technique: 89,
    tactics: 81,
    confidence: 'high',
  ),
  PlayerIdentityReference(
    id: 'luvanor',
    name: 'Luvanor',
    period: '1977–1982',
    creativity: 90,
    definition: 85,
    leadership: 80,
    intensity: 82,
    technique: 92,
    tactics: 76,
    confidence: 'medium',
  ),
];
