import 'dart:ui';

import 'package:goias_app/features/arena/games/lineup/formation_layout_service.dart';
import 'package:goias_app/features/arena/games/lineup/lineup_models.dart';
import 'package:goias_app/features/arena/games/lineup/word_evaluation_service.dart';

/// Banco de 31 escalações reais do Goiás, fonte:
/// "Missing_Eleven_Goias_31_Escalacoes.pdf" (fornecido pelo usuário,
/// 23/08/2026) — não é mock. [FormationConfidence] reflete a legenda do
/// próprio PDF: PRONTO → [FormationConfidence.confirmed] (XI e números
/// tratados como utilizáveis, vindos de ficha direta), MAPEADO →
/// [FormationConfidence.probable] (XI confirmado, números mapeados pelo
/// histórico do elenco/temporada — pendente de checagem final), REVISAR Nº
/// → [FormationConfidence.estimated] (XI histórico útil, mas a fonte não
/// comprovou os 11 números daquela partida — PDF usa '?', nunca inventado;
/// aqui viram [LineupPlayer.shirtNumber] `null`, exibido sem número, sem
/// '?').
final lineupMatches = <LineupMatch>[
  _m(
    id: '1990_flamengo_cdb_final_volta',
    competition: 'Copa do Brasil',
    season: '1990',
    phase: 'Final - volta',
    date: DateTime(1990, 11, 7),
    home: 'Goiás',
    homeScore: 0,
    away: 'Flamengo',
    awayScore: 0,
    formation: '4-4-2',
    confidence: FormationConfidence.estimated,
    lineup: const [
      _Row('GOL', null, 'Eduardo Heuser', 'EDUARDO'),
      _Row('LD', null, 'Wilson Goiano', 'WILSON'),
      _Row('ZAG', null, 'Richard', 'RICHARD'),
      _Row('ZAG', null, 'Jorge Batata', 'JORGE BATATA', ['J. Batata']),
      _Row('LE', null, 'Dalton', 'DALTON'),
      _Row('VOL', null, 'Wallace', 'WALLACE'),
      _Row('MC', null, 'Fagundes', 'FAGUNDES'),
      _Row('MEI', null, 'Luvanor', 'LUVANOR'),
      _Row('MEI', null, 'Josué', 'JOSUÉ'),
      _Row('ATA', null, 'Niltinho', 'NILTINHO'),
      _Row('ATA', null, 'Túlio Maravilha', 'TÚLIO', ['Túlio Maravilha']),
    ],
  ),
  _m(
    id: '1996_guarani_brA_quartas',
    competition: 'Campeonato Brasileiro Série A',
    season: '1996',
    phase: 'Quartas de final',
    date: DateTime(1996, 11, 27),
    home: 'Goiás',
    homeScore: 3,
    away: 'Guarani',
    awayScore: 1,
    formation: '4-3-3',
    confidence: FormationConfidence.estimated,
    lineup: const [
      _Row('GOL', null, 'Kléber', 'KLÉBER'),
      _Row('LD', null, 'Índio', 'ÍNDIO'),
      _Row('ZAG', null, 'Sílvio Criciúma', 'SILVIO', ['Sílvio']),
      _Row('ZAG', null, 'Richard', 'RICHARD'),
      _Row('LE', null, 'Augusto', 'AUGUSTO'),
      _Row('MC', null, 'Reidner', 'REIDNER'),
      _Row('MC', null, 'Túlio Maravilha', 'TÚLIO', ['Túlio Maravilha']),
      _Row('MEI', null, 'Lúcio', 'LÚCIO'),
      _Row('ATA', null, 'Alex Dias', 'ALEX'),
      _Row('ATA', null, 'Jaques', 'JAQUES'),
      _Row('ATA', null, 'Evandro', 'EVANDRO'),
    ],
  ),
  _m(
    id: '1996_gremio_brA_semi',
    competition: 'Campeonato Brasileiro Série A',
    season: '1996',
    phase: 'Semifinal',
    date: DateTime(1996, 12, 8),
    home: 'Grêmio',
    homeScore: 2,
    away: 'Goiás',
    awayScore: 2,
    formation: '4-4-2',
    confidence: FormationConfidence.estimated,
    lineup: const [
      _Row('GOL', null, 'Kléber', 'KLÉBER'),
      _Row('LD', null, 'Índio', 'ÍNDIO'),
      _Row('ZAG', null, 'Sílvio Criciúma', 'SILVIO'),
      _Row('ZAG', null, 'Richard', 'RICHARD'),
      _Row('LE', null, 'Augusto', 'AUGUSTO'),
      _Row('VOL', null, 'Romeu', 'ROMEU'),
      _Row('MC', null, 'Reidner', 'REIDNER'),
      _Row('MEI', null, 'Túlio Maravilha', 'TÚLIO', ['Túlio Maravilha']),
      _Row('MEI', null, 'Lúcio', 'LÚCIO'),
      _Row('ATA', null, 'Evandro', 'EVANDRO'),
      _Row('ATA', null, 'Alex Dias', 'ALEX'),
    ],
  ),
  _m(
    id: '1999_santacruz_brB_titulo',
    competition: 'Campeonato Brasileiro Série B',
    season: '1999',
    phase: 'Jogo do título',
    date: DateTime(1999, 12, 12),
    home: 'Goiás',
    homeScore: 0,
    away: 'Santa Cruz',
    awayScore: 0,
    formation: '4-4-2',
    confidence: FormationConfidence.estimated,
    lineup: const [
      _Row('GOL', null, 'Harlei', 'HARLEI'),
      _Row('LD', null, 'Neném', 'NENÉM'),
      _Row('ZAG', null, 'Sílvio Criciúma', 'SILVIO'),
      _Row('ZAG', null, 'Álvaro', 'ÁLVARO'),
      _Row('LE', null, 'Fernando Nunes', 'FERNANDO NUNES'),
      _Row('VOL', null, 'Túlio Maravilha', 'TÚLIO', ['Túlio Maravilha']),
      _Row('VOL', null, 'Marabá', 'MARABÁ'),
      _Row('MEI', null, 'Cacá', 'CACÁ'),
      _Row('MEI', null, 'Michael', 'MICHAEL'),
      _Row('ATA', null, 'Fernandão', 'FERNANDÃO'),
      _Row('ATA', null, 'Araújo', 'ARAÚJO'),
    ],
  ),
  _m(
    id: '2003_juventude_brA_reacao',
    competition: 'Campeonato Brasileiro Série A',
    season: '2003',
    phase: 'Campanha de reação',
    date: DateTime(2003),
    home: 'Goiás',
    homeScore: 7,
    away: 'Juventude',
    awayScore: 0,
    formation: '4-4-2',
    confidence: FormationConfidence.estimated,
    lineup: const [
      _Row('GOL', null, 'Harlei', 'HARLEI'),
      _Row('DEF', null, 'Alexandre', 'ALEXANDRE'),
      _Row('ZAG', null, 'Fabão', 'FABÃO'),
      _Row('ZAG', null, 'Leandro Smith', 'LEANDRO'),
      _Row('DEF', null, 'Michel Santana', 'MICHEL'),
      _Row('VOL', null, 'Marabá', 'MARABÁ'),
      _Row('VOL', null, 'Tiago Fraga', 'TIAGO FRAGA'),
      _Row('MEI', null, 'Caíco', 'CAÍCO'),
      _Row('MEI', null, 'Danilo', 'DANILO'),
      _Row('ATA', null, 'Araújo', 'ARAÚJO'),
      _Row('ATA', null, 'Dimba', 'DIMBA'),
    ],
  ),
  _m(
    id: '2003_fluminense_brA_reacao',
    competition: 'Campeonato Brasileiro Série A',
    season: '2003',
    phase: 'Campanha de reação',
    date: DateTime(2003),
    home: 'Goiás',
    homeScore: 6,
    away: 'Fluminense',
    awayScore: 1,
    formation: '3-4-3',
    confidence: FormationConfidence.estimated,
    lineup: const [
      _Row('GOL', null, 'Rodrigo Calaça', 'RODRIGO CALAÇA', ['Calaça']),
      _Row('ZAG', null, 'Fabão', 'FABÃO'),
      _Row('ZAG', null, 'Renato Silva', 'RENATO SILVA'),
      _Row('ZAG', null, 'Leandro Smith', 'LEANDRO'),
      _Row('MC', null, 'Cléber Goiano', 'CLÉBER GOIANO'),
      _Row('MC', null, 'Josué', 'JOSUÉ'),
      _Row('MC', null, 'Simão', 'SIMÃO'),
      _Row('ALA', null, 'Gil Baiano', 'GIL BAIANO'),
      _Row('ATA', null, 'Wando', 'WANDO'),
      _Row('ATA', null, 'Araújo', 'ARAÚJO'),
      _Row('ATA', null, 'Grafite', 'GRAFITE'),
    ],
  ),
  _m(
    id: '2003_santos_brA_reacao',
    competition: 'Campeonato Brasileiro Série A',
    season: '2003',
    phase: 'Campanha de reação',
    date: DateTime(2003),
    home: 'Goiás',
    homeScore: 3,
    away: 'Santos',
    awayScore: 0,
    formation: '3-5-2',
    confidence: FormationConfidence.estimated,
    lineup: const [
      _Row('GOL', null, 'Rodrigo Calaça', 'RODRIGO CALAÇA', ['Calaça']),
      _Row('ZAG', null, 'Pedro Paulo', 'PEDRO PAULO'),
      _Row('ZAG', null, 'Esquerdinha', 'ESQUERDINHA'),
      _Row('ZAG', null, 'Gustavo', 'GUSTAVO'),
      _Row('ALA', null, 'Cléber Goiano', 'CLÉBER GOIANO'),
      _Row('MC', null, 'Josué', 'JOSUÉ'),
      _Row('MC', null, 'Marabá', 'MARABÁ'),
      _Row('ALA', null, 'Simão', 'SIMÃO'),
      _Row('MEI', null, 'Danilo', 'DANILO'),
      _Row('ATA', null, 'Dimba', 'DIMBA'),
      _Row('ATA', null, 'Grafite', 'GRAFITE'),
    ],
  ),
  _m(
    id: '2005_pontepreta_brA_3lugar',
    competition: 'Campeonato Brasileiro Série A',
    season: '2005',
    phase: '3º lugar - vaga na Libertadores',
    date: DateTime(2005),
    home: 'Goiás',
    homeScore: 4,
    away: 'Ponte Preta',
    awayScore: 1,
    formation: '4-4-2',
    confidence: FormationConfidence.estimated,
    lineup: const [
      _Row('GOL', null, 'Harlei', 'HARLEI'),
      _Row('DEF', null, 'André Dias', 'ANDRÉ DIAS'),
      _Row('ZAG', null, 'André Leone', 'ANDRÉ LEONE'),
      _Row('ZAG', null, 'Rogério Corrêa', 'ROGÉRIO CORRÊA'),
      _Row('LE', null, 'Jadílson', 'JADÍLSON'),
      _Row('MC', null, 'Cléber Gaúcho', 'CLÉBER GAÚCHO'),
      _Row('MC', null, 'Cléber Goiano', 'CLÉBER GOIANO'),
      _Row('MEI', null, 'Paulo Baier', 'PAULO BAIER'),
      _Row('MEI', null, 'Rodrigo Tabata', 'RODRIGO TABATA', ['Tabata']),
      _Row('ATA', null, 'Roni', 'RONI'),
      _Row('ATA', null, 'Souza', 'SOUZA'),
    ],
  ),
  _m(
    id: '2005_athleticopr_brA_3lugar',
    competition: 'Campeonato Brasileiro Série A',
    season: '2005',
    phase: '3º lugar - vaga na Libertadores',
    date: DateTime(2005),
    home: 'Goiás',
    homeScore: 4,
    away: 'Athletico-PR',
    awayScore: 2,
    formation: '3-5-2',
    confidence: FormationConfidence.estimated,
    lineup: const [
      _Row('GOL', null, 'Harlei', 'HARLEI'),
      _Row('ZAG', null, 'Júlio Santos', 'JÚLIO SANTOS'),
      _Row('ZAG', null, 'Jadílson', 'JADÍLSON'),
      _Row('ZAG', null, 'Luciano Almeida', 'LUCIANO ALMEIDA'),
      _Row('MC', null, 'Cléber Goiano', 'CLÉBER GOIANO'),
      _Row('MC', null, 'Danilo Portugal', 'DANILO PORTUGAL'),
      _Row('MEI', null, 'Paulo Baier', 'PAULO BAIER'),
      _Row('MEI', null, 'Romerito', 'ROMERITO'),
      _Row('MEI', null, 'Rodrigo Tabata', 'RODRIGO TABATA', ['Tabata']),
      _Row('ATA', null, 'Roni', 'RONI'),
      _Row('ATA', null, 'Souza', 'SOUZA'),
    ],
  ),
  _m(
    id: '2005_saopaulo_brA_3lugar',
    competition: 'Campeonato Brasileiro Série A',
    season: '2005',
    phase: '3º lugar - vaga na Libertadores',
    date: DateTime(2005, 11, 16),
    home: 'Goiás',
    homeScore: 3,
    away: 'São Paulo',
    awayScore: 0,
    formation: '3-5-2',
    confidence: FormationConfidence.estimated,
    lineup: const [
      _Row('GOL', null, 'Harlei', 'HARLEI'),
      _Row('ZAG', null, 'André Leone', 'ANDRÉ LEONE'),
      _Row('ZAG', null, 'Rafael Dias', 'RAFAEL DIAS'),
      _Row('ZAG', null, 'André Dias', 'ANDRÉ DIAS'),
      _Row('ALA', null, 'Paulo Baier', 'PAULO BAIER'),
      _Row('MC', null, 'Cléber Goiano', 'CLÉBER GOIANO'),
      _Row('MC', null, 'Cléber Gaúcho', 'CLÉBER GAÚCHO'),
      _Row('MEI', null, 'Romerito', 'ROMERITO'),
      _Row('ALA', null, 'Jadílson', 'JADÍLSON'),
      _Row('ATA', null, 'Roni', 'RONI'),
      _Row('ATA', null, 'Souza', 'SOUZA'),
    ],
  ),
  _m(
    id: '2005_corinthians_brA_3lugar',
    competition: 'Campeonato Brasileiro Série A',
    season: '2005',
    phase: '3º lugar - vaga na Libertadores',
    date: DateTime(2005),
    home: 'Goiás',
    homeScore: 3,
    away: 'Corinthians',
    awayScore: 2,
    formation: '4-4-2',
    confidence: FormationConfidence.estimated,
    lineup: const [
      _Row('GOL', null, 'Harlei', 'HARLEI'),
      _Row('LD', null, 'Aldo', 'ALDO'),
      _Row('ZAG', null, 'André Leone', 'ANDRÉ LEONE'),
      _Row('ZAG', null, 'Rafael Dias', 'RAFAEL DIAS'),
      _Row('LE', null, 'Jadílson', 'JADÍLSON'),
      _Row('MC', null, 'Cléber Gaúcho', 'CLÉBER GAÚCHO'),
      _Row('MC', null, 'Cléber Goiano', 'CLÉBER GOIANO'),
      _Row('MEI', null, 'Paulo Baier', 'PAULO BAIER'),
      _Row('MEI', null, 'Rodrigo Tabata', 'RODRIGO TABATA', ['Tabata']),
      _Row('ATA', null, 'Roni', 'RONI'),
      _Row('ATA', null, 'Souza', 'SOUZA'),
    ],
  ),
  _m(
    id: '2006_cuenca_lib_1fase',
    competition: 'Copa Libertadores',
    season: '2006',
    phase: '1ª fase - classificação',
    date: DateTime(2006, 2, 1),
    home: 'Goiás',
    homeScore: 3,
    away: 'Deportivo Cuenca',
    awayScore: 0,
    formation: '3-5-2',
    confidence: FormationConfidence.estimated,
    lineup: const [
      _Row('GOL', null, 'Harlei', 'HARLEI'),
      _Row('ZAG', null, 'Rogério Corrêa', 'ROGÉRIO CORRÊA'),
      _Row('ZAG', null, 'Júlio Santos', 'JÚLIO SANTOS'),
      _Row('ZAG', null, 'Leonardo', 'LEONARDO'),
      _Row('ALA', null, 'Cléber Goiano', 'CLÉBER GOIANO'),
      _Row('MC', null, 'Fabiano', 'FABIANO'),
      _Row('MC', null, 'Danilo Portugal', 'DANILO PORTUGAL'),
      _Row('MEI', null, 'Juliano', 'JULIANO'),
      _Row('ALA', null, 'Jadílson', 'JADÍLSON'),
      _Row('ATA', null, 'Nonato', 'NONATO'),
      _Row('ATA', null, 'Romerito', 'ROMERITO'),
    ],
  ),
  _m(
    id: '2006_newells_lib_grupos',
    competition: 'Copa Libertadores',
    season: '2006',
    phase: 'Fase de grupos',
    date: DateTime(2006),
    home: "Newell's Old Boys",
    homeScore: 0,
    away: 'Goiás',
    awayScore: 0,
    formation: '5-3-2',
    confidence: FormationConfidence.estimated,
    lineup: const [
      _Row('GOL', null, 'Harlei', 'HARLEI'),
      _Row('DEF', null, 'Fabiano', 'FABIANO'),
      _Row('ZAG', null, 'Leonardo', 'LEONARDO'),
      _Row('ZAG', null, 'Rogério Corrêa', 'ROGÉRIO CORRÊA'),
      _Row('ZAG', null, 'Júlio Santos', 'JÚLIO SANTOS'),
      _Row('DEF', null, 'Jadílson', 'JADÍLSON'),
      _Row('MC', null, 'Cléber Goiano', 'CLÉBER GOIANO'),
      _Row('MC', null, 'Danilo Portugal', 'DANILO PORTUGAL'),
      _Row('MEI', null, 'Vampeta', 'VAMPETA'),
      _Row('ATA', null, 'Souza', 'SOUZA'),
      _Row('ATA', null, 'Welliton', 'WELLITON'),
    ],
  ),
  _m(
    id: '2006_estudiantes_lib_oitavas_volta',
    competition: 'Copa Libertadores',
    season: '2006',
    phase: 'Oitavas de final - volta',
    date: DateTime(2006, 5, 4),
    home: 'Goiás',
    homeScore: 3,
    away: 'Estudiantes',
    awayScore: 1,
    formation: '3-4-3',
    confidence: FormationConfidence.estimated,
    lineup: const [
      _Row('GOL', null, 'Harlei', 'HARLEI'),
      _Row('DEF', null, 'Fabiano', 'FABIANO'),
      _Row('ZAG', null, 'Júlio Santos', 'JÚLIO SANTOS'),
      _Row('DEF', null, 'Jadílson', 'JADÍLSON'),
      _Row('ZAG', null, 'Rogério Corrêa', 'ROGÉRIO CORRÊA'),
      _Row('ALA', null, 'Vítor', 'VÍTOR'),
      _Row('MC', null, 'Danilo Portugal', 'DANILO PORTUGAL'),
      _Row('MEI', null, 'Romerito', 'ROMERITO'),
      _Row('ATA', null, 'Welliton', 'WELLITON'),
      _Row('ATA', null, 'Nonato', 'NONATO'),
      _Row('ATA', null, 'Roni', 'RONI'),
    ],
  ),
  _m(
    id: '2010_palmeiras_sulamericana_semi_volta',
    competition: 'Copa Sul-Americana',
    season: '2010',
    phase: 'Semifinal - volta',
    date: DateTime(2010, 11, 24),
    home: 'Palmeiras',
    homeScore: 1,
    away: 'Goiás',
    awayScore: 2,
    formation: '3-5-2',
    confidence: FormationConfidence.confirmed,
    lineup: const [
      _Row('GOL', 1, 'Harlei', 'HARLEI'),
      _Row('ZAG', 3, 'Rafael Tolói', 'RAFAEL TOLOI', ['Tolói']),
      _Row('ZAG', 4, 'Ernando', 'ERNANDO'),
      _Row('ZAG', 19, 'Marcão', 'MARCÃO'),
      _Row('ALA', 20, 'Douglas', 'DOUGLAS'),
      _Row('VOL', 8, 'Amaral', 'AMARAL'),
      _Row('MEI', 2, 'Carlos Alberto', 'CARLOS ALBERTO'),
      _Row('MEI', 17, 'Marcelo Costa', 'MARCELO COSTA'),
      _Row('ALA', 6, 'Wellington Saci', 'WELLINGTON SACI', ['Saci']),
      _Row('ATA', 22, 'Otacílio Neto', 'OTACILIO NETO'),
      _Row('ATA', 9, 'Rafael Moura', 'RAFAEL MOURA', ['He-Man', 'Heman']),
    ],
  ),
  _m(
    id: '2010_independiente_sulamericana_final_ida',
    competition: 'Copa Sul-Americana',
    season: '2010',
    phase: 'Final - ida',
    date: DateTime(2010, 12, 1),
    home: 'Goiás',
    homeScore: 2,
    away: 'Independiente',
    awayScore: 0,
    formation: '3-5-2',
    confidence: FormationConfidence.confirmed,
    lineup: const [
      _Row('GOL', 1, 'Harlei', 'HARLEI'),
      _Row('ZAG', 4, 'Ernando', 'ERNANDO'),
      _Row('ZAG', 3, 'Rafael Tolói', 'RAFAEL TOLOI', ['Tolói']),
      _Row('ZAG', 19, 'Marcão', 'MARCÃO'),
      _Row('ALA', 20, 'Douglas', 'DOUGLAS'),
      _Row('VOL', 8, 'Amaral', 'AMARAL'),
      _Row('MEI', 2, 'Carlos Alberto', 'CARLOS ALBERTO'),
      _Row('MEI', 17, 'Marcelo Costa', 'MARCELO COSTA'),
      _Row('ALA', 6, 'Wellington Saci', 'WELLINGTON SACI', ['Saci']),
      _Row('ATA', 9, 'Rafael Moura', 'RAFAEL MOURA', ['He-Man', 'Heman']),
      _Row('ATA', 22, 'Otacílio Neto', 'OTACILIO NETO'),
    ],
  ),
  _m(
    id: '2010_independiente_sulamericana_final_volta',
    competition: 'Copa Sul-Americana',
    season: '2010',
    phase: 'Final - volta (Independiente campeão nos pênaltis, 5 x 3)',
    date: DateTime(2010, 12, 8),
    home: 'Independiente',
    homeScore: 3,
    away: 'Goiás',
    awayScore: 1,
    formation: '3-5-2',
    confidence: FormationConfidence.confirmed,
    lineup: const [
      _Row('GOL', 1, 'Harlei', 'HARLEI'),
      _Row('ZAG', 3, 'Rafael Tolói', 'RAFAEL TOLOI', ['Tolói']),
      _Row('ZAG', 4, 'Ernando', 'ERNANDO'),
      _Row('ZAG', 19, 'Marcão', 'MARCÃO'),
      _Row('ALA', 20, 'Douglas', 'DOUGLAS'),
      _Row('VOL', 8, 'Amaral', 'AMARAL'),
      _Row('MEI', 2, 'Carlos Alberto', 'CARLOS ALBERTO'),
      _Row('MEI', 17, 'Marcelo Costa', 'MARCELO COSTA'),
      _Row('ALA', 6, 'Wellington Saci', 'WELLINGTON SACI', ['Saci']),
      _Row('ATA', 22, 'Otacílio Neto', 'OTACILIO NETO'),
      _Row('ATA', 9, 'Rafael Moura', 'RAFAEL MOURA', ['He-Man', 'Heman']),
    ],
  ),
  _m(
    id: '2012_guarani_brB_retafinal',
    competition: 'Campeonato Brasileiro Série B',
    season: '2012',
    phase: 'Reta final da campanha campeã',
    date: DateTime(2012),
    home: 'Goiás',
    homeScore: 5,
    away: 'Guarani',
    awayScore: 0,
    formation: '4-4-2',
    confidence: FormationConfidence.probable,
    lineup: const [
      _Row('GOL', 1, 'Harlei', 'HARLEI'),
      _Row('LD', 2, 'Vítor', 'VÍTOR'),
      _Row('ZAG', 4, 'Ernando', 'ERNANDO'),
      _Row('ZAG', 3, 'Valmir Lucas', 'VALMIR LUCAS'),
      _Row('LE', 6, 'Egídio', 'EGÍDIO'),
      _Row('VOL', 5, 'Amaral', 'AMARAL'),
      _Row('MC', 8, 'Thiago Mendes', 'THIAGO MENDES'),
      _Row('MEI', 7, 'Ramón', 'RAMÓN'),
      _Row('MEI', 11, 'Renan Oliveira', 'RENAN OLIVEIRA'),
      _Row('ATA', 9, 'Ricardo Goulart', 'RICARDO GOULART', ['Goulart']),
      _Row('ATA', 18, 'Walter', 'WALTER'),
    ],
  ),
  _m(
    id: '2012_joinville_brB_titulo',
    competition: 'Campeonato Brasileiro Série B',
    season: '2012',
    phase: 'Última rodada - título',
    date: DateTime(2012, 11, 24),
    home: 'Goiás',
    homeScore: 2,
    away: 'Joinville',
    awayScore: 1,
    formation: '4-4-2',
    confidence: FormationConfidence.probable,
    lineup: const [
      _Row('GOL', 1, 'Harlei', 'HARLEI'),
      _Row('LD', 2, 'Vítor', 'VÍTOR'),
      _Row('ZAG', 4, 'Ernando', 'ERNANDO'),
      _Row('ZAG', 13, 'Rafael Lacerda', 'RAFAEL LACERDA'),
      _Row('LE', 6, 'Egídio', 'EGÍDIO'),
      _Row('VOL', 5, 'Amaral', 'AMARAL'),
      _Row('MC', 8, 'Thiago Mendes', 'THIAGO MENDES'),
      _Row('MEI', 7, 'Ramón', 'RAMÓN'),
      _Row('MEI', 11, 'Renan Oliveira', 'RENAN OLIVEIRA'),
      _Row('ATA', 9, 'Ricardo Goulart', 'RICARDO GOULART', ['Goulart']),
      _Row('ATA', 18, 'Walter', 'WALTER'),
    ],
  ),
  _m(
    id: '2013_fluminense_cdb_oitavas_volta',
    competition: 'Copa do Brasil',
    season: '2013',
    phase: 'Oitavas de final - volta',
    date: DateTime(2013, 8, 28),
    home: 'Goiás',
    homeScore: 2,
    away: 'Fluminense',
    awayScore: 0,
    formation: '4-2-3-1',
    confidence: FormationConfidence.probable,
    lineup: const [
      _Row('GOL', 12, 'Renan', 'RENAN'),
      _Row('LD', 2, 'Vítor', 'VÍTOR'),
      _Row('ZAG', 4, 'Ernando', 'ERNANDO'),
      _Row('ZAG', 13, 'Rodrigo', 'RODRIGO'),
      _Row('LE', 6, 'William Matheus', 'WILLIAM MATHEUS'),
      _Row('VOL', 8, 'Dudu Cearense', 'DUDU', ['Dudu']),
      _Row('VOL', 45, 'David', 'DAVID'),
      _Row('MEI', 11, 'Renan Oliveira', 'RENAN OLIVEIRA'),
      _Row('MEI', 20, 'Ramón', 'RAMÓN'),
      _Row('MEI', 10, 'Hugo', 'HUGO'),
      _Row('ATA', 18, 'Walter', 'WALTER'),
    ],
  ),
  _m(
    id: '2013_vasco_cdb_quartas_ida',
    competition: 'Copa do Brasil',
    season: '2013',
    phase: 'Quartas de final - ida',
    date: DateTime(2013),
    home: 'Goiás',
    homeScore: 2,
    away: 'Vasco',
    awayScore: 1,
    formation: '4-4-2',
    confidence: FormationConfidence.probable,
    lineup: const [
      _Row('GOL', 12, 'Renan', 'RENAN'),
      _Row('LD', 2, 'Vítor', 'VÍTOR'),
      _Row('ZAG', 4, 'Ernando', 'ERNANDO'),
      _Row('ZAG', 13, 'Rodrigo', 'RODRIGO'),
      _Row('LE', 6, 'William Matheus', 'WILLIAM MATHEUS'),
      _Row('VOL', 5, 'Amaral', 'AMARAL'),
      _Row('MC', 45, 'David', 'DAVID'),
      _Row('MEI', 10, 'Hugo', 'HUGO'),
      _Row('MEI', 11, 'Renan Oliveira', 'RENAN OLIVEIRA'),
      _Row('ATA', 9, 'Roni', 'RONI'),
      _Row('ATA', 18, 'Walter', 'WALTER'),
    ],
  ),
  _m(
    id: '2013_vasco_cdb_quartas_volta',
    competition: 'Copa do Brasil',
    season: '2013',
    phase: 'Quartas de final - volta (Goiás classificado)',
    date: DateTime(2013),
    home: 'Vasco',
    homeScore: 3,
    away: 'Goiás',
    awayScore: 2,
    formation: '4-4-2',
    confidence: FormationConfidence.probable,
    lineup: const [
      _Row('GOL', 12, 'Renan', 'RENAN'),
      _Row('LD', 2, 'Vítor', 'VÍTOR'),
      _Row('ZAG', 4, 'Ernando', 'ERNANDO'),
      _Row('ZAG', 13, 'Rodrigo', 'RODRIGO'),
      _Row('LE', 6, 'William Matheus', 'WILLIAM MATHEUS'),
      _Row('VOL', 5, 'Amaral', 'AMARAL'),
      _Row('MC', 45, 'David', 'DAVID'),
      _Row('MEI', 10, 'Hugo', 'HUGO'),
      _Row('MEI', 9, 'Roni', 'RONI'),
      _Row('ATA', 17, 'Eduardo Sasha', 'EDUARDO SASHA', ['Sasha']),
      _Row('ATA', 18, 'Walter', 'WALTER'),
    ],
  ),
  _m(
    id: '2018_aparecidense_goiano_final_volta',
    competition: 'Campeonato Goiano',
    season: '2018',
    phase: 'Final - volta / tetracampeonato',
    date: DateTime(2018, 4, 8),
    home: 'Goiás',
    homeScore: 3,
    away: 'Aparecidense',
    awayScore: 1,
    formation: '4-3-3',
    confidence: FormationConfidence.estimated,
    lineup: const [
      _Row('GOL', null, 'Marcelo Rangel', 'MARCELO RANGEL', ['Rangel']),
      _Row('LD', null, 'Caíque Sá', 'CAIQUE SA'),
      _Row('ZAG', null, 'David Duarte', 'DAVID DUARTE'),
      _Row('ZAG', null, 'Eduardo Brock', 'EDUARDO BROCK', ['Brock']),
      _Row('LE', null, 'Breno', 'BRENO'),
      _Row('MC', null, 'Léo Sena', 'LEO SENA'),
      _Row('MC', null, 'Giovanni', 'GIOVANNI'),
      _Row('MC', null, 'Madison', 'MADISON'),
      _Row('ATA', null, 'Maranhão', 'MARANHÃO'),
      _Row('ATA', null, 'Júnior Viçosa', 'JÚNIOR VIÇOSA', ['Viçosa']),
      _Row('ATA', null, 'Carlos Eduardo', 'CARLOS EDUARDO'),
    ],
  ),
  _m(
    id: '2021_csa_brB_g4',
    competition: 'Campeonato Brasileiro Série B',
    season: '2021',
    phase: 'Confronto direto pelo G-4',
    date: DateTime(2021, 10, 15),
    home: 'Goiás',
    homeScore: 3,
    away: 'CSA',
    awayScore: 1,
    formation: '4-2-3-1',
    confidence: FormationConfidence.probable,
    lineup: const [
      _Row('GOL', 1, 'Tadeu', 'TADEU'),
      _Row('LD', 2, 'Apodi', 'APODI'),
      _Row('ZAG', 3, 'David Duarte', 'DAVID DUARTE'),
      _Row('ZAG', 4, 'Reynaldo', 'REYNALDO'),
      _Row('LE', 6, 'Hugo', 'HUGO'),
      _Row('VOL', 8, 'Fellipe Bastos', 'FELLIPE BASTOS'),
      _Row('MC', 18, 'Dieguinho', 'DIEGUINHO'),
      _Row('MEI', 11, 'Luan Dias', 'LUAN DIAS'),
      _Row('MEI', 10, 'Élvis', 'ELVIS'),
      _Row('ATA', 9, 'Nicolas', 'NICOLAS'),
      _Row('ATA', 7, 'Alef Manga', 'ALEF MANGA'),
    ],
  ),
  _m(
    id: '2021_guarani_brB_acesso',
    competition: 'Campeonato Brasileiro Série B',
    season: '2021',
    phase: 'Jogo do acesso',
    date: DateTime(2021, 11, 22),
    home: 'Guarani',
    homeScore: 0,
    away: 'Goiás',
    awayScore: 2,
    formation: '4-3-3',
    confidence: FormationConfidence.probable,
    lineup: const [
      _Row('GOL', 1, 'Tadeu', 'TADEU'),
      _Row('ZAG', 4, 'Reynaldo', 'REYNALDO'),
      _Row('ZAG', 3, 'David Duarte', 'DAVID DUARTE'),
      _Row('VOL', 8, 'Fellipe Bastos', 'FELLIPE BASTOS'),
      _Row('LE', 6, 'Artur', 'ARTUR'),
      _Row('LD/MC', 18, 'Dieguinho', 'DIEGUINHO'),
      _Row('MEI', 10, 'Élvis', 'ELVIS'),
      _Row('MC', 11, 'Júlio César', 'JULIO CESAR'),
      _Row('VOL', 5, 'Caio Vinícius', 'CAIO VINICIUS'),
      _Row('ATA', 7, 'Dadá Belmonte', 'DADA', ['Dadá']),
      _Row('ATA', 9, 'Nicolas', 'NICOLAS'),
    ],
  ),
  _m(
    id: '2023_corinthians_brA_rodada2',
    competition: 'Campeonato Brasileiro Série A',
    season: '2023',
    phase: 'Rodada 2',
    date: DateTime(2023, 4, 23),
    home: 'Goiás',
    homeScore: 3,
    away: 'Corinthians',
    awayScore: 1,
    formation: '4-2-3-1',
    confidence: FormationConfidence.probable,
    lineup: const [
      _Row('GOL', 23, 'Tadeu', 'TADEU'),
      _Row('LD', 2, 'Maguinho', 'MAGUINHO'),
      _Row('ZAG', 3, 'Lucas Halter', 'LUCAS HALTER', ['Halter']),
      _Row('ZAG', 19, 'Bruno Melo', 'BRUNO MELO'),
      _Row('LE', 6, 'Sander', 'SANDER'),
      _Row('VOL', 20, 'Dieguinho', 'DIEGUINHO'),
      _Row('VOL', 5, 'Zé Ricardo', 'ZE RICARDO'),
      _Row('MEI', 40, 'Everton Morelli', 'MORELLI', ['Morelli']),
      _Row('MEI', 10, 'Julián Palacios', 'PALACIOS', ['Palacios']),
      _Row('ATA', 7, 'Vinícius', 'VINICIUS'),
      _Row('ATA', 17, 'Matheus Peixoto', 'MATHEUS PEIXOTO', ['Peixoto']),
    ],
  ),
  _m(
    id: '2023_botafogo_brA_rodada6',
    competition: 'Campeonato Brasileiro Série A',
    season: '2023',
    phase: 'Rodada 6',
    date: DateTime(2023, 5, 14),
    home: 'Goiás',
    homeScore: 2,
    away: 'Botafogo',
    awayScore: 1,
    formation: '4-3-3',
    confidence: FormationConfidence.probable,
    lineup: const [
      _Row('GOL', 1, 'Marcelo Rangel', 'MARCELO RANGEL', ['Rangel']),
      _Row('LD', 2, 'Maguinho', 'MAGUINHO'),
      _Row('ZAG', 3, 'Lucas Halter', 'LUCAS HALTER', ['Halter']),
      _Row('ZAG', 19, 'Bruno Melo', 'BRUNO MELO'),
      _Row('LE', 6, 'Sander', 'SANDER'),
      _Row('MC', 20, 'Dieguinho', 'DIEGUINHO'),
      _Row('VOL', 5, 'Zé Ricardo', 'ZE RICARDO'),
      _Row('MC', 12, 'Willian Oliveira', 'WILLIAN OLIVEIRA'),
      _Row('ATA', 10, 'Julián Palacios', 'PALACIOS', ['Palacios']),
      _Row('ATA', 11, 'Diego Gonçalves', 'DIEGO GONCALVES'),
      _Row('ATA', 17, 'Matheus Peixoto', 'MATHEUS PEIXOTO', ['Peixoto']),
    ],
  ),
  _m(
    id: '2025_paysandu_copaverde_final_ida',
    competition: 'Copa Verde',
    season: '2025',
    phase: 'Final - ida',
    date: DateTime(2025, 4, 9),
    home: 'Paysandu',
    homeScore: 0,
    away: 'Goiás',
    awayScore: 0,
    formation: '4-3-3',
    confidence: FormationConfidence.confirmed,
    lineup: const [
      _Row('GOL', 23, 'Tadeu', 'TADEU'),
      _Row('LD', 97, 'Willean Lepo', 'WILLEAN LEPO', ['Lepo']),
      _Row('ZAG', 14, 'Lucas Ribeiro', 'LUCAS RIBEIRO'),
      _Row('ZAG', 75, 'Messias', 'MESSIAS'),
      _Row('LE', 36, 'Lucas Lovat', 'LUCAS LOVAT', ['Lovat']),
      _Row('MC', 28, 'Juninho', 'JUNINHO'),
      _Row('MC', 32, 'Rodrigo Andrade', 'RODRIGO ANDRADE'),
      _Row('MEI', 77, 'Marcão', 'MARCÃO'),
      _Row('ATA', 45, 'Arthur Caíke', 'ARTHUR CAIKE'),
      _Row('ATA', 7, 'Jajá', 'JAJA', ['Jajá']),
      _Row('ATA', 71, 'Zé Hugo', 'ZE HUGO'),
    ],
  ),
  _m(
    id: '2025_cuiaba_brB_rodada17',
    competition: 'Campeonato Brasileiro Série B',
    season: '2025',
    phase: 'Rodada 17 - liderança',
    date: DateTime(2025, 7, 19),
    home: 'Goiás',
    homeScore: 3,
    away: 'Cuiabá',
    awayScore: 1,
    formation: '4-3-3',
    confidence: FormationConfidence.confirmed,
    lineup: const [
      _Row('GOL', 23, 'Tadeu', 'TADEU'),
      _Row('LD', 20, 'Diego Caito', 'DIEGO CAITO', ['Caito']),
      _Row('ZAG', 4, 'Titi', 'TITI'),
      _Row('ZAG', 75, 'Messias', 'MESSIAS'),
      _Row('LE', 97, 'Willean Lepo', 'WILLEAN LEPO', ['Lepo']),
      _Row('MEI', 27, 'Wellington Rato', 'WELLINGTON RATO', ['Rato']),
      _Row('MC', 28, 'Juninho', 'JUNINHO'),
      _Row('VOL', 5, 'Gonzalo Freitas', 'GONZALO FREITAS', ['Freitas']),
      _Row('ATA', 7, 'Jajá', 'JAJA', ['Jajá']),
      _Row('ATA', 9, 'Anselmo Ramón', 'ANSELMO RAMON'),
      _Row('ATA', 17, 'Pedrinho', 'PEDRINHO'),
    ],
  ),
  _m(
    id: '2026_atleticogo_goiano_final_ida',
    competition: 'Campeonato Goiano',
    season: '2026',
    phase: 'Final - ida',
    date: DateTime(2026, 3, 7),
    home: 'Atlético-GO',
    homeScore: 0,
    away: 'Goiás',
    awayScore: 2,
    formation: '4-5-1',
    confidence: FormationConfidence.confirmed,
    lineup: const [
      _Row('GOL', 23, 'Tadeu', 'TADEU'),
      _Row('LD', 20, 'Diego Caito', 'DIEGO CAITO', ['Caito']),
      _Row('ZAG', 25, 'Luisão', 'LUISAO'),
      _Row('ZAG', 14, 'Lucas Ribeiro', 'LUCAS RIBEIRO'),
      _Row('LE', 6, 'Nicolas', 'NICOLAS'),
      _Row('VOL', 5, 'Filipe Machado', 'FILIPE MACHADO'),
      _Row('MC', 28, 'Gegê', 'GEGE'),
      _Row('MEI', 97, 'Lourenço', 'LOURENÇO'),
      _Row('MEI', 10, 'Lucas Lima', 'LUCAS LIMA'),
      _Row('MEI', 21, 'Jean Carlos', 'JEAN CARLOS'),
      _Row('ATA', 9, 'Anselmo Ramón', 'ANSELMO RAMON'),
    ],
  ),
  _m(
    id: '2026_atleticogo_goiano_final_volta',
    competition: 'Campeonato Goiano',
    season: '2026',
    phase: 'Final - volta / título invicto',
    date: DateTime(2026, 3, 15),
    home: 'Goiás',
    homeScore: 0,
    away: 'Atlético-GO',
    awayScore: 0,
    formation: '4-5-1',
    confidence: FormationConfidence.confirmed,
    lineup: const [
      _Row('GOL', 23, 'Tadeu', 'TADEU'),
      _Row('LD', 20, 'Diego Caito', 'DIEGO CAITO', ['Caito']),
      _Row('ZAG', 25, 'Luisão', 'LUISAO'),
      _Row('ZAG', 14, 'Lucas Ribeiro', 'LUCAS RIBEIRO'),
      _Row('LE', 6, 'Nicolas', 'NICOLAS'),
      _Row('VOL', 5, 'Filipe Machado', 'FILIPE MACHADO'),
      _Row('MC', 28, 'Gegê', 'GEGE'),
      _Row('MEI', 97, 'Lourenço', 'LOURENÇO'),
      _Row('MEI', 10, 'Lucas Lima', 'LUCAS LIMA'),
      _Row('MEI', 21, 'Jean Carlos', 'JEAN CARLOS'),
      _Row('ATA', 9, 'Anselmo Ramón', 'ANSELMO RAMON'),
    ],
  ),
];

/// Ordem de exibição — deliberadamente NÃO cronológica. [lineupMatches]
/// acima fica agrupado por ano (mais fácil de conferir/manter), mas exibir
/// nessa ordem faz o torcedor cair em 2-3 partidas seguidas do mesmo ano
/// (às vezes até os dois jogos de uma mesma eliminatória, escalação quase
/// idêntica) — quebra a graça do jogo. Esta lista intercala os anos
/// (round-robin) e mantém qualquer ida/volta bem afastada uma da outra.
const _displayOrder = [
  '1990_flamengo_cdb_final_volta',
  '1996_guarani_brA_quartas',
  '1999_santacruz_brB_titulo',
  '2003_juventude_brA_reacao',
  '2005_pontepreta_brA_3lugar',
  '2006_cuenca_lib_1fase',
  '2010_palmeiras_sulamericana_semi_volta',
  '2012_guarani_brB_retafinal',
  '2013_fluminense_cdb_oitavas_volta',
  '2018_aparecidense_goiano_final_volta',
  '2021_csa_brB_g4',
  '2023_corinthians_brA_rodada2',
  '2025_paysandu_copaverde_final_ida',
  '2026_atleticogo_goiano_final_ida',
  '1996_gremio_brA_semi',
  '2003_fluminense_brA_reacao',
  '2005_athleticopr_brA_3lugar',
  '2006_newells_lib_grupos',
  '2010_independiente_sulamericana_final_ida',
  '2012_joinville_brB_titulo',
  '2013_vasco_cdb_quartas_ida',
  '2021_guarani_brB_acesso',
  '2023_botafogo_brA_rodada6',
  '2025_cuiaba_brB_rodada17',
  '2026_atleticogo_goiano_final_volta',
  '2003_santos_brA_reacao',
  '2005_saopaulo_brA_3lugar',
  '2006_estudiantes_lib_oitavas_volta',
  '2010_independiente_sulamericana_final_volta',
  '2013_vasco_cdb_quartas_volta',
  '2005_corinthians_brA_3lugar',
];

final orderedLineupMatches = [
  for (final id in _displayOrder)
    lineupMatches.firstWhere((match) => match.id == id),
];

class _Row {
  const _Row(
    this.pos,
    this.no,
    this.name,
    this.answer, [
    this.aliases = const [],
  ]);

  final String pos;
  final int? no;
  final String name;
  final String answer;
  final List<String> aliases;
}

LineupMatch _m({
  required String id,
  required String competition,
  required String season,
  required String phase,
  required DateTime date,
  String? venue,
  required String home,
  required int homeScore,
  required String away,
  required int awayScore,
  required String formation,
  required FormationConfidence confidence,
  required List<_Row> lineup,
}) {
  assert(
    lineup.length == 11,
    '$id: escalação precisa ter exatamente 11 titulares (tem ${lineup.length})',
  );
  final positions = FormationLayoutService.positionsFor(formation);
  return LineupMatch(
    id: id,
    competition: competition,
    season: season,
    phase: phase,
    date: date,
    venue: venue,
    homeTeam: home,
    awayTeam: away,
    homeScore: homeScore,
    awayScore: awayScore,
    teamToGuess: 'Goiás',
    formation: formation,
    formationConfidence: confidence,
    players: [
      for (var i = 0; i < lineup.length; i++)
        _player('$id-p$i', positions[i], lineup[i]),
    ],
  );
}

LineupPlayer _player(String id, Offset pos, _Row row) {
  final answer = row.answer.toUpperCase();
  return LineupPlayer(
    id: id,
    position: row.pos,
    x: pos.dx,
    y: pos.dy,
    shirtNumber: row.no,
    fullName: row.name,
    displayName: row.name,
    puzzleAnswer: answer,
    answerParts: answer.split(' ').map((word) => word.length).toList(),
    normalizedAnswer: WordEvaluationService.normalize(answer),
    aliases: row.aliases,
  );
}
